CREATE SCHEMA APEX_UTIL;

CREATE OR REPLACE PROCEDURE APEX_UTIL.AGENDA_CALENDAR(P_DATE_TYPE_FIELD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.CACHE_GET_DATE_OF_PAGE_CACHE(P_APPLICATION NUMBER,P_PAGE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.CACHE_GET_DATE_OF_REGION_CACHE(P_APPLICATION NUMBER,P_PAGE NUMBER,P_REGION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.CACHE_PURGE_BY_APPLICATION(P_APPLICATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CACHE_PURGE_BY_PAGE(P_APPLICATION NUMBER,P_PAGE NUMBER,P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CACHE_PURGE_STALE(P_APPLICATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CHANGE_CURRENT_USER_PW(P_NEW_PASSWORD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.CHANGE_PASSWORD_ON_FIRST_USE(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.CLEAR_APP_CACHE(P_APP_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CLEAR_PAGE_CACHE(P_PAGE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CLEAR_USER_CACHE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CLOSE_OPEN_DB_LINKS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.COUNT_CLICK(P_URL VARCHAR,P_CAT VARCHAR,P_ID VARCHAR,P_USER VARCHAR,P_COMPANY VARCHAR,P_WORKSPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CREATE_USER(P_USER_ID NUMBER,P_USER_NAME VARCHAR,P_FIRST_NAME VARCHAR,P_LAST_NAME VARCHAR,P_DESCRIPTION VARCHAR,P_EMAIL_ADDRESS VARCHAR,P_WEB_PASSWORD VARCHAR,P_WEB_PASSWORD_FORMAT VARCHAR,P_GROUP_IDS VARCHAR,P_DEVELOPER_PRIVS VARCHAR,P_DEFAULT_SCHEMA VARCHAR,P_DEFAULT_DATE_FORMAT VARCHAR,P_ALLOW_ACCESS_TO_SCHEMAS VARCHAR,P_ACCOUNT_EXPIRY DATE,P_ACCOUNT_LOCKED VARCHAR,P_FAILED_ACCESS_ATTEMPTS NUMBER,P_CHANGE_PASSWORD_ON_FIRST_USE VARCHAR,P_FIRST_PASSWORD_USE_OCCURRED VARCHAR,P_ATTRIBUTE_01 VARCHAR,P_ATTRIBUTE_02 VARCHAR,P_ATTRIBUTE_03 VARCHAR,P_ATTRIBUTE_04 VARCHAR,P_ATTRIBUTE_05 VARCHAR,P_ATTRIBUTE_06 VARCHAR,P_ATTRIBUTE_07 VARCHAR,P_ATTRIBUTE_08 VARCHAR,P_ATTRIBUTE_09 VARCHAR,P_ATTRIBUTE_10 VARCHAR,P_ALLOW_APP_BUILDING_YN VARCHAR,P_ALLOW_SQL_WORKSHOP_YN VARCHAR,P_ALLOW_WEBSHEET_DEV_YN VARCHAR,P_ALLOW_TEAM_DEVELOPMENT_YN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CREATE_USER_FROM_FILE(P_ID NUMBER,P_MODE VARCHAR,P_FORMAT VARCHAR,P_PASSWORD VARCHAR,P_APP VARCHAR,P_APPURL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.CREATE_USER_GROUP(P_ID NUMBER,P_GROUP_NAME VARCHAR,P_SECURITY_GROUP_ID NUMBER,P_GROUP_DESC VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.CURRENT_USER_IN_GROUP(P_GROUP_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.CURRENT_USER_IN_GROUP(P_GROUP_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.CUSTOM_CALENDAR(P_DATE_TYPE_FIELD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.DAILY_CALENDAR(P_DATE_TYPE_FIELD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.DECREMENT_CALENDAR()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.DELETE_USER_GROUP(P_GROUP_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.DOWNLOAD_PRINT_DOCUMENT(P_FILE_NAME VARCHAR,P_CONTENT_DISPOSITION VARCHAR,P_REPORT_DATA CLOB,P_REPORT_LAYOUT CLOB,P_REPORT_LAYOUT_TYPE VARCHAR,P_DOCUMENT_FORMAT VARCHAR,P_PRINT_SERVER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.DOWNLOAD_PRINT_DOCUMENT(P_FILE_NAME VARCHAR,P_CONTENT_DISPOSITION VARCHAR,P_REPORT_DATA BLOB,P_REPORT_LAYOUT CLOB,P_REPORT_LAYOUT_TYPE VARCHAR,P_DOCUMENT_FORMAT VARCHAR,P_PRINT_SERVER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.DOWNLOAD_PRINT_DOCUMENT(P_FILE_NAME VARCHAR,P_CONTENT_DISPOSITION VARCHAR,P_APPLICATION_ID NUMBER,P_REPORT_QUERY_NAME VARCHAR,P_REPORT_LAYOUT_NAME VARCHAR,P_REPORT_LAYOUT_TYPE VARCHAR,P_DOCUMENT_FORMAT VARCHAR,P_PRINT_SERVER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.DOWNLOAD_PRINT_DOCUMENT(P_FILE_NAME VARCHAR,P_CONTENT_DISPOSITION VARCHAR,P_APPLICATION_ID NUMBER,P_REPORT_QUERY_NAME VARCHAR,P_REPORT_LAYOUT CLOB,P_REPORT_LAYOUT_TYPE VARCHAR,P_DOCUMENT_FORMAT VARCHAR,P_PRINT_SERVER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.EDIT_USER(P_USER_ID NUMBER,P_USER_NAME VARCHAR,P_FIRST_NAME VARCHAR,P_LAST_NAME VARCHAR,P_WEB_PASSWORD VARCHAR,P_NEW_PASSWORD VARCHAR,P_EMAIL_ADDRESS VARCHAR,P_START_DATE VARCHAR,P_END_DATE VARCHAR,P_EMPLOYEE_ID VARCHAR,P_ALLOW_ACCESS_TO_SCHEMAS VARCHAR,P_PERSON_TYPE VARCHAR,P_DEFAULT_SCHEMA VARCHAR,P_DEFAULT_DATE_FORMAT VARCHAR,P_GROUP_IDS VARCHAR,P_DEVELOPER_ROLES VARCHAR,P_DESCRIPTION VARCHAR,P_ACCOUNT_EXPIRY DATE,P_ACCOUNT_LOCKED VARCHAR,P_FAILED_ACCESS_ATTEMPTS NUMBER,P_CHANGE_PASSWORD_ON_FIRST_USE VARCHAR,P_FIRST_PASSWORD_USE_OCCURRED VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.END_USER_ACCOUNT_DAYS_LEFT(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.EXPIRE_END_USER_ACCOUNT(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.EXPIRE_WORKSPACE_ACCOUNT(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.EXPORT_APPLICATION(P_WORKSPACE_ID NUMBER,P_APPLICATION_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.EXPORT_APPLICATION_COMPONENT(P_WORKSPACE_ID NUMBER,P_APPLICATION_ID NUMBER,P_COMPONENT_ID NUMBER,P_COMPONENT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.EXPORT_APPLICATION_PAGE(P_WORKSPACE_ID NUMBER,P_APPLICATION_ID NUMBER,P_PAGE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.EXPORT_USERS(P_EXPORT_FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.FEEDBACK_ENABLED(P_APP NUMBER,P_SESSION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.FETCH_USER(P_USER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.FETCH_USER(P_USER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.FETCH_USER(P_USER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.FILESIZE_MASK(P_NUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.FIND_SECURITY_GROUP_ID(P_WORKSPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.FIND_WORKSPACE(P_SECURITY_GROUP_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.FLASH2(P VARCHAR,PRELOADERLOADINGTEXT VARCHAR,SWFFILE VARCHAR,PRELOADERINITTEXT VARCHAR,XMLCALLDATE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_ACCOUNT_LOCKED_STATUS(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_APEX_CHAR_ID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_APEX_ID(P_APPLICATION_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_APPLICATION_NAME(P_WORKSPACE_ID NUMBER,P_APPLICATION_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_ATTRIBUTE(P_USERNAME VARCHAR,P_ATTRIBUTE_NUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_AUTHENTICATION_RESULT(A NUMBER,C NUMBER,P NUMBER,K1 VARCHAR,CK VARCHAR,RT VARCHAR,K2 VARCHAR,LM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.GET_BLOB_FILE(S NUMBER,A NUMBER,P NUMBER,D NUMBER,I NUMBER,P_PK1 VARCHAR,P_CK VARCHAR,P_PK2 VARCHAR,P_MIMETYPE VARCHAR,P_CONTENT_DISPOSITION VARCHAR,P_SHOW_LAST_MOD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_BLOB_FILE_SRC(P_ITEM_NAME VARCHAR,P_V1 VARCHAR,P_V2 VARCHAR,P_CONTENT_DISPOSITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_BUILD_OPTION_STATUS(P_APPLICATION_ID NUMBER,P_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_BUILD_OPTION_STATUS(P_APPLICATION_ID NUMBER,P_BUILD_OPTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_CURRENT_USER_ID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_DEFAULT_SCHEMA()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_EDITION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_FEEDBACK_FOLLOW_UP(P_FEEDBACK_ID NUMBER,P_ROW NUMBER,P_TEMPLATE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.GET_FILE(P_FILE_ID VARCHAR,P_MIME_TYPE VARCHAR,P_INLINE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_FILE_ID(P_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_FIRST_NAME(P_USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_GROUPS_USER_BELONGS_TO(P_USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_GROUP_ID(P_GROUP_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_GROUP_NAME(P_GROUP_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_GROUP_NAME(P_GROUP_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_HASH(P_VALUES WWV_FLOW_T_VARCHAR2,P_SALTED BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_HIGH_CONTRAST_MODE_TOGGLE(P_ON_MESSAGE VARCHAR,P_OFF_MESSAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_LANGUAGE_SELECTOR_LIST()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_LANGUAGE_SELECTOR_UL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_LANGUAGE_SELECTOR_UL2()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_NUMERIC_SESSION_STATE(P_ITEM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_PREFERENCE(P_PREFERENCE VARCHAR,P_USER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_PRINT_DOCUMENT(P_REPORT_DATA CLOB,P_REPORT_LAYOUT CLOB,P_REPORT_LAYOUT_TYPE VARCHAR,P_DOCUMENT_FORMAT VARCHAR,P_PRINT_SERVER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_PRINT_DOCUMENT(P_REPORT_DATA BLOB,P_REPORT_LAYOUT CLOB,P_REPORT_LAYOUT_TYPE VARCHAR,P_DOCUMENT_FORMAT VARCHAR,P_PRINT_SERVER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_PRINT_DOCUMENT(P_APPLICATION_ID NUMBER,P_REPORT_QUERY_NAME VARCHAR,P_REPORT_LAYOUT_NAME VARCHAR,P_REPORT_LAYOUT_TYPE VARCHAR,P_DOCUMENT_FORMAT VARCHAR,P_PRINT_SERVER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_PRINT_DOCUMENT(P_APPLICATION_ID NUMBER,P_REPORT_QUERY_NAME VARCHAR,P_REPORT_LAYOUT CLOB,P_REPORT_LAYOUT_TYPE VARCHAR,P_DOCUMENT_FORMAT VARCHAR,P_PRINT_SERVER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SCREEN_READER_MODE_TOGGLE(P_ON_MESSAGE VARCHAR,P_OFF_MESSAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SESSION_LANG()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SESSION_TERRITORY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SESSION_TIME_ZONE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SINCE(P_VALUE TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SINCE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SINCE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SINCE_TSWLTZ()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_SINCE_TSWTZ()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_TIMEFRAME(P_DAYS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_USERNAME(P_USERID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_USER_ID(P_USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_USER_ROLES(P_USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.GET_UUID(P_CHECK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.HOST_URL(P_OPTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.HTML_PCT_GRAPH_MASK(P_NUMBER NUMBER,P_SIZE NUMBER,P_BACKGROUND VARCHAR,P_BAR_BACKGROUND VARCHAR,P_FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.INCREMENT_CALENDAR(P_REPORT_ALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.IR_DELETE_REPORT(P_REPORT_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.IR_DELETE_SUBSCRIPTION(P_SUBSCRIPTION_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.IR_FILTER(P_PAGE_ID NUMBER,P_REPORT_COLUMN VARCHAR,P_OPERATOR_ABBR VARCHAR,P_FILTER_VALUE VARCHAR,P_REPORT_ALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.IR_RESET(P_PAGE_ID NUMBER,P_REPORT_ALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.IS_HIGH_CONTRAST_SESSION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.IS_HIGH_CONTRAST_SESSION_YN(P_PASSWORD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.IS_SCREEN_READER_SESSION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.IS_SCREEN_READER_SESSION_YN()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.JSON_FROM_ARRAY(P_ROWS NUMBER,P_COLS NUMBER,P_NAME01 VARCHAR,P_NAME02 VARCHAR,P_NAME03 VARCHAR,P_NAME04 VARCHAR,P_NAME05 VARCHAR,P_NAME06 VARCHAR,P_NAME07 VARCHAR,P_NAME08 VARCHAR,P_NAME09 VARCHAR,P_NAME10 VARCHAR,P_SUB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.JSON_FROM_ITEMS(P_ITEMS VARCHAR,P_SEPARATOR VARCHAR,P_SUB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.JSON_FROM_SQL(SQLQ VARCHAR,P_SUB VARCHAR,P_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.JSON_FROM_STRING(P_ITEMS VARCHAR,P_SEPARATOR VARCHAR,P_SUB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.KEYVAL_NUM()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.KEYVAL_VC2()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.MINIMUM_FREE_APPLICATION_ID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.PASSWORD_FIRST_USE_OCCURRED(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.PAUSE(P_SECONDS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.PREPARE_URL(P_URL VARCHAR,P_URL_CHARSET VARCHAR,P_CHECKSUM_TYPE VARCHAR,P_TRIGGERING_ELEMENT VARCHAR,P_DIALOG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.PUBLIC_CHECK_AUTHORIZATION(P_SECURITY_SCHEME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.PURGE_REGIONS_BY_APP(P_APPLICATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.PURGE_REGIONS_BY_NAME(P_APPLICATION NUMBER,P_PAGE NUMBER,P_REGION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.PURGE_REGIONS_BY_PAGE(P_APPLICATION NUMBER,P_PAGE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.REDIRECT_URL(P_URL VARCHAR,P_RESET_HTP_BUFFER BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.REMOVE_PREFERENCE(P_PREFERENCE VARCHAR,P_USER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.REMOVE_SORT_PREFERENCES(P_USER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.REMOVE_USER(P_USER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.REMOVE_USER(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.RESET_AUTHORIZATIONS(P_OLD_PASSWORD VARCHAR,P_NEW_PASSWORD VARCHAR,P_CHANGE_PASSWORD_ON_FIRST_USE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.RESET_PW(P_USER VARCHAR,P_MSG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.RESET_SESSION_LANG()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.RESET_SESSION_TERRITORY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.RESET_SESSION_TIME_ZONE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.SAVEKEY_VC2(P_VAL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_ATTRIBUTE(P_USERID NUMBER,P_ATTRIBUTE_NUMBER NUMBER,P_ATTRIBUTE_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_AUTHENTICATION_RESULT(P_CODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.SET_BLOB(P_APPLICATION_ID VARCHAR,P_PAGE_ID VARCHAR,P_SESSION_ID VARCHAR,P_REQUEST VARCHAR,P_ITEM_ID VARCHAR,P_FILE_NAME VARCHAR,P_MIME_TYPE VARCHAR,P_BLOB_CONTENT BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_BUILD_OPTION_STATUS(P_APPLICATION_ID NUMBER,P_ID NUMBER,P_BUILD_STATUS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_COMPATIBILITY_MODE(P_APPLICATION_ID NUMBER,P_COMPATIBILITY_MODE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_CURRENT_THEME_STYLE(P_THEME_NUMBER NUMBER,P_THEME_STYLE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_CUSTOM_AUTH_STATUS(P_STATUS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_EDITION(P_EDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_EMAIL(P_USERID NUMBER,P_EMAIL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_FIRST_NAME(P_USERID NUMBER,P_FIRST_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_GROUP_GROUP_GRANTS(P_GROUP_NAME VARCHAR,P_GRANTED_GROUP_NAMES WWV_FLOW_T_VARCHAR2)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_GROUP_USER_GRANTS(P_USER_NAME VARCHAR,P_GRANTED_GROUP_NAMES WWV_FLOW_T_VARCHAR2)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_LAST_NAME(P_USERID NUMBER,P_LAST_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_PREFERENCE(P_PREFERENCE VARCHAR,P_VALUE VARCHAR,P_USER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_REPORT_COLUMN_FORMAT()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SECURITY_GROUP_ID(P_SECURITY_GROUP_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SESSION_HIGH_CONTRAST_OFF()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SESSION_HIGH_CONTRAST_ON()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SESSION_LIFETIME_SECONDS(P_SECONDS NUMBER,P_SCOPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SESSION_MAX_IDLE_SECONDS(P_SECONDS NUMBER,P_SCOPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SESSION_SCREEN_READER_OFF()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SESSION_SCREEN_READER_ON(P_VALUE VARCHAR,P_COMMIT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SESSION_TERRITORY(P_TERRITORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_SESSION_TIME_ZONE(P_TIME_ZONE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SET_USERNAME(P_USERID NUMBER,P_USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SHOW_HIGH_CONTRAST_MODE_TOGGLE(P_ON_MESSAGE VARCHAR,P_OFF_MESSAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SHOW_SCREEN_READER_MODE_TOGGLE(P_ON_MESSAGE VARCHAR,P_OFF_MESSAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.STRING_TO_TABLE(P_STRING VARCHAR,P_SEPARATOR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.STRONG_PASSWORD_CHECK(P_USERNAME VARCHAR,P_PASSWORD VARCHAR,P_OLD_PASSWORD VARCHAR,P_WORKSPACE_NAME VARCHAR,P_USE_STRONG_RULES BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.STRONG_PASSWORD_VALIDATION(P_USERNAME VARCHAR,P_PASSWORD VARCHAR,P_OLD_PASSWORD VARCHAR,P_WORKSPACE_NAME VARCHAR,P_USE_STRONG_RULES BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.SUBMIT_FEEDBACK(P_COMMENT VARCHAR,P_TYPE NUMBER,P_APPLICATION_ID VARCHAR,P_PAGE_ID VARCHAR,P_EMAIL VARCHAR,P_SCREEN_WIDTH VARCHAR,P_SCREEN_HEIGHT VARCHAR,P_ATTRIBUTE_01 VARCHAR,P_ATTRIBUTE_02 VARCHAR,P_ATTRIBUTE_03 VARCHAR,P_ATTRIBUTE_04 VARCHAR,P_ATTRIBUTE_05 VARCHAR,P_ATTRIBUTE_06 VARCHAR,P_ATTRIBUTE_07 VARCHAR,P_ATTRIBUTE_08 VARCHAR,P_LABEL_01 VARCHAR,P_LABEL_02 VARCHAR,P_LABEL_03 VARCHAR,P_LABEL_04 VARCHAR,P_LABEL_05 VARCHAR,P_LABEL_06 VARCHAR,P_LABEL_07 VARCHAR,P_LABEL_08 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.SUBMIT_FEEDBACK_FOLLOWUP(P_FEEDBACK_ID NUMBER,P_FOLLOW_UP VARCHAR,P_EMAIL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.TABLE_TO_STRING(P_STRING VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.TODAY_CALENDAR()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.UNEXPIRE_END_USER_ACCOUNT(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.UNEXPIRE_WORKSPACE_ACCOUNT(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_UTIL.UNLOCK_ACCOUNT(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.URL_ENCODE(P_URL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_UTIL.USER_IN_GROUP(P_GROUP_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_UTIL.WEEKLY_CALENDAR(P_DATE_TYPE_FIELD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_UTIL.WORKSPACE_ACCOUNT_DAYS_LEFT(P_USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

