CREATE SCHEMA APEX_CUSTOM_AUTH;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.APPLICATION_PAGE_ITEM_EXISTS(P_ITEM_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.CURRENT_PAGE_IS_PUBLIC(P_SESSION_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_CUSTOM_AUTH.GET_COOKIE_PROPS(P_APP_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_CUSTOM_AUTH.GET_LDAP_PROPS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.GET_NEXT_SESSION_ID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.GET_SECURITY_GROUP_ID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.GET_SESSION_ID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.GET_SESSION_ID_FROM_COOKIE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.GET_USER()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.GET_USERNAME()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.IS_SESSION_VALID(P_PASSWORD VARCHAR,P_LDAP_HOST VARCHAR,P_LDAP_PORT NUMBER,P_USE_SSL VARCHAR,P_USE_EXACT_DN VARCHAR,P_LDAP_STRING VARCHAR,P_SEARCH_FILTER VARCHAR,P_LDAP_EDIT_FUNCTION VARCHAR,P_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.LDAP_DNPREP(P_USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_CUSTOM_AUTH.LOGIN(P_UNAME VARCHAR,P_PASSWORD VARCHAR,P_SESSION_ID VARCHAR,P_APP_PAGE VARCHAR,P_ENTRY_POINT VARCHAR,P_PRESERVE_CASE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_CUSTOM_AUTH.LOGOUT(P_THIS_APP VARCHAR,P_NEXT_APP_PAGE_SESS VARCHAR,P_NEXT_URL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_CUSTOM_AUTH.LOGOUT_THEN_GO_TO_PAGE(P_ARGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE APEX_CUSTOM_AUTH.LOGOUT_THEN_GO_TO_URL(P_ARGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.PORTAL_SSO_SENTRY_V1(P_SESSION_ID VARCHAR,P_APP_PAGE VARCHAR,P_PRESERVE_CASE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_CUSTOM_AUTH.REMOVE_SESSION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION APEX_CUSTOM_AUTH.SESSION_ID_EXISTS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE APEX_CUSTOM_AUTH.SET_SESSION_ID_TO_NEXT_VALUE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

