CREATE SCHEMA CTX_DOC;

CREATE OR REPLACE PROCEDURE CTX_DOC.FILTER(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,RESTAB VARCHAR,QUERY_ID NUMBER,PLAINTEXT BOOLEAN,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.FILTER(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,PLAINTEXT BOOLEAN,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_DOC.GET_KEY_TYPE(TEXTKEY VARCHAR,RESTAB VARCHAR,QUERY_ID NUMBER,GLEVEL VARCHAR,POV VARCHAR,NUMPARAGRAPHS NUMBER,MAXPERCENT NUMBER,NUM_THEMES NUMBER,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_DOC.GIST(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,GLEVEL VARCHAR,POV VARCHAR,NUMPARAGRAPHS NUMBER,MAXPERCENT NUMBER,NUM_THEMES NUMBER,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.HIGHLIGHT(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY VARCHAR,RESTAB VARCHAR,QUERY_ID NUMBER,PLAINTEXT BOOLEAN,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.HIGHLIGHT(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.HIGHLIGHT_CLOB_QUERY(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY CLOB,RESTAB VARCHAR,QUERY_ID NUMBER,PLAINTEXT BOOLEAN,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.HIGHLIGHT_CLOB_QUERY(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.IFILTER(DATA BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.MARKUP(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY VARCHAR,RESTAB VARCHAR,QUERY_ID NUMBER,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.MARKUP(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.MARKUP_CLOB_QUERY(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY CLOB,RESTAB VARCHAR,QUERY_ID NUMBER,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.MARKUP_CLOB_QUERY(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_DOC.PKENCODE(PK1 VARCHAR,PK2 VARCHAR,PK3 VARCHAR,PK4 VARCHAR,PK5 VARCHAR,PK6 VARCHAR,PK7 VARCHAR,PK8 VARCHAR,PK9 VARCHAR,PK10 VARCHAR,PK11 VARCHAR,PK12 VARCHAR,PK13 VARCHAR,PK14 VARCHAR,PK15 VARCHAR,PK16 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_FILTER(POLICY_NAME VARCHAR,DOCUMENT CLOB,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_FILTER(POLICY_NAME VARCHAR,DOCUMENT BLOB,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_FILTER(POLICY_NAME VARCHAR,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_FILTER(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_GIST(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,GLEVEL VARCHAR,POV VARCHAR,NUMPARAGRAPHS NUMBER,MAXPERCENT NUMBER,NUM_THEMES NUMBER,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_GIST(POLICY_NAME VARCHAR,DOCUMENT CLOB,GLEVEL VARCHAR,POV VARCHAR,NUMPARAGRAPHS NUMBER,MAXPERCENT NUMBER,NUM_THEMES NUMBER,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_GIST(POLICY_NAME VARCHAR,DOCUMENT BLOB,GLEVEL VARCHAR,POV VARCHAR,NUMPARAGRAPHS NUMBER,MAXPERCENT NUMBER,NUM_THEMES NUMBER,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_GIST(POLICY_NAME VARCHAR,GLEVEL VARCHAR,POV VARCHAR,NUMPARAGRAPHS NUMBER,MAXPERCENT NUMBER,NUM_THEMES NUMBER,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_HIGHLIGHT(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_HIGHLIGHT(POLICY_NAME VARCHAR,DOCUMENT CLOB,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_HIGHLIGHT(POLICY_NAME VARCHAR,DOCUMENT BLOB,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_HIGHLIGHT(POLICY_NAME VARCHAR,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_HIGHLIGHT_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_HIGHLIGHT_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT CLOB,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_HIGHLIGHT_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT BLOB,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_HIGHLIGHT_CLOB_QUERY(POLICY_NAME VARCHAR,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_LANGUAGES(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_LANGUAGES(POLICY_NAME VARCHAR,DOCUMENT CLOB,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_MARKUP(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_MARKUP(POLICY_NAME VARCHAR,DOCUMENT CLOB,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_MARKUP(POLICY_NAME VARCHAR,DOCUMENT BLOB,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_MARKUP(POLICY_NAME VARCHAR,TEXT_QUERY VARCHAR,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_MARKUP_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_MARKUP_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT CLOB,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_MARKUP_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT BLOB,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_MARKUP_CLOB_QUERY(POLICY_NAME VARCHAR,TEXT_QUERY CLOB,PLAINTEXT BOOLEAN,TAGSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,PREVTAG VARCHAR,NEXTTAG VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_NOUN_PHRASES(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_NOUN_PHRASES(POLICY_NAME VARCHAR,DOCUMENT CLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_PART_OF_SPEECH(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,DISAMBIGUATE_TAGS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_PART_OF_SPEECH(POLICY_NAME VARCHAR,DOCUMENT CLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,DISAMBIGUATE_TAGS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_DOC.POLICY_SNIPPET(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,TEXT_QUERY VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_DOC.POLICY_SNIPPET(POLICY_NAME VARCHAR,DOCUMENT CLOB,TEXT_QUERY VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_DOC.POLICY_SNIPPET(POLICY_NAME VARCHAR,DOCUMENT BLOB,TEXT_QUERY VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_DOC.POLICY_SNIPPET(POLICY_NAME VARCHAR,TEXT_QUERY VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_DOC.POLICY_SNIPPET_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,TEXT_QUERY CLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_DOC.POLICY_SNIPPET_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT CLOB,TEXT_QUERY CLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_DOC.POLICY_SNIPPET_CLOB_QUERY(POLICY_NAME VARCHAR,DOCUMENT BLOB,TEXT_QUERY CLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_DOC.POLICY_SNIPPET_CLOB_QUERY(POLICY_NAME VARCHAR,TEXT_QUERY CLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_STEMS(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_STEMS(POLICY_NAME VARCHAR,DOCUMENT CLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_THEMES(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,FULL_THEMES BOOLEAN,NUM_THEMES NUMBER,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_THEMES(POLICY_NAME VARCHAR,DOCUMENT CLOB,FULL_THEMES BOOLEAN,NUM_THEMES NUMBER,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_THEMES(POLICY_NAME VARCHAR,DOCUMENT BLOB,FULL_THEMES BOOLEAN,NUM_THEMES NUMBER,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_THEMES(POLICY_NAME VARCHAR,FULL_THEMES BOOLEAN,NUM_THEMES NUMBER,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_TOKENS(POLICY_NAME VARCHAR,DOCUMENT VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_TOKENS(POLICY_NAME VARCHAR,DOCUMENT CLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_TOKENS(POLICY_NAME VARCHAR,DOCUMENT BLOB,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.POLICY_TOKENS(POLICY_NAME VARCHAR,LANGUAGE VARCHAR,FORMAT VARCHAR,CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.SET_KEY_TYPE(KEY_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_DOC.SNIPPET(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY VARCHAR,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_DOC.SNIPPET_CLOB_QUERY(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,TEXT_QUERY CLOB,STARTTAG VARCHAR,ENDTAG VARCHAR,ENTITY_TRANSLATION BOOLEAN,SEPARATOR VARCHAR,RADIUS NUMBER,MAX_LENGTH NUMBER,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_DOC.THEMES(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,RESTAB VARCHAR,QUERY_ID NUMBER,FULL_THEMES BOOLEAN,NUM_THEMES NUMBER,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.THEMES(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,FULL_THEMES BOOLEAN,NUM_THEMES NUMBER,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.TOKENS(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,RESTAB VARCHAR,QUERY_ID NUMBER,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DOC.TOKENS(INDEX_NAME VARCHAR,TEXTKEY VARCHAR,USE_SAVED_COPY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

