CREATE SCHEMA CTX_THES;

CREATE OR REPLACE PROCEDURE CTX_THES.ALTER_PHRASE(TNAME VARCHAR,PHRASE VARCHAR,OP VARCHAR,OPERAND VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.ALTER_THESAURUS(TNAME VARCHAR,OP VARCHAR,OPERAND VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.BT(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.BT(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.BTG(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.BTG(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.BTI(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.BTI(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.BTP(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.BTP(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.CREATE_PHRASE(TNAME VARCHAR,PHRASE VARCHAR,REL VARCHAR,RELNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.CREATE_RELATION(TNAME VARCHAR,PHRASE VARCHAR,REL VARCHAR,RELPHRASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.CREATE_THESAURUS(NAME VARCHAR,CASESENS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.CREATE_TRANSLATION(TNAME VARCHAR,PHRASE VARCHAR,LANGUAGE VARCHAR,TRANSLATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.DROP_PHRASE(TNAME VARCHAR,PHRASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.DROP_RELATION(TNAME VARCHAR,PHRASE VARCHAR,REL VARCHAR,RELPHRASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.DROP_THESAURUS(NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.DROP_TRANSLATION(TNAME VARCHAR,PHRASE VARCHAR,LANGUAGE VARCHAR,TRANSLATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.EXPORT_THESAURUS(NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.HAS_RELATION(PHRASE VARCHAR,REL VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.IMPORT_THESAURUS(NAME VARCHAR,DATA CLOB,CASESENS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.NT(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.NT(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.NTG(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.NTG(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.NTI(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.NTI(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.NTP(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.NTP(PHRASE VARCHAR,LVL NUMBER,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.OUTPUT_STYLE(SHOWLEVEL BOOLEAN,SHOWQUALIFY BOOLEAN,SHOWPT BOOLEAN,SHOWID BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.PT(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.PT(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.RT(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.RT(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.SN(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_THES.SYN(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.SYN(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.THES_TT(TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.TR(PHRASE VARCHAR,LANG VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.TR(PHRASE VARCHAR,LANG VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.TRSYN(PHRASE VARCHAR,LANG VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.TRSYN(PHRASE VARCHAR,LANG VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_THES.TT(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_THES.TT(PHRASE VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_THES.UPDATE_TRANSLATION(TNAME VARCHAR,PHRASE VARCHAR,LANGUAGE VARCHAR,TRANSLATION VARCHAR,NEW_TRANSLATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

