CREATE SCHEMA CTX_DDL;

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_ATTR_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,TAG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_AUTO_OPTIMIZE(IDX_NAME VARCHAR,PART_NAME VARCHAR,OPTLEVEL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_FIELD_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,TAG VARCHAR,VISIBLE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_INDEX(SET_NAME VARCHAR,COLUMN_LIST VARCHAR,STORAGE_CLAUSE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_MDATA(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,MDATA_VALUE VARCHAR,MDATA_ROWID ROWID,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_MDATA(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,MDATA_VALUES ODCIVARCHAR2LIST,MDATA_ROWIDS ODCIRIDLIST,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_MDATA_COLUMN(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,COLUMN_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_MDATA_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,TAG VARCHAR,READ_ONLY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_MVDATA_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,TAG VARCHAR,DATATYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_NDATA_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,TAG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_SDATA(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,SDATA_VALUE VARCHAR,SDATA_ROWID ROWID,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_SDATA_COLUMN(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,COLUMN_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_SDATA_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,TAG VARCHAR,DATATYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_SEC_GRP_ATTR_VAL(GROUP_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_SPECIAL_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_STOPCLASS(STOPLIST_NAME VARCHAR,STOPCLASS VARCHAR,STOPPATTERN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_STOPTHEME(STOPLIST_NAME VARCHAR,STOPTHEME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_STOPWORD(STOPLIST_NAME VARCHAR,STOPWORD VARCHAR,LANGUAGE VARCHAR,LANGUAGE_DEPENDENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_STOP_SECTION(GROUP_NAME VARCHAR,TAG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_SUB_LEXER(LEXER_NAME VARCHAR,LANGUAGE VARCHAR,SUB_LEXER VARCHAR,ALT_VALUE VARCHAR,LANGUAGE_DEPENDENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ADD_ZONE_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,TAG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ALTER_INDEX(IDX_NAME VARCHAR,PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.COPY_POLICY(SOURCE_POLICY VARCHAR,POLICY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.CREATE_INDEX_SET(SET_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.CREATE_POLICY(POLICY_NAME VARCHAR,FILTER VARCHAR,SECTION_GROUP VARCHAR,LEXER VARCHAR,STOPLIST VARCHAR,WORDLIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.CREATE_PREFERENCE(PREFERENCE_NAME VARCHAR,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.CREATE_SECTION_GROUP(GROUP_NAME VARCHAR,GROUP_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.CREATE_SHADOW_INDEX(IDX_NAME VARCHAR,PARAMETER_STRING VARCHAR,PARALLEL_DEGREE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.CREATE_STOPLIST(STOPLIST_NAME VARCHAR,STOPLIST_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.DELETE_MVDATA_VALUES(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,MVDATA_VALUES ODCINUMBERLIST,MVDATA_ROWIDS ODCIRIDLIST,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.DROP_INDEX_SET(SET_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.DROP_POLICY(POLICY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.DROP_PREFERENCE(PREFERENCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.DROP_SECTION_GROUP(GROUP_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.DROP_SHADOW_INDEX(IDX_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.DROP_STOPLIST(STOPLIST_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.EXCHANGE_SHADOW_INDEX(IDX_NAME VARCHAR,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.INSERT_MVDATA_VALUES(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,MVDATA_VALUES ODCINUMBERLIST,MVDATA_ROWIDS ODCIRIDLIST,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.OPTIMIZE_INDEX(IDX_NAME VARCHAR,OPTLEVEL VARCHAR,MAXTIME NUMBER,TOKEN VARCHAR,PART_NAME VARCHAR,TOKEN_TYPE NUMBER,PARALLEL_DEGREE NUMBER,MEMORY VARCHAR,BACKGROUND BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.POPULATE_PENDING(IDX_NAME VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.RECREATE_INDEX_ONLINE(IDX_NAME VARCHAR,PARAMETER_STRING VARCHAR,PARALLEL_DEGREE NUMBER,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_AUTO_OPTIMIZE(IDX_NAME VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_INDEX(SET_NAME VARCHAR,COLUMN_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_MDATA(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,MDATA_VALUE VARCHAR,MDATA_ROWID ROWID,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_MDATA(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,MDATA_VALUES ODCIVARCHAR2LIST,MDATA_ROWIDS ODCIRIDLIST,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_SDATA(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,SDATA_VALUE VARCHAR,SDATA_ROWID ROWID,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_SECTION(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_SECTION(GROUP_NAME VARCHAR,SECTION_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_STOPCLASS(STOPLIST_NAME VARCHAR,STOPCLASS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_STOPTHEME(STOPLIST_NAME VARCHAR,STOPTHEME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_STOPWORD(STOPLIST_NAME VARCHAR,STOPWORD VARCHAR,LANGUAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REMOVE_SUB_LEXER(LEXER_NAME VARCHAR,LANGUAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REM_SEC_GRP_ATTR_VAL(GROUP_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REPLACE_INDEX_METADATA(IDX_NAME VARCHAR,PARAMETER_STRING VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.REPOPULATE_DOLLARN(IDX_NAME VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.SET_ATTRIBUTE(PREFERENCE_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.SET_SECTION_ATTRIBUTE(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.SET_SEC_GRP_ATTR(GROUP_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.SPLIT_DOLLARI(IDX_NAME VARCHAR,PART_NAME VARCHAR,MAPPING_TAB VARCHAR,NAME_PREFIX VARCHAR,TSPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.SPLIT_ZONE_TOKENS(IDX_NAME VARCHAR,PART_NAME VARCHAR,SOURCE_SECTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.SYNC_INDEX(IDX_NAME VARCHAR,MEMORY VARCHAR,PART_NAME VARCHAR,PARALLEL_DEGREE NUMBER,MAXTIME NUMBER,LOCKING NUMBER,DIRECT_PATH BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.UNSET_ATTRIBUTE(PREFERENCE_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.UNSET_SECTION_ATTRIBUTE(GROUP_NAME VARCHAR,SECTION_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.UNSET_SEC_GRP_ATTR(GROUP_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.UPDATE_MVDATA_SET(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,MVDATA_VALUES ODCINUMBERLIST,MVDATA_ROWIDS ODCIRIDLIST,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.UPDATE_POLICY(POLICY_NAME VARCHAR,FILTER VARCHAR,SECTION_GROUP VARCHAR,LEXER VARCHAR,STOPLIST VARCHAR,WORDLIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.UPDATE_SDATA(IDX_NAME VARCHAR,SECTION_NAME VARCHAR,SDATA_VALUE ANYDATA,SDATA_ROWID ROWID,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.UPDATE_SUB_LEXER(LEXER_NAME VARCHAR,LANGUAGE VARCHAR,SUB_LEXER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_DDL.ZONE_TO_FIELD(IDX_NAME VARCHAR,PART_NAME VARCHAR,LEX_PREF VARCHAR,STORAGE_PREF VARCHAR,ATTR_VAL_TAB VARCHAR,MEMORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

