CREATE SCHEMA CTX_QUERY;

CREATE OR REPLACE PROCEDURE CTX_QUERY.BROWSE_WORDS(INDEX_NAME VARCHAR,SEED VARCHAR,RESTAB VARCHAR,BROWSE_ID NUMBER,NUMWORDS NUMBER,DIRECTION VARCHAR,PART_NAME VARCHAR,TOKEN_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_QUERY.BROWSE_WORDS(INDEX_NAME VARCHAR,SEED VARCHAR,NUMWORDS NUMBER,DIRECTION VARCHAR,PART_NAME VARCHAR,TOKEN_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_QUERY.CHK_TXNQRY_DISBL_SWITCH(TEXT_QUERY VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_QUERY.COUNT_HITS(INDEX_NAME VARCHAR,TEXT_QUERY VARCHAR,EXACT BOOLEAN,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION CTX_QUERY.COUNT_HITS_CLOB_QUERY(INDEX_NAME VARCHAR,TEXT_QUERY CLOB,EXACT BOOLEAN,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_QUERY.EXPLAIN(INDEX_NAME VARCHAR,TEXT_QUERY VARCHAR,EXPLAIN_TABLE VARCHAR,SHARELEVEL NUMBER,EXPLAIN_ID VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_QUERY.EXPLAIN_CLOB_QUERY(INDEX_NAME VARCHAR,TEXT_QUERY CLOB,EXPLAIN_TABLE VARCHAR,SHARELEVEL NUMBER,EXPLAIN_ID VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION CTX_QUERY.FCONTAINS(TEXT_VALUE VARCHAR,TEXT_QUERY VARCHAR,POLICY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE CTX_QUERY.HFEEDBACK(INDEX_NAME VARCHAR,TEXT_QUERY VARCHAR,FEEDBACK_TABLE VARCHAR,SHARELEVEL NUMBER,FEEDBACK_ID VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_QUERY.HFEEDBACK_CLOB_QUERY(INDEX_NAME VARCHAR,TEXT_QUERY CLOB,FEEDBACK_TABLE VARCHAR,SHARELEVEL NUMBER,FEEDBACK_ID VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_QUERY.REMOVE_SQE(QUERY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_QUERY.RESULT_SET(INDEX_NAME VARCHAR,QUERY VARCHAR,RESULT_SET_DESCRIPTOR CLOB,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_QUERY.RESULT_SET_CLOB_QUERY(INDEX_NAME VARCHAR,QUERY CLOB,RESULT_SET_DESCRIPTOR CLOB,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_QUERY.STORE_SQE(QUERY_NAME VARCHAR,TEXT_QUERY VARCHAR,DURATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE CTX_QUERY.STORE_SQE_CLOB_QUERY(QUERY_NAME VARCHAR,TEXT_QUERY CLOB,DURATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

