CREATE SCHEMA DBMS_DDL;

CREATE OR REPLACE PROCEDURE DBMS_DDL.ALTER_COMPILE(TYPE VARCHAR,SCHEMA VARCHAR,NAME VARCHAR,REUSE_SETTINGS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DDL.ALTER_TABLE_NOT_REFERENCEABLE(TABLE_NAME VARCHAR,TABLE_SCHEMA VARCHAR,AFFECTED_SCHEMA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DDL.ALTER_TABLE_REFERENCEABLE(TABLE_NAME VARCHAR,TABLE_SCHEMA VARCHAR,AFFECTED_SCHEMA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DDL.ANALYZE_OBJECT(TYPE VARCHAR,SCHEMA VARCHAR,NAME VARCHAR,METHOD VARCHAR,ESTIMATE_ROWS NUMBER,ESTIMATE_PERCENT NUMBER,METHOD_OPT VARCHAR,PARTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DDL.CREATE_WRAPPED(DDL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DDL.CREATE_WRAPPED(LB NUMBER,UB NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DDL.CREATE_WRAPPED(LB NUMBER,UB NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DDL.IS_TRIGGER_FIRE_ONCE(TRIG_OWNER VARCHAR,TRIG_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DDL.IS_TRIGGER_FIRE_ONCE_INTERNAL(TRIG_OWNER VARCHAR,TRIG_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DDL.SET_TRIGGER_FIRING_PROPERTY(TRIG_OWNER VARCHAR,TRIG_NAME VARCHAR,FIRE_ONCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DDL.SET_TRIGGER_FIRING_PROPERTY(TRIG_OWNER VARCHAR,TRIG_NAME VARCHAR,PROPERTY NUMBER,SETTING BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DDL.WRAP(DDL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DDL.WRAP(LB NUMBER,UB NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DDL.WRAP(LB NUMBER,UB NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

