CREATE SCHEMA DBMS_REDEFINITION;

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.ABORT_REDEF_TABLE(UNAME VARCHAR,ORIG_TABLE VARCHAR,INT_TABLE VARCHAR,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.CAN_REDEF_TABLE(UNAME VARCHAR,TNAME VARCHAR,OPTIONS_FLAG NUMBER,PART_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS(UNAME VARCHAR,ORIG_TABLE VARCHAR,INT_TABLE VARCHAR,COPY_INDEXES NUMBER,COPY_TRIGGERS BOOLEAN,COPY_CONSTRAINTS BOOLEAN,COPY_PRIVILEGES BOOLEAN,IGNORE_ERRORS BOOLEAN,COPY_STATISTICS BOOLEAN,COPY_MVLOG BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.FINISH_REDEF_TABLE(UNAME VARCHAR,ORIG_TABLE VARCHAR,INT_TABLE VARCHAR,PART_NAME VARCHAR,DML_LOCK_TIMEOUT NUMBER,CONTINUE_AFTER_ERRORS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.REDEF_TABLE(UNAME VARCHAR,TNAME VARCHAR,TABLE_COMPRESSION_TYPE VARCHAR,TABLE_PART_TABLESPACE VARCHAR,INDEX_KEY_COMPRESSION_TYPE VARCHAR,INDEX_TABLESPACE VARCHAR,LOB_COMPRESSION_TYPE VARCHAR,LOB_TABLESPACE VARCHAR,LOB_STORE_AS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.REGISTER_DEPENDENT_OBJECT(UNAME VARCHAR,ORIG_TABLE VARCHAR,INT_TABLE VARCHAR,DEP_TYPE NUMBER,DEP_OWNER VARCHAR,DEP_ORIG_NAME VARCHAR,DEP_INT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.START_REDEF_TABLE(UNAME VARCHAR,ORIG_TABLE VARCHAR,INT_TABLE VARCHAR,COL_MAPPING VARCHAR,OPTIONS_FLAG NUMBER,ORDERBY_COLS VARCHAR,PART_NAME VARCHAR,COPY_VPD_OPT NUMBER,CONTINUE_AFTER_ERRORS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.SYNC_INTERIM_TABLE(UNAME VARCHAR,ORIG_TABLE VARCHAR,INT_TABLE VARCHAR,PART_NAME VARCHAR,CONTINUE_AFTER_ERRORS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REDEFINITION.UNREGISTER_DEPENDENT_OBJECT(UNAME VARCHAR,ORIG_TABLE VARCHAR,INT_TABLE VARCHAR,DEP_TYPE NUMBER,DEP_OWNER VARCHAR,DEP_ORIG_NAME VARCHAR,DEP_INT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

