CREATE SCHEMA DBMS_UTILITY;

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.ACTIVE_INSTANCES()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.ANALYZE_DATABASE(METHOD VARCHAR,ESTIMATE_ROWS NUMBER,ESTIMATE_PERCENT NUMBER,METHOD_OPT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.ANALYZE_PART_OBJECT(SCHEMA VARCHAR,OBJECT_NAME VARCHAR,OBJECT_TYPE CHAR,COMMAND_TYPE CHAR,COMMAND_OPT VARCHAR,SAMPLE_CLAUSE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.ANALYZE_SCHEMA(SCHEMA VARCHAR,METHOD VARCHAR,ESTIMATE_ROWS NUMBER,ESTIMATE_PERCENT NUMBER,METHOD_OPT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.CANONICALIZE(NAME VARCHAR,CANON_LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.COMMA_TO_TABLE(LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.COMMA_TO_TABLE(LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.COMPILE_SCHEMA(SCHEMA VARCHAR,COMPILE_ALL BOOLEAN,REUSE_SETTINGS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.CREATE_ALTER_TYPE_ERROR_TABLE(SCHEMA_NAME VARCHAR,TABLE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_UTILITY.CURRENT_INSTANCE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.DATA_BLOCK_ADDRESS_FILE(DBA NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.DB_VERSION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.EXEC_DDL_STATEMENT(PARSE_STRING VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.EXPAND_SQL_TEXT(INPUT_SQL_TEXT CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_UTILITY.FORMAT_CALL_STACK()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.FORMAT_ERROR_BACKTRACE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.FORMAT_ERROR_STACK()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.GET_CPU_TIME(SCHEMA VARCHAR,NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.GET_ENDIANNESS(BASE NUMBER,HASH_SIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.GET_PARAMETER_VALUE(PARNAM VARCHAR,LISTNO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.GET_SQL_HASH(NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.GET_TIME()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.INVALIDATE(P_OBJECT_ID NUMBER,P_PLSQL_OBJECT_SETTINGS VARCHAR,P_OPTION_FLAGS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_UTILITY.IS_BIT_SET(R RAW,N NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.IS_CLUSTER_DATABASE(BLOCK NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.NAME_RESOLVE(NAME VARCHAR,CONTEXT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.NAME_TOKENIZE(NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_UTILITY.OLD_CURRENT_SCHEMA()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.OLD_CURRENT_USER()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_UTILITY.PORT_STRING()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.TABLE_TO_COMMA()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.TABLE_TO_COMMA()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.VALIDATE(OBJECT_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_UTILITY.VALIDATE(OWNER VARCHAR,OBJNAME VARCHAR,NAMESPACE NUMBER,EDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_UTILITY.WAIT_ON_PENDING_DML(TABLES VARCHAR,TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

