CREATE SCHEMA DBMS_DATAPUMP;

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.ADD_DEVICE(HANDLE NUMBER,DEVICENAME VARCHAR,VOLUMESIZE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.ADD_FILE(HANDLE NUMBER,FILENAME VARCHAR,DIRECTORY VARCHAR,FILESIZE VARCHAR,FILETYPE NUMBER,REUSEFILE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DATAPUMP.ATTACH(JOB_NAME VARCHAR,JOB_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.CLIENT_LOB_APPEND(VALUE VARCHAR,POSITION NUMBER,AS_IS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.CLIENT_LOB_DELETE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DATAPUMP.CLIENT_LOB_GET(JOB_NAME VARCHAR,VIEW_NAME VARCHAR,VIEW_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.CREATE_JOB_VIEW(HANDLE NUMBER,VIEW_NAME VARCHAR,VIEW_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DATAPUMP.DATAPUMP_JOB(NAME VARCHAR,VALUE NUMBER,TABLE_NAME VARCHAR,SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.DATA_FILTER(HANDLE NUMBER,NAME VARCHAR,VALUE CLOB,TABLE_NAME VARCHAR,SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.DATA_FILTER(HANDLE NUMBER,NAME VARCHAR,VALUE VARCHAR,TABLE_NAME VARCHAR,SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.DATA_REMAP(HANDLE NUMBER,NAME VARCHAR,TABLE_NAME VARCHAR,COLUMN VARCHAR,FUNCTION VARCHAR,SCHEMA VARCHAR,REMAP_FLAGS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.DETACH(HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.DH_KEY_EXCHANGE(HANDLE NUMBER,A VARCHAR,B VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.ESTABLISH_REMOTE_CONTEXT(WORKER_ID NUMBER,REMOTE_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.GET_DUMPFILE_INFO(FILENAME VARCHAR,DIRECTORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DATAPUMP.GET_STATUS(HANDLE NUMBER,MASK NUMBER(38),TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.GET_STATUS(HANDLE NUMBER,MASK NUMBER(38),TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.GET_STATUS(HANDLE NUMBER,MASK NUMBER(38),TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.GET_STATUS(HANDLE NUMBER,MASK NUMBER(38),TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.GET_STATUS(HANDLE NUMBER,MASK NUMBER(38),TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DATAPUMP.GET_STATUS_VERSION(VERSION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATAPUMP.HAS_PRIVS(OPER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.LOG_ENTRY(HANDLE NUMBER,MESSAGE VARCHAR,LOG_FILE_ONLY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.LOG_ERROR(HANDLE NUMBER,MESSAGE VARCHAR,ERROR_NUMBER NUMBER,FATAL_ERROR NUMBER,LOG_FILE_ONLY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.METADATA_FILTER(HANDLE NUMBER,NAME VARCHAR,VALUE VARCHAR,OBJECT_PATH VARCHAR,OBJECT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.METADATA_FILTER(HANDLE NUMBER,NAME VARCHAR,VALUE CLOB,OBJECT_PATH VARCHAR,OBJECT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.METADATA_REMAP(HANDLE NUMBER,NAME VARCHAR,OLD_VALUE VARCHAR,VALUE VARCHAR,OBJECT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.METADATA_TRANSFORM(HANDLE NUMBER,NAME VARCHAR,VALUE VARCHAR,OBJECT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.METADATA_TRANSFORM(HANDLE NUMBER,NAME VARCHAR,VALUE NUMBER,OBJECT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DATAPUMP.OPEN(OPERATION VARCHAR,JOB_MODE VARCHAR,REMOTE_LINK VARCHAR,JOB_NAME VARCHAR,VERSION VARCHAR,COMPRESSION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.SETUP_REMOTE_CONTEXT(USER_NAME VARCHAR,JOB_NAME VARCHAR,VERSION NUMBER,STATUS_XML VARCHAR,STATUS_XML_LEN NUMBER,MORE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.SET_DEBUG(ON_OFF NUMBER,IP_ADDR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.SET_DEBUG(DEBUG_FLAGS NUMBER,VERSION_FLAG NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.SET_PARALLEL(HANDLE NUMBER,DEGREE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.SET_PARAMETER(HANDLE NUMBER,NAME VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.SET_PARAMETER(HANDLE NUMBER,NAME VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.SET_REMOTE_WORKER(WORKER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.START_JOB(HANDLE NUMBER,SKIP_CURRENT NUMBER,ABORT_STEP NUMBER,CLUSTER_OK NUMBER,SERVICE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.STOP_JOB(HANDLE NUMBER,IMMEDIATE NUMBER,KEEP_MASTER NUMBER,DELAY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.TEST_REMOTE_CONTEXT1010()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.TEST_REMOTE_CONTEXT1020()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.TEST_REMOTE_CONTEXT1120()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.TEST_REMOTE_CONTEXT1210(MSG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATAPUMP.WAIT_FOR_JOB(HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

