CREATE SCHEMA DBMS_REPCAT_ADMIN;

CREATE OR REPLACE FUNCTION DBMS_REPCAT_ADMIN.BIC(FLAG NUMBER,BIT_OFFSET NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPCAT_ADMIN.BIS(FLAG NUMBER,BIT_OFFSET NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.CHECK_REPCAT_PRIVS(REPUSER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.DO_SQL(STATEMENT VARCHAR,RESIGNAL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.GRANT_ADMIN_ANY_REPGROUP(USERID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.GRANT_ADMIN_ANY_REPSCHEMA(USERID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.GRANT_ADMIN_ANY_SCHEMA(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.GRANT_ADMIN_REPGROUP(USERID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.GRANT_ADMIN_REPSCHEMA(USERID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.GRANT_ADMIN_SCHEMA(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.GRANT_PROXY_SNAPADMIN_PRIVS(CANON_GNAME VARCHAR,CANON_SNAME VARCHAR,CANON_ONAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.GRANT_SNAPADMIN_PROXY(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REGISTER_REPCAT_PRIVS(USERNAME VARCHAR,GRANTS BOOLEAN,PRIV_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REGISTER_USER_REPGROUP(USERNAME VARCHAR,PRIVILEGE_TYPE VARCHAR,LIST_OF_GNAMES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REGISTER_USER_REPGROUP(USERNAME VARCHAR,PRIVILEGE_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPCAT_ADMIN.REPCAT_ISDBA(SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPCAT_ADMIN.REPGROUP_PRIVS_FUN(SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REVOKE_ADMIN_ANY_REPGROUP(USERID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REVOKE_ADMIN_ANY_REPSCHEMA(USERID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REVOKE_ADMIN_ANY_SCHEMA(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REVOKE_ADMIN_REPGROUP(USERID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REVOKE_ADMIN_REPSCHEMA(USERID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REVOKE_ADMIN_SCHEMA(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.REVOKE_SNAPADMIN_PROXY(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.UNREGISTER_USER_REPGROUP(USERNAME VARCHAR,PRIVILEGE_TYPE VARCHAR,LIST_OF_GNAMES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT_ADMIN.UNREGISTER_USER_REPGROUP(USERNAME VARCHAR,PRIVILEGE_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

