CREATE SCHEMA DBMS_WARNING;

CREATE OR REPLACE PROCEDURE DBMS_WARNING.ADD_WARNING_SETTING_CAT(WARNING_CATEGORY VARCHAR,WARNING_VALUE VARCHAR,SCOPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WARNING.ADD_WARNING_SETTING_NUM(WARNING_NUMBER NUMBER,WARNING_VALUE VARCHAR,SCOPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WARNING.GET_CATEGORY(WARNING_NUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WARNING.GET_WARNING_SETTING_CAT(WARNING_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WARNING.GET_WARNING_SETTING_NUM(WARNING_NUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WARNING.GET_WARNING_SETTING_STRING(SCOPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

