CREATE SCHEMA DBMS_AQADM;

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ADD_ALIAS_TO_LDAP(ALIAS VARCHAR,OBJ_LOCATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ADD_CONNECTION_TO_LDAP(CONNECTION VARCHAR,HOST VARCHAR,PORT NUMBER,SID VARCHAR,DRIVER VARCHAR,TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ADD_CONNECTION_TO_LDAP(CONNECTION VARCHAR,JDBC_STRING VARCHAR,USERNAME VARCHAR,PASSWORD VARCHAR,TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ADD_SUBSCRIBER(QUEUE_NAME VARCHAR,SUBSCRIBER AQ$_AGENT,RULE VARCHAR,TRANSFORMATION VARCHAR,QUEUE_TO_QUEUE BOOLEAN,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ALTER_AQ_AGENT(AGENT_NAME VARCHAR,CERTIFICATE_LOCATION VARCHAR,ENABLE_HTTP BOOLEAN,ENABLE_SMTP BOOLEAN,ENABLE_ANYP BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ALTER_PROPAGATION_SCHEDULE(QUEUE_NAME VARCHAR,DESTINATION VARCHAR,DURATION NUMBER,NEXT_TIME VARCHAR,LATENCY NUMBER,DESTINATION_QUEUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ALTER_QUEUE(QUEUE_NAME VARCHAR,MAX_RETRIES NUMBER,RETRY_DELAY NUMBER,RETENTION_TIME NUMBER,AUTO_COMMIT BOOLEAN,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ALTER_QUEUE_TABLE(QUEUE_TABLE VARCHAR,COMMENT VARCHAR,PRIMARY_INSTANCE NUMBER,SECONDARY_INSTANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ALTER_SUBSCRIBER(QUEUE_NAME VARCHAR,SUBSCRIBER AQ$_AGENT,RULE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ALTER_SUBSCRIBER(QUEUE_NAME VARCHAR,SUBSCRIBER AQ$_AGENT,RULE VARCHAR,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_AQADM.AQ$_PROPAQ(JOB NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_AQADM.AQ$_PROPAQ(JOB NUMBER,NEXT_DATE DATE,QNAME VARCHAR,SCHEMA VARCHAR,DESTINATION VARCHAR,TOID_CHAR VARCHAR,VERSION_CHAR VARCHAR,START_TIME VARCHAR,DURATION VARCHAR,NEXT_TIME VARCHAR,LATENCY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_AQADM.CREATE_AQ_AGENT(AGENT_NAME VARCHAR,CERTIFICATE_LOCATION VARCHAR,ENABLE_HTTP BOOLEAN,ENABLE_SMTP BOOLEAN,ENABLE_ANYP BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.CREATE_NP_QUEUE(QUEUE_NAME VARCHAR,MULTIPLE_CONSUMERS BOOLEAN,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.CREATE_QUEUE(QUEUE_NAME VARCHAR,QUEUE_TABLE VARCHAR,QUEUE_TYPE NUMBER,MAX_RETRIES NUMBER,RETRY_DELAY NUMBER,RETENTION_TIME NUMBER,DEPENDENCY_TRACKING BOOLEAN,COMMENT VARCHAR,AUTO_COMMIT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.CREATE_QUEUE_TABLE(QUEUE_TABLE VARCHAR,QUEUE_PAYLOAD_TYPE VARCHAR,STORAGE_CLAUSE VARCHAR,SORT_LIST VARCHAR,MULTIPLE_CONSUMERS BOOLEAN,MESSAGE_GROUPING NUMBER,COMMENT VARCHAR,AUTO_COMMIT BOOLEAN,PRIMARY_INSTANCE NUMBER,SECONDARY_INSTANCE NUMBER,COMPATIBLE VARCHAR,NON_REPUDIATION NUMBER,SECURE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.CREATE_SHARDED_QUEUE(QUEUE_NAME VARCHAR,STORAGE_CLAUSE VARCHAR,MULTIPLE_CONSUMERS BOOLEAN,MAX_RETRIES NUMBER,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.DEL_ALIAS_FROM_LDAP(ALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.DEL_CONNECTION_FROM_LDAP(CONNECTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.DISABLE_DB_ACCESS(AGENT_NAME VARCHAR,DB_USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.DISABLE_PROPAGATION_SCHEDULE(QUEUE_NAME VARCHAR,DESTINATION VARCHAR,DESTINATION_QUEUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.DROP_AQ_AGENT(AGENT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.DROP_QUEUE(QUEUE_NAME VARCHAR,AUTO_COMMIT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.DROP_QUEUE_TABLE(QUEUE_TABLE VARCHAR,FORCE BOOLEAN,AUTO_COMMIT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.DROP_SHARDED_QUEUE(QUEUE_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ENABLE_DB_ACCESS(AGENT_NAME VARCHAR,DB_USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ENABLE_JMS_TYPES(QUEUE_TABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.ENABLE_PROPAGATION_SCHEDULE(QUEUE_NAME VARCHAR,DESTINATION VARCHAR,DESTINATION_QUEUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GET_MAX_STREAMS_POOL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GET_MIN_STREAMS_POOL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GET_PROP_SEQNO(QID NUMBER,DQNAME VARCHAR,DBNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GET_REPLAY_INFO(QUEUE_NAME VARCHAR,SENDER_AGENT AQ$_AGENT,REPLAY_ATTRIBUTE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GET_TYPE_INFO(SCHEMA VARCHAR,QNAME VARCHAR,GETTDS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GET_TYPE_INFO(SCHEMA VARCHAR,QNAME VARCHAR,GETTDS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GET_WATERMARK()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GRANT_QUEUE_PRIVILEGE(PRIVILEGE VARCHAR,QUEUE_NAME VARCHAR,GRANTEE VARCHAR,GRANT_OPTION BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE(PRIVILEGE VARCHAR,GRANTEE VARCHAR,ADMIN_OPTION BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.GRANT_TYPE_ACCESS(USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.MIGRATE_QUEUE_TABLE(QUEUE_TABLE VARCHAR,COMPATIBLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.NONREPUDIATE_RECEIVER(QUEUE_NAME VARCHAR,MSGID RAW,RCVER_INFO AQ$_AGENT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.NONREPUDIATE_RECEIVER(QUEUE_NAME VARCHAR,MSGID RAW,RCVER_INFO AQ$_AGENT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.NONREPUDIATE_SENDER(QUEUE_NAME VARCHAR,MSGID RAW,SENDER_INFO AQ$_AGENT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.NONREPUDIATE_SENDER(QUEUE_NAME VARCHAR,MSGID RAW,SENDER_INFO AQ$_AGENT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.PURGE_QUEUE_TABLE(QUEUE_TABLE VARCHAR,PURGE_CONDITION VARCHAR,PURGE_OPTIONS VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_AQADM.QUEUE_SUBSCRIBERS(QUEUE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_AQADM.RECOVER_PROPAGATION(SCHEMA VARCHAR,QUEUE_NAME VARCHAR,DESTINATION VARCHAR,PROTOCOL NUMBER,URL VARCHAR,USERNAME VARCHAR,PASSWD VARCHAR,TRACE NUMBER,DESTQ NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.REMOVE_SUBSCRIBER(QUEUE_NAME VARCHAR,SUBSCRIBER AQ$_AGENT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.RESET_REPLAY_INFO(QUEUE_NAME VARCHAR,SENDER_AGENT AQ$_AGENT,REPLAY_ATTRIBUTE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.REVOKE_QUEUE_PRIVILEGE(PRIVILEGE VARCHAR,QUEUE_NAME VARCHAR,GRANTEE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.REVOKE_SYSTEM_PRIVILEGE(PRIVILEGE VARCHAR,GRANTEE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.SCHEDULE_PROPAGATION(QUEUE_NAME VARCHAR,DESTINATION VARCHAR,DURATION NUMBER,NEXT_TIME VARCHAR,LATENCY NUMBER,DESTINATION_QUEUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.SET_MAX_STREAMS_POOL(VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.SET_MIN_STREAMS_POOL(VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.SET_WATERMARK(WMVALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.START_QUEUE(QUEUE_NAME VARCHAR,ENQUEUE BOOLEAN,DEQUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.START_TIME_MANAGER(ENQUEUE BOOLEAN,DEQUEUE BOOLEAN,WAIT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.STOP_TIME_MANAGER(DESTINATION VARCHAR,DESTINATION_QUEUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.VERIFY_QUEUE_TYPES(SRC_QUEUE_NAME VARCHAR,DEST_QUEUE_NAME VARCHAR,DESTINATION VARCHAR,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.VERIFY_QUEUE_TYPES_GET_NRP(SRC_QUEUE_NAME VARCHAR,DEST_QUEUE_NAME VARCHAR,DESTINATION VARCHAR,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQADM.VERIFY_QUEUE_TYPES_NO_QUEUE(SRC_QUEUE_NAME VARCHAR,DEST_QUEUE_NAME VARCHAR,DESTINATION VARCHAR,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

