CREATE SCHEMA DBMS_ADDM;

CREATE OR REPLACE PROCEDURE DBMS_ADDM.ANALYZE_DB(BEGIN_SNAPSHOT NUMBER,END_SNAPSHOT NUMBER,DB_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.ANALYZE_INST(BEGIN_SNAPSHOT NUMBER,END_SNAPSHOT NUMBER,INSTANCE_NUMBER NUMBER,DB_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.ANALYZE_PARTIAL(INSTANCE_NUMBERS VARCHAR,BEGIN_SNAPSHOT NUMBER,END_SNAPSHOT NUMBER,DB_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_ADDM.COMPARE_CAPTURE_REPLAY_REPORT(REPLAY_ID NUMBER,REPORT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ADDM.COMPARE_DATABASES(BASE_DBID NUMBER,BASE_BEGIN_SNAP_ID NUMBER,BASE_END_SNAP_ID NUMBER,COMP_DBID NUMBER,COMP_BEGIN_SNAP_ID NUMBER,COMP_END_SNAP_ID NUMBER,REPORT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ADDM.COMPARE_INSTANCES(BASE_DBID NUMBER,BASE_INSTANCE_ID NUMBER,BASE_BEGIN_SNAP_ID NUMBER,BASE_END_SNAP_ID NUMBER,COMP_DBID NUMBER,COMP_INSTANCE_ID NUMBER,COMP_BEGIN_SNAP_ID NUMBER,COMP_END_SNAP_ID NUMBER,REPORT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ADDM.COMPARE_REPLAY_REPLAY_REPORT(REPLAY_ID1 NUMBER,REPLAY_ID2 NUMBER,REPORT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_ADDM.DELETE(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.DELETE_FINDING_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.DELETE_PARAMETER_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.DELETE_SEGMENT_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.DELETE_SQL_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_ADDM.GET_ASH_QUERY(TASK_NAME VARCHAR,FINDING_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ADDM.GET_REPORT(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_ADDM.INSERT_FINDING_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR,FINDING_NAME VARCHAR,MIN_ACTIVE_SESSIONS NUMBER,MIN_PERC_IMPACT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.INSERT_PARAMETER_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR,PARAMETER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.INSERT_SEGMENT_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR,OWNER_NAME VARCHAR,OBJECT_NAME VARCHAR,SUB_OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.INSERT_SEGMENT_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR,OBJECT_NUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADDM.INSERT_SQL_DIRECTIVE(TASK_NAME VARCHAR,DIR_NAME VARCHAR,SQL_ID VARCHAR,MIN_ACTIVE_SESSIONS NUMBER,MIN_RESPONSE_TIME NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_ADDM.REAL_TIME_ADDM_REPORT()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

