CREATE SCHEMA DBMS_REPORT;

CREATE OR REPLACE FUNCTION DBMS_REPORT.BUILD_GENERIC_TAG(TAG_NAME VARCHAR,TAG_INPUTS UNDEFINED)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.BUILD_REPORT_REFERENCE_STRUCT(COMPONENT_NAME VARCHAR,REPORT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.BUILD_REPORT_REFERENCE_VARG(COMPONENT_NAME VARCHAR,REPORT_NAME VARCHAR,ID_PARAM_VAL UNDEFINED)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPORT.CLEAR_FRAMEWORK(COMPONENT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPORT.FORMAT_MESSAGE(MESSAGE_NUMBER NUMBER,MESSAGE_FACILITY VARCHAR,LANGUAGE VARCHAR,ARG1 VARCHAR,ARG2 VARCHAR,ARG3 VARCHAR,ARG4 VARCHAR,ARG5 VARCHAR,ARG6 VARCHAR,ARG7 VARCHAR,ARG8 VARCHAR,ARG9 VARCHAR,ARG10 VARCHAR,ARG11 VARCHAR,ARG12 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.FORMAT_REPORT(REPORT XMLTYPE,FORMAT_NAME VARCHAR,COMPRESS_XML NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.FORMAT_REPORT(REPORT XMLTYPE,FORMAT_NAME VARCHAR,COMPRESS_XML NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPORT.GET_AWR_CONTEXT(P_START_TIME DATE,P_END_TIME DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPORT.GET_IMPORTED_REPORT_ATTRS(P_DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPORT.GET_PARAM(PARAM_NAME VARCHAR,MANDATORY BOOLEAN,DEFAULT_VALUE CLOB,NULLABLE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.GET_REPORT(REPORT_REFERENCE VARCHAR,COMPRESS_XML NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.GET_REPORT(REPORT_REFERENCE VARCHAR,COMPRESS_XML NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.GET_REPORT_WITH_SUMMARY(REPORT_REFERENCE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.GET_SNAP_ID(P_TIME DATE,P_DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPORT.GET_TIMING_INFO(PHASE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPORT.GZIP_REPORT_XML(REPORT CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.LOOKUP_COMPONENT_ID(COMPONENT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.LOOKUP_REPORT_ID(COMPONENT_NAME VARCHAR,REPORT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPORT.PARSE_REPORT_REFERENCE(REPORT_REFERENCE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPORT.REGISTER_COMPONENT(COMPONENT_NAME VARCHAR,COMPONENT_DESC VARCHAR,COMPONENT_OBJECT WRI$_REPT_ABSTRACT_T)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPORT.REGISTER_CUSTOM_FORMAT(COMPONENT_NAME VARCHAR,REPORT_NAME VARCHAR,FORMAT_NAME VARCHAR,FORMAT_DESC VARCHAR,FORMAT_CONTENT_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPORT.REGISTER_REPORT(COMPONENT_NAME VARCHAR,REPORT_NAME VARCHAR,REPORT_DESC VARCHAR,SCHEMA_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPORT.REGISTER_SWF(COMPONENT_NAME VARCHAR,REPORT_NAME VARCHAR,SWF_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPORT.REGISTER_TEXT_FORMAT(COMPONENT_NAME VARCHAR,REPORT_NAME VARCHAR,FORMAT_NAME VARCHAR,FORMAT_DESC VARCHAR,HTML_STYLESHEET_ID NUMBER,TEXT_MAX_LINESIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPORT.REGISTER_XSLT_FORMAT(COMPONENT_NAME VARCHAR,REPORT_NAME VARCHAR,FORMAT_NAME VARCHAR,FORMAT_DESC VARCHAR,FORMAT_CONTENT_TYPE NUMBER,STYLESHEET_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPORT.RESTORE_REPORT_ENV(ORIG_ENV FORMAT_PARAM_VALUES)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPORT.SETUP_REPORT_ENV()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.TRANSFORM_HTML_TO_TEXT(DOCUMENT XMLTYPE,MAX_LINESIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.TRANSFORM_REPORT_XML(REPORT_XML XMLTYPE,ZLIB2BASE64 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPORT.VALIDATE_REPORT(REPORT XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPORT.ZLIB2BASE64_CLOB(REPORT CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPORT.ZLIB2BASE64_REPORT_XML(REPORT_XML XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

