CREATE SCHEMA DBMS_AQIN;

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_ALTER_QUEUE(QUEUE_NAME VARCHAR,MAX_RETRIES NUMBER,RETRY_DELAY NUMBER,RETENTION_TIME NUMBER,AUTO_COMMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_CREATE_QUEUE(QUEUE_NAME VARCHAR,QUEUE_TABLE VARCHAR,QUEUE_TYPE NUMBER,MAX_RETRIES NUMBER,RETRY_DELAY NUMBER,RETENTION_TIME NUMBER,DEPENDENCY_TRACKING NUMBER,COMMENT VARCHAR,AUTO_COMMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_CREATE_QUEUE_TABLE(QUEUE_TABLE VARCHAR,QUEUE_PAYLOAD_TYPE VARCHAR,STORAGE_CLAUSE VARCHAR,SORT_LIST VARCHAR,MULTIPLE_CONSUMERS NUMBER,MESSAGE_GROUPING NUMBER,COMMENT VARCHAR,AUTO_COMMIT NUMBER,PRIMARY_INSTANCE NUMBER,SECONDARY_INSTANCE NUMBER,COMPATIBLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DEQUEUE_IN(QUEUE_NAME VARCHAR,SUBSCRIBER VARCHAR,MSGID RAW,CORRELATION VARCHAR,DEQUEUE_MODE NUMBER,NAVIGATION NUMBER,VISIBILITY NUMBER,WAIT NUMBER,PAYLOAD_TYPE NUMBER,DEQ_COND VARCHAR,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DEQUEUE_IN(QUEUE_NAME VARCHAR,SUBSCRIBER VARCHAR,MSGID RAW,CORRELATION VARCHAR,DEQUEUE_MODE NUMBER,NAVIGATION NUMBER,VISIBILITY NUMBER,WAIT NUMBER,PAYLOAD_TYPE NUMBER,DEQ_COND VARCHAR,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DEQUEUE_IN(QUEUE_NAME VARCHAR,SUBSCRIBER VARCHAR,MSGID RAW,CORRELATION VARCHAR,DEQUEUE_MODE NUMBER,NAVIGATION NUMBER,VISIBILITY NUMBER,WAIT NUMBER,PAYLOAD_TYPE NUMBER,DEQ_COND VARCHAR,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DEQUEUE_IN(QUEUE_NAME VARCHAR,SUBSCRIBER VARCHAR,MSGID RAW,CORRELATION VARCHAR,DEQUEUE_MODE NUMBER,NAVIGATION NUMBER,VISIBILITY NUMBER,WAIT NUMBER,PAYLOAD_TYPE NUMBER,DEQ_COND VARCHAR,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DEQUEUE_IN(QUEUE_NAME VARCHAR,SUBSCRIBER VARCHAR,MSGID RAW,CORRELATION VARCHAR,DEQUEUE_MODE NUMBER,NAVIGATION NUMBER,VISIBILITY NUMBER,WAIT NUMBER,PAYLOAD_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DEQUEUE_RAW(QUEUE_NAME VARCHAR,SUBSCRIBER VARCHAR,MSGID RAW,CORRELATION VARCHAR,DEQUEUE_MODE NUMBER,NAVIGATION NUMBER,VISIBILITY NUMBER,WAIT NUMBER,PAYLOAD_TYPE NUMBER,DEQ_COND VARCHAR,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DEQUEUE_RAW(QUEUE_NAME VARCHAR,SUBSCRIBER VARCHAR,MSGID RAW,CORRELATION VARCHAR,DEQUEUE_MODE NUMBER,NAVIGATION NUMBER,VISIBILITY NUMBER,WAIT NUMBER,PAYLOAD_TYPE NUMBER,DEQ_COND VARCHAR,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DROP_QUEUE(QUEUE_NAME VARCHAR,AUTO_COMMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_DROP_QUEUE_TABLE(QUEUE_TABLE VARCHAR,FORCE NUMBER,AUTO_COMMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_ENQUEUE_OBJ(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,OBJECT_USER_DATA <ADT_1>,RECIPIENTS AQ$_RECIPIENTS,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_ENQUEUE_OBJ(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,OBJECT_USER_DATA <OPAQUE_1>,RECIPIENTS AQ$_RECIPIENTS,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_ENQUEUE_OBJ_NO_RECPL(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,OBJECT_USER_DATA <ADT_1>,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_ENQUEUE_OBJ_NO_RECPL(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,OBJECT_USER_DATA <OPAQUE_1>,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_ENQUEUE_RAW(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,OBJECT_USER_DATA <ADT_1>,RECIPIENTS AQ$_RECIPIENTS,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_ENQUEUE_RAW_NO_RECPL(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_AQIN.AQ$_GETBLOB_FROM_JMSANYDATA(AD ANYDATA)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_AQIN.AQ$_GETCLOB_FROM_JMSANYDATA(AD ANYDATA)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_JMS_ENQUEUE_BYTES_MESSAGE(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,BYTES_MESSAGE AQ$_JMS_BYTES_MESSAGE,RECIPIENTS AQ$_RECIPIENTS,GEN_PAYLOAD NUMBER,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,CREATE_NEW_LOB NUMBER,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_JMS_ENQUEUE_MAP_MESSAGE(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,MAP_MESSAGE AQ$_JMS_MAP_MESSAGE,RECIPIENTS AQ$_RECIPIENTS,GEN_PAYLOAD NUMBER,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,CREATE_NEW_LOB NUMBER,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_JMS_ENQUEUE_OBJECT_MESSAGE(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,OBJECT_MESSAGE AQ$_JMS_OBJECT_MESSAGE,RECIPIENTS AQ$_RECIPIENTS,GEN_PAYLOAD NUMBER,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,CREATE_NEW_LOB NUMBER,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_JMS_ENQUEUE_STREAM_MESSAGE(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,STREAM_MESSAGE AQ$_JMS_STREAM_MESSAGE,RECIPIENTS AQ$_RECIPIENTS,GEN_PAYLOAD NUMBER,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,CREATE_NEW_LOB NUMBER,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_JMS_ENQUEUE_TEXT_MESSAGE(QUEUE_NAME VARCHAR,SENDER_NAME VARCHAR,SENDER_ADDR VARCHAR,SENDER_PROTOCOL NUMBER,ORIGINAL_MSGID RAW,CORRELATION VARCHAR,VISIBILITY NUMBER,PRIORITY NUMBER,DELAY NUMBER,EXPIRATION NUMBER,RELATIVE_MSGID RAW,SEQUENCE_DEVIATION NUMBER,EXCEPTION_QUEUE VARCHAR,PAYLOAD_TYPE NUMBER,RAW_USER_DATA RAW,TEXT_MESSAGE AQ$_JMS_TEXT_MESSAGE,RECIPIENTS AQ$_RECIPIENTS,GEN_PAYLOAD NUMBER,SIGNATURE AQ$_SIG_PROP,TRANSFORMATION VARCHAR,CREATE_NEW_LOB NUMBER,DELIVERY_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_LISTEN(AGENT_LIST AQ$_RECIPIENTS,WAIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_QUEUE_SUBSCRIBERS(QUEUE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_REGISTER_IN(NAME VARCHAR,NAMESPACE NUMBER,CALLBACK VARCHAR,CONTEXT RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_START_QUEUE(QUEUE_NAME VARCHAR,ENQUEUE NUMBER,DEQUEUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AQIN.AQ$_STOP_QUEUE(QUEUE_NAME VARCHAR,ENQUEUE NUMBER,DEQUEUE NUMBER,WAIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_AQIN.GET_DEQ_SORT()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_AQIN.GET_MULTI_RETRY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_AQIN.SET_MULTI_RETRY(STATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

