CREATE SCHEMA DBMS_XPLAN;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.BUILD_PLAN_XML(TABLE_NAME VARCHAR,STATEMENT_ID VARCHAR,PLAN_ID NUMBER,FORMAT VARCHAR,FILTER_PREDS VARCHAR,PLAN_TAG VARCHAR,REPORT_REF VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DIFF_PLAN(SQL_TEXT CLOB,OUTLINE CLOB,USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DIFF_PLAN_AWR(SQL_ID VARCHAR,PLAN_HASH_VALUE1 NUMBER,PLAN_HASH_VALUE2 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DIFF_PLAN_CURSOR(SQL_ID VARCHAR,CURSOR_CHILD_NUM1 NUMBER,CURSOR_CHILD_NUM2 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DIFF_PLAN_OUTLINE(SQL_TEXT CLOB,OUTLINE1 CLOB,OUTLINE2 CLOB,USER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DIFF_PLAN_SQL_BASELINE(BASELINE_PLAN_NAME1 VARCHAR,BASELINE_PLAN_NAME2 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DISPLAY(TABLE_NAME VARCHAR,STATEMENT_ID VARCHAR,FORMAT VARCHAR,FILTER_PREDS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DISPLAY_AWR(SQL_ID VARCHAR,PLAN_HASH_VALUE NUMBER(38),DB_ID NUMBER(38),FORMAT VARCHAR,CON_ID NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DISPLAY_CURSOR(SQL_ID VARCHAR,CURSOR_CHILD_NO NUMBER(38),FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DISPLAY_PLAN(TABLE_NAME VARCHAR,STATEMENT_ID VARCHAR,FORMAT VARCHAR,FILTER_PREDS VARCHAR,TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DISPLAY_SQLSET(SQLSET_NAME VARCHAR,SQL_ID VARCHAR,PLAN_HASH_VALUE NUMBER(38),FORMAT VARCHAR,SQLSET_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DISPLAY_SQL_PATCH_PLAN(NAME VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DISPLAY_SQL_PLAN_BASELINE(SQL_HANDLE VARCHAR,PLAN_NAME VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.DISPLAY_SQL_PROFILE_PLAN(NAME VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.FORMAT_NUMBER(NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.FORMAT_NUMBER2(NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.FORMAT_SIZE(NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.FORMAT_SIZE2(NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.FORMAT_TIME_S(NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.GET_CURSOR_ROWS(SQL_ID VARCHAR,CURSOR_CHILD_NO NUMBER(38),FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.GET_PLANDIFF_REPORT_XML(REPORT_REF VARCHAR,TID NUMBER,METHOD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.GET_PLAN_ROWS(TABLE_NAME VARCHAR,STATEMENT_ID VARCHAR,PLAN_ID VARCHAR,FORMAT VARCHAR,FILTER_PREDS VARCHAR,MASK_COST NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.I_DISPLAY_SMB_PLAN(NAME VARCHAR,FORMAT VARCHAR,OBJ_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.PREPARE_PLAN_XML_QUERY(PLAN_QUERY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.PREPARE_RECORDS(I_FORMAT_FLAGS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XPLAN.VALIDATE_FORMAT(HASPLANSTATS BOOLEAN,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

