CREATE SCHEMA DBMS_FREQUENT_ITEMSET;

CREATE OR REPLACE FUNCTION DBMS_FREQUENT_ITEMSET.FI_HORIZONTAL(SUPPORT_THRESHOLD NUMBER,ITEMSET_LENGTH_MIN NUMBER,ITEMSET_LENGTH_MAX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_FREQUENT_ITEMSET.FI_TRANSACTIONAL(SUPPORT_THRESHOLD NUMBER,ITEMSET_LENGTH_MIN NUMBER,ITEMSET_LENGTH_MAX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

