CREATE SCHEMA DBMS_STATS;

CREATE OR REPLACE PROCEDURE DBMS_STATS.ALTER_DATABASE_TAB_MONITORING(MONITORING BOOLEAN,SYSOBJS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.ALTER_SCHEMA_TAB_MONITORING(OWNNAME VARCHAR,MONITORING BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.ALTER_STATS_HISTORY_RETENTION(RETENTION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.CLEANUP_STATS_JOB_PROC(CTX NUMBER,JOB_OWNER VARCHAR,JOB_NAME VARCHAR,SESID NUMBER,SESSER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.CLOB_TO_VARRAY(CL CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STATS.CONVERT_RAW_VALUE(RAWVAL RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.CONVERT_RAW_VALUE(RAWVAL RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.CONVERT_RAW_VALUE(RAWVAL RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.CONVERT_RAW_VALUE(RAWVAL RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.CONVERT_RAW_VALUE(RAWVAL RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.CONVERT_RAW_VALUE_NVARCHAR(RAWVAL RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.CONVERT_RAW_VALUE_ROWID(RAWVAL RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.CONV_RAW(RAWVAL RAW,TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STATS.COPY_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,SRCPARTNAME VARCHAR,DSTPARTNAME VARCHAR,SCALE_FACTOR NUMBER,FLAGS NUMBER,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.CREATE_EXTENDED_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,EXTENSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.CREATE_EXTENDED_STATS(OWNNAME VARCHAR,TABNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STATS.CREATE_STAT_TABLE(OWNNAME VARCHAR,STATTAB VARCHAR,TBLSPACE VARCHAR,GLOBAL_TEMPORARY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_COLUMN_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,CASCADE_PARTS BOOLEAN,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN,COL_STAT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_DATABASE_PREFS(PNAME VARCHAR,ADD_SYS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_DATABASE_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_DICTIONARY_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_FIXED_OBJECTS_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,CASCADE_PARTS BOOLEAN,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_PENDING_STATS(OWNNAME VARCHAR,TABNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_PENDING_SYSTEM_STATS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_SCHEMA_PREFS(OWNNAME VARCHAR,PNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_SCHEMA_STATS(OWNNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_SYSTEM_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_TABLE_PREFS(OWNNAME VARCHAR,TABNAME VARCHAR,PNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DELETE_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,CASCADE_PARTS BOOLEAN,CASCADE_COLUMNS BOOLEAN,CASCADE_INDEXES BOOLEAN,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.DIFF_TABLE_STATS_IN_HISTORY(OWNNAME VARCHAR,TABNAME VARCHAR,PCTTHRESHOLD NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.DIFF_TABLE_STATS_IN_PENDING(OWNNAME VARCHAR,TABNAME VARCHAR,PCTTHRESHOLD NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.DIFF_TABLE_STATS_IN_STATTAB(OWNNAME VARCHAR,TABNAME VARCHAR,STATTAB1 VARCHAR,STATTAB2 VARCHAR,PCTTHRESHOLD NUMBER,STATID1 VARCHAR,STATID2 VARCHAR,STATTAB1OWN VARCHAR,STATTAB2OWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STATS.DROP_EXTENDED_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,EXTENSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.DROP_STAT_TABLE(OWNNAME VARCHAR,STATTAB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_COLUMN_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_DATABASE_PREFS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,ADD_SYS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_DATABASE_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_DICTIONARY_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_FIXED_OBJECTS_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_PENDING_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_PENDING_SYSTEM_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_SCHEMA_PREFS(OWNNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_SCHEMA_STATS(OWNNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_STATS_FOR_DP(OBJLIST_TAB_OWN VARCHAR,OBJLIST_TAB VARCHAR,DBLINK VARCHAR,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_SYSTEM_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_TABLE_PREFS(OWNNAME VARCHAR,TABNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.EXPORT_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,CASCADE BOOLEAN,STATOWN VARCHAR,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.FLUSH_DATABASE_MONITORING_INFO(BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,GATHER_SYS BOOLEAN,NO_INVALIDATE BOOLEAN,GATHER_TEMP BOOLEAN,GATHER_FIXED BOOLEAN,STATTYPE VARCHAR,OBJ_FILTER_LIST OBJECTTAB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_DATABASE_STATS(ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,GATHER_SYS BOOLEAN,NO_INVALIDATE BOOLEAN,GATHER_TEMP BOOLEAN,GATHER_FIXED BOOLEAN,STATTYPE VARCHAR,OBJ_FILTER_LIST OBJECTTAB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_DATABASE_STATS_JOB_PROC(ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,OBJ_FILTER_LIST OBJECTTAB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_DICTIONARY_STATS(COMP_ID VARCHAR,ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,OBJ_FILTER_LIST OBJECTTAB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_FIXED_OBJECTS_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,ESTIMATE_PERCENT NUMBER,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_PROCESSING_RATE(GATHERING_MODE VARCHAR,DURATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME VARCHAR,ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,GATHER_TEMP BOOLEAN,GATHER_FIXED BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,OBJ_FILTER_LIST OBJECTTAB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME VARCHAR,ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,GATHER_TEMP BOOLEAN,GATHER_FIXED BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,OBJ_FILTER_LIST OBJECTTAB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_SYSTEM_STATS(GATHERING_MODE VARCHAR,INTERVAL NUMBER(38),STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GATHER_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR,ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,CONTEXT CCONTEXT,OPTIONS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GENERATE_STATS(OWNNAME VARCHAR,OBJNAME VARCHAR,ORGANIZED NUMBER,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GEN_SELMAP(OWNER VARCHAR,TABNAME VARCHAR,PNAME VARCHAR,SPNAME VARCHAR,FLAG NUMBER,COLINFO COLDICTTAB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GET_COLUMN_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GET_COLUMN_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.GET_COMPATIBLE(INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STATS.GET_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GET_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GET_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.GET_PARAM(PNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.GET_PREFS(PNAME VARCHAR,OWNNAME VARCHAR,TABNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.GET_STATS_HISTORY_AVAILABILITY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.GET_STATS_HISTORY_RETENTION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.GET_STAT_TAB_VERSION(PNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STATS.GET_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.GET_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_COLUMN_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_DATABASE_PREFS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,ADD_SYS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_DATABASE_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_DICTIONARY_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_FIXED_OBJECTS_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_SCHEMA_PREFS(OWNNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_SCHEMA_STATS(OWNNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_STATS_FOR_DP(OBJLIST_TAB_OWN VARCHAR,OBJLIST_TAB VARCHAR,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_SYSTEM_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_TABLE_PREFS(OWNNAME VARCHAR,TABNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.IMPORT_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,CASCADE BOOLEAN,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN,STAT_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.INIT_PACKAGE(TABNAME VARCHAR,PARTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.LOCK_SCHEMA_STATS(OWNNAME VARCHAR,STATTYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.LOCK_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,STATTYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.MERGE_COL_USAGE(DBLINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.POSTPROCESS_STATS(OWNER VARCHAR,TABNAME VARCHAR,PNAME VARCHAR,SPNAME VARCHAR,FLAG NUMBER,RAWSTATS RAWCTAB,SELMAP SELTAB,CLIST CTAB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PREPARE_COLUMN_VALUES(CHARVALS CHARARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PREPARE_COLUMN_VALUES(DATEVALS DATEARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PREPARE_COLUMN_VALUES(NUMVALS NUMARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PREPARE_COLUMN_VALUES(FLTVALS FLTARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PREPARE_COLUMN_VALUES(DBLVALS DBLARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PREPARE_COLUMN_VALUES(RAWVALS RAWARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PREPARE_COLUMN_VALUES_NVARCHAR(NVMIN NVARCHAR2,NVMAX NVARCHAR2)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PREPARE_COLUMN_VALUES_ROWID(RWMIN ROWID,RWMAX ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PUBLISH_PENDING_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.PUBLISH_PENDING_SYSTEM_STATS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.REMAP_STAT_TABLE(OWNNAME VARCHAR,STATTAB VARCHAR,SRC_OWN VARCHAR,SRC_TAB VARCHAR,TGT_OWN VARCHAR,TGT_TAB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_COL_USAGE(OWNNAME VARCHAR,TABNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_GATHER_AUTO_STATS(DETAIL_LEVEL VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_GATHER_DATABASE_STATS(ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,GATHER_SYS BOOLEAN,NO_INVALIDATE BOOLEAN,GATHER_TEMP BOOLEAN,GATHER_FIXED BOOLEAN,STATTYPE VARCHAR,OBJ_FILTER_LIST OBJECTTAB,DETAIL_LEVEL VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_GATHER_DICTIONARY_STATS(COMP_ID VARCHAR,ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,OBJ_FILTER_LIST OBJECTTAB,DETAIL_LEVEL VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_GATHER_FIXED_OBJ_STATS(STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,DETAIL_LEVEL VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_GATHER_SCHEMA_STATS(OWNNAME VARCHAR,ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,OPTIONS VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,GATHER_TEMP BOOLEAN,GATHER_FIXED BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,OBJ_FILTER_LIST OBJECTTAB,DETAIL_LEVEL VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_GATHER_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR,ESTIMATE_PERCENT NUMBER,BLOCK_SAMPLE BOOLEAN,METHOD_OPT VARCHAR,DEGREE NUMBER,GRANULARITY VARCHAR,CASCADE BOOLEAN,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,STATTYPE VARCHAR,FORCE BOOLEAN,OPTIONS VARCHAR,DETAIL_LEVEL VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_SINGLE_STATS_OPERATION(OPID NUMBER,DETAIL_LEVEL VARCHAR,FORMAT VARCHAR,CONTAINER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.REPORT_STATS_OPERATIONS(DETAIL_LEVEL VARCHAR,FORMAT VARCHAR,LATESTN NUMBER,AUTO_ONLY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESET_COL_USAGE(OWNNAME VARCHAR,TABNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESET_GLOBAL_PREF_DEFAULTS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESET_PARAM_DEFAULTS(FORCE BOOLEAN,NO_INVALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESTORE_DICTIONARY_STATS(FORCE BOOLEAN,NO_INVALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESTORE_FIXED_OBJECTS_STATS(FORCE BOOLEAN,NO_INVALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESTORE_SCHEMA_STATS(OWNNAME VARCHAR,FORCE BOOLEAN,NO_INVALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESTORE_SYSTEM_STATS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESTORE_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,RESTORE_CLUSTER_INDEX BOOLEAN,FORCE BOOLEAN,NO_INVALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.RESUME_GATHER_STATS(OWNER_NAME VARCHAR,TIME_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_COLUMN_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,DISTCNT NUMBER,DENSITY NUMBER,NULLCNT NUMBER,SREC VARIANT,AVGCLEN NUMBER,FLAGS NUMBER,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_COLUMN_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,EXT_STATS RAW,STATTYPOWN VARCHAR,STATTYPNAME VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_DATABASE_PREFS(PNAME VARCHAR,PVALUE VARCHAR,ADD_SYS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_GLOBAL_PREFS(PNAME VARCHAR,PVALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,NUMROWS NUMBER,NUMLBLKS NUMBER,NUMDIST NUMBER,AVGLBLK NUMBER,AVGDBLK NUMBER,CLSTFCT NUMBER,INDLEVEL NUMBER,FLAGS NUMBER,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,GUESSQ NUMBER,CACHEDBLK NUMBER,CACHEHIT NUMBER,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_INDEX_STATS(OWNNAME VARCHAR,INDNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,EXT_STATS RAW,STATTYPOWN VARCHAR,STATTYPNAME VARCHAR,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_PARAM(PNAME VARCHAR,PVAL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_PROCESSING_RATE(OPNAME VARCHAR,PROCRATE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_SCHEMA_PREFS(OWNNAME VARCHAR,PNAME VARCHAR,PVALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_SYSTEM_STATS(PNAME VARCHAR,PVALUE NUMBER,STATTAB VARCHAR,STATID VARCHAR,STATOWN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_TABLE_PREFS(OWNNAME VARCHAR,TABNAME VARCHAR,PNAME VARCHAR,PVALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.SET_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR,STATTAB VARCHAR,STATID VARCHAR,NUMROWS NUMBER,NUMBLKS NUMBER,AVGRLEN NUMBER,FLAGS NUMBER,STATOWN VARCHAR,NO_INVALIDATE BOOLEAN,CACHEDBLK NUMBER,CACHEHIT NUMBER,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.SHOW_EXTENDED_STATS_NAME(OWNNAME VARCHAR,TABNAME VARCHAR,EXTENSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STATS.TO_NO_INVALIDATE_TYPE(NO_INVALIDATE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STATS.TRANSFER_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,DBLINK VARCHAR,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.UNLOCK_PARTITION_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,PARTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.UNLOCK_SCHEMA_STATS(OWNNAME VARCHAR,STATTYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.UNLOCK_TABLE_STATS(OWNNAME VARCHAR,TABNAME VARCHAR,STATTYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STATS.UPGRADE_STAT_TABLE(OWNNAME VARCHAR,STATTAB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STATS.VARRAY_TO_CLOB(VA DS_VARRAY_4_CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

