CREATE SCHEMA DBMS_STREAMS_ADM;

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_COLUMN(RULE_NAME VARCHAR,TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,COLUMN_VALUE ANYDATA,VALUE_TYPE VARCHAR,STEP_NUMBER NUMBER,OPERATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_COLUMN(RULE_NAME VARCHAR,TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,COLUMN_FUNCTION VARCHAR,VALUE_TYPE VARCHAR,STEP_NUMBER NUMBER,OPERATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_GLOBAL_PROPAGATION_RULES(STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_GLOBAL_PROPAGATION_RULES(STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_GLOBAL_RULES(STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_GLOBAL_RULES(STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_MESSAGE_PROPAGATION_RULE(MESSAGE_TYPE VARCHAR,RULE_CONDITION VARCHAR,STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUSION_RULE BOOLEAN,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_MESSAGE_PROPAGATION_RULE(MESSAGE_TYPE VARCHAR,RULE_CONDITION VARCHAR,STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUSION_RULE BOOLEAN,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_MESSAGE_RULE(MESSAGE_TYPE VARCHAR,RULE_CONDITION VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUSION_RULE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_MESSAGE_RULE(MESSAGE_TYPE VARCHAR,RULE_CONDITION VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUSION_RULE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_SCHEMA_PROPAGATION_RULES(SCHEMA_NAME VARCHAR,STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_SCHEMA_PROPAGATION_RULES(SCHEMA_NAME VARCHAR,STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_SCHEMA_RULES(SCHEMA_NAME VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_SCHEMA_RULES(SCHEMA_NAME VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_SUBSET_PROPAGATION_RULES(TABLE_NAME VARCHAR,DML_CONDITION VARCHAR,STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_SUBSET_PROPAGATION_RULES(TABLE_NAME VARCHAR,DML_CONDITION VARCHAR,STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_SUBSET_RULES(TABLE_NAME VARCHAR,DML_CONDITION VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_SUBSET_RULES(TABLE_NAME VARCHAR,DML_CONDITION VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_TABLE_PROPAGATION_RULES(TABLE_NAME VARCHAR,STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_TABLE_PROPAGATION_RULES(TABLE_NAME VARCHAR,STREAMS_NAME VARCHAR,SOURCE_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR,QUEUE_TO_QUEUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_TABLE_RULES(TABLE_NAME VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.ADD_TABLE_RULES(TABLE_NAME VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,QUEUE_NAME VARCHAR,INCLUDE_DML BOOLEAN,INCLUDE_DDL BOOLEAN,INCLUDE_TAGGED_LCR BOOLEAN,SOURCE_DATABASE VARCHAR,INCLUSION_RULE BOOLEAN,AND_CONDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.CLEANUP_INSTANTIATION_SETUP(MAINTAIN_MODE VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,BI_DIRECTIONAL BOOLEAN,CHANGE_GLOBAL_NAME BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.DELETE_COLUMN(RULE_NAME VARCHAR,TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,VALUE_TYPE VARCHAR,STEP_NUMBER NUMBER,OPERATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_STREAMS_ADM.GET_MESSAGE_TRACKING(SRC_PIT_SCN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_STREAMS_ADM.GET_TAG(TABLE_NAME VARCHAR,VALUE_TYPE VARCHAR,STEP_NUMBER NUMBER,OPERATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.KEEP_COLUMNS(RULE_NAME VARCHAR,TABLE_NAME VARCHAR,COLUMN_LIST VARCHAR,VALUE_TYPE VARCHAR,STEP_NUMBER NUMBER,OPERATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_CHANGE_TABLE(CHANGE_TABLE_NAME VARCHAR,SOURCE_TABLE_NAME VARCHAR,COLUMN_TYPE_LIST VARCHAR,EXTRA_COLUMN_LIST VARCHAR,CAPTURE_VALUES VARCHAR,OPTIONS_STRING VARCHAR,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,PERFORM_ACTIONS BOOLEAN,CAPTURE_NAME VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,KEEP_CHANGE_COLUMNS_ONLY BOOLEAN,EXECUTE_LCR BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_GLOBAL(SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,DUMP_FILE_NAME VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,LOG_FILE VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN,INSTANTIATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_SCHEMAS(SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,DUMP_FILE_NAME VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,LOG_FILE VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN,INSTANTIATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_SCHEMAS(SCHEMA_NAMES VARCHAR,SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,DUMP_FILE_NAME VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,LOG_FILE VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN,INSTANTIATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_SIMPLE_TABLESPACE(TABLESPACE_NAME VARCHAR,SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,DESTINATION_DATABASE VARCHAR,SETUP_STREAMS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,BI_DIRECTIONAL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_SIMPLE_TTS(TABLESPACE_NAME VARCHAR,SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,BI_DIRECTIONAL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_TABLES(SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,DUMP_FILE_NAME VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,LOG_FILE VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN,INSTANTIATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_TABLES(TABLE_NAMES VARCHAR,SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,DUMP_FILE_NAME VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,LOG_FILE VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN,INSTANTIATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_TABLESPACES(SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,DESTINATION_DATABASE VARCHAR,SETUP_STREAMS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,DUMP_FILE_NAME VARCHAR,SOURCE_QUEUE_TABLE VARCHAR,SOURCE_QUEUE_NAME VARCHAR,SOURCE_QUEUE_USER VARCHAR,DESTINATION_QUEUE_TABLE VARCHAR,DESTINATION_QUEUE_NAME VARCHAR,DESTINATION_QUEUE_USER VARCHAR,CAPTURE_NAME VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,LOG_FILE VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MAINTAIN_TTS(SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,DUMP_FILE_NAME VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,LOG_FILE VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MERGE_STREAMS(CLONED_PROPAGATION_NAME VARCHAR,PROPAGATION_NAME VARCHAR,QUEUE_NAME VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.MERGE_STREAMS_JOB(CLONED_PROPAGATION_NAME VARCHAR,PROPAGATION_NAME VARCHAR,QUEUE_NAME VARCHAR,MERGE_THRESHOLD NUMBER,SCHEDULE_NAME VARCHAR,MERGE_JOB_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.POST_INSTANTIATION_SETUP(MAINTAIN_MODE VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN,START_PROCESSES BOOLEAN,INSTANTIATION_SCN NUMBER,EXCLUDE_SCHEMAS VARCHAR,EXCLUDE_FLAGS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.PRE_INSTANTIATION_SETUP(MAINTAIN_MODE VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DATABASE VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,CAPTURE_NAME VARCHAR,CAPTURE_QUEUE_TABLE VARCHAR,CAPTURE_QUEUE_NAME VARCHAR,CAPTURE_QUEUE_USER VARCHAR,PROPAGATION_NAME VARCHAR,APPLY_NAME VARCHAR,APPLY_QUEUE_TABLE VARCHAR,APPLY_QUEUE_NAME VARCHAR,APPLY_QUEUE_USER VARCHAR,BI_DIRECTIONAL BOOLEAN,INCLUDE_DDL BOOLEAN,START_PROCESSES BOOLEAN,EXCLUDE_SCHEMAS VARCHAR,EXCLUDE_FLAGS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.PURGE_SOURCE_CATALOG(SOURCE_DATABASE VARCHAR,SOURCE_OBJECT_NAME VARCHAR,SOURCE_OBJECT_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.RECOVER_OPERATION(SCRIPT_ID RAW,OPERATION_MODE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.REMOVE_QUEUE(QUEUE_NAME VARCHAR,CASCADE BOOLEAN,DROP_UNUSED_QUEUE_TABLE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.REMOVE_RULE(RULE_NAME VARCHAR,STREAMS_TYPE VARCHAR,STREAMS_NAME VARCHAR,DROP_UNUSED_RULE BOOLEAN,INCLUSION_RULE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.REMOVE_STREAMS_CONFIGURATION(STREAMS_ONLY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.RENAME_COLUMN(RULE_NAME VARCHAR,TABLE_NAME VARCHAR,FROM_COLUMN_NAME VARCHAR,TO_COLUMN_NAME VARCHAR,VALUE_TYPE VARCHAR,STEP_NUMBER NUMBER,OPERATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.RENAME_SCHEMA(RULE_NAME VARCHAR,FROM_SCHEMA_NAME VARCHAR,TO_SCHEMA_NAME VARCHAR,STEP_NUMBER NUMBER,OPERATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.RENAME_TABLE(RULE_NAME VARCHAR,FROM_TABLE_NAME VARCHAR,TO_TABLE_NAME VARCHAR,STEP_NUMBER NUMBER,OPERATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.SET_MESSAGE_NOTIFICATION(STREAMS_NAME VARCHAR,NOTIFICATION_ACTION VARCHAR,NOTIFICATION_TYPE VARCHAR,NOTIFICATION_CONTEXT ANYDATA,INCLUDE_NOTIFICATION BOOLEAN,QUEUE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.SET_MESSAGE_TRACKING(TRACKING_LABEL VARCHAR,ACTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.SET_RULE_TRANSFORM_FUNCTION(RULE_NAME VARCHAR,TRANSFORM_FUNCTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.SET_TAG(TAG RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.SET_UP_QUEUE(QUEUE_TABLE VARCHAR,STORAGE_CLAUSE VARCHAR,QUEUE_NAME VARCHAR,QUEUE_USER VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADM.SPLIT_STREAMS(PROPAGATION_NAME VARCHAR,CLONED_PROPAGATION_NAME VARCHAR,CLONED_QUEUE_NAME VARCHAR,CLONED_CAPTURE_NAME VARCHAR,PERFORM_ACTIONS BOOLEAN,SCRIPT_NAME VARCHAR,SCRIPT_DIRECTORY_OBJECT VARCHAR,AUTO_MERGE_THRESHOLD NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

