CREATE SCHEMA DBMS_HM;

CREATE OR REPLACE PROCEDURE DBMS_HM.CREATE_OFFLINE_DICTIONARY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_HM.CREATE_SCHEMA()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_HM.GET_RUN_REPORT(RUN_NAME VARCHAR,REPORT_TYPE VARCHAR,REPORT_LEVEL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_HM.RUN_CHECK(CHECK_NAME VARCHAR,RUN_NAME VARCHAR,TIMEOUT NUMBER,INPUT_PARAMS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_HM.RUN_DDE_ACTION(INCIDENT_ID NUMBER,DIRECTORY_NAME VARCHAR,CHECK_NAME VARCHAR,RUN_NAME VARCHAR,TIMEOUT NUMBER,PARAMS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

