CREATE SCHEMA DBMS_LDAP;

CREATE OR REPLACE FUNCTION DBMS_LDAP.ADD_S(LD RAW(32),ENTRYDN VARCHAR,MODPTR RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LDAP.BER_FREE(BER RAW(32),FREEBUF NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LDAP.BIND_S(LD RAW(32),DN VARCHAR,CRED VARCHAR,METH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.CHECK_INTERFACE_VERSION(INTERFACE_VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.COMPARE_S(LD RAW(32),DN VARCHAR,ATTR VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.COUNT_ENTRIES(LD RAW(32),MSG RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.COUNT_VALUES()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.COUNT_VALUES_BLOB()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.COUNT_VALUES_LEN()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.CREATE_MOD_ARRAY(NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.DELETE(LD RAW(32),ENTRYDN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.DELETE_S(LD RAW(32),ENTRYDN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.ERR2STRING(LDAP_ERR NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.EXPLODE_DN(DN VARCHAR,NOTYPES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.FIRST_ATTRIBUTE(LD RAW(32),LDAPENTRY RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.FIRST_ENTRY(LD RAW(32),MSG RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LDAP.FREE_MOD_ARRAY(MODPTR RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LDAP.GET_DN(LD RAW(32),LDAPENTRY RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.GET_SESSION_INFO(LD RAW(32),DATA_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.GET_TRACE_LEVEL(LDAPENTRY RAW(32),ATTR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.GET_VALUES_BLOB(LD RAW(32),LDAPENTRY RAW(32),ATTR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.GET_VALUES_LEN(LD RAW(32),LDAPENTRY RAW(32),ATTR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.INIT(HOSTNAME VARCHAR,PORTNUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.MODIFY_S(LD RAW(32),ENTRYDN VARCHAR,MODPTR RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.MODRDN2_S(LD RAW(32),ENTRYDN VARCHAR,NEWRDN VARCHAR,DELETEOLDRDN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.MSGFREE(LM RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.NEXT_ATTRIBUTE(LD RAW(32),LDAPENTRY RAW(32),BER_ELEM RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.NEXT_ENTRY(LD RAW(32),MSG RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.NLS_CONVERT_FROM_UTF8(DATA_UTF8 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.NLS_CONVERT_FROM_UTF8()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.NLS_CONVERT_TO_UTF8(DATA_LOCAL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.NLS_CONVERT_TO_UTF8()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.NLS_GET_DBCHARSET_NAME(SSLWRL VARCHAR,SSLWALLETPASSWD VARCHAR,SSLAUTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LDAP.POPULATE_MOD_ARRAY(MODPTR RAW(32),MOD_OP NUMBER,MOD_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LDAP.POPULATE_MOD_ARRAY(MODPTR RAW(32),MOD_OP NUMBER,MOD_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LDAP.POPULATE_MOD_ARRAY(MODPTR RAW(32),MOD_OP NUMBER,MOD_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LDAP.RENAME_S(LD RAW(32),DN VARCHAR,NEWRDN VARCHAR,NEWPARENT VARCHAR,DELETEOLDRDN NUMBER,SERVERCTRLS VARIANT,CLIENTCTRLS VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.SEARCH_S(LD RAW(32),BASE VARCHAR,SCOPE NUMBER,FILTER VARCHAR,ATTRONLY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.SEARCH_ST(LD RAW(32),BASE VARCHAR,SCOPE NUMBER,FILTER VARCHAR,ATTRONLY NUMBER,TV VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LDAP.SET_TRACE_LEVEL(NEW_TRACE_LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LDAP.SIMPLE_BIND_S(LD RAW(32),DN VARCHAR,PASSWD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP.UNBIND_S()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LDAP.VALUE_FREE_BLOB()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

