CREATE SCHEMA DBMS_RECTIFIER_DIFF;

CREATE OR REPLACE PROCEDURE DBMS_RECTIFIER_DIFF.DIFFERENCES(SNAME1 VARCHAR,ONAME1 VARCHAR,REFERENCE_SITE VARCHAR,SNAME2 VARCHAR,ONAME2 VARCHAR,COMPARISON_SITE VARCHAR,WHERE_CLAUSE VARCHAR,COLUMN_LIST VARCHAR,MISSING_ROWS_SNAME VARCHAR,MISSING_ROWS_ONAME1 VARCHAR,MISSING_ROWS_ONAME2 VARCHAR,MISSING_ROWS_SITE VARCHAR,MAX_MISSING NUMBER(38),COMMIT_ROWS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RECTIFIER_DIFF.DIFFERENCES(SNAME1 VARCHAR,ONAME1 VARCHAR,REFERENCE_SITE VARCHAR,SNAME2 VARCHAR,ONAME2 VARCHAR,COMPARISON_SITE VARCHAR,WHERE_CLAUSE VARCHAR,MISSING_ROWS_SNAME VARCHAR,MISSING_ROWS_ONAME1 VARCHAR,MISSING_ROWS_ONAME2 VARCHAR,MISSING_ROWS_SITE VARCHAR,MAX_MISSING NUMBER(38),COMMIT_ROWS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RECTIFIER_DIFF.RECTIFY(SNAME1 VARCHAR,ONAME1 VARCHAR,REFERENCE_SITE VARCHAR,SNAME2 VARCHAR,ONAME2 VARCHAR,COMPARISON_SITE VARCHAR,COLUMN_LIST VARCHAR,MISSING_ROWS_SNAME VARCHAR,MISSING_ROWS_ONAME1 VARCHAR,MISSING_ROWS_ONAME2 VARCHAR,MISSING_ROWS_SITE VARCHAR,COMMIT_ROWS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RECTIFIER_DIFF.RECTIFY(SNAME1 VARCHAR,ONAME1 VARCHAR,REFERENCE_SITE VARCHAR,SNAME2 VARCHAR,ONAME2 VARCHAR,COMPARISON_SITE VARCHAR,MISSING_ROWS_SNAME VARCHAR,MISSING_ROWS_ONAME1 VARCHAR,MISSING_ROWS_ONAME2 VARCHAR,MISSING_ROWS_SITE VARCHAR,COMMIT_ROWS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RECTIFIER_DIFF.TURN_REPLICATION_OFF()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

