CREATE SCHEMA DBMS_PCLXUTIL;

CREATE OR REPLACE PROCEDURE DBMS_PCLXUTIL.BUILD_PART_INDEX(JOBS_PER_BATCH NUMBER,PROCS_PER_JOB NUMBER,TAB_NAME VARCHAR,IDX_NAME VARCHAR,FORCE_OPT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

