CREATE SCHEMA DBMS_DEFER_QUERY;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_ANYDATA_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_ARG_CSETID(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_ARG_FORM(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_ARG_TYPE(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_BLOB_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEFER_QUERY.GET_CALL_ARGS(CALLNO NUMBER,STARTARG NUMBER,ARGCNT NUMBER,ARGSIZE NUMBER,TRAN_DB VARCHAR,TRAN_ID VARCHAR,DATE_FMT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_QUERY.GET_CALL_ARGS(CALLNO NUMBER,STARTARG NUMBER,ARGCNT NUMBER,ARGSIZE NUMBER,TRAN_ID VARCHAR,DATE_FMT VARCHAR,TIME_FMT VARCHAR,TTZ_FMT VARCHAR,TIMESTAMP_FMT VARCHAR,TSTZ_FMT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_QUERY.GET_CALL_ARGS(CALLNO NUMBER,STARTARG NUMBER,ARGCNT NUMBER,ARGSIZE NUMBER,TRAN_ID VARCHAR,DATE_FMT VARCHAR,TIME_FMT VARCHAR,TTZ_FMT VARCHAR,TIMESTAMP_FMT VARCHAR,TSTZ_FMT VARCHAR,TSLTZ_FMT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_CHAR_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_CLOB_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_DATE_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_IDS_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_IYM_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_NCHAR_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_NCLOB_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_NUMBER_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_NVARCHAR2_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_OBJECT_NULL_VECTOR_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_RAW_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_ROWID_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_TIMESTAMP_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_TIME_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_TSLTZ_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_TSTZ_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_TTZ_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_QUERY.GET_VARCHAR2_ARG(CALLNO NUMBER,ARG_NO NUMBER,DEFERRED_TRAN_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

