CREATE SCHEMA DBMS_AW_STATS;

CREATE OR REPLACE PROCEDURE DBMS_AW_STATS.ANALYZE(INNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AW_STATS.CLEAR(INNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

