CREATE SCHEMA DBMS_CUBE_ADVISE;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_ATR_EXPR_RC()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_COLDISTINCTCOUNT(OWNER VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_DIMHIERJOIN_DISPOSITION(TABOWNER VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_DIMLVL_DISPOSITION(TABOWNER VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_DIM_DISPOSITION(DIMOWNER VARCHAR,DIMNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_FK_NAME(TABOWNER VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_LVL_NAME(OWNER VARCHAR,DIMNAME VARCHAR,COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_MEAS_COL(MVOWNER VARCHAR,MVNAME VARCHAR,COLALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.GET_PK_NAME(TABOWNER VARCHAR,TABNAME VARCHAR,COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.IS_MD_CLASS(MDCLASS NUMBER,OWNER VARCHAR,OBJNAME VARCHAR,COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_CUBE_ADVISE.LOG(MSGID NUMBER,MSGTXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_CUBE_ADVISE.MV_CUBE_ADVICE(OWNER VARCHAR,OBJNAME VARCHAR,REQTYPE VARCHAR,VALIDATE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_CUBE_ADVISE.SET_CNS_EXCEPTION_LOG(EXCEPTLOGTAB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CUBE_ADVISE.TRACE(DIAGLEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

