CREATE SCHEMA DBMS_PROPAGATION_ADM;

CREATE OR REPLACE PROCEDURE DBMS_PROPAGATION_ADM.ALTER_PROPAGATION(PROPAGATION_NAME VARCHAR,RULE_SET_NAME VARCHAR,REMOVE_RULE_SET BOOLEAN,NEGATIVE_RULE_SET_NAME VARCHAR,REMOVE_NEGATIVE_RULE_SET BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_PROPAGATION_ADM.CREATE_PROPAGATION(PROPAGATION_NAME VARCHAR,SOURCE_QUEUE VARCHAR,DESTINATION_QUEUE VARCHAR,DESTINATION_DBLINK VARCHAR,RULE_SET_NAME VARCHAR,NEGATIVE_RULE_SET_NAME VARCHAR,QUEUE_TO_QUEUE BOOLEAN,ORIGINAL_PROPAGATION_NAME VARCHAR,AUTO_MERGE_THRESHOLD NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_PROPAGATION_ADM.DROP_PROPAGATION(PROPAGATION_NAME VARCHAR,DROP_UNUSED_RULE_SETS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_PROPAGATION_ADM.START_PROPAGATION(PROPAGATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_PROPAGATION_ADM.STOP_PROPAGATION(PROPAGATION_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

