CREATE SCHEMA DBMS_EPG;

CREATE OR REPLACE PROCEDURE DBMS_EPG.AUTHORIZE_DAD(DAD_NAME VARCHAR,USER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.CREATE_DAD(DAD_NAME VARCHAR,PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.DEAUTHORIZE_DAD(DAD_NAME VARCHAR,USER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.DELETE_DAD_ATTRIBUTE(DAD_NAME VARCHAR,ATTR_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.DELETE_GLOBAL_ATTRIBUTE(ATTR_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.DROP_DAD(DAD_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.GET_ALL_DAD_ATTRIBUTES(DAD_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.GET_ALL_DAD_MAPPINGS(DAD_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.GET_ALL_GLOBAL_ATTRIBUTES()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_EPG.GET_DAD_ATTRIBUTE(DAD_NAME VARCHAR,ATTR_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_EPG.GET_DAD_LIST()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_EPG.GET_GLOBAL_ATTRIBUTE(ATTR_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_EPG.MAP_DAD(DAD_NAME VARCHAR,PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.SET_DAD_ATTRIBUTE(DAD_NAME VARCHAR,ATTR_NAME VARCHAR,ATTR_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.SET_GLOBAL_ATTRIBUTE(ATTR_NAME VARCHAR,ATTR_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_EPG.UNMAP_DAD(DAD_NAME VARCHAR,PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

