CREATE SCHEMA DBMS_DATA_MINING_TRANSFORM;

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.CREATE_BIN_CAT(BIN_TABLE_NAME VARCHAR,BIN_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.CREATE_BIN_NUM(BIN_TABLE_NAME VARCHAR,BIN_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.CREATE_CLIP(CLIP_TABLE_NAME VARCHAR,CLIP_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.CREATE_COL_REM(REM_TABLE_NAME VARCHAR,REM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.CREATE_MISS_CAT(MISS_TABLE_NAME VARCHAR,MISS_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.CREATE_MISS_NUM(MISS_TABLE_NAME VARCHAR,MISS_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.CREATE_NORM_LIN(NORM_TABLE_NAME VARCHAR,NORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.DESCRIBE_STACK(XFORM_LIST TRANSFORM_LIST,DATA_TABLE_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.DESCRIBE_STACK(XFORM_LIST TRANSFORM_LIST,DATA_TABLE_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING_TRANSFORM.GET_EXPRESSION(EXPRESSION VARIANT,CHUNK_NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_AUTOBIN_NUM_EQWIDTH(BIN_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,BIN_NUM NUMBER,MAX_BIN_NUM NUMBER,EXCLUDE_LIST COLUMN_LIST,ROUND_NUM NUMBER,SAMPLE_SIZE NUMBER,BIN_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,REM_TABLE_NAME VARCHAR,REM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_BIN_CAT_FREQ(BIN_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,BIN_NUM NUMBER,EXCLUDE_LIST COLUMN_LIST,DEFAULT_NUM NUMBER,BIN_SUPPORT NUMBER,BIN_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_BIN_NUM_EQWIDTH(BIN_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,BIN_NUM NUMBER,EXCLUDE_LIST COLUMN_LIST,ROUND_NUM NUMBER,BIN_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_BIN_NUM_QTILE(BIN_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,BIN_NUM NUMBER,EXCLUDE_LIST COLUMN_LIST,BIN_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_BIN_SUPER(NUM_TABLE_NAME VARCHAR,CAT_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,TARGET_COLUMN_NAME VARCHAR,MAX_BIN_NUM NUMBER,EXCLUDE_LIST COLUMN_LIST,NUM_SCHEMA_NAME VARCHAR,CAT_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,REM_TABLE_NAME VARCHAR,REM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_CLIP_TRIM_TAIL(CLIP_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,TAIL_FRAC NUMBER,EXCLUDE_LIST COLUMN_LIST,CLIP_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_CLIP_WINSOR_TAIL(CLIP_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,TAIL_FRAC NUMBER,EXCLUDE_LIST COLUMN_LIST,CLIP_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_MISS_CAT_MODE(MISS_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,EXCLUDE_LIST COLUMN_LIST,MISS_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_MISS_NUM_MEAN(MISS_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,EXCLUDE_LIST COLUMN_LIST,ROUND_NUM NUMBER,MISS_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_NORM_LIN_MINMAX(NORM_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,EXCLUDE_LIST COLUMN_LIST,ROUND_NUM NUMBER,NORM_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_NORM_LIN_SCALE(NORM_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,EXCLUDE_LIST COLUMN_LIST,ROUND_NUM NUMBER,NORM_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.INSERT_NORM_LIN_ZSCORE(NORM_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,EXCLUDE_LIST COLUMN_LIST,ROUND_NUM NUMBER,NORM_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.SET_EXPRESSION(CHUNK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.SET_TRANSFORM(ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_SUBNAME VARCHAR,EXPRESSION CLOB,REVERSE_EXPRESSION VARCHAR,ATTRIBUTE_SPEC VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.STACK_BIN_CAT(BIN_TABLE_NAME VARCHAR,LITERAL_FLAG BOOLEAN,BIN_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.STACK_BIN_NUM(BIN_TABLE_NAME VARCHAR,LITERAL_FLAG BOOLEAN,BIN_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.STACK_CLIP(CLIP_TABLE_NAME VARCHAR,CLIP_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.STACK_COL_REM(REM_TABLE_NAME VARCHAR,REM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.STACK_MISS_CAT(MISS_TABLE_NAME VARCHAR,MISS_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.STACK_MISS_NUM(MISS_TABLE_NAME VARCHAR,MISS_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.STACK_NORM_LIN(NORM_TABLE_NAME VARCHAR,NORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_BIN_CAT(BIN_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,LITERAL_FLAG BOOLEAN,BIN_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_BIN_NUM(BIN_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,LITERAL_FLAG BOOLEAN,BIN_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_CLIP(CLIP_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,CLIP_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_COL_REM(REM_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,REM_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_EXPR_NUM(EXPR_PATTERN VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,EXCLUDE_LIST COLUMN_LIST,INCLUDE_LIST COLUMN_LIST,COL_PATTERN VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_EXPR_STR(EXPR_PATTERN VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,EXCLUDE_LIST COLUMN_LIST,INCLUDE_LIST COLUMN_LIST,COL_PATTERN VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_MISS_CAT(MISS_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,MISS_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_MISS_NUM(MISS_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,MISS_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_NORM_LIN(NORM_TABLE_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,NORM_SCHEMA_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING_TRANSFORM.XFORM_STACK(XFORM_LIST TRANSFORM_LIST,DATA_TABLE_NAME VARCHAR,XFORM_VIEW_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,XFORM_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

