CREATE SCHEMA DBMS_APPLY_ADM;

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.ADD_STMT_HANDLER(OBJECT_NAME VARCHAR,OPERATION_NAME VARCHAR,HANDLER_NAME VARCHAR,STATEMENT CLOB,APPLY_NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.ADD_STMT_HANDLER(OBJECT_NAME VARCHAR,OPERATION_NAME VARCHAR,HANDLER_NAME VARCHAR,APPLY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.ALTER_APPLY(APPLY_NAME VARCHAR,RULE_SET_NAME VARCHAR,REMOVE_RULE_SET BOOLEAN,MESSAGE_HANDLER VARCHAR,REMOVE_MESSAGE_HANDLER BOOLEAN,DDL_HANDLER VARCHAR,REMOVE_DDL_HANDLER BOOLEAN,APPLY_USER VARCHAR,APPLY_TAG RAW,REMOVE_APPLY_TAG BOOLEAN,PRECOMMIT_HANDLER VARCHAR,REMOVE_PRECOMMIT_HANDLER BOOLEAN,NEGATIVE_RULE_SET_NAME VARCHAR,REMOVE_NEGATIVE_RULE_SET BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.COMPARE_OLD_VALUES(OBJECT_NAME VARCHAR,COLUMN_LIST VARCHAR,OPERATION VARCHAR,COMPARE BOOLEAN,APPLY_DATABASE_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.COMPARE_OLD_VALUES(OBJECT_NAME VARCHAR,OPERATION VARCHAR,COMPARE BOOLEAN,APPLY_DATABASE_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.CREATE_APPLY(QUEUE_NAME VARCHAR,APPLY_NAME VARCHAR,RULE_SET_NAME VARCHAR,MESSAGE_HANDLER VARCHAR,DDL_HANDLER VARCHAR,APPLY_USER VARCHAR,APPLY_DATABASE_LINK VARCHAR,APPLY_TAG RAW,APPLY_CAPTURED BOOLEAN,PRECOMMIT_HANDLER VARCHAR,NEGATIVE_RULE_SET_NAME VARCHAR,SOURCE_DATABASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.CREATE_OBJECT_DEPENDENCY(OBJECT_NAME VARCHAR,PARENT_OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.DELETE_ALL_ERRORS(APPLY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.DELETE_ERROR(LOCAL_TRANSACTION_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.DROP_APPLY(APPLY_NAME VARCHAR,DROP_UNUSED_RULE_SETS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.DROP_OBJECT_DEPENDENCY(OBJECT_NAME VARCHAR,PARENT_OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.EXECUTE_ALL_ERRORS(APPLY_NAME VARCHAR,EXECUTE_AS_USER BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.EXECUTE_ERROR(LOCAL_TRANSACTION_ID VARCHAR,EXECUTE_AS_USER BOOLEAN,USER_PROCEDURE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_APPLY_ADM.GET_ERROR_MESSAGE(MESSAGE_NUMBER NUMBER,LOCAL_TRANSACTION_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_APPLY_ADM.GET_ERROR_MESSAGE(MESSAGE_NUMBER NUMBER,LOCAL_TRANSACTION_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.HANDLE_COLLISIONS(APPLY_NAME VARCHAR,ENABLE BOOLEAN,OBJECT VARCHAR,SOURCE_OBJECT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.REMOVE_STMT_HANDLER(OBJECT_NAME VARCHAR,OPERATION_NAME VARCHAR,HANDLER_NAME VARCHAR,APPLY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_CHANGE_HANDLER(CHANGE_TABLE_NAME VARCHAR,SOURCE_TABLE_NAME VARCHAR,CAPTURE_VALUES VARCHAR,APPLY_NAME VARCHAR,OPERATION_NAME VARCHAR,CHANGE_HANDLER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_DML_CONFLICT_HANDLER(APPLY_NAME VARCHAR,CONFLICT_HANDLER_NAME VARCHAR,OBJECT VARCHAR,OPERATION_NAME VARCHAR,CONFLICT_TYPE VARCHAR,METHOD_NAME VARCHAR,COLUMN_LIST VARCHAR,RESOLUTION_COLUMN VARCHAR,SOURCE_OBJECT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_DML_CONFLICT_HANDLER(APPLY_NAME VARCHAR,CONFLICT_HANDLER_NAME VARCHAR,OBJECT VARCHAR,OPERATION_NAME VARCHAR,CONFLICT_TYPE VARCHAR,METHOD_NAME VARCHAR,RESOLUTION_COLUMN VARCHAR,SOURCE_OBJECT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_DML_HANDLER(OBJECT_NAME VARCHAR,OBJECT_TYPE VARCHAR,OPERATION_NAME VARCHAR,ERROR_HANDLER BOOLEAN,USER_PROCEDURE VARCHAR,APPLY_DATABASE_LINK VARCHAR,APPLY_NAME VARCHAR,ASSEMBLE_LOBS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_ENQUEUE_DESTINATION(RULE_NAME VARCHAR,DESTINATION_QUEUE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_EXECUTE(RULE_NAME VARCHAR,EXECUTE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_GLOBAL_INSTANTIATION_SCN(SOURCE_DATABASE_NAME VARCHAR,INSTANTIATION_SCN NUMBER,APPLY_DATABASE_LINK VARCHAR,RECURSIVE BOOLEAN,SOURCE_ROOT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_KEY_COLUMNS(OBJECT_NAME VARCHAR,COLUMN_LIST VARCHAR,APPLY_DATABASE_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_KEY_COLUMNS(OBJECT_NAME VARCHAR,APPLY_DATABASE_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_PARAMETER(APPLY_NAME VARCHAR,PARAMETER VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_REPERROR_HANDLER(APPLY_NAME VARCHAR,OBJECT VARCHAR,ERROR_NUMBER NUMBER,METHOD VARCHAR,SOURCE_OBJECT VARCHAR,MAX_RETRIES NUMBER,DELAY_CSECS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_SCHEMA_INSTANTIATION_SCN(SOURCE_SCHEMA_NAME VARCHAR,SOURCE_DATABASE_NAME VARCHAR,INSTANTIATION_SCN NUMBER,APPLY_DATABASE_LINK VARCHAR,RECURSIVE BOOLEAN,SOURCE_ROOT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_TABLE_INSTANTIATION_SCN(SOURCE_OBJECT_NAME VARCHAR,SOURCE_DATABASE_NAME VARCHAR,INSTANTIATION_SCN NUMBER,APPLY_DATABASE_LINK VARCHAR,SOURCE_ROOT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_UPDATE_CONFLICT_HANDLER(OBJECT_NAME VARCHAR,METHOD_NAME VARCHAR,RESOLUTION_COLUMN VARCHAR,APPLY_DATABASE_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_VALUE_DEPENDENCY(DEPENDENCY_NAME VARCHAR,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.SET_VALUE_DEPENDENCY(DEPENDENCY_NAME VARCHAR,OBJECT_NAME VARCHAR,ATTRIBUTE_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.START_APPLY(APPLY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLY_ADM.STOP_APPLY(APPLY_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

