CREATE SCHEMA DBMS_SERVER_ALERT;

CREATE OR REPLACE FUNCTION DBMS_SERVER_ALERT.EXPAND_MESSAGE(USER_LANGUAGE VARCHAR,MESSAGE_ID NUMBER,ARGUMENT_1 VARCHAR,ARGUMENT_2 VARCHAR,ARGUMENT_3 VARCHAR,ARGUMENT_4 VARCHAR,ARGUMENT_5 VARCHAR,OBJARGPOS NUMBER,PDB_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SERVER_ALERT.GET_THRESHOLD(METRICS_ID NUMBER,INSTANCE_NAME VARCHAR,OBJECT_TYPE NUMBER,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SERVER_ALERT.SET_THRESHOLD(METRICS_ID NUMBER,WARNING_OPERATOR NUMBER,WARNING_VALUE VARCHAR,CRITICAL_OPERATOR NUMBER,CRITICAL_VALUE VARCHAR,OBSERVATION_PERIOD NUMBER,CONSECUTIVE_OCCURRENCES NUMBER,INSTANCE_NAME VARCHAR,OBJECT_TYPE NUMBER,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SERVER_ALERT.VIEW_THRESHOLDS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

