CREATE SCHEMA DBMS_LOGMNR;

CREATE OR REPLACE PROCEDURE DBMS_LOGMNR.ADD_LOGFILE(LOGFILENAME VARCHAR,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LOGMNR.COLUMN_PRESENT(SQL_REDO_UNDO NUMBER,COLUMN_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LOGMNR.END_LOGMNR(COLUMN_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGMNR.REMOVE_LOGFILE(LOGFILENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGMNR.START_LOGMNR(STARTSCN NUMBER,ENDSCN NUMBER,STARTTIME DATE,ENDTIME DATE,DICTFILENAME VARCHAR,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

