CREATE SCHEMA DBMS_WORKLOAD_CAPTURE;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.ADD_FILTER(FNAME VARCHAR,FATTRIBUTE VARCHAR,FVALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.ADD_FILTER(FNAME VARCHAR,FATTRIBUTE VARCHAR,FVALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.DELETE_CAPTURE_INFO(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.DELETE_FILTER(FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.EXPORT_AWR(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.EXPORT_PERFORMANCE_DATA(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.EXPORT_UC_GRAPH(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.FINISH_CAPTURE(TIMEOUT NUMBER,REASON VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_CAPTURE.GET_CAPTURE_INFO(DIR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_CAPTURE.GET_CAPTURE_PATH(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.GET_PERF_DATA_EXPORT_STATUS(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_CAPTURE.GET_STATE(STAGING_SCHEMA VARCHAR,FORCE_CLEANUP BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_CAPTURE.IMPORT_PERFORMANCE_DATA(CAPTURE_ID NUMBER,STAGING_SCHEMA VARCHAR,FORCE_CLEANUP BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.IMPORT_UC_GRAPH(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_CAPTURE.REPORT(CAPTURE_ID NUMBER,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_CAPTURE.START_CAPTURE(NAME VARCHAR,DIR VARCHAR,DURATION NUMBER,DEFAULT_ACTION VARCHAR,AUTO_UNRESTRICT BOOLEAN,CAPTURE_STS BOOLEAN,STS_CAP_INTERVAL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_CAPTURE.USER_CALLS_GRAPH(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

