CREATE SCHEMA DBMS_RESOURCE_MANAGER;

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.BEGIN_SQL_BLOCK(MAX_LATENCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.CLEAR_PENDING_AREA(COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.CREATE_CDB_PLAN(PLAN VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.CREATE_CDB_PLAN_DIRECTIVE(PLAN VARCHAR,PLUGGABLE_DATABASE VARCHAR,COMMENT VARCHAR,SHARES NUMBER,UTILIZATION_LIMIT NUMBER,PARALLEL_SERVER_LIMIT NUMBER,MEMORY_MIN NUMBER,MEMORY_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.CREATE_CDB_PROFILE_DIRECTIVE(PLAN VARCHAR,PROFILE VARCHAR,COMMENT VARCHAR,SHARES NUMBER,UTILIZATION_LIMIT NUMBER,PARALLEL_SERVER_LIMIT NUMBER,MEMORY_MIN NUMBER,MEMORY_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.CREATE_CONSUMER_GROUP(CONSUMER_GROUP VARCHAR,COMMENT VARCHAR,CPU_MTH VARCHAR,MGMT_MTH VARCHAR,CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA(COMMENT VARCHAR,CPU_MTH VARCHAR,ACTIVE_SESS_POOL_MTH VARCHAR,PARALLEL_DEGREE_LIMIT_MTH VARCHAR,QUEUEING_MTH VARCHAR,MGMT_MTH VARCHAR,SUB_PLAN BOOLEAN,MAX_IOPS NUMBER,MAX_MBPS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE(PLAN VARCHAR,GROUP_OR_SUBPLAN VARCHAR,COMMENT VARCHAR,CPU_P1 NUMBER,CPU_P2 NUMBER,CPU_P3 NUMBER,CPU_P4 NUMBER,CPU_P5 NUMBER,CPU_P6 NUMBER,CPU_P7 NUMBER,CPU_P8 NUMBER,ACTIVE_SESS_POOL_P1 NUMBER,QUEUEING_P1 NUMBER,PARALLEL_DEGREE_LIMIT_P1 NUMBER,SWITCH_GROUP VARCHAR,SWITCH_TIME NUMBER,SWITCH_ESTIMATE BOOLEAN,MAX_EST_EXEC_TIME NUMBER,UNDO_POOL NUMBER,MAX_IDLE_TIME NUMBER,MAX_IDLE_BLOCKER_TIME NUMBER,SWITCH_TIME_IN_CALL NUMBER,MGMT_P1 NUMBER,MGMT_P2 NUMBER,MGMT_P3 NUMBER,MGMT_P4 NUMBER,MGMT_P5 NUMBER,MGMT_P6 NUMBER,MGMT_P7 NUMBER,MGMT_P8 NUMBER,SWITCH_IO_MEGABYTES NUMBER,SWITCH_IO_REQS NUMBER,SWITCH_FOR_CALL BOOLEAN,MAX_UTILIZATION_LIMIT NUMBER,PARALLEL_TARGET_PERCENTAGE NUMBER,PARALLEL_QUEUE_TIMEOUT NUMBER,PARALLEL_SERVER_LIMIT NUMBER,UTILIZATION_LIMIT NUMBER,SWITCH_IO_LOGICAL NUMBER,SWITCH_ELAPSED_TIME NUMBER,SHARES NUMBER,PARALLEL_STMT_CRITICAL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.CREATE_SIMPLE_PLAN(SIMPLE_PLAN VARCHAR,CONSUMER_GROUP1 VARCHAR,GROUP1_CPU NUMBER,CONSUMER_GROUP2 VARCHAR,GROUP2_CPU NUMBER,CONSUMER_GROUP3 VARCHAR,GROUP3_CPU NUMBER,CONSUMER_GROUP4 VARCHAR,GROUP4_CPU NUMBER,CONSUMER_GROUP5 VARCHAR,GROUP5_CPU NUMBER,CONSUMER_GROUP6 VARCHAR,GROUP6_CPU NUMBER,CONSUMER_GROUP7 VARCHAR,GROUP7_CPU NUMBER,CONSUMER_GROUP8 VARCHAR,GROUP8_CPU NUMBER,GROUP1_PERCENT NUMBER,GROUP2_PERCENT NUMBER,GROUP3_PERCENT NUMBER,GROUP4_PERCENT NUMBER,GROUP5_PERCENT NUMBER,GROUP6_PERCENT NUMBER,GROUP7_PERCENT NUMBER,GROUP8_PERCENT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.DELETE_CATEGORY(CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.DELETE_CDB_PLAN(PLAN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.DELETE_CDB_PLAN_DIRECTIVE(PLAN VARCHAR,PLUGGABLE_DATABASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.DELETE_CDB_PROFILE_DIRECTIVE(PLAN VARCHAR,PROFILE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.DELETE_CONSUMER_GROUP(CONSUMER_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.DELETE_PLAN(PLAN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.DELETE_PLAN_CASCADE(PLAN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.DELETE_PLAN_DIRECTIVE(PLAN VARCHAR,GROUP_OR_SUBPLAN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.END_SQL_BLOCK(VALUE VARCHAR,CONSUMER_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.SET_CONSUMER_GROUP_MAPPING_PRI(EXPLICIT NUMBER,ORACLE_USER NUMBER,SERVICE_NAME NUMBER,CLIENT_OS_USER NUMBER,CLIENT_PROGRAM NUMBER,CLIENT_MACHINE NUMBER,MODULE_NAME NUMBER,MODULE_NAME_ACTION NUMBER,SERVICE_MODULE NUMBER,SERVICE_MODULE_ACTION NUMBER,CLIENT_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.SET_INITIAL_CONSUMER_GROUP(USER VARCHAR,CONSUMER_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA(SESSION_SERIAL NUMBER,CONSUMER_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.SWITCH_CONSUMER_GROUP_FOR_USER(USER VARCHAR,CONSUMER_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.SWITCH_PLAN(PLAN_NAME VARCHAR,SID VARCHAR,ALLOW_SCHEDULER_PLAN_SWITCHES BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_CATEGORY(CATEGORY VARCHAR,NEW_COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_CDB_AUTOTASK_DIRECTIVE(PLAN VARCHAR,NEW_COMMENT VARCHAR,NEW_SHARES NUMBER,NEW_UTILIZATION_LIMIT NUMBER,NEW_PARALLEL_SERVER_LIMIT NUMBER,NEW_MEMORY_MIN NUMBER,NEW_MEMORY_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_CDB_DEFAULT_DIRECTIVE(PLAN VARCHAR,NEW_COMMENT VARCHAR,NEW_SHARES NUMBER,NEW_UTILIZATION_LIMIT NUMBER,NEW_PARALLEL_SERVER_LIMIT NUMBER,NEW_MEMORY_MIN NUMBER,NEW_MEMORY_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_CDB_PLAN(PLAN VARCHAR,NEW_COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_CDB_PLAN_DIRECTIVE(PLAN VARCHAR,PLUGGABLE_DATABASE VARCHAR,NEW_COMMENT VARCHAR,NEW_SHARES NUMBER,NEW_UTILIZATION_LIMIT NUMBER,NEW_PARALLEL_SERVER_LIMIT NUMBER,NEW_MEMORY_MIN NUMBER,NEW_MEMORY_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_CDB_PROFILE_DIRECTIVE(PLAN VARCHAR,PROFILE VARCHAR,NEW_COMMENT VARCHAR,NEW_SHARES NUMBER,NEW_UTILIZATION_LIMIT NUMBER,NEW_PARALLEL_SERVER_LIMIT NUMBER,NEW_MEMORY_MIN NUMBER,NEW_MEMORY_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_CONSUMER_GROUP(CONSUMER_GROUP VARCHAR,NEW_COMMENT VARCHAR,NEW_CPU_MTH VARCHAR,NEW_MGMT_MTH VARCHAR,NEW_CATEGORY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_PLAN(PLAN VARCHAR,NEW_COMMENT VARCHAR,NEW_CPU_MTH VARCHAR,NEW_ACTIVE_SESS_POOL_MTH VARCHAR,NEW_PARALLEL_DEGREE_LIMIT_MTH VARCHAR,NEW_QUEUEING_MTH VARCHAR,NEW_MGMT_MTH VARCHAR,NEW_SUB_PLAN BOOLEAN,NEW_MAX_IOPS NUMBER,NEW_MAX_MBPS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.UPDATE_PLAN_DIRECTIVE(PLAN VARCHAR,GROUP_OR_SUBPLAN VARCHAR,NEW_COMMENT VARCHAR,NEW_CPU_P1 NUMBER,NEW_CPU_P2 NUMBER,NEW_CPU_P3 NUMBER,NEW_CPU_P4 NUMBER,NEW_CPU_P5 NUMBER,NEW_CPU_P6 NUMBER,NEW_CPU_P7 NUMBER,NEW_CPU_P8 NUMBER,NEW_ACTIVE_SESS_POOL_P1 NUMBER,NEW_QUEUEING_P1 NUMBER,NEW_PARALLEL_DEGREE_LIMIT_P1 NUMBER,NEW_SWITCH_GROUP VARCHAR,NEW_SWITCH_TIME NUMBER,NEW_SWITCH_ESTIMATE BOOLEAN,NEW_MAX_EST_EXEC_TIME NUMBER,NEW_UNDO_POOL NUMBER,NEW_MAX_IDLE_TIME NUMBER,NEW_MAX_IDLE_BLOCKER_TIME NUMBER,NEW_SWITCH_TIME_IN_CALL NUMBER,NEW_MGMT_P1 NUMBER,NEW_MGMT_P2 NUMBER,NEW_MGMT_P3 NUMBER,NEW_MGMT_P4 NUMBER,NEW_MGMT_P5 NUMBER,NEW_MGMT_P6 NUMBER,NEW_MGMT_P7 NUMBER,NEW_MGMT_P8 NUMBER,NEW_SWITCH_IO_MEGABYTES NUMBER,NEW_SWITCH_IO_REQS NUMBER,NEW_SWITCH_FOR_CALL BOOLEAN,NEW_MAX_UTILIZATION_LIMIT NUMBER,NEW_PARALLEL_TARGET_PERCENTAGE NUMBER,NEW_PARALLEL_QUEUE_TIMEOUT NUMBER,NEW_PARALLEL_SERVER_LIMIT NUMBER,NEW_UTILIZATION_LIMIT NUMBER,NEW_SWITCH_IO_LOGICAL NUMBER,NEW_SWITCH_ELAPSED_TIME NUMBER,NEW_SHARES NUMBER,NEW_PARALLEL_STMT_CRITICAL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

