CREATE SCHEMA DBMS_LOGSTDBY;

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.APPLY_SET(INNAME VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.APPLY_UNSET(INNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.BUILD()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LOGSTDBY.DB_IS_LOGSTDBY(TABLE_NAME VARCHAR,P_DBLINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.EDS_EVOLVE_AUTOMATIC(OPTIONS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.EDS_EVOLVE_MANUAL(OPTIONS VARCHAR,TABLE_OWNER VARCHAR,TABLE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.EDS_REMOVE_TABLE(TABLE_OWNER VARCHAR,TABLE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.INSTANTIATE_TABLE(SCHEMA_NAME VARCHAR,TABLE_NAME VARCHAR,DBLINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LOGSTDBY.IS_APPLY_SERVER()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.PREPARE_FOR_NEW_PRIMARY(FORMER_STANDBY_TYPE VARCHAR,DBLINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.PURGE_SESSION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.REBUILD()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.SKIP(STMT VARCHAR,SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR,PROC_NAME VARCHAR,USE_LIKE BOOLEAN,ESC CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.SKIP_ERROR(STMT VARCHAR,SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR,PROC_NAME VARCHAR,USE_LIKE BOOLEAN,ESC CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.SKIP_TRANSACTION(XIDUSN_P NUMBER,XIDSLT_P NUMBER,XIDSQN_P NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.UNSKIP(STMT VARCHAR,SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.UNSKIP_ERROR(STMT VARCHAR,SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGSTDBY.UNSKIP_TRANSACTION(XIDUSN_P NUMBER,XIDSLT_P NUMBER,XIDSQN_P NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

