CREATE SCHEMA DBMS_LOCK;

CREATE OR REPLACE PROCEDURE DBMS_LOCK.ALLOCATE_UNIQUE(LOCKNAME VARCHAR,EXPIRATION_SECS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOCK.ALLOCATE_UNIQUE_AUTONOMOUS(LOCKNAME VARCHAR,EXPIRATION_SECS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LOCK.CONVERT(ID NUMBER(38),LOCKMODE NUMBER(38),TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LOCK.CONVERT(LOCKHANDLE VARCHAR,LOCKMODE NUMBER(38),TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LOCK.RELEASE(ID NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LOCK.RELEASE(LOCKHANDLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LOCK.REQUEST(ID NUMBER(38),LOCKMODE NUMBER(38),TIMEOUT NUMBER(38),RELEASE_ON_COMMIT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LOCK.REQUEST(LOCKHANDLE VARCHAR,LOCKMODE NUMBER(38),TIMEOUT NUMBER(38),RELEASE_ON_COMMIT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LOCK.SLEEP(SECONDS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

