CREATE SCHEMA DBMS_DESCRIBE;

CREATE OR REPLACE PROCEDURE DBMS_DESCRIBE.DESCRIBE_PROCEDURE(OBJECT_NAME VARCHAR,RESERVED1 VARCHAR,RESERVED2 VARCHAR,INCLUDE_STRING_CONSTRAINTS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

