CREATE SCHEMA DBMS_FGA;

CREATE OR REPLACE PROCEDURE DBMS_FGA.ADD_POLICY(OBJECT_SCHEMA VARCHAR,OBJECT_NAME VARCHAR,POLICY_NAME VARCHAR,AUDIT_CONDITION VARCHAR,AUDIT_COLUMN VARCHAR,HANDLER_SCHEMA VARCHAR,HANDLER_MODULE VARCHAR,ENABLE BOOLEAN,STATEMENT_TYPES VARCHAR,AUDIT_TRAIL NUMBER,AUDIT_COLUMN_OPTS NUMBER,POLICY_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_FGA.DISABLE_POLICY(OBJECT_SCHEMA VARCHAR,OBJECT_NAME VARCHAR,POLICY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_FGA.DROP_POLICY(OBJECT_SCHEMA VARCHAR,OBJECT_NAME VARCHAR,POLICY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_FGA.ENABLE_POLICY(OBJECT_SCHEMA VARCHAR,OBJECT_NAME VARCHAR,POLICY_NAME VARCHAR,ENABLE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

