CREATE SCHEMA DBMS_NETWORK_ACL_UTILITY;

CREATE OR REPLACE FUNCTION DBMS_NETWORK_ACL_UTILITY.CONTAINS_HOST(HOST VARCHAR,DOMAIN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_NETWORK_ACL_UTILITY.DOMAINS(HOST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_NETWORK_ACL_UTILITY.DOMAIN_LEVEL(HOST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_NETWORK_ACL_UTILITY.EQUALS_HOST(HOST1 VARCHAR,HOST2 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

