CREATE SCHEMA DBMS_OFFLINE_OG;

CREATE OR REPLACE PROCEDURE DBMS_OFFLINE_OG.BEGIN_FLAVOR_CHANGE(GNAME VARCHAR,SITE VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_OFFLINE_OG.BEGIN_INSTANTIATION(GNAME VARCHAR,NEW_SITE VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_OFFLINE_OG.BEGIN_LOAD(GNAME VARCHAR,NEW_SITE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_OFFLINE_OG.END_FLAVOR_CHANGE(GNAME VARCHAR,SITE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_OFFLINE_OG.END_INSTANTIATION(GNAME VARCHAR,NEW_SITE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_OFFLINE_OG.END_LOAD(GNAME VARCHAR,NEW_SITE VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_OFFLINE_OG.RESUME_SUBSET_OF_MASTERS(GNAME VARCHAR,NEW_SITE VARCHAR,OVERRIDE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

