CREATE SCHEMA DBMS_MONITOR;

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.CLIENT_ID_STAT_DISABLE(CLIENT_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.CLIENT_ID_STAT_ENABLE(CLIENT_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.CLIENT_ID_TRACE_DISABLE(CLIENT_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.CLIENT_ID_TRACE_ENABLE(CLIENT_ID VARCHAR,WAITS BOOLEAN,BINDS BOOLEAN,PLAN_STAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.DATABASE_TRACE_DISABLE(INSTANCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.DATABASE_TRACE_ENABLE(WAITS BOOLEAN,BINDS BOOLEAN,INSTANCE_NAME VARCHAR,PLAN_STAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.SERV_MOD_ACT_STAT_DISABLE(SERVICE_NAME VARCHAR,MODULE_NAME VARCHAR,ACTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.SERV_MOD_ACT_STAT_ENABLE(SERVICE_NAME VARCHAR,MODULE_NAME VARCHAR,ACTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.SERV_MOD_ACT_TRACE_DISABLE(SERVICE_NAME VARCHAR,MODULE_NAME VARCHAR,ACTION_NAME VARCHAR,INSTANCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.SERV_MOD_ACT_TRACE_ENABLE(SERVICE_NAME VARCHAR,MODULE_NAME VARCHAR,ACTION_NAME VARCHAR,WAITS BOOLEAN,BINDS BOOLEAN,INSTANCE_NAME VARCHAR,PLAN_STAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.SESSION_TRACE_DISABLE(SESSION_ID NUMBER,SERIAL_NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_MONITOR.SESSION_TRACE_ENABLE(SESSION_ID NUMBER,SERIAL_NUM NUMBER,WAITS BOOLEAN,BINDS BOOLEAN,PLAN_STAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

