CREATE SCHEMA DBMS_WORKLOAD_REPLAY;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.ADD_CAPTURE(CAPTURE_DIR_NAME VARCHAR,START_DELAY_SECONDS NUMBER,STOP_REPLAY BOOLEAN,TAKE_BEGIN_SNAPSHOT BOOLEAN,TAKE_END_SNAPSHOT BOOLEAN,QUERY_ONLY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.ADD_CAPTURE(CAPTURE_DIR_NAME VARCHAR,START_DELAY_SECONDS NUMBER,STOP_REPLAY VARCHAR,TAKE_BEGIN_SNAPSHOT VARCHAR,TAKE_END_SNAPSHOT VARCHAR,QUERY_ONLY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.ADD_FILTER(FNAME VARCHAR,FATTRIBUTE VARCHAR,FVALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.ADD_FILTER(FNAME VARCHAR,FATTRIBUTE VARCHAR,FVALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.ADD_SCHEDULE_ORDERING(SCHEDULE_CAPTURE_ID NUMBER,WAITFOR_CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.ADJUST_TIMES_TO_SNAP_TIMEZONE(AWRBSNAP NUMBER,AWRESNAP NUMBER,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.ASSIGN_GROUP_TO_INSTANCE(GROUP_ID NUMBER(38),INSTANCE_NUMBER NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.BEGIN_REPLAY_SCHEDULE(SCHEDULE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.CALIBRATE(CAPTURE_DIR VARCHAR,PROCESS_PER_CPU NUMBER,THREADS_PER_PROCESS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.CANCEL_REPLAY(REASON VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.CLIENT_CONNECT(WHO NUMBER,ARG NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.CLIENT_GET_REPLAY_SUBDIR()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.CLIENT_VITALS(ID NUMBER,NAME VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.COMPARE_PERIOD_REPORT(REPLAY_ID1 NUMBER,REPLAY_ID2 NUMBER,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.COMPARE_SQLSET_REPORT(REPLAY_ID1 NUMBER,REPLAY_ID2 NUMBER,FORMAT VARCHAR,R_LEVEL VARCHAR,R_SECTIONS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.CREATE_FILTER_SET(REPLAY_DIR VARCHAR,FILTER_SET VARCHAR,DEFAULT_ACTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.DELETE_ATTRIBUTE(CAPTURE_ID NUMBER,REPLAY_ID NUMBER,NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.DELETE_FILTER(FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.DELETE_REPLAY_INFO(REPLAY_ID NUMBER,PERMANENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.DELETE_REPLAY_INFO(REPLAY_DIR VARCHAR,PERMANENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.DIVERGING_STATEMENT_STATUS(REPLAY_ID NUMBER,STREAM_ID NUMBER,CALL_COUNTER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.END_REPLAY_SCHEDULE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.EXPORT_PERFORMANCE_DATA(REPLAY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.EXPORT_UC_GRAPH(REPLAY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.GENERATE_CAPTURE_SUBSET(INPUT_CAPTURE_DIR VARCHAR,OUTPUT_CAPTURE_DIR VARCHAR,NEW_CAPTURE_NAME VARCHAR,BEGIN_TIME NUMBER,BEGIN_INCLUDE_INCOMPLETE BOOLEAN,END_TIME NUMBER,END_INCLUDE_INCOMPLETE BOOLEAN,PARALLEL_LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_ADVANCED_PARAMETER(PNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_ATTRIBUTE(CAPTURE_ID NUMBER,REPLAY_ID NUMBER,NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_CAPTURED_TABLES(CAPTURE_DIR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_CLOCK(STREAM_ID NUMBER,CALL_COUNTER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.GET_PERF_DATA_EXPORT_STATUS(REPLAY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_PROCESSING_PATH(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_REPLAY_DIRECTORY(LOAD_DIVERGENCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_REPLAY_INFO(REPLAY_DIR VARCHAR,LOAD_DIVERGENCE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_REPLAY_PATH(REPLAY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.GET_REPLAY_TIMEOUT()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.GET_STATE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.IMPORT_AWR(REPLAY_ID NUMBER,STAGING_SCHEMA VARCHAR,FORCE_CLEANUP BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.IMPORT_PERFORMANCE_DATA(REPLAY_ID NUMBER,STAGING_SCHEMA VARCHAR,FORCE_CLEANUP BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.IMPORT_UC_GRAPH(REPLAY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.INITIALIZE_CONSOLIDATED_REPLAY(REPLAY_NAME VARCHAR,SCHEDULE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.INITIALIZE_REPLAY(REPLAY_NAME VARCHAR,REPLAY_DIR VARCHAR,RAC_INST_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.INITIALIZE_REPLAY_INTERNAL(REPLAY_NAME VARCHAR,REPLAY_DIR VARCHAR,REPLAY_TYPE VARCHAR,RAC_INST_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.IS_REPLAY_PAUSED()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.LOAD_DIVERGENCE(REPLAY_DIR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.LOAD_TRACKED_COMMITS(REPLAY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.PAUSE_REPLAY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.POPULATE_DIVERGENCE(REPLAY_ID NUMBER,STREAM_ID NUMBER,CALL_COUNTER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.POPULATE_DIVERGENCE_STATUS(REPLAY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.PREPARE_CONSOLIDATED_REPLAY(SYNCHRONIZATION BOOLEAN,CONNECT_TIME_SCALE NUMBER,THINK_TIME_SCALE NUMBER,THINK_TIME_AUTO_CORRECT BOOLEAN,CAPTURE_STS BOOLEAN,STS_CAP_INTERVAL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.PREPARE_CONSOLIDATED_REPLAY(SYNCHRONIZATION VARCHAR,CONNECT_TIME_SCALE NUMBER,THINK_TIME_SCALE NUMBER,THINK_TIME_AUTO_CORRECT BOOLEAN,CAPTURE_STS BOOLEAN,STS_CAP_INTERVAL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.PREPARE_REPLAY(SYNCHRONIZATION BOOLEAN,CONNECT_TIME_SCALE NUMBER,THINK_TIME_SCALE NUMBER,THINK_TIME_AUTO_CORRECT BOOLEAN,SCALE_UP_MULTIPLIER NUMBER,CAPTURE_STS BOOLEAN,STS_CAP_INTERVAL NUMBER,RAC_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.PREPARE_REPLAY(SYNCHRONIZATION VARCHAR,CONNECT_TIME_SCALE NUMBER,THINK_TIME_SCALE NUMBER,THINK_TIME_AUTO_CORRECT BOOLEAN,SCALE_UP_MULTIPLIER NUMBER,CAPTURE_STS BOOLEAN,STS_CAP_INTERVAL NUMBER,RAC_MODE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.PROCESS_CAPTURE(CAPTURE_DIR VARCHAR,PARALLEL_LEVEL NUMBER,IS_AS_REPLAY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.PROCESS_CAPTURE_COMPLETION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.PROCESS_CAPTURE_REMAINING_TIME()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.REMAP_CONNECTION(CONNECTION_ID NUMBER,REPLAY_CONNECTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.REMAP_CONNECTION(SCHEDULE_CAP_ID NUMBER,CONNECTION_ID NUMBER,REPLAY_CONNECTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.REMOVE_CAPTURE(SCHEDULE_CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.REMOVE_REPLAY_SCHEDULE(SCHEDULE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.REMOVE_SCHEDULE_ORDERING(SCHEDULE_CAPTURE_ID NUMBER,WAITFOR_CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.REPORT(REPLAY_ID NUMBER,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.RESET_ADVANCED_PARAMETERS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.RESUME_REPLAY(FILTER_SET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_ADVANCED_PARAMETER(PNAME VARCHAR,PVALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_ADVANCED_PARAMETER(PNAME VARCHAR,PVALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_ADVANCED_PARAMETER(PNAME VARCHAR,PVALUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_ATTRIBUTE(CAPTURE_ID NUMBER,REPLAY_ID NUMBER,NAME VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_CONSOLIDATED_DIRECTORY(REPLAY_DIR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_REPLAY_DIRECTORY(REPLAY_DIR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_REPLAY_TIMEOUT(ENABLED BOOLEAN,MIN_DELAY NUMBER,MAX_DELAY NUMBER,DELAY_FACTOR NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_USER_MAPPING(SCHEDULE_CAP_ID NUMBER,CAPTURE_USER VARCHAR,REPLAY_USER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SET_USER_MAPPING(CAPTURE_USER VARCHAR,REPLAY_USER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.START_CONSOLIDATED_REPLAY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.START_REPLAY(STS_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.SYNC_ATTRIBUTES_FROM_FILE(CAPTURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.USER_CALLS_GRAPH(REPLAY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPLAY.USE_FILTER_SET(FILTER_SET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPLAY.WORKLOAD_INTELLIGENCE_REPORT(WI_JOB_NAME VARCHAR,TOP_RESULTS NUMBER,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

