CREATE SCHEMA DBMS_AUTO_TASK_ADMIN;

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.DEFAULT_RESET(CLIENT_NAME VARCHAR,OPERATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.DISABLE(OPERATION VARCHAR,WINDOW_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.ENABLE(OPERATION VARCHAR,WINDOW_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.GET_CLIENT_ATTRIBUTES(CLIENT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.GET_P1_RESOURCES()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.OVERRIDE_PRIORITY(CLIENT_NAME VARCHAR,PRIORITY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.OVERRIDE_PRIORITY(CLIENT_NAME VARCHAR,OPERATION VARCHAR,PRIORITY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.SET_ATTRIBUTE(CLIENT_NAME VARCHAR,ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.SET_ATTRIBUTE(CLIENT_NAME VARCHAR,OPERATION VARCHAR,ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.SET_CLIENT_SERVICE(CLIENT_NAME VARCHAR,SERVICE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_AUTO_TASK_ADMIN.SET_P1_RESOURCES(STATS_GROUP_PCT NUMBER,SEG_GROUP_PCT NUMBER,TUNE_GROUP_PCT NUMBER,HEALTH_GROUP_PCT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

