CREATE SCHEMA DBMS_APPLICATION_INFO;

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.READ_CLIENT_INFO()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.READ_MODULE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_ACTION(ACTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_CLIENT_INFO(CLIENT_INFO VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_MODULE(MODULE_NAME VARCHAR,ACTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_SESSION_LONGOPS(OP_NAME VARCHAR,TARGET NUMBER,CONTEXT NUMBER,SOFAR NUMBER,TOTALWORK NUMBER,TARGET_DESC VARCHAR,UNITS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

