CREATE SCHEMA DBMS_TRACE;

CREATE OR REPLACE PROCEDURE DBMS_TRACE.CLEAR_PLSQL_TRACE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_TRACE.GET_PLSQL_TRACE_LEVEL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_TRACE.GET_PLSQL_TRACE_RUNNUMBER()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_TRACE.INTERNAL_VERSION_CHECK()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_TRACE.PAUSE_PLSQL_TRACE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_TRACE.RESUME_PLSQL_TRACE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

