CREATE SCHEMA DBMS_STREAMS_ADVISOR_ADM;

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_ADVISOR_ADM.ANALYZE_CURRENT_PERFORMANCE(COMPONENT_NAME VARCHAR,COMPONENT_DB VARCHAR,COMPONENT_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

