CREATE SCHEMA DBMS_FLASHBACK;

CREATE OR REPLACE PROCEDURE DBMS_FLASHBACK.DISABLE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_FLASHBACK.ENABLE_AT_TIME(QUERY_TIME TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_FLASHBACK.GET_SYSTEM_CHANGE_NUMBER(XIDS XID_ARRAY,OPTIONS NUMBER,SCNHINT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_FLASHBACK.TRANSACTION_BACKOUT(NUMTXNS NUMBER,XIDS XID_ARRAY,OPTIONS NUMBER,TIMEHINT TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_FLASHBACK.TRANSACTION_BACKOUT(NUMTXNS NUMBER,NAMES TXNAME_ARRAY,OPTIONS NUMBER,SCNHINT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_FLASHBACK.TRANSACTION_BACKOUT(NUMTXNS NUMBER,NAMES TXNAME_ARRAY,OPTIONS NUMBER,TIMEHINT TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

