CREATE SCHEMA DBMS_SPACE;

CREATE OR REPLACE FUNCTION DBMS_SPACE.ASA_RECOMMENDATIONS(ALL_RUNS VARCHAR,SHOW_MANUAL VARCHAR,SHOW_FINDINGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SPACE.AUTO_SPACE_ADVISOR_JOB_PROC(PLAN_TABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SPACE.CREATE_TABLE_COST(TABLESPACE_NAME VARCHAR,AVG_ROW_SIZE NUMBER,ROW_COUNT NUMBER,PCT_FREE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SPACE.CREATE_TABLE_COST(TABLESPACE_NAME VARCHAR,COLINFOS CREATE_TABLE_COST_COLUMNS,ROW_COUNT NUMBER,PCT_FREE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SPACE.DBFS_DF(USERID NUMBER,NTBS NUMBER,INTS_LIST TABLESPACE_LIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SPACE.FREE_BLOCKS(SEGMENT_OWNER VARCHAR,SEGMENT_NAME VARCHAR,SEGMENT_TYPE VARCHAR,FREELIST_GROUP_ID NUMBER,SCAN_LIMIT NUMBER,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SPACE.ISDATAFILEDROPPABLE_NAME(FILENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SPACE.OBJECT_DEPENDENT_SEGMENTS(OBJOWNER VARCHAR,OBJNAME VARCHAR,PARTNAME VARCHAR,OBJTYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SPACE.OBJECT_GROWTH_TREND(OBJECT_OWNER VARCHAR,OBJECT_NAME VARCHAR,OBJECT_TYPE VARCHAR,PARTITION_NAME VARCHAR,START_TIME TIMESTAMP,END_TIME TIMESTAMP,SKIP_INTERPOLATED VARCHAR,TIMEOUT_SECONDS NUMBER,SINGLE_DATAPOINT_FLAG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SPACE.OBJECT_GROWTH_TREND_CUR(OBJECT_OWNER VARCHAR,OBJECT_NAME VARCHAR,OBJECT_TYPE VARCHAR,PARTITION_NAME VARCHAR,START_TIME TIMESTAMP,END_TIME TIMESTAMP,SKIP_INTERPOLATED VARCHAR,TIMEOUT_SECONDS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SPACE.OBJECT_GROWTH_TREND_CURTAB()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SPACE.OBJECT_GROWTH_TREND_SWRF(OBJECT_OWNER VARCHAR,OBJECT_NAME VARCHAR,OBJECT_TYPE VARCHAR,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SPACE.OBJECT_GROWTH_TREND_S_TO_I(SECSIN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SPACE.OBJECT_SPACE_USAGE(OBJECT_OWNER VARCHAR,OBJECT_NAME VARCHAR,OBJECT_TYPE VARCHAR,SAMPLE_CONTROL NUMBER,PARTITION_NAME VARCHAR,PRESERVE_RESULT BOOLEAN,TIMEOUT_SECONDS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SPACE.OBJECT_SPACE_USAGE_TBF(OBJECT_OWNER VARCHAR,OBJECT_NAME VARCHAR,OBJECT_TYPE VARCHAR,SAMPLE_CONTROL NUMBER,PARTITION_NAME VARCHAR,PRESERVE_RESULT VARCHAR,TIMEOUT_SECONDS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SPACE.PARSE_SPACE_ADV_INFO(INFO VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SPACE.SPACE_USAGE(SEGMENT_OWNER VARCHAR,SEGMENT_NAME VARCHAR,SEGMENT_TYPE VARCHAR,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SPACE.SPACE_USAGE(SEGMENT_OWNER VARCHAR,SEGMENT_NAME VARCHAR,SEGMENT_TYPE VARCHAR,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SPACE.SPACE_USAGE(SEGMENT_OWNER VARCHAR,SEGMENT_NAME VARCHAR,SEGMENT_TYPE VARCHAR,SUOPTION NUMBER,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SPACE.UNUSED_SPACE(SEGMENT_OWNER VARCHAR,SEGMENT_NAME VARCHAR,SEGMENT_TYPE VARCHAR,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SPACE.VERIFY_SHRINK_CANDIDATE(SEGMENT_OWNER VARCHAR,SEGMENT_NAME VARCHAR,SEGMENT_TYPE VARCHAR,SHRINK_TARGET_BYTES NUMBER,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SPACE.VERIFY_SHRINK_CANDIDATE_TBF(SEGMENT_OWNER VARCHAR,SEGMENT_NAME VARCHAR,SEGMENT_TYPE VARCHAR,SHRINK_TARGET_BYTES NUMBER,PARTITION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

