CREATE SCHEMA DBMS_STREAMS_MESSAGING;

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_MESSAGING.DEQUEUE(QUEUE_NAME VARCHAR,STREAMS_NAME VARCHAR,DEQUEUE_MODE VARCHAR,NAVIGATION VARCHAR,WAIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_MESSAGING.DEQUEUE(QUEUE_NAME VARCHAR,STREAMS_NAME VARCHAR,DEQUEUE_MODE VARCHAR,NAVIGATION VARCHAR,WAIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_MESSAGING.ENQUEUE(QUEUE_NAME VARCHAR,PAYLOAD ANYDATA)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_MESSAGING.ENQUEUE(QUEUE_NAME VARCHAR,PAYLOAD ANYDATA)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

