CREATE SCHEMA DBMS_CDC_SUBSCRIBE;

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.ACTIVATE_SUBSCRIPTION(SUBSCRIPTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.ACTIVATE_SUBSCRIPTION(SUBSCRIPTION_HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.CREATE_SUBSCRIPTION(CHANGE_SET_NAME VARCHAR,DESCRIPTION VARCHAR,SUBSCRIPTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.DROP_SUBSCRIBER_VIEW(SUBSCRIPTION_HANDLE NUMBER,SOURCE_SCHEMA VARCHAR,SOURCE_TABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.DROP_SUBSCRIPTION(SUBSCRIPTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.DROP_SUBSCRIPTION(SUBSCRIPTION_HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.EXTEND_WINDOW(SUBSCRIPTION_NAME VARCHAR,UPPER_BOUND DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.EXTEND_WINDOW(SUBSCRIPTION_HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.GET_SUBSCRIPTION_HANDLE(CHANGE_SET VARCHAR,DESCRIPTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.PREPARE_SUBSCRIBER_VIEW(SUBSCRIPTION_HANDLE NUMBER,SOURCE_SCHEMA VARCHAR,SOURCE_TABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.PURGE_WINDOW(SUBSCRIPTION_NAME VARCHAR,LOWER_BOUND DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.PURGE_WINDOW(SUBSCRIPTION_HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.SUBSCRIBE(SUBSCRIPTION_NAME VARCHAR,SOURCE_SCHEMA VARCHAR,SOURCE_TABLE VARCHAR,COLUMN_LIST VARCHAR,SUBSCRIBER_VIEW VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.SUBSCRIBE(SUBSCRIPTION_NAME VARCHAR,PUBLICATION_ID NUMBER,COLUMN_LIST VARCHAR,SUBSCRIBER_VIEW VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.SUBSCRIBE(SUBSCRIPTION_HANDLE NUMBER,SOURCE_SCHEMA VARCHAR,SOURCE_TABLE VARCHAR,COLUMN_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_SUBSCRIBE.SUBSCRIBE(SUBSCRIPTION_HANDLE NUMBER,PUBLICATION_ID NUMBER,COLUMN_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

