CREATE SCHEMA DBMS_RULE;

CREATE OR REPLACE PROCEDURE DBMS_RULE.CLOSE_ITERATOR(ITERATOR NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RULE.EVALUATE(RULE_SET_NAME VARCHAR,EVALUATION_CONTEXT VARCHAR,EVENT_CONTEXT RE$NV_LIST,TABLE_VALUES RE$TABLE_VALUE_LIST,COLUMN_VALUES RE$COLUMN_VALUE_LIST,VARIABLE_VALUES RE$VARIABLE_VALUE_LIST,ATTRIBUTE_VALUES RE$ATTRIBUTE_VALUE_LIST,STOP_ON_FIRST_HIT BOOLEAN,SIMPLE_RULES_ONLY BOOLEAN,RESULT_CACHE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RULE.EVALUATE(RULE_SET_NAME VARCHAR,EVALUATION_CONTEXT VARCHAR,EVENT_CONTEXT RE$NV_LIST,TABLE_VALUES RE$TABLE_VALUE_LIST,COLUMN_VALUES RE$COLUMN_VALUE_LIST,VARIABLE_VALUES RE$VARIABLE_VALUE_LIST,ATTRIBUTE_VALUES RE$ATTRIBUTE_VALUE_LIST,SIMPLE_RULES_ONLY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RULE.EVALUATE_EXPRESSION(RULE_EXPRESSION VARCHAR,TABLE_ALIASES RE$TABLE_ALIAS_LIST,VARIABLE_TYPES RE$VARIABLE_TYPE_LIST,TABLE_VALUES RE$TABLE_VALUE_LIST,COLUMN_VALUES RE$COLUMN_VALUE_LIST,VARIABLE_VALUES RE$VARIABLE_VALUE_LIST,ATTRIBUTE_VALUES RE$ATTRIBUTE_VALUE_LIST,CACHE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_RULE.GET_NEXT_HIT(ITERATOR NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_RULE.IS_FAST(EXPRESSION VARCHAR,TABLE_ALIASES RE$TABLE_ALIAS_LIST,VARIABLE_TYPES RE$VARIABLE_TYPE_LIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

