CREATE SCHEMA DBMS_FILE_TRANSFER;

CREATE OR REPLACE PROCEDURE DBMS_FILE_TRANSFER.COPY_FILE(SOURCE_DIRECTORY_OBJECT VARCHAR,SOURCE_FILE_NAME VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,DESTINATION_FILE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_FILE_TRANSFER.GET_FILE(SOURCE_DIRECTORY_OBJECT VARCHAR,SOURCE_FILE_NAME VARCHAR,SOURCE_DATABASE VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,DESTINATION_FILE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_FILE_TRANSFER.PUT_FILE(SOURCE_DIRECTORY_OBJECT VARCHAR,SOURCE_FILE_NAME VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,DESTINATION_FILE_NAME VARCHAR,DESTINATION_DATABASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

