CREATE SCHEMA DBMS_WORKLOAD_REPOSITORY;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.ADD_COLORED_SQL(SQL_ID VARCHAR,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.ASH_GLOBAL_REPORT_HTML(L_DBID NUMBER,L_INST_NUM VARCHAR,L_BTIME DATE,L_ETIME DATE,L_OPTIONS NUMBER,L_SLOT_WIDTH NUMBER,L_SID NUMBER,L_SQL_ID VARCHAR,L_WAIT_CLASS VARCHAR,L_SERVICE_HASH NUMBER,L_MODULE VARCHAR,L_ACTION VARCHAR,L_CLIENT_ID VARCHAR,L_PLSQL_ENTRY VARCHAR,L_DATA_SRC NUMBER,L_CONTAINER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.ASH_GLOBAL_REPORT_TEXT(L_DBID NUMBER,L_INST_NUM VARCHAR,L_BTIME DATE,L_ETIME DATE,L_OPTIONS NUMBER,L_SLOT_WIDTH NUMBER,L_SID NUMBER,L_SQL_ID VARCHAR,L_WAIT_CLASS VARCHAR,L_SERVICE_HASH NUMBER,L_MODULE VARCHAR,L_ACTION VARCHAR,L_CLIENT_ID VARCHAR,L_PLSQL_ENTRY VARCHAR,L_DATA_SRC NUMBER,L_CONTAINER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.ASH_REPORT_ANALYTICS(DBID NUMBER,INST_ID NUMBER,BEGIN_TIME DATE,END_TIME DATE,REPORT_LEVEL VARCHAR,FILTER_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.ASH_REPORT_HTML(L_DBID NUMBER,L_INST_NUM NUMBER,L_BTIME DATE,L_ETIME DATE,L_OPTIONS NUMBER,L_SLOT_WIDTH NUMBER,L_SID NUMBER,L_SQL_ID VARCHAR,L_WAIT_CLASS VARCHAR,L_SERVICE_HASH NUMBER,L_MODULE VARCHAR,L_ACTION VARCHAR,L_CLIENT_ID VARCHAR,L_PLSQL_ENTRY VARCHAR,L_DATA_SRC NUMBER,L_CONTAINER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.ASH_REPORT_TEXT(L_DBID NUMBER,L_INST_NUM NUMBER,L_BTIME DATE,L_ETIME DATE,L_OPTIONS NUMBER,L_SLOT_WIDTH NUMBER,L_SID NUMBER,L_SQL_ID VARCHAR,L_WAIT_CLASS VARCHAR,L_SERVICE_HASH NUMBER,L_MODULE VARCHAR,L_ACTION VARCHAR,L_CLIENT_ID VARCHAR,L_PLSQL_ENTRY VARCHAR,L_DATA_SRC NUMBER,L_CONTAINER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_DIFF_REPORT_HTML(DBID1 NUMBER,INST_NUM1 NUMBER,BID1 NUMBER,EID1 NUMBER,DBID2 NUMBER,INST_NUM2 NUMBER,BID2 NUMBER,EID2 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_DIFF_REPORT_TEXT(DBID1 NUMBER,INST_NUM1 NUMBER,BID1 NUMBER,EID1 NUMBER,DBID2 NUMBER,INST_NUM2 NUMBER,BID2 NUMBER,EID2 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_GLOBAL_DIFF_REPORT_HTML(DBID1 NUMBER,INST_NUM1 AWRRPT_INSTANCE_LIST_TYPE,BID1 NUMBER,EID1 NUMBER,DBID2 NUMBER,INST_NUM2 AWRRPT_INSTANCE_LIST_TYPE,BID2 NUMBER,EID2 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_GLOBAL_DIFF_REPORT_HTML(DBID1 NUMBER,INST_NUM1 VARCHAR,BID1 NUMBER,EID1 NUMBER,DBID2 NUMBER,INST_NUM2 VARCHAR,BID2 NUMBER,EID2 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_GLOBAL_DIFF_REPORT_TEXT(DBID1 NUMBER,INST_NUM1 AWRRPT_INSTANCE_LIST_TYPE,BID1 NUMBER,EID1 NUMBER,DBID2 NUMBER,INST_NUM2 AWRRPT_INSTANCE_LIST_TYPE,BID2 NUMBER,EID2 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_GLOBAL_DIFF_REPORT_TEXT(DBID1 NUMBER,INST_NUM1 VARCHAR,BID1 NUMBER,EID1 NUMBER,DBID2 NUMBER,INST_NUM2 VARCHAR,BID2 NUMBER,EID2 NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_GLOBAL_REPORT_HTML(L_DBID NUMBER,L_INST_NUM AWRRPT_INSTANCE_LIST_TYPE,L_BID NUMBER,L_EID NUMBER,L_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_GLOBAL_REPORT_HTML(L_DBID NUMBER,L_INST_NUM VARCHAR,L_BID NUMBER,L_EID NUMBER,L_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_GLOBAL_REPORT_TEXT(L_DBID NUMBER,L_INST_NUM AWRRPT_INSTANCE_LIST_TYPE,L_BID NUMBER,L_EID NUMBER,L_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_GLOBAL_REPORT_TEXT(L_DBID NUMBER,L_INST_NUM VARCHAR,L_BID NUMBER,L_EID NUMBER,L_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_REPORT_HTML(L_DBID NUMBER,L_INST_NUM NUMBER,L_BID NUMBER,L_EID NUMBER,L_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_REPORT_TEXT(L_DBID NUMBER,L_INST_NUM NUMBER,L_BID NUMBER,L_EID NUMBER,L_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.AWR_SET_REPORT_THRESHOLDS(TOP_N_EVENTS NUMBER,TOP_N_FILES NUMBER,TOP_N_SEGMENTS NUMBER,TOP_N_SERVICES NUMBER,TOP_N_SQL NUMBER,TOP_N_SQL_MAX NUMBER,TOP_SQL_PCT NUMBER,SHMEM_THRESHOLD NUMBER,VERSIONS_THRESHOLD NUMBER,TOP_N_DISKS NUMBER,OUTLIER_PCT NUMBER,OUTLIER_CPU_PCT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_SQL_REPORT_HTML(L_DBID NUMBER,L_INST_NUM NUMBER,L_BID NUMBER,L_EID NUMBER,L_SQLID VARCHAR,L_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.AWR_SQL_REPORT_TEXT(L_DBID NUMBER,L_INST_NUM NUMBER,L_BID NUMBER,L_EID NUMBER,L_SQLID VARCHAR,L_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.CONTROL_RESTRICTED_SNAPSHOT(ALLOW BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.CREATE_BASELINE(START_SNAP_ID NUMBER,END_SNAP_ID NUMBER,BASELINE_NAME VARCHAR,DBID NUMBER,EXPIRATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.CREATE_BASELINE(START_SNAP_ID NUMBER,END_SNAP_ID NUMBER,BASELINE_NAME VARCHAR,DBID NUMBER,EXPIRATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.CREATE_BASELINE(START_TIME DATE,END_TIME DATE,BASELINE_NAME VARCHAR,DBID NUMBER,EXPIRATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.CREATE_BASELINE(START_TIME DATE,END_TIME DATE,BASELINE_NAME VARCHAR,DBID NUMBER,EXPIRATION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.CREATE_BASELINE_TEMPLATE(START_TIME DATE,END_TIME DATE,BASELINE_NAME VARCHAR,TEMPLATE_NAME VARCHAR,EXPIRATION NUMBER,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.CREATE_BASELINE_TEMPLATE(DAY_OF_WEEK VARCHAR,HOUR_IN_DAY NUMBER,DURATION NUMBER,START_TIME DATE,END_TIME DATE,BASELINE_NAME_PREFIX VARCHAR,TEMPLATE_NAME VARCHAR,EXPIRATION NUMBER,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.CREATE_SNAPSHOT(FLUSH_LEVEL VARCHAR,DBID NUMBER,SOURCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.CREATE_SNAPSHOT(FLUSH_LEVEL VARCHAR,DBID NUMBER,SOURCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.DROP_BASELINE(BASELINE_NAME VARCHAR,CASCADE BOOLEAN,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.DROP_BASELINE_TEMPLATE(TEMPLATE_NAME VARCHAR,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.DROP_SNAPSHOT_RANGE(LOW_SNAP_ID NUMBER,HIGH_SNAP_ID NUMBER,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.MODIFY_BASELINE_WINDOW_SIZE(WINDOW_SIZE NUMBER,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.MODIFY_SNAPSHOT_SETTINGS(RETENTION NUMBER,INTERVAL NUMBER,TOPNSQL NUMBER,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.MODIFY_SNAPSHOT_SETTINGS(RETENTION NUMBER,INTERVAL NUMBER,TOPNSQL VARCHAR,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.PURGE_SQL_DETAILS(NUMROWS NUMBER,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.REMOVE_COLORED_SQL(SQL_ID VARCHAR,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.RENAME_BASELINE(OLD_BASELINE_NAME VARCHAR,NEW_BASELINE_NAME VARCHAR,DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.SELECT_BASELINE_DETAILS(L_BASELINE_ID NUMBER,L_BEG_SNAP NUMBER,L_END_SNAP NUMBER,L_DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_WORKLOAD_REPOSITORY.SELECT_BASELINE_METRIC(L_BASELINE_NAME VARCHAR,L_DBID NUMBER,L_INSTANCE_NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_WORKLOAD_REPOSITORY.UPDATE_DATAFILE_INFO()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

