CREATE SCHEMA DBMS_NETWORK_ACL_ADMIN;

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE(ACL VARCHAR,PRINCIPAL VARCHAR,IS_GRANT BOOLEAN,PRIVILEGE VARCHAR,POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.APPEND_HOST_ACE(HOST VARCHAR,LOWER_PORT NUMBER,UPPER_PORT NUMBER,ACE XS$ACE_TYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.APPEND_HOST_ACL(HOST VARCHAR,LOWER_PORT NUMBER,UPPER_PORT NUMBER,ACL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.APPEND_WALLET_ACE(WALLET_PATH VARCHAR,ACE XS$ACE_TYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.APPEND_WALLET_ACL(WALLET_PATH VARCHAR,ACL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL(ACL VARCHAR,HOST VARCHAR,LOWER_PORT NUMBER,UPPER_PORT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.ASSIGN_WALLET_ACL(ACL VARCHAR,WALLET_PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_NETWORK_ACL_ADMIN.CHECK_PRIVILEGE(ACL VARCHAR,USER VARCHAR,PRIVILEGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_NETWORK_ACL_ADMIN.CHECK_PRIVILEGE_ACLID(ACLID RAW,USER VARCHAR,PRIVILEGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.CREATE_ACL(ACL VARCHAR,DESCRIPTION VARCHAR,PRINCIPAL VARCHAR,IS_GRANT BOOLEAN,PRIVILEGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.DELETE_PRIVILEGE(ACL VARCHAR,PRINCIPAL VARCHAR,IS_GRANT BOOLEAN,PRIVILEGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.DROP_ACL(ACL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_NETWORK_ACL_ADMIN.GET_HOST_ACLIDS(HOST VARCHAR,PORT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_NETWORK_ACL_ADMIN.GET_WALLET_ACLID(WALLET_PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.INSTANCE_CALLOUT_IMP(OBJ_NAME VARCHAR,OBJ_SCHEMA VARCHAR,OBJ_TYPE NUMBER,PREPOST NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.INSTANCE_EXPORT_ACTION(OBJ_NAME VARCHAR,OBJ_SCHEMA VARCHAR,OBJ_TYPE NUMBER,TGT_VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.REMOVE_HOST_ACE(HOST VARCHAR,LOWER_PORT NUMBER,UPPER_PORT NUMBER,ACE XS$ACE_TYPE,REMOVE_EMPTY_ACL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.REMOVE_WALLET_ACE(WALLET_PATH VARCHAR,ACE XS$ACE_TYPE,REMOVE_EMPTY_ACL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.SET_HOST_ACL(HOST VARCHAR,LOWER_PORT NUMBER,UPPER_PORT NUMBER,ACL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.SET_WALLET_ACL(WALLET_PATH VARCHAR,ACL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.UNASSIGN_ACL(ACL VARCHAR,HOST VARCHAR,LOWER_PORT NUMBER,UPPER_PORT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_NETWORK_ACL_ADMIN.UNASSIGN_WALLET_ACL(ACL VARCHAR,WALLET_PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

