CREATE SCHEMA DBMS_DISTRIBUTED_TRUST_ADMIN;

CREATE OR REPLACE PROCEDURE DBMS_DISTRIBUTED_TRUST_ADMIN.ALLOW_ALL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DISTRIBUTED_TRUST_ADMIN.DENY_ALL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

