CREATE SCHEMA DBMS_REFRESH;

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.ADD(NAME VARCHAR,LIST VARCHAR,LAX BOOLEAN,SITEID NUMBER,EXPORT_DB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.ADD(NAME VARCHAR,LAX BOOLEAN,SITEID NUMBER,EXPORT_DB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.CHANGE(NAME VARCHAR,NEXT_DATE DATE,INTERVAL VARCHAR,IMPLICIT_DESTROY BOOLEAN,ROLLBACK_SEG VARCHAR,PUSH_DEFERRED_RPC BOOLEAN,REFRESH_AFTER_ERRORS BOOLEAN,PURGE_OPTION NUMBER,PARALLELISM NUMBER,HEAP_SIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.DESTROY(NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.MAKE(NAME VARCHAR,LIST VARCHAR,NEXT_DATE DATE,INTERVAL VARCHAR,IMPLICIT_DESTROY BOOLEAN,LAX BOOLEAN,JOB NUMBER,ROLLBACK_SEG VARCHAR,PUSH_DEFERRED_RPC BOOLEAN,REFRESH_AFTER_ERRORS BOOLEAN,PURGE_OPTION NUMBER,PARALLELISM NUMBER,HEAP_SIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.MAKE(NAME VARCHAR,NEXT_DATE DATE,INTERVAL VARCHAR,IMPLICIT_DESTROY BOOLEAN,LAX BOOLEAN,JOB NUMBER,ROLLBACK_SEG VARCHAR,PUSH_DEFERRED_RPC BOOLEAN,REFRESH_AFTER_ERRORS BOOLEAN,PURGE_OPTION NUMBER,PARALLELISM NUMBER,HEAP_SIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.MAKE_REPAPI(REFGROUP NUMBER,NAME VARCHAR,SITEID NUMBER,REFRESH_SEQ NUMBER,EXPORT_DB VARCHAR,FLAG NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.REFRESH(NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.SUBTRACT(NAME VARCHAR,LIST VARCHAR,LAX BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.SUBTRACT(NAME VARCHAR,LAX BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.USER_EXPORT(RG# NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REFRESH.USER_EXPORT_CHILD(MYOWNER VARCHAR,MYNAME VARCHAR,MYTYPE VARCHAR,MYSITE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

