CREATE SCHEMA DBMS_ERRLOG;

CREATE OR REPLACE PROCEDURE DBMS_ERRLOG.CREATE_ERROR_LOG(DML_TABLE_NAME VARCHAR,ERR_LOG_TABLE_NAME VARCHAR,ERR_LOG_TABLE_OWNER VARCHAR,ERR_LOG_TABLE_SPACE VARCHAR,SKIP_UNSUPPORTED BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

