CREATE SCHEMA DBMS_XDB_ADMIN;

CREATE OR REPLACE PROCEDURE DBMS_XDB_ADMIN.CLEARREPOSITORYXMLINDEX()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XDB_ADMIN.CREATENONCEKEY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XDB_ADMIN.CREATEREPOSITORYXMLINDEX()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XDB_ADMIN.DROPREPOSITORYXMLINDEX()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XDB_ADMIN.INSTALLDEFAULTWALLET(TRACE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XDB_ADMIN.REBUILDHIERARCHICALINDEX(RECURSE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XDB_ADMIN.XMLINDEXREMOVEPATH(PATH VARCHAR,RECURSE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

