CREATE SCHEMA DBMS_APPLICATION_INFO;

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.READ_CLIENT_INFO()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$


CREATE OR REPLACE FUNCTION DBMS_APPLICATION_INFO.READ_MODULE() returns object language sql as
$$
    object_construct('module_name',GETVARIABLE('APPLICATION_INFO_MODULENAME'),'action_name',GETVARIABLE('APPLICATION_INFO_ACTION_NAME'))
$$


CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_ACTION(ACTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE SQL
execute as caller
as
$$
begin
    select setvariable('APPLICATION_INFO_ACTION_NAME',:action);
    let newquerytag varchar := CONCAT(NVL(GETVARIABLE('APPLICATION_INFO_MODULENAME'),''),';',NVL(GETVARIABLE('APPLICATION_INFO_ACTION_NAME'),''));
    execute immediate 'alter session set query_tag = ''' || :newquerytag || '''';
    return newquerytag;
end;
$$;

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_ACTION(ACTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_CLIENT_INFO(CLIENT_INFO VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_MODULE(MODULE_NAME VARCHAR,ACTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_MODULE(MODULE_NAME VARCHAR,ACTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE sql
execute as caller
as
$$
begin
    select setvariable('APPLICATION_INFO_MODULENAME',:module);
    let newquerytag varchar := CONCAT(NVL(GETVARIABLE('APPLICATION_INFO_MODULENAME'),''),';',NVL(GETVARIABLE('APPLICATION_INFO_ACTION_NAME'),''));
    execute immediate 'alter session set query_tag = ''' || :newquerytag || '''';
    return newquerytag;
end;
$$;

CREATE OR REPLACE PROCEDURE DBMS_APPLICATION_INFO.SET_SESSION_LONGOPS(OP_NAME VARCHAR,TARGET NUMBER,CONTEXT NUMBER,SOFAR NUMBER,TOTALWORK NUMBER,TARGET_DESC VARCHAR,UNITS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

