CREATE SCHEMA DBMS_STREAMS_TABLESPACE_ADM;

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.ATTACH_SIMPLE_TABLESPACE(DIRECTORY_OBJECT VARCHAR,TABLESPACE_FILE_NAME VARCHAR,CONVERTED_FILE_NAME VARCHAR,DATAFILE_PLATFORM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.ATTACH_TABLESPACES(DUMP_FILE VARIANT,DATAFILES_PLATFORM VARCHAR,LOG_FILE VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.ATTACH_TABLESPACES(FILE_GROUP_NAME VARCHAR,VERSION_NAME VARCHAR,DATAFILES_DIRECTORY_OBJECT VARCHAR,LOG_FILE_DIRECTORY_OBJECT VARCHAR,REPOSITORY_DB_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.CLONE_SIMPLE_TABLESPACE(TABLESPACE_NAME VARCHAR,DIRECTORY_OBJECT VARCHAR,DESTINATION_PLATFORM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.CLONE_TABLESPACES(DUMP_FILE VARIANT,DESTINATION_PLATFORM VARCHAR,LOG_FILE VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.CLONE_TABLESPACES(TABLESPACE_DIRECTORY_OBJECT VARCHAR,LOG_FILE_DIRECTORY_OBJECT VARCHAR,FILE_GROUP_NAME VARCHAR,VERSION_NAME VARCHAR,REPOSITORY_DB_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.DETACH_SIMPLE_TABLESPACE(TABLESPACE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.DETACH_TABLESPACES(DUMP_FILE VARIANT,LOG_FILE VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.DETACH_TABLESPACES(EXPORT_DIRECTORY_OBJECT VARCHAR,LOG_FILE_DIRECTORY_OBJECT VARCHAR,FILE_GROUP_NAME VARCHAR,VERSION_NAME VARCHAR,REPOSITORY_DB_LINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.PULL_SIMPLE_TABLESPACE(TABLESPACE_NAME VARCHAR,DATABASE_LINK VARCHAR,DIRECTORY_OBJECT VARCHAR,CONVERSION_EXTENSION VARCHAR,CONVERT_DIRECTORY_OBJECT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_TABLESPACE_ADM.PULL_TABLESPACES(DATABASE_LINK VARCHAR,LOG_FILE VARIANT,CONVERSION_EXTENSION VARCHAR,CONVERT_DIRECTORY_OBJECT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

