CREATE SCHEMA DBMS_STREAMS_AUTH;

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_AUTH.GRANT_ADMIN_PRIVILEGE(GRANTEE VARCHAR,GRANT_PRIVILEGES BOOLEAN,FILE_NAME VARCHAR,DIRECTORY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_AUTH.GRANT_REMOTE_ADMIN_ACCESS(GRANTEE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_AUTH.REVOKE_ADMIN_PRIVILEGE(GRANTEE VARCHAR,REVOKE_PRIVILEGES BOOLEAN,FILE_NAME VARCHAR,DIRECTORY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STREAMS_AUTH.REVOKE_REMOTE_ADMIN_ACCESS(GRANTEE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

