CREATE SCHEMA DBMS_STAT_FUNCS;

CREATE OR REPLACE PROCEDURE DBMS_STAT_FUNCS.EXPONENTIAL_DIST_FIT(OWNERNAME VARCHAR,TABLENAME VARCHAR,COLUMNNAME VARCHAR,TEST_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STAT_FUNCS.NORMAL_DIST_FIT(OWNERNAME VARCHAR,TABLENAME VARCHAR,COLUMNNAME VARCHAR,TEST_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STAT_FUNCS.POISSON_DIST_FIT(OWNERNAME VARCHAR,TABLENAME VARCHAR,COLUMNNAME VARCHAR,TEST_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STAT_FUNCS.SUMMARY(P_OWNERNAME VARCHAR,P_TABLENAME VARCHAR,P_COLUMNNAME VARCHAR,P_SIGMA_VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STAT_FUNCS.UNIFORM_DIST_FIT(OWNERNAME VARCHAR,TABLENAME VARCHAR,COLUMNNAME VARCHAR,VAR_TYPE VARCHAR,TEST_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STAT_FUNCS.WEIBULL_DIST_FIT(OWNERNAME VARCHAR,TABLENAME VARCHAR,COLUMNNAME VARCHAR,TEST_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

