CREATE SCHEMA DBMS_COMPARISON;

CREATE OR REPLACE FUNCTION DBMS_COMPARISON.COMPARE(COMPARISON_NAME VARCHAR,MIN_VALUE VARCHAR,MAX_VALUE VARCHAR,PERFORM_ROW_DIF BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_COMPARISON.CONVERGE(COMPARISON_NAME VARCHAR,SCAN_ID NUMBER,CONVERGE_OPTIONS VARCHAR,PERFORM_COMMIT BOOLEAN,LOCAL_CONVERGE_TAG RAW,REMOTE_CONVERGE_TAG RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_COMPARISON.CREATE_COMPARISON(COMPARISON_NAME VARCHAR,SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR,DBLINK_NAME VARCHAR,INDEX_SCHEMA_NAME VARCHAR,INDEX_NAME VARCHAR,REMOTE_SCHEMA_NAME VARCHAR,REMOTE_OBJECT_NAME VARCHAR,COMPARISON_MODE VARCHAR,COLUMN_LIST VARCHAR,SCAN_MODE VARCHAR,SCAN_PERCENT NUMBER,NULL_VALUE VARCHAR,LOCAL_CONVERGE_TAG RAW,REMOTE_CONVERGE_TAG RAW,MAX_NUM_BUCKETS NUMBER,MIN_ROWS_IN_BUCKET NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_COMPARISON.DROP_COMPARISON(COMPARISON_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_COMPARISON.PURGE_COMPARISON(COMPARISON_NAME VARCHAR,SCAN_ID NUMBER,PURGE_TIME TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_COMPARISON.RECHECK(COMPARISON_NAME VARCHAR,SCAN_ID NUMBER,PERFORM_ROW_DIF BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

