CREATE SCHEMA DBMS_CDC_PUBLISH;

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.ALTER_AUTOLOG_CHANGE_SOURCE(CHANGE_SOURCE_NAME VARCHAR,DESCRIPTION VARCHAR,REMOVE_DESCRIPTION CHAR,FIRST_SCN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.ALTER_CHANGE_SET(CHANGE_SET_NAME VARCHAR,DESCRIPTION VARCHAR,REMOVE_DESCRIPTION CHAR,ENABLE_CAPTURE CHAR,RECOVER_AFTER_ERROR CHAR,REMOVE_DDL CHAR,STOP_ON_DDL CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.ALTER_CHANGE_TABLE(OWNER VARCHAR,CHANGE_TABLE_NAME VARCHAR,OPERATION VARCHAR,COLUMN_LIST VARCHAR,RS_ID CHAR,ROW_ID CHAR,USER_ID CHAR,TIMESTAMP CHAR,OBJECT_ID CHAR,SOURCE_COLMAP CHAR,TARGET_COLMAP CHAR,DDL_MARKERS CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.ALTER_HOTLOG_CHANGE_SOURCE(CHANGE_SOURCE_NAME VARCHAR,DESCRIPTION VARCHAR,REMOVE_DESCRIPTION CHAR,ENABLE_SOURCE CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.CREATE_AUTOLOG_CHANGE_SOURCE(CHANGE_SOURCE_NAME VARCHAR,DESCRIPTION VARCHAR,SOURCE_DATABASE VARCHAR,FIRST_SCN NUMBER,ONLINE_LOG CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.CREATE_CHANGE_SET(CHANGE_SET_NAME VARCHAR,DESCRIPTION VARCHAR,CHANGE_SOURCE_NAME VARCHAR,STOP_ON_DDL CHAR,BEGIN_DATE DATE,END_DATE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.CREATE_CHANGE_TABLE(OWNER VARCHAR,CHANGE_TABLE_NAME VARCHAR,CHANGE_SET_NAME VARCHAR,SOURCE_SCHEMA VARCHAR,SOURCE_TABLE VARCHAR,COLUMN_TYPE_LIST VARCHAR,CAPTURE_VALUES VARCHAR,RS_ID CHAR,ROW_ID CHAR,USER_ID CHAR,TIMESTAMP CHAR,OBJECT_ID CHAR,SOURCE_COLMAP CHAR,TARGET_COLMAP CHAR,OPTIONS_STRING VARCHAR,DDL_MARKERS CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.CREATE_HOTLOG_CHANGE_SOURCE(CHANGE_SOURCE_NAME VARCHAR,DESCRIPTION VARCHAR,SOURCE_DATABASE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.DROP_CHANGE_SET(CHANGE_SET_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.DROP_CHANGE_SOURCE(CHANGE_SOURCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.DROP_CHANGE_TABLE(OWNER VARCHAR,CHANGE_TABLE_NAME VARCHAR,FORCE_FLAG CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.DROP_SUBSCRIBER_VIEW(SUBSCRIPTION_HANDLE NUMBER,SOURCE_SCHEMA VARCHAR,SOURCE_TABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.DROP_SUBSCRIPTION(SUBSCRIPTION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.DROP_SUBSCRIPTION(SUBSCRIPTION_HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_CDC_PUBLISH.GET_DDLOPER(DDLOPER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.PURGE(FORCE CHAR,PURGE_DATE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_CDC_PUBLISH.PURGE_CHANGE_TABLE(OWNER VARCHAR,CHANGE_TABLE_NAME VARCHAR,FORCE CHAR,PURGE_DATE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

