CREATE SCHEMA DBMS_JOB;

CREATE OR REPLACE FUNCTION DBMS_JOB.BACKGROUND_PROCESS(BROKEN BOOLEAN,NEXT_DATE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_JOB.CHANGE(JOB NUMBER,WHAT VARCHAR,NEXT_DATE DATE,INTERVAL VARCHAR,INSTANCE NUMBER,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_JOB.INSTANCE(JOB NUMBER,INSTANCE NUMBER,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_JOB.INTERVAL(JOB NUMBER,INTERVAL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_JOB.ISUBMIT(JOB NUMBER,WHAT VARCHAR,NEXT_DATE DATE,INTERVAL VARCHAR,NO_PARSE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_JOB.IS_JOBQ(NEXT_DATE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_JOB.REMOVE(JOB NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_JOB.RUN(JOB NUMBER,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_JOB.SUBMIT(WHAT VARCHAR,NEXT_DATE DATE,INTERVAL VARCHAR,NO_PARSE BOOLEAN,INSTANCE NUMBER,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_JOB.USER_EXPORT(JOB NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_JOB.USER_EXPORT(JOB NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_JOB.WHAT(JOB NUMBER,WHAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

