CREATE SCHEMA DBMS_SQL;

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_ARRAY(C NUMBER(38),NAME VARCHAR,INDEX1 NUMBER(38),INDEX2 NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE VARCHAR,OUT_VALUE_SIZE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE TIME)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE BINARY_FLOAT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE BINARY_DOUBLE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE <ADT_1>)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE <TABLE_1>)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE <VARRAY_1>)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE(C NUMBER(38),NAME VARCHAR,VALUE <OPAQUE_1>)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE_CHAR(C NUMBER(38),NAME VARCHAR,VALUE CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE_CHAR(C NUMBER(38),NAME VARCHAR,VALUE CHAR,OUT_VALUE_SIZE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE_RAW(C NUMBER(38),NAME VARCHAR,VALUE RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE_RAW(C NUMBER(38),NAME VARCHAR,VALUE RAW,OUT_VALUE_SIZE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.BIND_VARIABLE_ROWID(C NUMBER(38),NAME VARCHAR,VALUE ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.CLOSE_CURSOR()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE_CHAR(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE_CHAR(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE_LONG(C NUMBER(38),POSITION NUMBER(38),LENGTH NUMBER(38),OFFSET NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE_RAW(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE_RAW(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE_ROWID(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.COLUMN_VALUE_ROWID(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_ARRAY(C NUMBER(38),POSITION NUMBER(38),CNT NUMBER(38),LOWER_BOUND NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN VARCHAR,COLUMN_SIZE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN TIME)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN BINARY_FLOAT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER(38),COLUMN BINARY_DOUBLE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER,COLUMN <ADT_1>)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER,COLUMN <TABLE_1>)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER,COLUMN <VARRAY_1>)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN(C NUMBER(38),POSITION NUMBER,COLUMN <OPAQUE_1>)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN_CHAR(C NUMBER(38),POSITION NUMBER(38),COLUMN CHAR,COLUMN_SIZE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN_LONG(C NUMBER(38),POSITION NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN_RAW(C NUMBER(38),POSITION NUMBER(38),COLUMN RAW,COLUMN_SIZE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DEFINE_COLUMN_ROWID(C NUMBER(38),POSITION NUMBER(38),COLUMN ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DESCRIBE_COLUMNS(C NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DESCRIBE_COLUMNS2(C NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.DESCRIBE_COLUMNS3(C NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQL.EXECUTE(C NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.EXECUTE_AND_FETCH(C NUMBER(38),EXACT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.FETCH_ROWS(C NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQL.GET_NEXT_RESULT(C NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.GET_NEXT_RESULT(C NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQL.IS_OPEN(C NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.LAST_ERROR_POSITION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.LAST_ROW_COUNT()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.LAST_ROW_ID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.LAST_SQL_FUNCTION_CODE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.OPEN_CURSOR()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.OPEN_CURSOR(TREAT_AS_CLIENT_FOR_RESULTS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.OPEN_CURSOR(SECURITY_LEVEL NUMBER(38),TREAT_AS_CLIENT_FOR_RESULTS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT VARCHAR,LANGUAGE_FLAG NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT CLOB,LANGUAGE_FLAG NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT VARCHAR,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT VARCHAR,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT CLOB,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT CLOB,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT VARCHAR,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN,SCHEMA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT CLOB,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN,SCHEMA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN,SCHEMA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN,SCHEMA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT VARCHAR,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN,SCHEMA VARCHAR,CONTAINER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),STATEMENT CLOB,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN,SCHEMA VARCHAR,CONTAINER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN,SCHEMA VARCHAR,CONTAINER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.PARSE(C NUMBER(38),LB NUMBER(38),UB NUMBER(38),LFFLG BOOLEAN,LANGUAGE_FLAG NUMBER(38),EDITION VARCHAR,APPLY_CROSSEDITION_TRIGGER VARCHAR,FIRE_APPLY_TRIGGER BOOLEAN,SCHEMA VARCHAR,CONTAINER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.RETURN_RESULT(TO_CLIENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.RETURN_RESULT(TO_CLIENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQL.TO_CURSOR_NUMBER()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQL.TO_REFCURSOR()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE_CHAR(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE_RAW(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQL.VARIABLE_VALUE_ROWID(C NUMBER(38),NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

