CREATE SCHEMA DBMS_SERVICE;

CREATE OR REPLACE PROCEDURE DBMS_SERVICE.CREATE_SERVICE(SERVICE_NAME VARCHAR,NETWORK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SERVICE.CREATE_SERVICE(SERVICE_NAME VARCHAR,NETWORK_NAME VARCHAR,GOAL NUMBER,DTP BOOLEAN,AQ_HA_NOTIFICATIONS BOOLEAN,FAILOVER_METHOD VARCHAR,FAILOVER_TYPE VARCHAR,FAILOVER_RETRIES NUMBER,FAILOVER_DELAY NUMBER,CLB_GOAL NUMBER,EDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SERVICE.DELETE_SERVICE(SERVICE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SERVICE.DISCONNECT_SESSION(SERVICE_NAME VARCHAR,DISCONNECT_OPTION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SERVICE.MODIFY_SERVICE(SERVICE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SERVICE.MODIFY_SERVICE(SERVICE_NAME VARCHAR,GOAL NUMBER,DTP BOOLEAN,AQ_HA_NOTIFICATIONS BOOLEAN,FAILOVER_METHOD VARCHAR,FAILOVER_TYPE VARCHAR,FAILOVER_RETRIES NUMBER,FAILOVER_DELAY NUMBER,CLB_GOAL NUMBER,EDITION VARCHAR,MODIFY_EDITION BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SERVICE.START_SERVICE(SERVICE_NAME VARCHAR,INSTANCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SERVICE.STOP_SERVICE(SERVICE_NAME VARCHAR,INSTANCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

