CREATE SCHEMA DBMS_DEFER_SYS;

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.ADD_DEFAULT_DEST(DBLINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.CLEAR_PROP_STATISTICS(DBLINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.DELETE_DEFAULT_DEST(DBLINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.DELETE_DEF_DESTINATION(DESTINATION VARCHAR,FORCE BOOLEAN,CATCHUP RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.DELETE_ERROR(DEFERRED_TRAN_ID VARCHAR,DESTINATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.DELETE_TRAN(DEFERRED_TRAN_ID VARCHAR,DESTINATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEFER_SYS.DISABLED(DESTINATION VARCHAR,CATCHUP RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_SYS.EXCLUDE_PUSH(TIMEOUT NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.EXECUTE(DESTINATION VARCHAR,STOP_ON_ERROR BOOLEAN,TRANSACTION_COUNT NUMBER,EXECUTION_SECONDS NUMBER,EXECUTE_AS_USER BOOLEAN,DELAY_SECONDS NUMBER,BATCH_SIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.EXECUTE(DESTINATION VARCHAR,STOP_ON_ERROR BOOLEAN,TRANSACTION_COUNT NUMBER,EXECUTION_SECONDS NUMBER,DELAY_SECONDS NUMBER,BATCH_SIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.EXECUTE_ERROR(DEFERRED_TRAN_ID VARCHAR,DESTINATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.EXECUTE_ERROR_AS_USER(DEFERRED_TRAN_ID VARCHAR,DESTINATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.EXECUTE_ERROR_CALL(DEFERRED_TRAN_ID VARCHAR,CALLNO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.EXECUTE_ERROR_CALL_AS_USER(DEFERRED_TRAN_ID VARCHAR,CALLNO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.NULLIFY_ALL_TRANS(CATCHUP RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEFER_SYS.PURGE(PURGE_METHOD NUMBER,ROLLBACK_SEGMENT VARCHAR,STARTUP_SECONDS NUMBER,EXECUTION_SECONDS NUMBER,DELAY_SECONDS NUMBER,TRANSACTION_COUNT NUMBER,WRITE_TRACE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_SYS.PUSH(DESTINATION VARCHAR,PARALLELISM NUMBER,HEAP_SIZE NUMBER,STOP_ON_ERROR BOOLEAN,WRITE_TRACE BOOLEAN,STARTUP_SECONDS NUMBER,EXECUTION_SECONDS NUMBER,DELAY_SECONDS NUMBER,TRANSACTION_COUNT NUMBER,DELIVERY_ORDER_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEFER_SYS.PUSH_WITH_CATCHUP(DESTINATION VARCHAR,PARALLELISM NUMBER,HEAP_SIZE NUMBER,STOP_ON_ERROR BOOLEAN,WRITE_TRACE BOOLEAN,STARTUP_SECONDS NUMBER,EXECUTION_SECONDS NUMBER,DELAY_SECONDS NUMBER,TRANSACTION_COUNT NUMBER,DELIVERY_ORDER_LIMIT NUMBER,CATCHUP RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.REGISTER_PROPAGATOR(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.SCHEDULE_EXECUTION(DBLINK VARCHAR,INTERVAL VARCHAR,NEXT_DATE DATE,RESET BOOLEAN,STOP_ON_ERROR BOOLEAN,TRANSACTION_COUNT NUMBER,EXECUTION_SECONDS NUMBER,EXECUTE_AS_USER BOOLEAN,DELAY_SECONDS NUMBER,BATCH_SIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.SCHEDULE_EXECUTION(DBLINK VARCHAR,INTERVAL VARCHAR,NEXT_DATE DATE,RESET BOOLEAN,STOP_ON_ERROR BOOLEAN,TRANSACTION_COUNT NUMBER,EXECUTION_SECONDS NUMBER,DELAY_SECONDS NUMBER,BATCH_SIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.SCHEDULE_PURGE(INTERVAL VARCHAR,NEXT_DATE DATE,RESET BOOLEAN,PURGE_METHOD NUMBER,ROLLBACK_SEGMENT VARCHAR,STARTUP_SECONDS NUMBER,EXECUTION_SECONDS NUMBER,DELAY_SECONDS NUMBER,TRANSACTION_COUNT NUMBER,WRITE_TRACE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.SCHEDULE_PUSH(DESTINATION VARCHAR,INTERVAL VARCHAR,NEXT_DATE DATE,RESET BOOLEAN,PARALLELISM NUMBER,HEAP_SIZE NUMBER,STOP_ON_ERROR BOOLEAN,WRITE_TRACE BOOLEAN,STARTUP_SECONDS NUMBER,EXECUTION_SECONDS NUMBER,DELAY_SECONDS NUMBER,TRANSACTION_COUNT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.SET_DISABLED(DESTINATION VARCHAR,DISABLED BOOLEAN,CATCHUP RAW,OVERRIDE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.UNREGISTER_PROPAGATOR(USERNAME VARCHAR,TIMEOUT NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.UNSCHEDULE_EXECUTION(DBLINK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEFER_SYS.UNSCHEDULE_PURGE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

