CREATE SCHEMA DBMS_LOGMNR_D;

CREATE OR REPLACE PROCEDURE DBMS_LOGMNR_D.BUILD(DICTIONARY_FILENAME VARCHAR,DICTIONARY_LOCATION VARCHAR,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LOGMNR_D.SET_TABLESPACE(NEW_TABLESPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

