CREATE SCHEMA DBMS_TRANSFORM;

CREATE OR REPLACE PROCEDURE DBMS_TRANSFORM.COMPUTE_TRANSFORMATION(MESSAGE <ADT_1>,TRANSFORMATION_SCHEMA VARCHAR,TRANSFORMATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_TRANSFORM.CREATE_TRANSFORMATION(SCHEMA VARCHAR,NAME VARCHAR,FROM_SCHEMA VARCHAR,FROM_TYPE VARCHAR,TO_SCHEMA VARCHAR,TO_TYPE VARCHAR,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_TRANSFORM.DROP_TRANSFORMATION(SCHEMA VARCHAR,NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_TRANSFORM.MODIFY_TRANSFORMATION(SCHEMA VARCHAR,NAME VARCHAR,ATTRIBUTE_NUMBER NUMBER,TRANSFORMATION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

