CREATE SCHEMA DBMS_SQLDIAG;

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.ACCEPT_SQL_PATCH(TASK_NAME VARCHAR,OBJECT_ID NUMBER,NAME VARCHAR,DESCRIPTION VARCHAR,CATEGORY VARCHAR,TASK_OWNER VARCHAR,REPLACE BOOLEAN,FORCE_MATCH BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.ACCEPT_SQL_PATCH(TASK_NAME VARCHAR,OBJECT_ID NUMBER,NAME VARCHAR,DESCRIPTION VARCHAR,CATEGORY VARCHAR,TASK_OWNER VARCHAR,REPLACE BOOLEAN,FORCE_MATCH BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.ALTER_SQL_PATCH(NAME VARCHAR,ATTRIBUTE_NAME VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.CANCEL_DIAGNOSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.CREATE_DIAGNOSIS_TASK(SQL_TEXT CLOB,BIND_LIST SQL_BINDS,USER_NAME VARCHAR,SCOPE VARCHAR,TIME_LIMIT NUMBER,TASK_NAME VARCHAR,DESCRIPTION VARCHAR,PROBLEM_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.CREATE_DIAGNOSIS_TASK(SQL_ID VARCHAR,PLAN_HASH_VALUE NUMBER,SCOPE VARCHAR,TIME_LIMIT NUMBER,TASK_NAME VARCHAR,DESCRIPTION VARCHAR,PROBLEM_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.CREATE_DIAGNOSIS_TASK(SQLSET_NAME VARCHAR,BASIC_FILTER VARCHAR,OBJECT_FILTER VARCHAR,RANK1 VARCHAR,RANK2 VARCHAR,RANK3 VARCHAR,RESULT_PERCENTAGE NUMBER,RESULT_LIMIT NUMBER,SCOPE VARCHAR,TIME_LIMIT NUMBER,TASK_NAME VARCHAR,DESCRIPTION VARCHAR,PLAN_FILTER VARCHAR,SQLSET_OWNER VARCHAR,PROBLEM_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.CREATE_STGTAB_SQLPATCH(TABLE_NAME VARCHAR,SCHEMA_NAME VARCHAR,TABLESPACE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.DROP_DIAGNOSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.DROP_SQL_PATCH(NAME VARCHAR,IGNORE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.DUMP_TRACE(P_SQL_ID VARCHAR,P_CHILD_NUMBER NUMBER,P_COMPONENT VARCHAR,P_FILE_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.EXECUTE_DIAGNOSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.EXPLAIN_SQL_TESTCASE(SQLTESTCASE CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.EXPORT_SQL_TESTCASE(DIRECTORY VARCHAR,SQL_TEXT CLOB,USER_NAME VARCHAR,BIND_LIST SQL_BINDS,EXPORTENVIRONMENT BOOLEAN,EXPORTMETADATA BOOLEAN,EXPORTDATA BOOLEAN,EXPORTPKGBODY BOOLEAN,SAMPLINGPERCENT NUMBER,CTRLOPTIONS VARCHAR,TIMELIMIT NUMBER,TESTCASE_NAME VARCHAR,PRESERVESCHEMAMAPPING BOOLEAN,VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.EXPORT_SQL_TESTCASE(DIRECTORY VARCHAR,INCIDENT_ID VARCHAR,EXPORTENVIRONMENT BOOLEAN,EXPORTMETADATA BOOLEAN,EXPORTDATA BOOLEAN,EXPORTPKGBODY BOOLEAN,SAMPLINGPERCENT NUMBER,CTRLOPTIONS VARCHAR,TIMELIMIT NUMBER,TESTCASE_NAME VARCHAR,PRESERVESCHEMAMAPPING BOOLEAN,VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.EXPORT_SQL_TESTCASE(DIRECTORY VARCHAR,SQL_ID VARCHAR,PLAN_HASH_VALUE NUMBER,EXPORTENVIRONMENT BOOLEAN,EXPORTMETADATA BOOLEAN,EXPORTDATA BOOLEAN,EXPORTPKGBODY BOOLEAN,SAMPLINGPERCENT NUMBER,CTRLOPTIONS VARCHAR,TIMELIMIT NUMBER,TESTCASE_NAME VARCHAR,PRESERVESCHEMAMAPPING BOOLEAN,VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.EXPORT_SQL_TESTCASE_DIR_BY_INC(INCIDENT_ID NUMBER,DIRECTORY VARCHAR,SAMPLINGPERCENT NUMBER,EXPORTENVIRONMENT BOOLEAN,EXPORTMETADATA BOOLEAN,EXPORTPKGBODY BOOLEAN,PRESERVESCHEMAMAPPING BOOLEAN,VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.EXPORT_SQL_TESTCASE_DIR_BY_TXT(INCIDENT_ID NUMBER,DIRECTORY VARCHAR,SQL_TEXT CLOB,USER_NAME VARCHAR,SAMPLINGPERCENT NUMBER,EXPORTENVIRONMENT BOOLEAN,EXPORTMETADATA BOOLEAN,EXPORTPKGBODY BOOLEAN,PRESERVESCHEMAMAPPING BOOLEAN,VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.GETSQL(INCIDENT_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.GET_FIX_CONTROL(BUG_NUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.IMPORT_SQL_TESTCASE(DIRECTORY VARCHAR,SQLTESTCASE CLOB,IMPORTENVIRONMENT BOOLEAN,IMPORTMETADATA BOOLEAN,IMPORTDATA BOOLEAN,IMPORTPKGBODY BOOLEAN,IMPORTDIAGNOSIS BOOLEAN,IGNORESTORAGE BOOLEAN,CTRLOPTIONS VARCHAR,PRESERVESCHEMAMAPPING BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.IMPORT_SQL_TESTCASE(DIRECTORY VARCHAR,FILENAME VARCHAR,IMPORTENVIRONMENT BOOLEAN,IMPORTMETADATA BOOLEAN,IMPORTDATA BOOLEAN,IMPORTPKGBODY BOOLEAN,IMPORTDIAGNOSIS BOOLEAN,IGNORESTORAGE BOOLEAN,CTRLOPTIONS VARCHAR,PRESERVESCHEMAMAPPING BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.INCIDENTID_2_SQL(INCIDENT_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.INTERRUPT_DIAGNOSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.LOAD_SQLSET_FROM_TCB(DIRECTORY VARCHAR,FILENAME VARCHAR,SQLSET_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.PACK_STGTAB_SQLPATCH(PATCH_NAME VARCHAR,PATCH_CATEGORY VARCHAR,STAGING_TABLE_NAME VARCHAR,STAGING_SCHEMA_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.REPLAY_SQL_TESTCASE(DIRECTORY VARCHAR,SQLTESTCASE CLOB,CTRLOPTIONS VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.REPLAY_SQL_TESTCASE(DIRECTORY VARCHAR,FILENAME VARCHAR,CTRLOPTIONS VARCHAR,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLDIAG.REPORT_DIAGNOSIS_TASK(TASK_NAME VARCHAR,TYPE VARCHAR,LEVEL VARCHAR,SECTION VARCHAR,OBJECT_ID NUMBER,RESULT_LIMIT NUMBER,OWNER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.RESET_DIAGNOSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.RESUME_DIAGNOSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.SET_DIAGNOSIS_TASK_PARAMETER(TASK_NAME VARCHAR,PARAMETER VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.SET_TCB_TRACING(STATUS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLDIAG.UNPACK_STGTAB_SQLPATCH(PATCH_NAME VARCHAR,PATCH_CATEGORY VARCHAR,REPLACE BOOLEAN,STAGING_TABLE_NAME VARCHAR,STAGING_SCHEMA_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

