CREATE SCHEMA DBMS_DATA_MINING;

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.ADD_COST_MATRIX(MODEL_NAME VARCHAR,COST_MATRIX_TABLE_NAME VARCHAR,COST_MATRIX_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.ALTER_REVERSE_EXPRESSION(MODEL_NAME VARCHAR,EXPRESSION CLOB,ATTRIBUTE_NAME VARCHAR,ATTRIBUTE_SUBNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.APPLY(MODEL_NAME VARCHAR,DATA_TABLE_NAME VARCHAR,CASE_ID_COLUMN_NAME VARCHAR,RESULT_TABLE_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.COMPUTE_CONFUSION_MATRIX(APPLY_RESULT_TABLE_NAME VARCHAR,TARGET_TABLE_NAME VARCHAR,CASE_ID_COLUMN_NAME VARCHAR,TARGET_COLUMN_NAME VARCHAR,CONFUSION_MATRIX_TABLE_NAME VARCHAR,SCORE_COLUMN_NAME VARCHAR,SCORE_CRITERION_COLUMN_NAME VARCHAR,COST_MATRIX_TABLE_NAME VARCHAR,APPLY_RESULT_SCHEMA_NAME VARCHAR,TARGET_SCHEMA_NAME VARCHAR,COST_MATRIX_SCHEMA_NAME VARCHAR,SCORE_CRITERION_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.COMPUTE_LIFT(APPLY_RESULT_TABLE_NAME VARCHAR,TARGET_TABLE_NAME VARCHAR,CASE_ID_COLUMN_NAME VARCHAR,TARGET_COLUMN_NAME VARCHAR,LIFT_TABLE_NAME VARCHAR,POSITIVE_TARGET_VALUE VARCHAR,SCORE_COLUMN_NAME VARCHAR,SCORE_CRITERION_COLUMN_NAME VARCHAR,NUM_QUANTILES NUMBER,COST_MATRIX_TABLE_NAME VARCHAR,APPLY_RESULT_SCHEMA_NAME VARCHAR,TARGET_SCHEMA_NAME VARCHAR,COST_MATRIX_SCHEMA_NAME VARCHAR,SCORE_CRITERION_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.COMPUTE_ROC(APPLY_RESULT_TABLE_NAME VARCHAR,TARGET_TABLE_NAME VARCHAR,CASE_ID_COLUMN_NAME VARCHAR,TARGET_COLUMN_NAME VARCHAR,ROC_TABLE_NAME VARCHAR,POSITIVE_TARGET_VALUE VARCHAR,SCORE_COLUMN_NAME VARCHAR,SCORE_CRITERION_COLUMN_NAME VARCHAR,APPLY_RESULT_SCHEMA_NAME VARCHAR,TARGET_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.CREATE_MODEL(MODEL_NAME VARCHAR,MINING_FUNCTION VARCHAR,DATA_TABLE_NAME VARCHAR,CASE_ID_COLUMN_NAME VARCHAR,TARGET_COLUMN_NAME VARCHAR,SETTINGS_TABLE_NAME VARCHAR,DATA_SCHEMA_NAME VARCHAR,SETTINGS_SCHEMA_NAME VARCHAR,XFORM_LIST TRANSFORM_LIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.DROP_MODEL(MODEL_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.EXPORT_MODEL(FILENAME VARCHAR,DIRECTORY VARCHAR,MODEL_FILTER VARCHAR,FILESIZE VARCHAR,OPERATION VARCHAR,REMOTE_LINK VARCHAR,JOBNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_ASSOCIATION_RULES(MODEL_NAME VARCHAR,TOPN NUMBER,RULE_ID NUMBER(38),MIN_CONFIDENCE NUMBER,MIN_SUPPORT NUMBER,MAX_RULE_LENGTH NUMBER(38),MIN_RULE_LENGTH NUMBER(38),SORT_ORDER ORA_MINING_VARCHAR2_NT,ANTECEDENT_ITEMS DM_ITEMS,CONSEQUENT_ITEMS DM_ITEMS,MIN_LIFT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_DEFAULT_SETTINGS(TOPN NUMBER,MAX_ITEMSET_LENGTH NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_COST_MATRIX(MODEL_NAME VARCHAR,MATRIX_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_AI(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_EM(MODEL_NAME VARCHAR,CLUSTER_ID NUMBER,ATTRIBUTE VARCHAR,CENTROID NUMBER,HISTOGRAM NUMBER,RULES NUMBER,ATTRIBUTE_SUBNAME VARCHAR,TOPN_ATTRIBUTES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_EM_COMP(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_EM_PROJ(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_GLM(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_GLOBAL(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_KM(MODEL_NAME VARCHAR,CLUSTER_ID NUMBER,ATTRIBUTE VARCHAR,CENTROID NUMBER,HISTOGRAM NUMBER,RULES NUMBER,ATTRIBUTE_SUBNAME VARCHAR,TOPN_ATTRIBUTES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_NB(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_NMF(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_OC(MODEL_NAME VARCHAR,CLUSTER_ID NUMBER,ATTRIBUTE VARCHAR,CENTROID NUMBER,HISTOGRAM NUMBER,RULES NUMBER,TOPN_ATTRIBUTES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_SVD(MODEL_NAME VARCHAR,MATRIX_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_SVM(MODEL_NAME VARCHAR,REVERSE_COEF NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_DETAILS_XML(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_SETTINGS(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_SIGNATURE(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DATA_MINING.GET_MODEL_TRANSFORMATIONS(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.GET_TRANSFORM_LIST(MODEL_XFORMS DM_TRANSFORMS)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.IMPORT_MODEL(FILENAME VARCHAR,DIRECTORY VARCHAR,MODEL_FILTER VARCHAR,OPERATION VARCHAR,REMOTE_LINK VARCHAR,JOBNAME VARCHAR,SCHEMA_REMAP VARCHAR,TABLESPACE_REMAP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.IMPORT_MODEL(MODEL_NAME VARCHAR,PMMLDOC XMLTYPE,STRICT_CHECK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.RANK_APPLY(APPLY_RESULT_TABLE_NAME VARCHAR,CASE_ID_COLUMN_NAME VARCHAR,SCORE_COLUMN_NAME VARCHAR,SCORE_CRITERION_COLUMN_NAME VARCHAR,RANKED_APPLY_TABLE_NAME VARCHAR,TOP_N NUMBER(38),COST_MATRIX_TABLE_NAME VARCHAR,APPLY_RESULT_SCHEMA_NAME VARCHAR,COST_MATRIX_SCHEMA_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.REMOVE_COST_MATRIX(MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DATA_MINING.RENAME_MODEL(MODEL_NAME VARCHAR,NEW_MODEL_NAME VARCHAR,VERSIONED_MODEL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

