CREATE SCHEMA DBMS_SQLPA;

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.CANCEL_ANALYSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLPA.CREATE_ANALYSIS_TASK(SQL_TEXT CLOB,BIND_LIST SQL_BINDS,PARSING_SCHEMA VARCHAR,TASK_NAME VARCHAR,DESCRIPTION VARCHAR,CON_DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLPA.CREATE_ANALYSIS_TASK(SQL_ID VARCHAR,PLAN_HASH_VALUE NUMBER,TASK_NAME VARCHAR,DESCRIPTION VARCHAR,CON_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLPA.CREATE_ANALYSIS_TASK(BEGIN_SNAP NUMBER,END_SNAP NUMBER,SQL_ID VARCHAR,PLAN_HASH_VALUE NUMBER,TASK_NAME VARCHAR,DESCRIPTION VARCHAR,CON_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SQLPA.CREATE_ANALYSIS_TASK(SQLSET_NAME VARCHAR,BASIC_FILTER VARCHAR,ORDER_BY VARCHAR,TOP_SQL NUMBER,TASK_NAME VARCHAR,DESCRIPTION VARCHAR,SQLSET_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.DROP_ANALYSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLPA.EXECUTE_ANALYSIS_TASK(TASK_NAME VARCHAR,EXECUTION_TYPE VARCHAR,EXECUTION_NAME VARCHAR,EXECUTION_PARAMS ARGLIST,EXECUTION_DESC VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.EXECUTE_ANALYSIS_TASK(TASK_NAME VARCHAR,EXECUTION_TYPE VARCHAR,EXECUTION_NAME VARCHAR,EXECUTION_PARAMS ARGLIST,EXECUTION_DESC VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLPA.GET_SESS_OPTIMIZER_ENV()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.REMOTE_PROCESS_SQL(SQL_TEXT CLOB,PARSING_SCHEMA VARCHAR,BIND_DATA RAW,BIND_LIST SQL_BINDS,ACTION VARCHAR,TIME_LIMIT NUMBER,TRACE_FLAGS NUMBER,ACTION_FLAGS NUMBER,CONTROL_OPTIONS_XML VARCHAR,CON_DBID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SQLPA.REPORT_ANALYSIS_TASK(TASK_NAME VARCHAR,TYPE VARCHAR,LEVEL VARCHAR,SECTION VARCHAR,OBJECT_ID NUMBER,TOP_SQL NUMBER,EXECUTION_NAME VARCHAR,TASK_OWNER VARCHAR,ORDER_BY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.RESET_ANALYSIS_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.RESUME_ANALYSIS_TASK(TASK_NAME VARCHAR,BASIC_FILTER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.SET_ANALYSIS_DEFAULT_PARAMETER(PARAMETER VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.SET_ANALYSIS_DEFAULT_PARAMETER(PARAMETER VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.SET_ANALYSIS_TASK_PARAMETER(TASK_NAME VARCHAR,PARAMETER VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SQLPA.SET_ANALYSIS_TASK_PARAMETER(TASK_NAME VARCHAR,PARAMETER VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

