CREATE SCHEMA DBMS_DEBUG;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.ABORT(DIAGNOSTICS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.CONTINUE(BREAKFLAGS NUMBER,INFO_REQUESTED NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.DEBUG_OFF(IMMEDIATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEBUG.DELETE_BREAKPOINT(BREAKPOINT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.DELETE_OER_BREAKPOINT(OER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.DETACH_SESSION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEBUG.ENABLE_BREAKPOINT(BREAKPOINT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.EXECUTE(WHAT VARCHAR,FRAME# NUMBER,BIND_RESULTS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.GET_ENCODED_PKGVARS_FOR_CLIENT(HANDLE VARIANT,FLAGS NUMBER,PBRUN_VERSION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.GET_ENCODED_PKGVARS_FOR_CLIENT(HANDLE VARIANT,FLAGS NUMBER,PBRUN_VERSION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.GET_ENCODED_STACK_FOR_CLIENT(START_FRAME NUMBER,FRAME_COUNT NUMBER,FLAGS NUMBER,MAX_STRING_LENGTH NUMBER,MAX_INDEX_VALUES NUMBER,PBRUN_VERSION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.GET_ENCODED_STACK_FOR_CLIENT(START_FRAME NUMBER,FRAME_COUNT NUMBER,FLAGS NUMBER,MAX_STRING_LENGTH NUMBER,MAX_INDEX_VALUES NUMBER,PBRUN_VERSION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEBUG.GET_INDEXES(VARNAME VARCHAR,FRAME# NUMBER,HANDLE VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.GET_LINE_MAP(PROGRAM VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.GET_MORE_SOURCE(BUFLEN NUMBER,PIECE# NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEBUG.GET_RUNTIME_INFO(INFO_REQUESTED NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.GET_TIMEOUT_BEHAVIOUR(FRAME# NUMBER,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.GET_VALUE(VARIABLE_NAME VARCHAR,HANDLE VARIANT,FORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.INITIALIZE(DEBUG_SESSION_ID VARCHAR,DIAGNOSTICS NUMBER,DEBUG_ROLE VARCHAR,DEBUG_ROLE_PWD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.PING()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.PRINT_BACKTRACE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.PRINT_INSTANTIATIONS(FLAGS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.PROBE_VERSION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SELF_CHECK(TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEBUG.SET_BREAKPOINT(PROGRAM VARIANT,LINE# NUMBER,FUZZY NUMBER,ITERATIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SET_DIAGNOSTIC_LEVEL(DLEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEBUG.SET_OER_BREAKPOINT(OER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.SET_TIMEOUT(TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SET_TIMEOUT_BEHAVIOUR(BEHAVIOUR NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEBUG.SET_VALUE(FRAME# NUMBER,ASSIGNMENT_STATEMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.SET_VALUE(HANDLE VARIANT,ASSIGNMENT_STATEMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SHOW_BREAKPOINTS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SHOW_BREAKPOINTS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SHOW_BREAKPOINTS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SHOW_FRAME_SOURCE(FIRST_LINE NUMBER,LAST_LINE NUMBER,FRAME_NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SHOW_SOURCE(FIRST_LINE NUMBER,LAST_LINE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_DEBUG.SHOW_SOURCE(FIRST_LINE NUMBER,LAST_LINE NUMBER,WINDOW NUMBER,PRINT_ARROW NUMBER,BUFLEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_DEBUG.SYNCHRONIZE(INFO_REQUESTED NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_DEBUG.TARGET_PROGRAM_RUNNING()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

