CREATE SCHEMA DBMS_XMLSCHEMA;

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.COMPILESCHEMA(SCHEMAURL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_XMLSCHEMA.CONVERTTODATE(STRVAL VARCHAR,XMLTYPENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XMLSCHEMA.CONVERTTOTS(STRVAL VARCHAR,XMLTYPENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XMLSCHEMA.CONVERTTOTSWITHTZ(STRVAL VARCHAR,XMLTYPENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.COPYEVOLVE(SCHEMAURLS XDB$STRING_LIST_T,NEWSCHEMAS XMLSEQUENCETYPE,TRANSFORMS XMLSEQUENCETYPE,PRESERVEOLDDOCS BOOLEAN,MAPTABNAME VARCHAR,GENERATETABLES BOOLEAN,FORCE BOOLEAN,SCHEMAOWNERS XDB$STRING_LIST_T,PARALLELDEGREE NUMBER,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.DELETESCHEMA(SCHEMAURL VARCHAR,DELETE_OPTION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.GENERATEBEAN(SCHEMAURL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_XMLSCHEMA.GENERATESCHEMA(SCHEMANAME VARCHAR,TYPENAME VARCHAR,ELEMENTNAME VARCHAR,RECURSE BOOLEAN,ANNOTATE BOOLEAN,EMBEDCOLL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_XMLSCHEMA.GENERATESCHEMAS(SCHEMANAME VARCHAR,TYPENAME VARCHAR,ELEMENTNAME VARCHAR,SCHEMAURL VARCHAR,ANNOTATE BOOLEAN,EMBEDCOLL BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.INPLACEEVOLVE(SCHEMAURL VARCHAR,DIFFXML XMLTYPE,FLAGS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.PURGESCHEMA(SCHEMA_ID RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.REGISTERSCHEMA(SCHEMAURL VARCHAR,SCHEMADOC VARCHAR,LOCAL BOOLEAN,GENTYPES BOOLEAN,GENBEAN BOOLEAN,GENTABLES BOOLEAN,FORCE BOOLEAN,OWNER VARCHAR,ENABLEHIERARCHY NUMBER,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.REGISTERSCHEMA(SCHEMAURL VARCHAR,SCHEMADOC CLOB,LOCAL BOOLEAN,GENTYPES BOOLEAN,GENBEAN BOOLEAN,GENTABLES BOOLEAN,FORCE BOOLEAN,OWNER VARCHAR,ENABLEHIERARCHY NUMBER,OPTIONS NUMBER,SCHEMAOID RAW,IMPORT_OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.REGISTERSCHEMA(SCHEMAURL VARCHAR,SCHEMADOC BLOB,LOCAL BOOLEAN,GENTYPES BOOLEAN,GENBEAN BOOLEAN,GENTABLES BOOLEAN,FORCE BOOLEAN,OWNER VARCHAR,CSID NUMBER,ENABLEHIERARCHY NUMBER,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.REGISTERSCHEMA(SCHEMAURL VARCHAR,LOCAL BOOLEAN,GENTYPES BOOLEAN,GENBEAN BOOLEAN,GENTABLES BOOLEAN,FORCE BOOLEAN,OWNER VARCHAR,CSID NUMBER,ENABLEHIERARCHY NUMBER,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.REGISTERSCHEMA(SCHEMAURL VARCHAR,SCHEMADOC XMLTYPE,LOCAL BOOLEAN,GENTYPES BOOLEAN,GENBEAN BOOLEAN,GENTABLES BOOLEAN,FORCE BOOLEAN,OWNER VARCHAR,ENABLEHIERARCHY NUMBER,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.REGISTERSCHEMA(SCHEMAURL VARCHAR,SCHEMADOC URITYPE,LOCAL BOOLEAN,GENTYPES BOOLEAN,GENBEAN BOOLEAN,GENTABLES BOOLEAN,FORCE BOOLEAN,OWNER VARCHAR,ENABLEHIERARCHY NUMBER,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_XMLSCHEMA.REGISTERURI(SCHEMAURL VARCHAR,SCHEMADOCURI VARCHAR,LOCAL BOOLEAN,GENTYPES BOOLEAN,GENBEAN BOOLEAN,GENTABLES BOOLEAN,FORCE BOOLEAN,OWNER VARCHAR,ENABLEHIERARCHY NUMBER,OPTIONS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

