CREATE SCHEMA DBMS_HS_PARALLEL;

CREATE OR REPLACE PROCEDURE DBMS_HS_PARALLEL.CREATE_OR_REPLACE_VIEW(REMOTE_TABLE VARCHAR,DATABASE_LINK VARCHAR,ORACLE_VIEW VARCHAR,PARALLEL_DEGREE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_HS_PARALLEL.CREATE_TABLE_TEMPLATE(REMOTE_TABLE VARCHAR,DATABASE_LINK VARCHAR,ORACLE_TABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_HS_PARALLEL.DROP_VIEW(ORACLE_VIEW VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_HS_PARALLEL.LOAD_TABLE(REMOTE_TABLE VARCHAR,DATABASE_LINK VARCHAR,ORACLE_TABLE VARCHAR,TRUNCATE BOOLEAN,PARALLEL_DEGREE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

