CREATE SCHEMA DBMS_SCHEDULER;

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ADD_EVENT_QUEUE_SUBSCRIBER(SUBSCRIBER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ADD_GROUP_MEMBER(GROUP_NAME VARCHAR,MEMBER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ADD_JOB_EMAIL_NOTIFICATION(JOB_NAME VARCHAR,RECIPIENTS VARCHAR,SENDER VARCHAR,SUBJECT VARCHAR,BODY VARCHAR,EVENTS VARCHAR,FILTER_CONDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ADD_WINDOW_GROUP_MEMBER(GROUP_NAME VARCHAR,WINDOW_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ALTER_CHAIN(CHAIN_NAME VARCHAR,STEP_NAME VARCHAR,ATTRIBUTE VARCHAR,VALUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ALTER_CHAIN(CHAIN_NAME VARCHAR,STEP_NAME VARCHAR,ATTRIBUTE VARCHAR,CHAR_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ALTER_RUNNING_CHAIN(JOB_NAME VARCHAR,STEP_NAME VARCHAR,ATTRIBUTE VARCHAR,VALUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ALTER_RUNNING_CHAIN(JOB_NAME VARCHAR,STEP_NAME VARCHAR,ATTRIBUTE VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ANALYZE_CHAIN(CHAIN_NAME VARCHAR,RULES SCHEDULER$_RULE_LIST,STEPS SCHEDULER$_STEP_TYPE_LIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.AUTO_PURGE(DESTINATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.CHECK_SYS_PRIVS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.COPY_JOB(OLD_JOB VARCHAR,NEW_JOB VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_CALENDAR_STRING(FREQUENCY NUMBER,INTERVAL NUMBER,BYSECOND BYLIST,BYMINUTE BYLIST,BYHOUR BYLIST,BYDAY_DAYS BYLIST,BYDAY_OCCURRENCE BYLIST,BYMONTHDAY BYLIST,BYYEARDAY BYLIST,BYWEEKNO BYLIST,BYMONTH BYLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_CHAIN(CHAIN_NAME VARCHAR,RULE_SET_NAME VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_CREDENTIAL(CREDENTIAL_NAME VARCHAR,USERNAME VARCHAR,PASSWORD VARCHAR,DATABASE_ROLE VARCHAR,WINDOWS_DOMAIN VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_DATABASE_DESTINATION(DESTINATION_NAME VARCHAR,AGENT VARCHAR,TNS_NAME VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_EVENT_SCHEDULE(SCHEDULE_NAME VARCHAR,EVENT_CONDITION VARCHAR,QUEUE_SPEC VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_FILE_WATCHER(FILE_WATCHER_NAME VARCHAR,DIRECTORY_PATH VARCHAR,FILE_NAME VARCHAR,CREDENTIAL_NAME VARCHAR,DESTINATION VARCHAR,MIN_FILE_SIZE NUMBER,COMMENTS VARCHAR,ENABLED BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_GROUP(GROUP_NAME VARCHAR,GROUP_TYPE VARCHAR,MEMBER VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOB(JOB_NAME VARCHAR,JOB_TYPE VARCHAR,JOB_ACTION VARCHAR,NUMBER_OF_ARGUMENTS NUMBER,REPEAT_INTERVAL VARCHAR,JOB_CLASS VARCHAR,ENABLED BOOLEAN,AUTO_DROP BOOLEAN,COMMENTS VARCHAR,CREDENTIAL_NAME VARCHAR,DESTINATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOB(JOB_NAME VARCHAR,JOB_TYPE VARCHAR,JOB_ACTION VARCHAR,NUMBER_OF_ARGUMENTS NUMBER,EVENT_CONDITION VARCHAR,QUEUE_SPEC VARCHAR,JOB_CLASS VARCHAR,ENABLED BOOLEAN,AUTO_DROP BOOLEAN,COMMENTS VARCHAR,CREDENTIAL_NAME VARCHAR,DESTINATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOB(JOB_NAME VARCHAR,PROGRAM_NAME VARCHAR,SCHEDULE_NAME VARCHAR,JOB_CLASS VARCHAR,ENABLED BOOLEAN,AUTO_DROP BOOLEAN,COMMENTS VARCHAR,JOB_STYLE VARCHAR,CREDENTIAL_NAME VARCHAR,DESTINATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOB(JOB_NAME VARCHAR,PROGRAM_NAME VARCHAR,REPEAT_INTERVAL VARCHAR,JOB_CLASS VARCHAR,ENABLED BOOLEAN,AUTO_DROP BOOLEAN,COMMENTS VARCHAR,JOB_STYLE VARCHAR,CREDENTIAL_NAME VARCHAR,DESTINATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOB(JOB_NAME VARCHAR,PROGRAM_NAME VARCHAR,EVENT_CONDITION VARCHAR,QUEUE_SPEC VARCHAR,JOB_CLASS VARCHAR,ENABLED BOOLEAN,AUTO_DROP BOOLEAN,COMMENTS VARCHAR,JOB_STYLE VARCHAR,CREDENTIAL_NAME VARCHAR,DESTINATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOB(JOB_NAME VARCHAR,SCHEDULE_NAME VARCHAR,JOB_TYPE VARCHAR,JOB_ACTION VARCHAR,NUMBER_OF_ARGUMENTS NUMBER,JOB_CLASS VARCHAR,ENABLED BOOLEAN,AUTO_DROP BOOLEAN,COMMENTS VARCHAR,CREDENTIAL_NAME VARCHAR,DESTINATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOBS(JOBDEF_ARRAY JOB_DEFINITION_ARRAY,COMMIT_SEMANTICS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOBS(JOB_ARRAY JOB_ARRAY,COMMIT_SEMANTICS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_JOB_CLASS(JOB_CLASS_NAME VARCHAR,RESOURCE_CONSUMER_GROUP VARCHAR,SERVICE VARCHAR,LOGGING_LEVEL NUMBER,LOG_HISTORY NUMBER,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_PROGRAM(PROGRAM_NAME VARCHAR,PROGRAM_TYPE VARCHAR,PROGRAM_ACTION VARCHAR,NUMBER_OF_ARGUMENTS NUMBER,ENABLED BOOLEAN,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_SCHEDULE(SCHEDULE_NAME VARCHAR,REPEAT_INTERVAL VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_WINDOW(WINDOW_NAME VARCHAR,RESOURCE_PLAN VARCHAR,SCHEDULE_NAME VARCHAR,WINDOW_PRIORITY VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_WINDOW(WINDOW_NAME VARCHAR,RESOURCE_PLAN VARCHAR,REPEAT_INTERVAL VARCHAR,WINDOW_PRIORITY VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.CREATE_WINDOW_GROUP(GROUP_NAME VARCHAR,WINDOW_LIST VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DEFINE_ANYDATA_ARGUMENT(PROGRAM_NAME VARCHAR,ARGUMENT_POSITION NUMBER,ARGUMENT_NAME VARCHAR,ARGUMENT_TYPE VARCHAR,DEFAULT_VALUE ANYDATA,OUT_ARGUMENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DEFINE_CHAIN_EVENT_STEP(CHAIN_NAME VARCHAR,STEP_NAME VARCHAR,EVENT_SCHEDULE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DEFINE_CHAIN_EVENT_STEP(CHAIN_NAME VARCHAR,STEP_NAME VARCHAR,EVENT_CONDITION VARCHAR,QUEUE_SPEC VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DEFINE_CHAIN_RULE(CHAIN_NAME VARCHAR,CONDITION VARCHAR,ACTION VARCHAR,RULE_NAME VARCHAR,COMMENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DEFINE_CHAIN_STEP(CHAIN_NAME VARCHAR,STEP_NAME VARCHAR,PROGRAM_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DEFINE_METADATA_ARGUMENT(PROGRAM_NAME VARCHAR,METADATA_ATTRIBUTE VARCHAR,ARGUMENT_POSITION NUMBER,ARGUMENT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DEFINE_PROGRAM_ARGUMENT(PROGRAM_NAME VARCHAR,ARGUMENT_POSITION NUMBER,ARGUMENT_NAME VARCHAR,ARGUMENT_TYPE VARCHAR,DEFAULT_VALUE VARCHAR,OUT_ARGUMENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DEFINE_PROGRAM_ARGUMENT(PROGRAM_NAME VARCHAR,ARGUMENT_POSITION NUMBER,ARGUMENT_NAME VARCHAR,ARGUMENT_TYPE VARCHAR,OUT_ARGUMENT BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DISABLE(NAME VARCHAR,FORCE BOOLEAN,COMMIT_SEMANTICS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DISABLE1_CALENDAR_CHECK()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_CHAIN(CHAIN_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_CHAIN_RULE(CHAIN_NAME VARCHAR,RULE_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_CHAIN_STEP(CHAIN_NAME VARCHAR,STEP_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_CREDENTIAL(CREDENTIAL_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_DATABASE_DESTINATION(DESTINATION_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_FILE_WATCHER(FILE_WATCHER_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_GROUP(GROUP_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_JOB(JOB_NAME VARCHAR,FORCE BOOLEAN,DEFER BOOLEAN,COMMIT_SEMANTICS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_JOB_CLASS(JOB_CLASS_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_PROGRAM(PROGRAM_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_PROGRAM_ARGUMENT(PROGRAM_NAME VARCHAR,ARGUMENT_POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_PROGRAM_ARGUMENT(PROGRAM_NAME VARCHAR,ARGUMENT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_SCHEDULE(SCHEDULE_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_WINDOW(WINDOW_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.DROP_WINDOW_GROUP(GROUP_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.ENABLE(NAME VARCHAR,COMMIT_SEMANTICS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.END_DETACHED_JOB_RUN(JOB_NAME VARCHAR,ERROR_NUMBER NUMBER,ADDITIONAL_INFO VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.EVALUATE_CALENDAR_STRING(CALENDAR_STRING VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.EVALUATE_RUNNING_CHAIN(JOB_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.FILE_WATCH_FILTER(SCH_NAME VARCHAR,OBJ_NAME VARCHAR,OBJ_SUBNAME VARCHAR,FW_MSGID RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GENERATE_EVENT_LIST(STATUSVEC NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GENERATE_JOB_NAME(PREFIX VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GET_AGENT_INFO(AGENT_NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GET_AGENT_VERSION(AGENT_HOST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GET_CHAIN_RULE_ACTION(ACTION_IN RE$NV_LIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GET_CHAIN_RULE_CONDITION(ACTION_IN RE$NV_LIST,CONDITION_IN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GET_DEFAULT_VALUE(ATTRIBUTE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_FILE(SOURCE_FILE VARCHAR,SOURCE_HOST VARCHAR,CREDENTIAL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_FILE(SOURCE_FILE VARCHAR,SOURCE_HOST VARCHAR,CREDENTIAL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_FILE(SOURCE_FILE VARCHAR,SOURCE_HOST VARCHAR,CREDENTIAL_NAME VARCHAR,DESTINATION_FILE_NAME VARCHAR,DESTINATION_DIRECTORY_OBJECT VARCHAR,DESTINATION_PERMISSIONS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GET_JOB_STEP_CF(IEC VARCHAR,ICN VARCHAR,VNAME VARCHAR,IEV RE$NV_LIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.GET_SCHEDULER_ATTRIBUTE(ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GET_SYS_TIME_ZONE_NAME()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.GET_VARCHAR2_VALUE(A BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.IS_SCHEDULER_CREATED_AGENT(SCHEMA_NAME VARCHAR,AGENT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.OPEN_WINDOW(WINDOW_NAME VARCHAR,FORCE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.PURGE_LOG(LOG_HISTORY NUMBER,WHICH_LOG VARCHAR,JOB_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.PUT_FILE(DESTINATION_FILE VARCHAR,DESTINATION_HOST VARCHAR,CREDENTIAL_NAME VARCHAR,FILE_CONTENTS CLOB,DESTINATION_PERMISSIONS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.PUT_FILE(DESTINATION_FILE VARCHAR,DESTINATION_HOST VARCHAR,CREDENTIAL_NAME VARCHAR,FILE_CONTENTS BLOB,DESTINATION_PERMISSIONS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.PUT_FILE(DESTINATION_FILE VARCHAR,DESTINATION_HOST VARCHAR,CREDENTIAL_NAME VARCHAR,SOURCE_FILE_NAME VARCHAR,SOURCE_DIRECTORY_OBJECT VARCHAR,DESTINATION_PERMISSIONS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.REMOVE_EVENT_QUEUE_SUBSCRIBER(SUBSCRIBER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.REMOVE_GROUP_MEMBER(GROUP_NAME VARCHAR,MEMBER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.REMOVE_JOB_EMAIL_NOTIFICATION(JOB_NAME VARCHAR,RECIPIENTS VARCHAR,EVENTS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.REMOVE_WINDOW_GROUP_MEMBER(GROUP_NAME VARCHAR,WINDOW_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.RESET_JOB_ARGUMENT_VALUE(JOB_NAME VARCHAR,ARGUMENT_POSITION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.RESET_JOB_ARGUMENT_VALUE(JOB_NAME VARCHAR,ARGUMENT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.RESOLVE_CALENDAR_STRING(CALENDAR_STRING VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.RESOLVE_CALENDAR_STRING(CALENDAR_STRING VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.RESOLVE_NAME(FULL_NAME VARCHAR,DEFAULT_OWNER VARCHAR,RETURN_PART NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.RUN_CHAIN(CHAIN_NAME VARCHAR,START_STEPS VARCHAR,JOB_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.RUN_CHAIN(CHAIN_NAME VARCHAR,STEP_STATE_LIST SCHEDULER$_STEP_TYPE_LIST,JOB_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.RUN_JOB(JOB_NAME VARCHAR,USE_CURRENT_SESSION BOOLEAN,EVENT_MESSAGE ANYDATA)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_AGENT_REGISTRATION_PASS(REGISTRATION_PASSWORD VARCHAR,MAX_USES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR,VALUE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR,VALUE VARCHAR,VALUE2 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR,VALUE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR,VALUE TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_ATTRIBUTE(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_ATTRIBUTE_NULL(NAME VARCHAR,ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_JOB_ANYDATA_VALUE(JOB_NAME VARCHAR,ARGUMENT_POSITION NUMBER,ARGUMENT_VALUE ANYDATA)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_JOB_ANYDATA_VALUE(JOB_NAME VARCHAR,ARGUMENT_NAME VARCHAR,ARGUMENT_VALUE ANYDATA)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE(JOB_NAME VARCHAR,ARGUMENT_POSITION NUMBER,ARGUMENT_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE(JOB_NAME VARCHAR,ARGUMENT_NAME VARCHAR,ARGUMENT_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_JOB_ATTRIBUTES(JOBATTR_ARRAY JOBATTR_ARRAY,COMMIT_SEMANTICS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SET_SCHEDULER_ATTRIBUTE(ATTRIBUTE VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SHOW_ERRORS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_SCHEDULER.STIME(FOLLOW_DEFAULT_TIMEZONE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.STOP_JOB(JOB_NAME VARCHAR,FORCE BOOLEAN,COMMIT_SEMANTICS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_SCHEDULER.SUBMIT_REMOTE_EXTERNAL_JOB(JOB_NAME VARCHAR,JOB_SUBNAME VARCHAR,JOB_OWNER VARCHAR,COMMAND VARCHAR,ARGUMENTS ODCIVARCHAR2LIST,CREDENTIAL_NAME VARCHAR,CREDENTIAL_OWNER VARCHAR,DESTINATION VARCHAR,DESTINATION_OWNER VARCHAR,DESTINATION_NAME VARCHAR,JOB_DEST_ID VARCHAR,JOB_ACTION VARCHAR,CHAINID VARCHAR,REQUEST_ID NUMBER,LOG_ID NUMBER,LOGGING_LEVEL NUMBER,STORE_OUTPUT NUMBER,CONNECT_CREDENTIAL_NAME VARCHAR,CONNECT_CREDENTIAL_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

