CREATE SCHEMA DBMS_ADVISOR;

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.ADD_SQLWKLD_REF(TASK_NAME VARCHAR,WORKLOAD_NAME VARCHAR,IS_STS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.ADD_SQLWKLD_STATEMENT(WORKLOAD_NAME VARCHAR,MODULE VARCHAR,ACTION VARCHAR,CPU_TIME NUMBER,ELAPSED_TIME NUMBER,DISK_READS NUMBER,BUFFER_GETS NUMBER,ROWS_PROCESSED NUMBER,OPTIMIZER_COST NUMBER,EXECUTIONS NUMBER,PRIORITY NUMBER,LAST_EXECUTION_DATE DATE,STAT_PERIOD NUMBER,USERNAME VARCHAR,SQL_TEXT CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.ADD_STS_REF(TASK_NAME VARCHAR,STS_OWNER VARCHAR,WORKLOAD_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CANCEL_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CHECK_PRIVS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.COPY_SQLWKLD_TO_STS(WORKLOAD_NAME VARCHAR,STS_NAME VARCHAR,IMPORT_MODE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CREATE_FILE(BUFFER CLOB,LOCATION VARCHAR,FILENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CREATE_OBJECT(TASK_NAME VARCHAR,OBJECT_TYPE VARCHAR,ATTR1 VARCHAR,ATTR2 VARCHAR,ATTR3 VARCHAR,ATTR4 CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CREATE_OBJECT(TASK_NAME VARCHAR,OBJECT_TYPE VARCHAR,ATTR1 VARCHAR,ATTR2 VARCHAR,ATTR3 VARCHAR,ATTR4 CLOB,ATTR5 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CREATE_SQLWKLD(DESCRIPTION VARCHAR,TEMPLATE VARCHAR,IS_TEMPLATE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CREATE_TASK(ADVISOR_NAME VARCHAR,TASK_DESC VARCHAR,TEMPLATE VARCHAR,IS_TEMPLATE VARCHAR,HOW_CREATED VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CREATE_TASK(ADVISOR_NAME VARCHAR,TASK_NAME VARCHAR,TASK_DESC VARCHAR,TEMPLATE VARCHAR,IS_TEMPLATE VARCHAR,HOW_CREATED VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.CREATE_TASK(PARENT_TASK_NAME VARCHAR,REC_ID NUMBER,TASK_DESC VARCHAR,TEMPLATE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.DELETE_DIRECTIVE(DIRECTIVE_ID NUMBER,INSTANCE_NAME VARCHAR,TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.DELETE_SQLWKLD(WORKLOAD_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.DELETE_SQLWKLD_REF(TASK_NAME VARCHAR,WORKLOAD_NAME VARCHAR,IS_STS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.DELETE_SQLWKLD_STATEMENT(WORKLOAD_NAME VARCHAR,SQL_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.DELETE_SQLWKLD_STATEMENT(WORKLOAD_NAME VARCHAR,SEARCH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.DELETE_STS_REF(TASK_NAME VARCHAR,STS_OWNER VARCHAR,WORKLOAD_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.DELETE_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_ADVISOR.EVALUATE_DIRECTIVE(DIRECTIVE_ID NUMBER,INSTANCE_NAME VARCHAR,TASK_NAME VARCHAR,P1 CLOB,P2 CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.EXECUTE_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_ADVISOR.EXECUTE_TASK(TASK_NAME VARCHAR,EXECUTION_TYPE VARCHAR,EXECUTION_NAME VARCHAR,EXECUTION_DESC VARCHAR,EXECUTION_PARAMS ARGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ADVISOR.FORMAT_MESSAGE(MSG_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ADVISOR.FORMAT_MESSAGE_GROUP(GROUP_ID NUMBER,MSG_TYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.GET_ACCESS_ADVISOR_DEFAULTS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.GET_REC_ATTRIBUTES(TASK_NAME VARCHAR,REC_ID NUMBER,ACTION_ID NUMBER,ATTRIBUTE_NAME VARCHAR,OWNER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_ADVISOR.GET_TASK_REPORT(TASK_NAME VARCHAR,TYPE VARCHAR,LEVEL VARCHAR,SECTION VARCHAR,OWNER_NAME VARCHAR,EXECUTION_NAME VARCHAR,OBJECT_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ADVISOR.GET_TASK_SCRIPT(TASK_NAME VARCHAR,TYPE VARCHAR,REC_ID NUMBER,ACT_ID NUMBER,OWNER_NAME VARCHAR,EXECUTION_NAME VARCHAR,OBJECT_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.IMPLEMENT_TASK(TASK_NAME VARCHAR,REC_ID NUMBER,EXIT_ON_ERROR BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.IMPORT_SQLWKLD_SCHEMA(WORKLOAD_NAME VARCHAR,IMPORT_MODE VARCHAR,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.IMPORT_SQLWKLD_SQLCACHE(WORKLOAD_NAME VARCHAR,IMPORT_MODE VARCHAR,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.IMPORT_SQLWKLD_STS(WORKLOAD_NAME VARCHAR,STS_OWNER VARCHAR,STS_NAME VARCHAR,IMPORT_MODE VARCHAR,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.IMPORT_SQLWKLD_STS(WORKLOAD_NAME VARCHAR,STS_NAME VARCHAR,IMPORT_MODE VARCHAR,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.IMPORT_SQLWKLD_SUMADV(WORKLOAD_NAME VARCHAR,IMPORT_MODE VARCHAR,PRIORITY NUMBER,SUMADV_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.IMPORT_SQLWKLD_USER(WORKLOAD_NAME VARCHAR,IMPORT_MODE VARCHAR,OWNER_NAME VARCHAR,TABLE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.INSERT_DIRECTIVE(DIRECTIVE_ID NUMBER,INSTANCE_NAME VARCHAR,TASK_NAME VARCHAR,DOCUMENT CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.INTERRUPT_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.MARK_RECOMMENDATION(TASK_NAME VARCHAR,ID NUMBER,ACTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.QUICK_TUNE(ADVISOR_NAME VARCHAR,TASK_NAME VARCHAR,ATTR1 CLOB,ATTR2 VARCHAR,ATTR3 NUMBER,TEMPLATE VARCHAR,IMPLEMENT BOOLEAN,DESCRIPTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.RESET_SQLWKLD(WORKLOAD_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.RESET_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.RESUME_TASK(TASK_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SETUP_REPOSITORY()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SET_DEFAULT_SQLWKLD_PARAMETER(PARAMETER VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SET_DEFAULT_SQLWKLD_PARAMETER(PARAMETER VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SET_DEFAULT_TASK_PARAMETER(ADVISOR_NAME VARCHAR,PARAMETER VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SET_DEFAULT_TASK_PARAMETER(ADVISOR_NAME VARCHAR,PARAMETER VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SET_SQLWKLD_PARAMETER(WORKLOAD_NAME VARCHAR,PARAMETER VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SET_SQLWKLD_PARAMETER(WORKLOAD_NAME VARCHAR,PARAMETER VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SET_TASK_PARAMETER(TASK_NAME VARCHAR,PARAMETER VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.SET_TASK_PARAMETER(TASK_NAME VARCHAR,PARAMETER VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.TUNE_MVIEW(MV_CREATE_STMT CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.UPDATE_DIRECTIVE(DIRECTIVE_ID NUMBER,INSTANCE_NAME VARCHAR,TASK_NAME VARCHAR,DOCUMENT CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.UPDATE_OBJECT(TASK_NAME VARCHAR,OBJECT_ID NUMBER,ATTR1 VARCHAR,ATTR2 VARCHAR,ATTR3 VARCHAR,ATTR4 CLOB,ATTR5 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.UPDATE_REC_ATTRIBUTES(TASK_NAME VARCHAR,REC_ID NUMBER,ACTION_ID NUMBER,ATTRIBUTE_NAME VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.UPDATE_SQLWKLD_ATTRIBUTES(WORKLOAD_NAME VARCHAR,NEW_NAME VARCHAR,DESCRIPTION VARCHAR,READ_ONLY VARCHAR,IS_TEMPLATE VARCHAR,HOW_CREATED VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.UPDATE_SQLWKLD_STATEMENT(WORKLOAD_NAME VARCHAR,SQL_ID NUMBER,APPLICATION VARCHAR,ACTION VARCHAR,PRIORITY NUMBER,USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.UPDATE_SQLWKLD_STATEMENT(WORKLOAD_NAME VARCHAR,SEARCH VARCHAR,APPLICATION VARCHAR,ACTION VARCHAR,PRIORITY NUMBER,USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_ADVISOR.UPDATE_TASK_ATTRIBUTES(TASK_NAME VARCHAR,NEW_NAME VARCHAR,DESCRIPTION VARCHAR,READ_ONLY VARCHAR,IS_TEMPLATE VARCHAR,HOW_CREATED VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

