CREATE SCHEMA DBMS_REPCAT;

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ABORT_FLAVOR_DEFINITION(GNAME VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_COLUMNS_TO_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,SNAME VARCHAR,ONAME VARCHAR,CNAME_LIST VARCHAR,DEFER_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_COLUMNS_TO_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,SNAME VARCHAR,ONAME VARCHAR,DEFER_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_COLUMN_GROUP_TO_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,DEFER_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_DELETE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,SEQUENCE_NO NUMBER,FUNCTION_NAME VARCHAR,COMMENT VARCHAR,METHOD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_DELETE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,SEQUENCE_NO NUMBER,PARAMETER_COLUMN_NAME VARCHAR,FUNCTION_NAME VARCHAR,COMMENT VARCHAR,METHOD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_GROUPED_COLUMN(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,LIST_OF_COLUMN_NAMES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_GROUPED_COLUMN(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_MASTER_DATABASE(GNAME VARCHAR,MASTER VARCHAR,USE_EXISTING_OBJECTS BOOLEAN,COPY_ROWS BOOLEAN,COMMENT VARCHAR,PROPAGATION_MODE VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_NEW_MASTERS(EXPORT_REQUIRED BOOLEAN,BREAK_TRANS_TO_MASTERDEF BOOLEAN,BREAK_TRANS_TO_NEW_MASTERS BOOLEAN,PERCENTAGE_FOR_CATCHUP_MDEF NUMBER,CYCLE_SECONDS_MDEF NUMBER,PERCENTAGE_FOR_CATCHUP_NEW NUMBER,CYCLE_SECONDS_NEW NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_NEW_MASTERS(EXPORT_REQUIRED BOOLEAN,AVAILABLE_MASTER_LIST VARCHAR,BREAK_TRANS_TO_MASTERDEF BOOLEAN,BREAK_TRANS_TO_NEW_MASTERS BOOLEAN,PERCENTAGE_FOR_CATCHUP_MDEF NUMBER,CYCLE_SECONDS_MDEF NUMBER,PERCENTAGE_FOR_CATCHUP_NEW NUMBER,CYCLE_SECONDS_NEW NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_OBJECT_TO_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,DEFER_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_PRIORITY_CHAR(GNAME VARCHAR,PGROUP VARCHAR,VALUE CHAR,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_PRIORITY_DATE(GNAME VARCHAR,PGROUP VARCHAR,VALUE DATE,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_PRIORITY_NCHAR(GNAME VARCHAR,PGROUP VARCHAR,VALUE NCHAR,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_PRIORITY_NUMBER(GNAME VARCHAR,PGROUP VARCHAR,VALUE NUMBER,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_PRIORITY_NVARCHAR2(GNAME VARCHAR,PGROUP VARCHAR,VALUE NVARCHAR2,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_PRIORITY_RAW(GNAME VARCHAR,PGROUP VARCHAR,VALUE RAW,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_PRIORITY_VARCHAR2(GNAME VARCHAR,PGROUP VARCHAR,VALUE VARCHAR,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_SITE_PRIORITY_SITE(GNAME VARCHAR,NAME VARCHAR,SITE VARCHAR,PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_UNIQUE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,CONSTRAINT_NAME VARCHAR,SEQUENCE_NO NUMBER,METHOD VARCHAR,FUNCTION_NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_UNIQUE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,CONSTRAINT_NAME VARCHAR,SEQUENCE_NO NUMBER,METHOD VARCHAR,FUNCTION_NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_UNIQUE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,CONSTRAINT_NAME VARCHAR,SEQUENCE_NO NUMBER,METHOD VARCHAR,PARAMETER_COLUMN_NAME VARCHAR,FUNCTION_NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_UPDATE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,SEQUENCE_NO NUMBER,METHOD VARCHAR,PRIORITY_GROUP VARCHAR,FUNCTION_NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_UPDATE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,SEQUENCE_NO NUMBER,METHOD VARCHAR,PRIORITY_GROUP VARCHAR,FUNCTION_NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ADD_UPDATE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,SEQUENCE_NO NUMBER,METHOD VARCHAR,PARAMETER_COLUMN_NAME VARCHAR,PRIORITY_GROUP VARCHAR,FUNCTION_NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_CATCHUP_PARAMETERS(EXTENSION_ID RAW,PERCENTAGE_FOR_CATCHUP_MDEF NUMBER,CYCLE_SECONDS_MDEF NUMBER,PERCENTAGE_FOR_CATCHUP_NEW NUMBER,CYCLE_SECONDS_NEW NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_MASTER_PROPAGATION(GNAME VARCHAR,MASTER VARCHAR,PROPAGATION_MODE VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_MASTER_PROPAGATION(GNAME VARCHAR,MASTER VARCHAR,DBLINK_LIST VARCHAR,PROPAGATION_MODE VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_MASTER_REPOBJECT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,DDL_TEXT VARCHAR,COMMENT VARCHAR,RETRY BOOLEAN,SAFE_TABLE_CHANGE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_MVIEW_PROPAGATION(GNAME VARCHAR,PROPAGATION_MODE VARCHAR,COMMENT VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_PRIORITY(GNAME VARCHAR,PGROUP VARCHAR,OLD_PRIORITY NUMBER,NEW_PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_PRIORITY_CHAR(GNAME VARCHAR,PGROUP VARCHAR,OLD_VALUE CHAR,NEW_VALUE CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_PRIORITY_DATE(GNAME VARCHAR,PGROUP VARCHAR,OLD_VALUE DATE,NEW_VALUE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_PRIORITY_NCHAR(GNAME VARCHAR,PGROUP VARCHAR,OLD_VALUE NCHAR,NEW_VALUE NCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_PRIORITY_NUMBER(GNAME VARCHAR,PGROUP VARCHAR,OLD_VALUE NUMBER,NEW_VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_PRIORITY_NVARCHAR2(GNAME VARCHAR,PGROUP VARCHAR,OLD_VALUE NVARCHAR2,NEW_VALUE NVARCHAR2)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_PRIORITY_RAW(GNAME VARCHAR,PGROUP VARCHAR,OLD_VALUE RAW,NEW_VALUE RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_PRIORITY_VARCHAR2(GNAME VARCHAR,PGROUP VARCHAR,OLD_VALUE VARCHAR,NEW_VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_SITE_PRIORITY(GNAME VARCHAR,NAME VARCHAR,OLD_PRIORITY NUMBER,NEW_PRIORITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_SITE_PRIORITY_SITE(GNAME VARCHAR,NAME VARCHAR,OLD_SITE VARCHAR,NEW_SITE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ALTER_SNAPSHOT_PROPAGATION(GNAME VARCHAR,PROPAGATION_MODE VARCHAR,COMMENT VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.BEGIN_FLAVOR_DEFINITION(GNAME VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.BEGIN_FLAVOR_DEFINITION(GNAME VARCHAR,FNAME VARCHAR,COPY_FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.CANCEL_STATISTICS(SNAME VARCHAR,ONAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMA_TO_TABLE(LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_COLUMN_GROUP(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_DELETE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,SEQUENCE_NO NUMBER,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_MVIEW_REPSITES(GOWNER VARCHAR,GNAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_PRIORITY_GROUP(GNAME VARCHAR,PGROUP VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_REPGROUP(GNAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_REPOBJECT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_REPSITES(GNAME VARCHAR,MASTER VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_REPSITES(GNAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_SITE_PRIORITY(GNAME VARCHAR,NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_SNAPSHOT_REPSITES(GOWNER VARCHAR,GNAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_UNIQUE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,CONSTRAINT_NAME VARCHAR,SEQUENCE_NO NUMBER,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMMENT_ON_UPDATE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,SEQUENCE_NO NUMBER,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMPARE_OLD_VALUES(SNAME VARCHAR,ONAME VARCHAR,COLUMN_LIST VARCHAR,OPERATION VARCHAR,COMPARE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMPARE_OLD_VALUES(SNAME VARCHAR,ONAME VARCHAR,OPERATION VARCHAR,COMPARE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.COMPARE_OLD_VALUES(SNAME VARCHAR,ONAME VARCHAR,OPERATION VARCHAR,COMPARE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.CREATE_MASTER_REPGROUP(GNAME VARCHAR,GROUP_COMMENT VARCHAR,MASTER_COMMENT VARCHAR,QUALIFIER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.CREATE_MASTER_REPOBJECT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,USE_EXISTING_OBJECT BOOLEAN,DDL_TEXT VARCHAR,COMMENT VARCHAR,RETRY BOOLEAN,COPY_ROWS BOOLEAN,GNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.CREATE_MVIEW_REPGROUP(GNAME VARCHAR,MASTER VARCHAR,COMMENT VARCHAR,PROPAGATION_MODE VARCHAR,FNAME VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.CREATE_MVIEW_REPOBJECT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,DDL_TEXT VARCHAR,COMMENT VARCHAR,GNAME VARCHAR,GEN_OBJS_OWNER VARCHAR,MIN_COMMUNICATION BOOLEAN,GENERATE_80_COMPATIBLE BOOLEAN,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.CREATE_SNAPSHOT_REPGROUP(GNAME VARCHAR,MASTER VARCHAR,COMMENT VARCHAR,PROPAGATION_MODE VARCHAR,FNAME VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.CREATE_SNAPSHOT_REPOBJECT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,DDL_TEXT VARCHAR,COMMENT VARCHAR,GNAME VARCHAR,GEN_OBJS_OWNER VARCHAR,MIN_COMMUNICATION BOOLEAN,GENERATE_80_COMPATIBLE BOOLEAN,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DEFINE_COLUMN_GROUP(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DEFINE_PRIORITY_GROUP(GNAME VARCHAR,PGROUP VARCHAR,DATATYPE VARCHAR,FIXED_LENGTH NUMBER(38),COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DEFINE_SITE_PRIORITY(GNAME VARCHAR,NAME VARCHAR,COMMENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DO_DEFERRED_REPCAT_ADMIN(GNAME VARCHAR,ALL_SITES BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_COLUMNS_FROM_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,SNAME VARCHAR,ONAME VARCHAR,CNAME_LIST VARCHAR,DEFER_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_COLUMNS_FROM_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,SNAME VARCHAR,ONAME VARCHAR,DEFER_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_COLUMN_GROUP(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_COLUMN_GROUP_FROM_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,DEFER_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_DELETE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,SEQUENCE_NO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_GROUPED_COLUMN(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_GROUPED_COLUMN(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,LIST_OF_COLUMN_NAMES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_MASTER_REPGROUP(GNAME VARCHAR,DROP_CONTENTS BOOLEAN,ALL_SITES BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_MASTER_REPOBJECT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,DROP_OBJECTS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_MVIEW_REPGROUP(GNAME VARCHAR,DROP_CONTENTS BOOLEAN,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_MVIEW_REPOBJECT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,DROP_OBJECTS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_OBJECT_FROM_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,DEFER_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY(GNAME VARCHAR,PGROUP VARCHAR,PRIORITY_NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY_CHAR(GNAME VARCHAR,PGROUP VARCHAR,VALUE CHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY_DATE(GNAME VARCHAR,PGROUP VARCHAR,VALUE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY_GROUP(GNAME VARCHAR,PGROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY_NCHAR(GNAME VARCHAR,PGROUP VARCHAR,VALUE NCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY_NUMBER(GNAME VARCHAR,PGROUP VARCHAR,VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY_NVARCHAR2(GNAME VARCHAR,PGROUP VARCHAR,VALUE NVARCHAR2)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY_RAW(GNAME VARCHAR,PGROUP VARCHAR,VALUE RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_PRIORITY_VARCHAR2(GNAME VARCHAR,PGROUP VARCHAR,VALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_SITE_PRIORITY(GNAME VARCHAR,NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_SITE_PRIORITY_SITE(GNAME VARCHAR,NAME VARCHAR,SITE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_SNAPSHOT_REPGROUP(GNAME VARCHAR,DROP_CONTENTS BOOLEAN,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_SNAPSHOT_REPOBJECT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,DROP_OBJECTS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_UNIQUE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,CONSTRAINT_NAME VARCHAR,SEQUENCE_NO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.DROP_UPDATE_RESOLUTION(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,SEQUENCE_NO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.EXECUTE_DDL(GNAME VARCHAR,MASTER_LIST VARCHAR,DDL_TEXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.EXECUTE_DDL(GNAME VARCHAR,DDL_TEXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPCAT.GENERATE_FLAVOR_NAME(GNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.GENERATE_MVIEW_SUPPORT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,GEN_OBJS_OWNER VARCHAR,MIN_COMMUNICATION BOOLEAN,GENERATE_80_COMPATIBLE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.GENERATE_REPLICATION_PACKAGE(SNAME VARCHAR,ONAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.GENERATE_REPLICATION_SUPPORT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,PACKAGE_PREFIX VARCHAR,PROCEDURE_PREFIX VARCHAR,DISTRIBUTED BOOLEAN,GEN_OBJS_OWNER VARCHAR,MIN_COMMUNICATION BOOLEAN,GENERATE_80_COMPATIBLE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.GENERATE_REPLICATION_TRIGGER(SNAME VARCHAR,ONAME VARCHAR,GEN_OBJS_OWNER VARCHAR,MIN_COMMUNICATION BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.GENERATE_REPLICATION_TRIGGER(GNAME VARCHAR,GEN_OBJS_OWNER VARCHAR,MIN_COMMUNICATION BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.GENERATE_SNAPSHOT_SUPPORT(SNAME VARCHAR,ONAME VARCHAR,TYPE VARCHAR,GEN_OBJS_OWNER VARCHAR,MIN_COMMUNICATION BOOLEAN,GENERATE_80_COMPATIBLE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.MAKE_COLUMN_GROUP(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR,LIST_OF_COLUMN_NAMES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.MAKE_COLUMN_GROUP(SNAME VARCHAR,ONAME VARCHAR,COLUMN_GROUP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.OBSOLETE_FLAVOR_DEFINITION(GNAME VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ORDER_USER_OBJECTS(LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.ORDER_USER_OBJECTS(OWNERS VARCHAR,OBJECTS VARCHAR,TYPES VARCHAR,LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.PREPARE_INSTANTIATED_MASTER(EXTENSION_ID RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.PUBLISH_FLAVOR_DEFINITION(GNAME VARCHAR,FNAME VARCHAR,SKIP_VALIDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.PURGE_FLAVOR_DEFINITION(GNAME VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.PURGE_MASTER_LOG(ID NUMBER,SOURCE VARCHAR,GNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.PURGE_STATISTICS(SNAME VARCHAR,ONAME VARCHAR,START_DATE DATE,END_DATE DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REFRESH_MVIEW_REPGROUP(GNAME VARCHAR,DROP_MISSING_CONTENTS BOOLEAN,REFRESH_MVIEWS BOOLEAN,REFRESH_OTHER_OBJECTS BOOLEAN,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REFRESH_SNAPSHOT_REPGROUP(GNAME VARCHAR,DROP_MISSING_CONTENTS BOOLEAN,REFRESH_SNAPSHOTS BOOLEAN,REFRESH_OTHER_OBJECTS BOOLEAN,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REGISTER_MVIEW_REPGROUP(GNAME VARCHAR,MVIEWSITE VARCHAR,COMMENT VARCHAR,REP_TYPE NUMBER,FNAME VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REGISTER_SNAPSHOT_REPGROUP(GNAME VARCHAR,SNAPSITE VARCHAR,COMMENT VARCHAR,REP_TYPE NUMBER,FNAME VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REGISTER_STATISTICS(SNAME VARCHAR,ONAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.RELOCATE_MASTERDEF(GNAME VARCHAR,OLD_MASTERDEF VARCHAR,NEW_MASTERDEF VARCHAR,NOTIFY_MASTERS BOOLEAN,INCLUDE_OLD_MASTERDEF BOOLEAN,REQUIRE_FLAVOR_CHANGE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REMOVE_MASTER_DATABASES(GNAME VARCHAR,MASTER_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REMOVE_MASTER_DATABASES(GNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.RENAME_SHADOW_COLUMN_GROUP(SNAME VARCHAR,ONAME VARCHAR,NEW_COL_GROUP_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REPCAT_IMPORT_CHECK(GNAME VARCHAR,MASTER BOOLEAN,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REPCAT_IMPORT_CHECK()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.REPCAT_IMPORT_REPSCHEMA()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPCAT.REPCAT_IMPORT_REPSCHEMA_STRING(OVERRIDE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.RESUME_PROPAGATION_TO_MDEF(EXTENSION_ID RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SEND_AND_COMPARE_OLD_VALUES(SNAME VARCHAR,ONAME VARCHAR,COLUMN_LIST VARCHAR,OPERATION VARCHAR,SEND BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SEND_AND_COMPARE_OLD_VALUES(SNAME VARCHAR,ONAME VARCHAR,OPERATION VARCHAR,SEND BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SEND_OLD_VALUES(SNAME VARCHAR,ONAME VARCHAR,COLUMN_LIST VARCHAR,OPERATION VARCHAR,SEND BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SEND_OLD_VALUES(SNAME VARCHAR,ONAME VARCHAR,OPERATION VARCHAR,SEND BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SEND_OLD_VALUES(SNAME VARCHAR,ONAME VARCHAR,OPERATION VARCHAR,SEND BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SET_COLUMNS(SNAME VARCHAR,ONAME VARCHAR,COLUMN_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SET_COLUMNS(SNAME VARCHAR,ONAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SET_COLUMNS(SNAME VARCHAR,ONAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SET_LOCAL_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,VALIDATE BOOLEAN,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SPECIFY_NEW_MASTERS(GNAME VARCHAR,MASTER_LIST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SPECIFY_NEW_MASTERS(GNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.STREAMS_MIGRATION(FILE_LOCATION VARCHAR,FILENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SUSPEND_MASTER_ACTIVITY(GNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SWITCH_MVIEW_MASTER(GNAME VARCHAR,MASTER VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.SWITCH_SNAPSHOT_MASTER(GNAME VARCHAR,MASTER VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.TICKLE_JOB(CANON_SNAME VARCHAR,START_NOW BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.UNDO_ADD_NEW_MASTERS_REQUEST(EXTENSION_ID RAW,DROP_CONTENTS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.UNREGISTER_MVIEW_REPGROUP(GNAME VARCHAR,MVIEWSITE VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.UNREGISTER_SNAPSHOT_REPGROUP(GNAME VARCHAR,SNAPSITE VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_REPCAT.VALIDATE(GNAME VARCHAR,CHECK_GENFLAGS BOOLEAN,CHECK_VALID_OBJS BOOLEAN,CHECK_LINKS_SCHED BOOLEAN,CHECK_LINKS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_REPCAT.VALIDATE(GNAME VARCHAR,CHECK_GENFLAGS BOOLEAN,CHECK_VALID_OBJS BOOLEAN,CHECK_LINKS_SCHED BOOLEAN,CHECK_LINKS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.VALIDATE_FLAVOR_DEFINITION(GNAME VARCHAR,FNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.VALIDATE_FOR_LOCAL_FLAVOR(GNAME VARCHAR,FNAME VARCHAR,GOWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_REPCAT.WAIT_MASTER_LOG(GNAME VARCHAR,RECORD_COUNT NUMBER,TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

