CREATE SCHEMA DBMS_RESCONFIG;

CREATE OR REPLACE PROCEDURE DBMS_RESCONFIG.ADDREPOSITORYRESCONFIG(RCPATH VARCHAR,POS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESCONFIG.ADDRESCONFIG(RESPATH VARCHAR,RCPATH VARCHAR,POS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESCONFIG.APPENDRESCONFIG(RESPATH VARCHAR,RCPATH VARCHAR,APPENDOPTION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESCONFIG.DELETEREPOSITORYRESCONFIG(POS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESCONFIG.DELETERESCONFIG(RESPATH VARCHAR,POS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_RESCONFIG.DELETERESCONFIG(RESPATH VARCHAR,RCPATH VARCHAR,DELETEOPTION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_RESCONFIG.GETLISTENERS(PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_RESCONFIG.GETREPOSITORYRESCONFIG(POS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_RESCONFIG.GETREPOSITORYRESCONFIGPATHS(POS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_RESCONFIG.GETRESCONFIGPATHS(RESPATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

