CREATE SCHEMA DBMS_ROWID;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_BLOCK_NUMBER(ROW_ID ROWID,TS_TYPE_IN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_CREATE(ROWID_TYPE NUMBER,OBJECT_NUMBER NUMBER,RELATIVE_FNO NUMBER,BLOCK_NUMBER NUMBER,ROW_NUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_ROWID.ROWID_INFO(ROWID_IN ROWID,TS_TYPE_IN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_OBJECT(ROW_ID ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_RELATIVE_FNO(ROW_ID ROWID,TS_TYPE_IN VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_ROW_NUMBER(ROW_ID ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_TO_ABSOLUTE_FNO(ROW_ID ROWID,SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_TO_EXTENDED(OLD_ROWID ROWID,SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR,CONVERSION_TYPE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_TO_RESTRICTED(OLD_ROWID ROWID,CONVERSION_TYPE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_TYPE(ROW_ID ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_ROWID.ROWID_VERIFY(ROWID_IN ROWID,SCHEMA_NAME VARCHAR,OBJECT_NAME VARCHAR,CONVERSION_TYPE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

