CREATE SCHEMA DBMS_STORAGE_MAP;

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.DROP_ALL(DICTIONARY_UPDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.DROP_ELEMENT(ELEMNAME VARCHAR,CASCADE BOOLEAN,DICTIONARY_UPDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.DROP_FILE(FILENAME VARCHAR,CASCADE BOOLEAN,DICTIONARY_UPDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.LOCK_MAP(DICTIONARY_UPDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.MAP_ELEMENT(ELEMNAME VARCHAR,CASCADE BOOLEAN,DICTIONARY_UPDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.MAP_FILE(FILENAME VARCHAR,FILETYPE VARCHAR,CASCADE BOOLEAN,MAX_NUM_FILEEXTENT NUMBER,DICTIONARY_UPDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.MAP_OBJECT(OBJNAME VARCHAR,OWNER VARCHAR,OBJTYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.RESTORE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_STORAGE_MAP.SAVE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

