CREATE SCHEMA DBMS_LDAP_UTL;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.AUTHENTICATE_USER(LD RAW(32),USER_HANDLE RAW(32),AUTH_TYPE NUMBER,CREDENTIALS VARCHAR,BINARY_CREDENTIALS RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.AUTHENTICATE_USER_EXT(LD RAW(32),USER_HANDLE RAW(32),AUTH_TYPE NUMBER,PASSWORD_ATTR VARCHAR,PASSWORD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.CHECK_GROUP_MEMBERSHIP(LD RAW(32),USER_HANDLE RAW(32),GROUP_HANDLE RAW(32),NESTED NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.CHECK_INTERFACE_VERSION(INTERFACE_VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.CHECK_USER_SUBSCRIPTION(LD RAW(32),USER_HANDLE RAW(32),SERVICE_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.CREATE_GROUP_HANDLE(GROUP_TYPE NUMBER,GROUP_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.CREATE_MOD_PROPERTYSET(PSET_TYPE NUMBER,PSET_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.CREATE_SERVICE_HANDLE(SERVICE_TYPE NUMBER,SERVICE_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.CREATE_SUBSCRIBER_HANDLE(SUBSCRIBER_TYPE NUMBER,SUBSCRIBER_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.CREATE_USER_HANDLE(USER_TYPE NUMBER,USER_ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LDAP_UTL.FREE_HANDLE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LDAP_UTL.FREE_MOD_PROPERTYSET()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE DBMS_LDAP_UTL.FREE_PROPERTYSET_COLLECTION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_AVAILABLE_SERVICES(LD RAW(32),SUBSCRIBER_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_GROUP_DN(LD RAW(32),GROUP_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_GROUP_MEMBERSHIP(LD RAW(32),USER_HANDLE RAW(32),NESTED NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_GROUP_PROPERTIES(LD RAW(32),GROUP_HANDLE RAW(32),PTYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_PROPERTY_NAMES(PSET RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_PROPERTY_VALUES(PSET RAW(32),PROPERTY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_PROPERTY_VALUES_BLOB(PSET RAW(32),PROPERTY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_PROPERTY_VALUES_LEN(PSET RAW(32),PROPERTY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_SUBSCRIBED_SERVICES(LD RAW(32),USER_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_SUBSCRIBED_USERS(LD RAW(32),SERVICE_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_SUBSCRIBER_DN(LD RAW(32),SUBSCRIBER_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_SUBSCRIBER_EXT_PROPERTIES(LD RAW(32),SUBSCRIBER_HANDLE RAW(32),PTYPE NUMBER,FILTER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_SUBSCRIBER_PROPERTIES(LD RAW(32),SUBSCRIBER_HANDLE RAW(32),PTYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_USER_DN(LD RAW(32),USER_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_USER_EXTENDED_PROPERTIES(LD RAW(32),USER_HANDLE RAW(32),PTYPE NUMBER,FILTER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_USER_PROPERTIES(LD RAW(32),USER_HANDLE RAW(32),PTYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.GET_USER_PROPS_AND_AUTH(LD RAW(32),USER_HANDLE RAW(32),AUTH_TYPE NUMBER,CREDENTIALS VARCHAR,BINARY_CREDENTIALS RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.LOCATE_SUBSCRIBER_FOR_USER(LD RAW(32),USER_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.NORMALIZE_DN_WITH_CASE(DN VARCHAR,LOWER_CASE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.POPULATE_MOD_PROPERTYSET(MOD_PSET RAW(32),PROPERTY_MOD_OP NUMBER,PROPERTY_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE DBMS_LDAP_UTL.PROPERTY_VALUE_FREE_BLOB()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.SET_GROUP_HANDLE_PROPERTIES(GROUP_HD RAW(32),PROPERTY_TYPE NUMBER,PROPERTY RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.SET_USER_HANDLE_PROPERTIES(USER_HD RAW(32),PROPERTY_TYPE NUMBER,PROPERTY RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.SET_USER_PROPERTIES(LD RAW(32),USER_HANDLE RAW(32),PSET_TYPE NUMBER,MOD_PSET RAW(32),MOD_OP NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.SUBSCRIBE_USER(LD RAW(32),USER_HANDLE RAW(32),SERVICE_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION DBMS_LDAP_UTL.UNSUBSCRIBE_USER(LD RAW(32),USER_HANDLE RAW(32),SERVICE_HANDLE RAW(32))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

