python3 ../scripts/generate_snowflake_stub.py   --input ../packages/APEX_CUSTOM_AUTH.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/APEX_APPLICATION.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/APEX_ITEM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/APEX_UTIL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_ADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_CLS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_DDL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_DOC.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_OUTPUT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_QUERY.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_REPORT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_THES.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/CTX_ULEXER.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_ADDM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_ADVANCED_REWRITE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_ADVISOR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_ALERT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_APPLICATION_INFO.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_APPLY_ADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_AQ.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_AQADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_AQELM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_AQIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_ASSERT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_AUTO_TASK_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_AW_STATS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CAPTURE_ADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CDC_PUBLISH.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CDC_SUBSCRIBE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_COMPARISON.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CONNECTION_POOL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CQ_NOTIFICATION.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CRYPTO.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CSX_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CUBE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_CUBE_ADVISE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DATA_MINING.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DATA_MINING_TRANSFORM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DATAPUMP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DB_VERSION.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DDL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DEBUG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DEFER.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DEFER_QUERY.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DEFER_SYS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DESCRIBE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DIMENSION.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_DISTRIBUTED_TRUST_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_EPG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_ERRLOG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_EXPFIL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_FGA.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_FILE_GROUP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_FILE_TRANSFER.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_FLASHBACK.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_FREQUENT_ITEMSET.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_HM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_HPROF.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_HS_PARALLEL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_HS_PASSTHROUGH.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_JAVA.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_IOT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_JOB.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_LDAP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_LDAP_UTL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_LIBCACHE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_LOB.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_LOCK.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_LOGMNR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_LOGMNR_D.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_LOGSTDBY.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_METADATA.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_MGD_ID_UTL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_MGWADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_MGWMSG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_MONITOR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_MVIEW.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_NETWORK_ACL_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_NETWORK_ACL_UTILITY.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_OBFUSCATION_TOOLKIT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_ODCI.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_OFFLINE_OG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_OUTLN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_OUTPUT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_PCLXUTIL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_PIPE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_PREDICTIVE_ANALYTICS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_PREPROCESSOR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_PROFILER.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_PROPAGATION_ADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RANDOM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RECTIFIER_DIFF.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REDEFINITION.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REFRESH.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REPAIR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REPCAT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REPCAT_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REPCAT_INSTANTIATE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REPORT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REPCAT_RGT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_REPUTIL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RESCONFIG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RESOURCE_MANAGER.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RESOURCE_MANAGER_PRIVS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RESULT_CACHE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RESUMABLE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RLMGR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RLS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_ROWID.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RULE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_RULE_ADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SCHEDULER.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SERVER_ALERT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SERVICE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SESSION.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SHARED_POOL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SPACE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SPACE_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SPM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SQL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SQLDIAG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SQLPA.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_SQLTUNE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STAT_FUNCS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STATS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STORAGE_MAP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STREAMS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STREAMS_ADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STREAMS_ADVISOR_ADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STREAMS_AUTH.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STREAMS_MESSAGING.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_STREAMS_TABLESPACE_ADM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_TDB.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_TRACE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_TRANSACTION.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_TRANSFORM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_TTS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_TYPES.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_UTILITY.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_WARNING.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_WM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_WORKLOAD_CAPTURE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_WORKLOAD_REPLAY.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_WORKLOAD_REPOSITORY.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XA.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XDB.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XDB_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XDBRESOURCE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XDB_VERSION.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XDBT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XDBZ.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XEVENT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLDOM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLGEN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLINDEX.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLPARSER.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLQUERY.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLSAVE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLSCHEMA.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLSTORE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XMLTRANSLATIONS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XPLAN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DBMS_XSLPROCESSOR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/DEBUG_EXTPROC.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/HTF.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/HTP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/ORD_DICOM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/ORD_DICOM_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_CACHE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_COOKIE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_CUSTOM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_IMAGE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_OPT_LOCK.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_PATTERN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_SEC.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_TEXT.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/OWA_UTIL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_CS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_CSW_PROCESS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_GCDR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_GEOM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_GEOR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_GEOR_ADMIN.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_GEOR_UTL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_LRS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_MIGRATE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_NET.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_NET_MEM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_OLS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_PC_PKG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_SAM.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_TIN_PKG.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_TOPO.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_TOPO_MAP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_TUNE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_UTIL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_WFS_LOCK.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SDO_WFS_PROCESS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SEM_APIS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/SEM_PERF.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_COLL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_COMPRESS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_ENCODE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_FILE.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_HTTP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_I18N.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_INADDR.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_LMS.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_MAIL.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_NLA.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_RAW.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_RECOMP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_REF.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_SMTP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_SPADV.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_TCP.txt
python3 ../scripts/generate_snowflake_stub.py   --input ../packages/UTL_URL.txt
