CREATE SCHEMA HTP;

CREATE OR REPLACE PROCEDURE HTP.ADDDEFAULTHTMLHDR(BADDHTMLHDR BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.ADDRESS(CVALUE VARCHAR,CNOWRAP VARCHAR,CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.ANCHOR(CURL VARCHAR,CTEXT VARCHAR,CNAME VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.ANCHOR2(CURL VARCHAR,CTEXT VARCHAR,CNAME VARCHAR,CTARGET VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.APPLETCLOSE(CWIDTH NUMBER(38),CHEIGHT NUMBER(38),CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.AREA(CCOORDS VARCHAR,CSHAPE VARCHAR,CHREF VARCHAR,CNOHREF VARCHAR,CTARGET VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.BASE(CTARGET VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.BASEFONT(NSIZE NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.BGSOUND(CSRC VARCHAR,CLOOP VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.BIG(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.BLOCKQUOTECLOSE(CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.BODYCLOSE(CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.BOLD(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.BR(CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.CENTER(CTEXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.CENTERCLOSE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.CENTEROPEN(CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.CODE(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.COMMENT(CTEXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.DFN(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.DIRLISTCLOSE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.DIRLISTOPEN(CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.DLISTCLOSE(CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.DLISTOPEN(CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.DLISTTERM(CTEXT VARCHAR,CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.DOWNLOAD_FILE(SFILENAME VARCHAR,BCOMPRESS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.EM(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.EMPHASIS(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.ESCAPE_SC(CTEXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FLUSH()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FONTCLOSE(CFACE VARCHAR,CSIZE VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMCHECKBOX(CNAME VARCHAR,CVALUE VARCHAR,CCHECKED VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMCLOSE(CACCEPT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMHIDDEN(CNAME VARCHAR,CVALUE VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMIMAGE(CNAME VARCHAR,CSRC VARCHAR,CALIGN VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMOPEN(CURL VARCHAR,CMETHOD VARCHAR,CTARGET VARCHAR,CENCTYPE VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMPASSWORD(CNAME VARCHAR,CSIZE VARCHAR,CMAXLENGTH VARCHAR,CVALUE VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMRADIO(CNAME VARCHAR,CVALUE VARCHAR,CCHECKED VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMRESET(CVALUE VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMSELECTCLOSE(CPROMPT VARCHAR,NSIZE NUMBER(38),CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMSELECTOPTION(CVALUE VARCHAR,CSELECTED VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMSUBMIT(CNAME VARCHAR,CVALUE VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMTEXT(CNAME VARCHAR,CSIZE VARCHAR,CMAXLENGTH VARCHAR,CVALUE VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMTEXTAREA(CNAME VARCHAR,NROWS NUMBER(38),NCOLUMNS NUMBER(38),CALIGN VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMTEXTAREA2(CNAME VARCHAR,NROWS NUMBER(38),NCOLUMNS NUMBER(38),CALIGN VARCHAR,CWRAP VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMTEXTAREACLOSE(NROWS NUMBER(38),NCOLUMNS NUMBER(38),CALIGN VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FORMTEXTAREAOPEN2(CNAME VARCHAR,NROWS NUMBER(38),NCOLUMNS NUMBER(38),CALIGN VARCHAR,CWRAP VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FRAME(CSRC VARCHAR,CNAME VARCHAR,CMARGINWIDTH VARCHAR,CMARGINHEIGHT VARCHAR,CSCROLLING VARCHAR,CNORESIZE VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.FRAMESETCLOSE(CCOLS VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.GET_DOWNLOAD_FILES_LIST()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION HTP.GET_LINE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE HTP.GET_PAGE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.GET_PAGE_CHARSET_CONVERT(CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.GET_PAGE_RAW()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.HEADCLOSE(CHEADER VARCHAR,CALIGN VARCHAR,CNOWRAP VARCHAR,CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.HEADOPEN(CSRC VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.HTITLE(CTITLE VARCHAR,NSIZE NUMBER(38),CALIGN VARCHAR,CNOWRAP VARCHAR,CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.HTMLCLOSE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.HTMLOPEN(CALIGN VARCHAR,CALT VARCHAR,CISMAP VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.IMG2(CURL VARCHAR,CALIGN VARCHAR,CALT VARCHAR,CISMAP VARCHAR,CUSEMAP VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.INIT(CURL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.ITALIC(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.KBD(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.KEYBOARD(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.LINE(CCLEAR VARCHAR,CSRC VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.LINKREL(CREL VARCHAR,CURL VARCHAR,CTITLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.LINKREV(CREV VARCHAR,CURL VARCHAR,CTITLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.LISTHEADER(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.LISTINGCLOSE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.LISTINGOPEN(CCLEAR VARCHAR,CDINGBAT VARCHAR,CSRC VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.MAILTO(CADDRESS VARCHAR,CTEXT VARCHAR,CNAME VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.MAPCLOSE(CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.MENULISTCLOSE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.MENULISTOPEN(CNAME VARCHAR,CCONTENT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.NEXTID(CIDENTIFIER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.NL(CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.NOBR(CTEXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.NOFRAMESCLOSE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.NOFRAMESOPEN()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.OLISTCLOSE(CWRAP VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.P(CBUF VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.P(DBUF DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.P(NBUF NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PARA(CNOWRAP VARCHAR,CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PARAM(CNAME VARCHAR,CVALUE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PLAINTEXT(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRECLOSE(CWIDTH VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRINT(CBUF VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRINT(DBUF DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRINT(NBUF NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRINTS(CTEXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRINT_HEADER(CBUF VARCHAR,NLINE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRN(CBUF VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRN(DBUF DATE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PRN(NBUF NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PS(CTEXT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.PUTRAW(BBUF RAW,BUFLEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.RESET_GET_PAGE(CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.SAMPLE(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.SCRIPT(CSCRIPT VARCHAR,CLANGUAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.SETHTTPCHARSET(IANA_CHARSET VARCHAR,ORA_CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.SET_TRANSFER_MODE(TMODE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.SHOWPAGE(CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.STRIKE(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.STRONG(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.STYLE(CSTYLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.SUB(CTEXT VARCHAR,CALIGN VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.SUP(CTEXT VARCHAR,CALIGN VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.TABLECAPTION(CCAPTION VARCHAR,CALIGN VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.TABLECLOSE(CALIGN VARCHAR,CDP VARCHAR,CNOWRAP VARCHAR,CROWSPAN VARCHAR,CCOLSPAN VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.TABLEHEADER(CVALUE VARCHAR,CALIGN VARCHAR,CDP VARCHAR,CNOWRAP VARCHAR,CROWSPAN VARCHAR,CCOLSPAN VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.TABLEOPEN(CBORDER VARCHAR,CALIGN VARCHAR,CNOWRAP VARCHAR,CCLEAR VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.TABLEROWCLOSE(CVALIGN VARCHAR,CDP VARCHAR,CNOWRAP VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.TELETYPE(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.TITLE(CTITLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.ULISTCLOSE(CWRAP VARCHAR,CDINGBAT VARCHAR,CSRC VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.UNDERLINE(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.VARIABLE(CTEXT VARCHAR,CATTRIBUTES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE HTP.WBR()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

