CREATE SCHEMA ORD_DICOM;

CREATE OR REPLACE PROCEDURE ORD_DICOM.CREATEDICOMIMAGE(SRC BLOB,METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.CREATEDICOMIMAGE(METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.CREATEDICOMIMAGE(SRC ORDIMAGE,METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.EXPORT(SRC BLOB,DEST_TYPE VARCHAR,DEST_LOCATION VARCHAR,DEST_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION ORD_DICOM.EXTRACTMETADATA(DATA BLOB,EXTRACTOPTION VARCHAR,DOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.EXTRACTMETADATA(EXTRACTOPTION VARCHAR,DOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.EXTRACTMETADATA(DATA ORDIMAGE,EXTRACTOPTION VARCHAR,DOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.GETDICTIONARYTAG(ATTRIBUTENAME VARCHAR,DEFINERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.GETMAPPINGXPATH(TAG VARCHAR,DOCNAME VARCHAR,DEFINERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE ORD_DICOM.IMPORTFROM(SOURCE_TYPE VARCHAR,SOURCE_LOCATION VARCHAR,SOURCE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION ORD_DICOM.ISANONYMOUS(SRC BLOB,ANONYMITYDOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.ISANONYMOUS(ANONYMITYDOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.ISANONYMOUS(SRC ORDIMAGE,ANONYMITYDOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.ISCONFORMANCEVALID(SRC BLOB,CONSTRAINTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.ISCONFORMANCEVALID(CONSTRAINTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM.ISCONFORMANCEVALID(SRC ORDIMAGE,CONSTRAINTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE ORD_DICOM.MAKEANONYMOUS(SRC BLOB,DEST_SOP_INSTANCE_UID VARCHAR,ANONYMITYDOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.MAKEANONYMOUS(DEST_SOP_INSTANCE_UID VARCHAR,ANONYMITYDOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.MAKEANONYMOUS(SRC ORDIMAGE,DEST_SOP_INSTANCE_UID VARCHAR,ANONYMITYDOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.PROCESSCOPY(SRC BLOB,COMMAND VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.PROCESSCOPY(COMMAND VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.PROCESSCOPY(SRC ORDIMAGE,COMMAND VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.PROCESSCOPY(SRC BLOB,COMMAND VARCHAR,DEST_SOP_INSTANCE_UID VARCHAR,METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.PROCESSCOPY(COMMAND VARCHAR,DEST_SOP_INSTANCE_UID VARCHAR,METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.PROCESSCOPY(SRC ORDIMAGE,COMMAND VARCHAR,DEST_SOP_INSTANCE_UID VARCHAR,METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.SETDATAMODEL(MODELNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.SETDATAMODEL(MODELNAME VARCHAR,FORCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.WRITEMETADATA(SRC BLOB,METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.WRITEMETADATA(METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM.WRITEMETADATA(SRC ORDIMAGE,METADATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

