CREATE SCHEMA ORD_DICOM_ADMIN;

CREATE OR REPLACE PROCEDURE ORD_DICOM_ADMIN.DELETEDOCUMENT(DOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM_ADMIN.EDITDATAMODEL(EXPORTOPTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM_ADMIN.EXPORTDOCUMENT(DOCNAME VARCHAR,DIRNAME VARCHAR,FILENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION ORD_DICOM_ADMIN.GENERATETAGLISTDOCUMENT(DOCSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION ORD_DICOM_ADMIN.GETDOCUMENTCONTENT(DOCNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE ORD_DICOM_ADMIN.IMPORTDATAMODEL(DIRNAME VARCHAR,ZIPFILENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM_ADMIN.INSERTDOCUMENT(DOCNAME VARCHAR,DOCTYPE VARCHAR,XMLDOC XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE ORD_DICOM_ADMIN.PUBLISHDATAMODEL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

