CREATE SCHEMA OWA_PATTERN;

CREATE OR REPLACE FUNCTION OWA_PATTERN.AMATCH(LINE VARCHAR,FROM_LOC NUMBER(38),PAT VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.AMATCH(LINE VARCHAR,FROM_LOC NUMBER(38),FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.AMATCH(LINE VARCHAR,FROM_LOC NUMBER(38),PAT VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.AMATCH(LINE VARCHAR,FROM_LOC NUMBER(38),FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.CHANGE(FROM_STR VARCHAR,TO_STR VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE OWA_PATTERN.CHANGE(FROM_STR VARCHAR,TO_STR VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION OWA_PATTERN.CHANGE(FROM_STR VARCHAR,TO_STR VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE OWA_PATTERN.CHANGE(FROM_STR VARCHAR,TO_STR VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE OWA_PATTERN.GETPAT(ARG VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION OWA_PATTERN.MATCH(LINE VARCHAR,PAT VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.MATCH(LINE VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.MATCH(LINE VARCHAR,PAT VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.MATCH(LINE VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.MATCH(MLINE VARIANT,PAT VARCHAR,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_PATTERN.MATCH(MLINE VARIANT,FLAGS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

