CREATE SCHEMA OWA_IMAGE;

CREATE OR REPLACE FUNCTION OWA_IMAGE.GET_X()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_IMAGE.GET_Y()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

