CREATE SCHEMA OWA_OPT_LOCK;

CREATE OR REPLACE FUNCTION OWA_OPT_LOCK.CHECKSUM(P_BUFF VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_OPT_LOCK.CHECKSUM(P_OWNER VARCHAR,P_TNAME VARCHAR,P_ROWID ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION OWA_OPT_LOCK.GET_ROWID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE OWA_OPT_LOCK.STORE_VALUES(P_OWNER VARCHAR,P_TNAME VARCHAR,P_ROWID ROWID)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION OWA_OPT_LOCK.VERIFY_VALUES()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

