CREATE SCHEMA OWA_COOKIE;

CREATE OR REPLACE FUNCTION OWA_COOKIE.GET(NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE OWA_COOKIE.GET_ALL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE OWA_COOKIE.INIT(VAL VARCHAR,PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE OWA_COOKIE.SEND(NAME VARCHAR,VALUE VARCHAR,EXPIRES DATE,PATH VARCHAR,DOMAIN VARCHAR,SECURE VARCHAR,HTTPONLY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

