CREATE SCHEMA SDO_GEOR;

CREATE OR REPLACE PROCEDURE SDO_GEOR.ADDNODATA(LAYERNUMBER NUMBER,NODATA NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.ADDNODATA(LAYERNUMBER NUMBER,NODATA SDO_RANGE_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.ADDSOURCEINFO(SOURCEINFO VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.CALCCOMPRESSIONRATIO(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.CHANGECELLVALUE(WINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,NEWCELLVALUE NUMBER,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.CHANGECELLVALUE(WINDOW SDO_GEOMETRY,LAYERNUMBERS VARCHAR,NEWCELLVALUE NUMBER,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.CHANGEFORMAT(STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.CHANGEFORMATCOPY(INGEORASTER SDO_GEORASTER,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.CHANGEFORMATCOPY(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.COPY(INGEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.CREATEBLANK(RASTERTYPE NUMBER(38),ULTCOORD SDO_NUMBER_ARRAY,DIMSIZES SDO_NUMBER_ARRAY,CELLVALUE NUMBER,RASTERDATATABLE VARCHAR,RASTERID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.CREATETEMPLATE(RASTERTYPE NUMBER,RASTERSPEC VARCHAR,MASKLAYERS VARCHAR,INITRDTENTRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.DELETECONTROLPOINT(CONTROLPOINTID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.DELETENODATA(LAYERNUMBER NUMBER,NODATA NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.DELETENODATA(LAYERNUMBER NUMBER,NODATA SDO_RANGE_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.DELETEPYRAMID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.EVALUATEDOUBLE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,ROW NUMBER,COLUMN NUMBER,BANDS VARCHAR,INTERPOLATIONMETHOD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.EVALUATEDOUBLE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,PTGEOM SDO_GEOMETRY,LAYERS VARCHAR,INTERPOLATIONMETHOD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.EXPORTTO(GEORASTER SDO_GEORASTER,SUBSETPARAM VARCHAR,R_DESTFORMAT VARCHAR,R_DESTTYPE VARCHAR,R_DESTNAME VARCHAR,H_DESTFORMAT VARCHAR,H_DESTTYPE VARCHAR,H_DESTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.EXPORTTO(GEORASTER SDO_GEORASTER,SUBSETPARAM VARCHAR,DESTFORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.EXPORTTO(GEORASTER SDO_GEORASTER,SUBSETPARAM VARCHAR,R_DESTFORMAT VARCHAR,H_DESTFORMAT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GENERATEBLOCKMBR(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GENERATEPYRAMID(PYRAMIDPARAMS VARCHAR,BGVALUES SDO_NUMBER_ARRAY,PARALLELPARAM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESPATIALEXTENT(GEORASTER SDO_GEORASTER,HEIGHT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.GENERATESPATIALRESOLUTIONS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESPATIALRESOLUTIONS(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SRID NUMBER,RESOLUTIONUNIT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICS(SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_GEOMETRY,HISTOGRAM VARCHAR,LAYERNUMBERS VARCHAR,USEBIN VARCHAR,BINFUNCTION SDO_NUMBER_ARRAY,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICS(SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_NUMBER_ARRAY,HISTOGRAM VARCHAR,LAYERNUMBERS VARCHAR,USEBIN VARCHAR,BINFUNCTION SDO_NUMBER_ARRAY,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICS(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICS(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_GEOMETRY,BANDNUMBERS VARCHAR,NODATA VARCHAR,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMAX(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMAX(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_GEOMETRY,BANDNUMBERS VARCHAR,NODATA VARCHAR,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMEAN(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMEAN(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_GEOMETRY,BANDNUMBERS VARCHAR,NODATA VARCHAR,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMEDIAN(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMEDIAN(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_GEOMETRY,BANDNUMBERS VARCHAR,NODATA VARCHAR,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMIN(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMIN(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_GEOMETRY,BANDNUMBERS VARCHAR,NODATA VARCHAR,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMODE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSMODE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_GEOMETRY,BANDNUMBERS VARCHAR,NODATA VARCHAR,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSSTD(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,NODATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GENERATESTATISTICSSTD(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SAMPLINGFACTOR VARCHAR,SAMPLINGWINDOW SDO_GEOMETRY,BANDNUMBERS VARCHAR,NODATA VARCHAR,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.GEOREFERENCE(SRID NUMBER,MODELCOORDINATELOCATION NUMBER,XCOEFFICIENTS SDO_NUMBER_ARRAY,YCOEFFICIENTS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GEOREFERENCE(FFMETHODTYPE VARCHAR,NGCP NUMBER,GCPS SDO_GEOR_GCP_COLLECTION,STOREGCP VARCHAR,SRID NUMBER,MODELCOORDINATELOCATION NUMBER,SETRESOLUTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GEOREFERENCE(GCPGEOREFMODEL SDO_GEOR_GCPGEOREFTYPE,STOREGCP VARCHAR,SRID NUMBER,MODELCOORDINATELOCATION NUMBER,SETRESOLUTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GEOREFERENCE(FFMETHOD VARCHAR,SRID NUMBER,MODELCOORDINATELOCATION NUMBER,SETRESOLUTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBANDDIMSIZE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBEGINDATETIME(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBINFUNCTION(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBINTABLE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBINTYPE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETBITMAPMASK(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER,STORAGEPARAM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETBITMAPMASKSUBSET(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER,PYRAMIDLEVEL NUMBER,WINDOW SDO_NUMBER_ARRAY,STORAGEPARAM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETBITMAPMASKSUBSET(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER,PYRAMIDLEVEL NUMBER,WINDOW SDO_GEOMETRY,STORAGEPARAM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETBITMAPMASKSUBSET(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER,PYRAMIDLEVEL NUMBER,INWINDOW SDO_NUMBER_ARRAY,STORAGEPARAM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETBITMAPMASKSUBSET(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER,PYRAMIDLEVEL NUMBER,INWINDOW SDO_GEOMETRY,STORAGEPARAM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBITMAPMASKVALUE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER,PYRAMIDLEVEL NUMBER,ROWNUMBER NUMBER,COLNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBITMAPMASKVALUE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER,PYRAMIDLEVEL NUMBER,PTGEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBLANKCELLVALUE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBLOCKINGTYPE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETBLOCKSIZE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCELLCOORDINATE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,MODELCOORDINATE SDO_GEOMETRY,SUBCELL VARCHAR,HEIGHT NUMBER,VERT_ID NUMBER,ELLIPSOIDAL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETCELLCOORDINATE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,MODELCOORDINATE SDO_GEOMETRY,SUBCELL VARCHAR,HEIGHT NUMBER,VERT_ID NUMBER,ELLIPSOIDAL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCELLCOORDINATE(GEORASTER SDO_GEORASTER,SOURCEPYRAMIDLEVEL NUMBER,SOURCECELLCOORDINATE SDO_NUMBER_ARRAY,TARGETPYRAMIDLEVEL NUMBER,SUBCELL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCELLCOORDINATE(GEORASTER SDO_GEORASTER,SOURCEPYRAMIDLEVEL NUMBER,SOURCECELLCOORDINATE SDO_GEOMETRY,TARGETPYRAMIDLEVEL NUMBER,SUBCELL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCELLDEPTH(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCELLVALUE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,ROWNUMBER NUMBER,COLNUMBER NUMBER,BANDNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCELLVALUE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,PTGEOM SDO_GEOMETRY,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCELLVALUE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,ROWNUMBER NUMBER,COLNUMBER NUMBER,BANDS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCELLVALUE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,PTGEOM SDO_GEOMETRY,LAYERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCOLORMAP(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCOLORMAPTABLE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCOMPRESSIONTYPE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETCONTROLPOINT(INGEORASTER SDO_GEORASTER,CONTROLPOINTID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETDEFAULTALPHA(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETDEFAULTBLUE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETDEFAULTCOLORLAYER(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETDEFAULTGREEN(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETDEFAULTPYRAMIDLEVEL(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETDEFAULTRED(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETENDDATETIME(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETGCPGEOREFMETHOD(INGEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETGCPGEOREFMODEL(INGEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETGEOREFERENCETYPE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETGRAYSCALE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETGRAYSCALETABLE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETHISTOGRAM(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETHISTOGRAMTABLE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETID(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETINTERLEAVINGTYPE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETLAYERDIMENSION(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETLAYERID(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETLAYERORDINATE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETMODELCOORDINATE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,CELLCOORDINATE SDO_NUMBER_ARRAY,HEIGHT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETMODELCOORDINATE(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,CELLCOORDINATE SDO_GEOMETRY,HEIGHT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GETMODELCOORDLOCATION(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETMODELSRID(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETNODATA(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETNODATA(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETPYRAMIDMAXLEVEL(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETPYRAMIDTYPE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETRASTERBLOCKLOCATOR(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,BANDBLOCKNUMBER NUMBER,ROWBLOCKNUMBER NUMBER,COLUMNBLOCKNUMBER NUMBER,ISBITMAPMASK VARCHAR,LOCK_FOR_WRITE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETRASTERBLOCKLOCATOR(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,ROWNUMBER NUMBER,COLNUMBER NUMBER,BANDNUMBER NUMBER,ISBITMAPMASK VARCHAR,LOCK_FOR_WRITE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETRASTERBLOCKLOCATOR(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,PTGEOM SDO_GEOMETRY,LAYERNUMBER NUMBER,ISBITMAPMASK VARCHAR,LOCK_FOR_WRITE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GETRASTERBLOCKS(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,WINDOW SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETRASTERBLOCKS(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,WINDOW SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETRASTERDATA(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GETRASTERRANGE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETRASTERSUBSET(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,WINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETRASTERSUBSET(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,INWINDOW SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETRASTERSUBSET(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,WINDOW SDO_GEOMETRY,LAYERNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.GETRASTERSUBSET(GEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,INWINDOW SDO_GEOMETRY,LAYERNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSCALING(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSOURCEINFO(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSPATIALDIMNUMBER(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSPATIALDIMSIZES(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSPATIALRESOLUTIONS(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSPECTRALRESOLUTION(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSPECTRALUNIT(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSRS(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETSTATISTICS(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETTOTALLAYERNUMBER(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETULTCOORDINATE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETVAT(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.GETVERSION(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.HASBITMAPMASK(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.HASGRAYSCALE(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.HASNODATAMASK(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.HASPSEUDOCOLOR(GEORASTER SDO_GEORASTER,LAYERNUMBER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.IMPORTFROM(STORAGEPARAM VARCHAR,R_SOURCEFORMAT VARCHAR,R_SOURCETYPE VARCHAR,R_SOURCENAME VARCHAR,H_SOURCEFORMAT VARCHAR,H_SOURCETYPE VARCHAR,H_SOURCENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.IMPORTFROM(STORAGEPARAM VARCHAR,R_SOURCEFORMAT VARCHAR,R_SOURCEBLOB BLOB,H_SOURCEFORMAT VARCHAR,H_SOURCECLOB CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.INIT(RASTERDATATABLE VARCHAR,RASTERID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.ISBLANK(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.ISLOSSLESS(GEOR SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.ISORTHORECTIFIED(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.ISRECTIFIED(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GEOR.ISSPATIALREFERENCED(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.MASK(INGEORASTER SDO_GEORASTER,BANDNUMBERS VARCHAR,MASK SDO_GEORASTER,STORAGEPARAM VARCHAR,ZEROMAPPING NUMBER,ONEMAPPING NUMBER,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.MERGELAYERS(SOURCEGEORASTER SDO_GEORASTER,SOURCELAYERNUMBERS VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.MERGELAYERS(SOURCE1GEORASTER SDO_GEORASTER,SOURCE1LAYERNUMBERS VARCHAR,SOURCE2GEORASTER SDO_GEORASTER,SOURCE2LAYERNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY,PYRAMIDLEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.MOSAIC(GEORASTERTABLENAME VARCHAR,GEORASTERCOLUMNNAME VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.MOSAIC(PYRAMIDLEVEL NUMBER,WINDOW SDO_GEOMETRY,LAYERNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.RECTIFY(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,ELEVATIONPARAM VARCHAR,DEM SDO_GEORASTER,OUTSRID NUMBER,OUTMODELCOORDLOC NUMBER,CROPAREA SDO_GEOMETRY,POLYGONCLIP VARCHAR,LAYERNUMBERS VARCHAR,OUTRESOLUTIONS SDO_NUMBER_ARRAY,RESOLUTIONUNIT VARCHAR,REFERENCEPOINT SDO_GEOMETRY,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.RECTIFY(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,ELEVATIONPARAM VARCHAR,DEM SDO_GEORASTER,OUTSRID NUMBER,OUTMODELCOORDLOC NUMBER,CROPAREA SDO_GEOMETRY,POLYGONCLIP VARCHAR,LAYERNUMBERS VARCHAR,OUTRESOLUTIONS SDO_NUMBER_ARRAY,RESOLUTIONUNIT VARCHAR,REFERENCEPOINT SDO_GEOMETRY,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.REPROJECT(INGEORASTER SDO_GEORASTER,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,OUTSRID NUMBER,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.REPROJECT(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,CROPAREA SDO_GEOMETRY,LAYERNUMBERS VARCHAR,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,OUTSRID NUMBER,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.REPROJECT(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,CROPAREA SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,OUTSRID NUMBER,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.REPROJECT(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,CROPAREA SDO_GEOMETRY,LAYERNUMBERS VARCHAR,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,OUTSRID NUMBER,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.REPROJECT(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,CROPAREA SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,OUTSRID NUMBER,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SCALE(SCALEPARAM VARCHAR,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SCALECOPY(INGEORASTER SDO_GEORASTER,SCALEPARAM VARCHAR,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SCALECOPY(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,SCALEPARAM VARCHAR,RESAMPLEPARAM VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.SCHEMAVALIDATE(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETBEGINDATETIME()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETBINFUNCTION(LAYERNUMBER NUMBER,BINFUNCTION SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETBINTABLE(LAYERNUMBER NUMBER,TABLENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETBITMAPMASK(LAYERNUMBER NUMBER,MASK SDO_GEORASTER,NODATAMASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETBLANKCELLVALUE(VALUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETCOLORMAP(LAYERNUMBER NUMBER,COLORMAP SDO_GEOR_COLORMAP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETCOLORMAPTABLE(LAYERNUMBER NUMBER,TABLENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETCONTROLPOINT(CONTROLPOINT SDO_GEOR_GCP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETDEFAULTALPHA(DEFAULTALPHA NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETDEFAULTBLUE(DEFAULTBLUE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETDEFAULTCOLORLAYER(DEFAULTRGB SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETDEFAULTGREEN(DEFAULTGREEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETDEFAULTPYRAMIDLEVEL(DEFAULTPYRAMIDLEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETDEFAULTRED(DEFAULTRED NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETENDDATETIME()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETGCPGEOREFMETHOD(GEOREFMETHOD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETGCPGEOREFMODEL(GCPGEOREFMODEL SDO_GEOR_GCPGEOREFTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETGRAYSCALE(LAYERNUMBER NUMBER,GRAYSCALE SDO_GEOR_GRAYSCALE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETGRAYSCALETABLE(LAYERNUMBER NUMBER,TABLENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETHISTOGRAMTABLE(LAYERNUMBER NUMBER,TABLENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETID(ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETLAYERID(LAYERNUMBER NUMBER,ID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETLAYERORDINATE(LAYERNUMBER NUMBER,ORDINATE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETMODELCOORDLOCATION(MODELCOORDLOC VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETMODELSRID(SRID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETNODATAMASK(LAYERNUMBER NUMBER,ISNODATAMASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETORTHORECTIFIED(ISORTHORECTIFIED VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETRASTERTYPE(RASTERTYPE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETRECTIFIED(ISRECTIFIED VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSCALING(LAYERNUMBER NUMBER,SCALINGFUNC SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSOURCEINFO(SOURCEINFO VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSPATIALREFERENCED(ISREFERENCED VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSPATIALRESOLUTIONS(RESOLUTIONS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSPECTRALRESOLUTION(RESOLUTION NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSPECTRALUNIT(UNIT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSRS(SRS SDO_GEOR_SRS)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSTATISTICS(LAYERNUMBER NUMBER,STATISTICS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSTATISTICS(LAYERNUMBER NUMBER,STATISTICS SDO_NUMBER_ARRAY,HISTOGRAM SDO_GEOR_HISTOGRAM,SAMPLINGFACTOR NUMBER,SAMPLINGWINDOW SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETSTATISTICS(LAYERNUMBER NUMBER,STATISTICS SDO_NUMBER_ARRAY,HISTOGRAMTABLE VARCHAR,SAMPLINGFACTOR NUMBER,SAMPLINGWINDOW SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETULTCOORDINATE(ULTCOORD SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETVAT(LAYERNUMBER NUMBER,VATNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SETVERSION(MAJORVERSION VARCHAR,MINORVERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SUBSET(INGEORASTER SDO_GEORASTER,CROPAREA SDO_GEOMETRY,LAYERNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SUBSET(INGEORASTER SDO_GEORASTER,CROPAREA SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SUBSET(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,CROPAREA SDO_GEOMETRY,LAYERNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY,POLYGONCLIP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.SUBSET(INGEORASTER SDO_GEORASTER,PYRAMIDLEVEL NUMBER,CROPAREA SDO_NUMBER_ARRAY,BANDNUMBERS VARCHAR,STORAGEPARAM VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.UPDATERASTER(TARGETPYRAMIDLEVEL NUMBER,TARGETLAYERNUMBERS VARCHAR,TARGETAREA SDO_GEOMETRY,SOURCEGEORASTER SDO_GEORASTER,SOURCEPYRAMIDLEVEL NUMBER,SOURCELAYERNUMBERS VARCHAR,UPDATEUPPERPYRAMIDS VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GEOR.UPDATERASTER(TARGETPYRAMIDLEVEL NUMBER,TARGETBANDNUMBERS VARCHAR,TARGETAREA SDO_NUMBER_ARRAY,SOURCEGEORASTER SDO_GEORASTER,SOURCEPYRAMIDLEVEL NUMBER,SOURCEBANDNUMBERS VARCHAR,UPDATEUPPERPYRAMIDS VARCHAR,BGVALUES SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.VALIDATEBLOCKMBR(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GEOR.VALIDATEFORMOSAIC(GEORASTERTABLENAME VARCHAR,GEORASTERCOLUMNNAME VARCHAR,RESULTTABLENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GEOR.VALIDATEGEORASTER(GEORASTER SDO_GEORASTER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

