CREATE SCHEMA SDO_NET;

CREATE OR REPLACE PROCEDURE SDO_NET.ADD_CHILD_FEATURE(PARENT_LAYER_ID NUMBER,PARENT_FEATURE_ID NUMBER,CHILD_LAYER_ID NUMBER,CHILD_FEATURE_ID NUMBER,SEQUENCE_NUMBER NUMBER,CHECK_INTEGRITY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.ADD_CHILD_FEATURES(PARENT_LAYER_ID NUMBER,PARENT_FEATURE_ID NUMBER,CHILD_FEATURE_IDS SDO_NET_LAYER_FEAT_ARRAY,CHECK_INTEGRITY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.ADD_FEATURE(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER,FEATURE_ELEMENTS SDO_NET_FEAT_ELEM_ARRAY,CHILD_FEATURE_IDS SDO_NET_LAYER_FEAT_ARRAY,CHECK_INTEGRITY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.ADD_FEATURE_ELEMENT(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER,FEATURE_ELEMENT SDO_NET_FEAT_ELEM,SEQUENCE_NUMBER NUMBER,CHECK_INTEGRITY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.ADD_FEATURE_ELEMENTS(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER,FEATURE_ELEMENTS SDO_NET_FEAT_ELEM_ARRAY,CHECK_INTEGRITY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.ADD_FEATURE_LAYER(NETWORK_NAME VARCHAR,FEATURE_LAYER_NAME VARCHAR,FEATURE_LAYER_TYPE NUMBER,FEATURE_TABLE VARCHAR,RELATION_TABLE VARCHAR,HIERARCHY_TABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_NET.COMPUTE_PATH_GEOMETRY(NETWORK VARCHAR,PATH_ID NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_NET.COPY_NETWORK(SOURCE_NETWORK VARCHAR,TARGET_NETWORK VARCHAR,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_COMPONENT_TABLE(TABLE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_DELETE_TRIGGER(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_LINK_TABLE(TABLE_NAME VARCHAR,GEOM_TYPE VARCHAR,GEOM_COLUMN VARCHAR,COST_COLUMN VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,ADD_BIDIRECTED_COLUMN BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_LOGICAL_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_COST_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,SUBPATH_TABLE_NAME VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_LOGICAL_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_COST_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_LOGICAL_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_WITH_COST BOOLEAN,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_LRS_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_COST_COLUMN VARCHAR,LRS_TABLE_NAME VARCHAR,LRS_GEOM_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,SUBPATH_TABLE_NAME VARCHAR,SUBPATH_GEOM_COLUMN VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_LRS_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_COST_COLUMN VARCHAR,LRS_TABLE_NAME VARCHAR,LRS_GEOM_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_LRS_NETWORK(NETWORK VARCHAR,LRS_TABLE_NAME VARCHAR,LRS_GEOM_COLUMN VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_WITH_COST BOOLEAN,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_LRS_TABLE(TABLE_NAME VARCHAR,GEOM_COLUMN VARCHAR,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_NETWORK(NETWORK VARCHAR,GEOM_TYPE VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_GEOM_COLUMN VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_GEOM_COLUMN VARCHAR,LINK_COST_COLUMN VARCHAR,LRS_TABLE_NAME VARCHAR,LRS_GEOM_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,SUBPATH_TABLE_NAME VARCHAR,SUBPATH_GEOM_COLUMN VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_NETWORK(NETWORK VARCHAR,GEOM_TYPE VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_GEOM_COLUMN VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_GEOM_COLUMN VARCHAR,LINK_COST_COLUMN VARCHAR,LRS_TABLE_NAME VARCHAR,LRS_GEOM_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_NETWORK(NETWORK VARCHAR,GEOM_TYPE VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_WITH_COST BOOLEAN,LRS_TABLE_NAME VARCHAR,LRS_GEOM_COLUMN VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_NODE_TABLE(TABLE_NAME VARCHAR,GEOM_TYPE VARCHAR,GEOM_COLUMN VARCHAR,COST_COLUMN VARCHAR,PARTITION_COLUMN VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_NODE_TABLE(TABLE_NAME VARCHAR,GEOM_TYPE VARCHAR,GEOM_COLUMN VARCHAR,COST_COLUMN VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_PARTITION_BLOB_TABLE(TABLE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_PARTITION_TABLE(TABLE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_PATH_LINK_TABLE(TABLE_NAME VARCHAR,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_PATH_TABLE(TABLE_NAME VARCHAR,GEOM_COLUMN VARCHAR,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_REF_CONSTRAINTS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_SDO_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_GEOM_COLUMN VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_GEOM_COLUMN VARCHAR,LINK_COST_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,SUBPATH_TABLE_NAME VARCHAR,SUBPATH_GEOM_COLUMN VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_SDO_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_GEOM_COLUMN VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_GEOM_COLUMN VARCHAR,LINK_COST_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_SDO_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_WITH_COST BOOLEAN,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_SUBPATH_TABLE(TABLE_NAME VARCHAR,GEOM_COLUMN VARCHAR,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_TOPO_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_GEOM_COLUMN VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_GEOM_COLUMN VARCHAR,LINK_COST_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,SUBPATH_TABLE_NAME VARCHAR,SUBPATH_GEOM_COLUMN VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_TOPO_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_GEOM_COLUMN VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_GEOM_COLUMN VARCHAR,LINK_COST_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_TOPO_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_TABLE_NAME VARCHAR,NODE_COST_COLUMN VARCHAR,LINK_TABLE_NAME VARCHAR,LINK_COST_COLUMN VARCHAR,PATH_TABLE_NAME VARCHAR,PATH_GEOM_COLUMN VARCHAR,PATH_LINK_TABLE_NAME VARCHAR,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_TOPO_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_WITH_COST BOOLEAN,IS_COMPLEX BOOLEAN,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.CREATE_TOPO_NETWORK(NETWORK VARCHAR,NO_OF_HIERARCHY_LEVELS NUMBER,IS_DIRECTED BOOLEAN,NODE_WITH_COST BOOLEAN,IS_COMPLEX BOOLEAN,TOPOLOGY VARCHAR,STORAGE_PARAMETERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DB_SYNC_CLEAR(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DB_SYNC_DISABLE(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DB_SYNC_ENABLE(NETWORK VARCHAR,BASE_NODE_TABLE VARCHAR,BASE_LINK_TABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_NET.DB_SYNC_GET_UPDATE(NETWORK VARCHAR,LAST_GET_TIME TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.DB_SYNC_GET_UPDATE(NETWORK VARCHAR,LAST_GET_TIME TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_CHILD_FEATURES(PARENT_LAYER_ID NUMBER,PARENT_FEATURE_ID NUMBER,CHILD_FEATURE_IDS SDO_NET_LAYER_FEAT_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_CHILD_FEATURES_AT(PARENT_LAYER_ID NUMBER,PARENT_ID NUMBER,SEQUENCE_NUMBERS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_DANGLING_FEATURES(FEATURE_LAYER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_DANGLING_LINKS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_DANGLING_NODES(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_FEATURES(FEATURE_LAYER_ID NUMBER,FEATURE_IDS SDO_NUMBER_ARRAY,DELETE_NET_ELEMS BOOLEAN,DELETE_CHILDREN BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_FEATURE_ELEMENTS(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER,FEATURE_ELEMENTS SDO_NET_FEAT_ELEM_ARRAY,DELETE_NET_ELEMS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_FEATURE_ELEMENTS_AT(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER,SEQUENCE_NUMBERS SDO_NUMBER_ARRAY,DELETE_NET_ELEMS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_LINK(NETWORK VARCHAR,LINK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_NODE(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_PATH(NETWORK VARCHAR,PATH_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_PHANTOM_FEATURES(FEATURE_LAYER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DELETE_SUBPATH(NETWORK VARCHAR,SUBPATH_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DEREGISTER_CONSTRAINT(CONSTRAINT_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DEREGISTER_JAVA_OBJECT(NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DISABLE_REF_CONSTRAINTS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DROP_FEATURE_LAYER(NETWORK_NAME VARCHAR,FEATURE_LAYER_NAME VARCHAR,DROP_TABLES BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DROP_NETWORK(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.DROP_REF_CONSTRAINTS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.ENABLE_REF_CONSTRAINTS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.FIND_CONNECTED_COMPONENTS(NETWORK VARCHAR,LINK_LEVEL NUMBER,COMPONENT_TABLE_NAME VARCHAR,LOG_LOC VARCHAR,LOG_FILE VARCHAR,OPEN_MODE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.GENERATE_NODE_LEVELS(NETWORK VARCHAR,NODE_LEVEL_TABLE_NAME VARCHAR,OVERWRITE BOOLEAN,LOG_LOC VARCHAR,LOG_FILE VARCHAR,OPEN_MODE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.GENERATE_PARENT_LINK_TABLE(PARENT_NETWORK VARCHAR,COST_FUNCTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.GENERATE_PARTITION_BLOB(NETWORK VARCHAR,LINK_LEVEL NUMBER,PARTITION_ID NUMBER,INCLUDE_USER_DATA BOOLEAN,LOG_LOC VARCHAR,LOG_FILE VARCHAR,OPEN_MODE VARCHAR,PERFORM_DELTA_UPDATE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.GENERATE_PARTITION_BLOBS(NETWORK VARCHAR,LINK_LEVEL NUMBER,PARTITION_BLOB_TABLE_NAME VARCHAR,INCLUDE_USER_DATA BOOLEAN,COMMIT_FOR_EACH_BLOB BOOLEAN,LOG_LOC VARCHAR,LOG_FILE VARCHAR,OPEN_MODE VARCHAR,PERFORM_DELTA_UPDATE BOOLEAN,REGENERATE_NODE_LEVELS BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_NET.GET_BUFFER_COST(QUERY_PERCENTAGE NUMBER,INTERVAL_START_PERCENTAGE NUMBER,INTERVAL_END_PERCENTAGE NUMBER,INTERVAL_START_COST NUMBER,INTERVAL_END_COST NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_CHILD_FEATURE_IDS(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_CHILD_LINKS(NETWORK VARCHAR,LINK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_CHILD_NODES(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_DANGLING_FEATURES(FEATURE_LAYER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_DANGLING_LINKS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_DANGLING_NODES(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_FEATURES_ON_LINKS(FEATURE_LAYER_ID NUMBER,LINK_IDS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_FEATURES_ON_NODES(FEATURE_LAYER_ID NUMBER,NODE_IDS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_FEATURE_ELEMENTS(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_FEATURE_LAYER_ID(NETWORK_NAME VARCHAR,FEATURE_LAYER_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_GEOMETRY(NETWORK VARCHAR,LINK_ID NUMBER,START_PERCENTAGE NUMBER,END_PERCENTAGE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_GEOMETRY_TYPE(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_INVALID_LINKS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_INVALID_NODES(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_INVALID_PATHS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_IN_LINKS(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_ISOLATED_NODES(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LINKS_IN_CHILD_NETWORK(NETWORK VARCHAR,LINK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LINKS_IN_PATH(NETWORK VARCHAR,PATH_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LINK_COST_COLUMN(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LINK_DIRECTION(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LINK_GEOMETRY(NETWORK VARCHAR,LINK_ID NUMBER,START_PERCENTAGE NUMBER,END_PERCENTAGE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LINK_GEOM_COLUMN(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LINK_PARTITION_COLUMN(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LINK_TABLE_NAME(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LOGGING_LEVEL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LRS_LINK_GEOMETRY(NETWORK VARCHAR,LINK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LRS_NODE_GEOMETRY(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_LRS_TABLE_NAME(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NETWORK_CATEGORY(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NETWORK_ID(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NETWORK_NAME(NETWORK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NETWORK_NAME(NETWORK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NETWORK_OWNER(NETWORK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NETWORK_TYPE(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODES_IN_CHILD_NETWORK(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODES_IN_PATH(NETWORK VARCHAR,PATH_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_COST_COLUMN(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_DEGREE(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_GEOMETRY(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_GEOM_COLUMN(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_HIERARCHY_LEVEL(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_IN_DEGREE(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_OUT_DEGREE(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_PARTITION_COLUMN(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NODE_TABLE_NAME(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NO_OF_HIERARCHY_LEVELS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NO_OF_LINKS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NO_OF_LINKS(NETWORK VARCHAR,HIERARCHY_LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NO_OF_LINKS_IN_PATH(NETWORK VARCHAR,PATH_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NO_OF_NODES(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NO_OF_NODES(NETWORK VARCHAR,HIERARCHY_LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NO_OF_NODES_IN_PATH(NETWORK VARCHAR,PATH_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_NO_OF_PARTITIONS(NETWORK VARCHAR,LINK_LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_OUT_LINKS(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PARENT_FEATURE_IDS(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PARTITION_BLOB_TABLE_NAME(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PARTITION_SIZE(NETWORK VARCHAR,PARTITION_ID NUMBER,LINK_LEVEL NUMBER,INCLUDE_USER_DATA VARCHAR,INCLUDE_SPATIAL_DATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PARTITION_TABLE_NAME(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PATH_GEOM_COLUMN(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PATH_LINK_TABLE_NAME(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PATH_TABLE_NAME(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PERCENTAGE(NETWORK VARCHAR,LINK_ID NUMBER,PT_GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PHANTOM_FEATURES(FEATURE_LAYER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PT(NETWORK VARCHAR,LINK_ID NUMBER,PERCENTAGE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_PT_GEOM_ORD(GEOMETRY SDO_GEOMETRY,IDX NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_SUBPATH_GEOM_COLUMN(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_SUBPATH_TABLE_NAME(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_TOPOLOGY(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_TOPO_LINK_GEOMETRY(NETWORK VARCHAR,LINK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_TOPO_NODE_GEOMETRY(NETWORK VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.GET_USER_DEFINED_DATA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_NET.INSERT_GEOM_METADATA(GEOM_TABLE_NAME VARCHAR,GEOM_COLUMN_NAME VARCHAR,DIMINFO SDO_DIM_ARRAY,SRID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.INSERT_GEOM_METADATA(NETWORK VARCHAR,DIMINFO SDO_DIM_ARRAY,SRID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.INSERT_PATH_LINK_INFO(NETWORK VARCHAR,PATH_ID NUMBER,LINKS SDO_NUMBER_ARRAY,IS_SIMPLE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_NET.IS_COMPLEX(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_COVERED_BY_LINK_INTERVAL(QUERY_PERCENTAGE NUMBER,INTERVAL_START_PERCENTAGE NUMBER,INTERVAL_END_PERCENTAGE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_GEODETIC(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_HIERARCHICAL(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_LINK_IN_PATH(NETWORK VARCHAR,PATH_ID NUMBER,LINK_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_LOGICAL(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_NODE_IN_PATH(NETWORK VARCHAR,PATH_ID NUMBER,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_SIMPLE(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_SIMPLE(NETWORK VARCHAR,PATH_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.IS_SPATIAL(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_NET.LOAD_CONFIG(FILE_DIRECTORY VARCHAR,FILE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.LOGICAL_PARTITION(NETWORK VARCHAR,PARTITION_TABLE_NAME VARCHAR,MAX_NUM_NODES NUMBER,LOG_LOC VARCHAR,LOG_FILE VARCHAR,OPEN_MODE VARCHAR,LINK_LEVEL NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.LOGICAL_PARTITION(NETWORK VARCHAR,PARTITION_TABLE_NAME VARCHAR,MAX_NUM_NODES NUMBER,LOG_LOC VARCHAR,LOG_FILE VARCHAR,OPEN_MODE VARCHAR,LINK_LEVEL NUMBER(38),PART_SIZE_TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.LOGICAL_POWERLAW_PARTITION(NETWORK VARCHAR,PARTITION_TABLE_NAME VARCHAR,MAX_NUM_NODES NUMBER,LOG_LOC VARCHAR,LOG_FILE VARCHAR,OPEN_MODE VARCHAR,LINK_LEVEL NUMBER(38),PART_SIZE_TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_NET.LRS_GEOMETRY_NETWORK(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.NETWORK_EXISTS(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.POST_XML(URL VARCHAR,REQUEST XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_NET.REGISTER_CONSTRAINT(CONSTRAINT_NAME VARCHAR,CLASS_NAME VARCHAR,DIRECTORY_NAME VARCHAR,DESCRIPTION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.REGISTER_JAVA_OBJECT(NAME VARCHAR,CLASS_NAME VARCHAR,DIRECTORY_NAME VARCHAR,DESCRIPTION VARCHAR,JAVA_INTERFACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_NET.SDO_GEOMETRY_NETWORK(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_NET.SET_LOGGING_LEVEL(LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.SET_MAX_JAVA_HEAP_SIZE(BYTES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.SPATIAL_PARTITION(NETWORK VARCHAR,PARTITION_TABLE_NAME VARCHAR,MAX_NUM_NODES NUMBER,LOG_LOC VARCHAR,LOG_FILE VARCHAR,OPEN_MODE VARCHAR,LINK_LEVEL NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.SWITCH_TO_LOGICAL_NETWORK(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.SWITCH_TO_SPATIAL_NETWORK(NETWORK VARCHAR,NODE_GEOM_COL VARCHAR,LINK_GEOM_COL VARCHAR,PATH_GEOM_COL VARCHAR,SUBPATH_GEOM_COL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_NET.TOPO_GEOMETRY_NETWORK(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_NET.UPDATE_CONSISTENCY(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.UPDATE_FEATURE(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER,FEATURE_ELEMENTS SDO_NET_FEAT_ELEM_ARRAY,CHILD_FEATURE_IDS SDO_NET_LAYER_FEAT_ARRAY,CHECK_INTEGRITY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_NET.UPDATE_FEATURE_ELEMENT(FEATURE_LAYER_ID NUMBER,FEATURE_ID NUMBER,SEQUENCE_NUMBER NUMBER,FEATURE_ELEMENT SDO_NET_FEAT_ELEM,CHECK_INTEGRITY BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_COMPONENT_SCHEMA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_CONSISTENCY(NETWORK VARCHAR,IS_FAST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_LINK_SCHEMA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_LRS_SCHEMA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_NETWORK(NETWORK VARCHAR,CHECK_DATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_NODE_SCHEMA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_PARTITION_BLOB_SCHEMA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_PARTITION_INFO(NETWORK VARCHAR,CHECK_DATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_PARTITION_SCHEMA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_PATH_SCHEMA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_NET.VALIDATE_SUBPATH_SCHEMA(NETWORK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

