CREATE SCHEMA SDO_LRS;

CREATE OR REPLACE FUNCTION SDO_LRS.CLIP_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CLIP_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CLIP_GEOM_SEGMENT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CLIP_GEOM_SEGMENT_3D(GEOM_SEGMENT SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONCATENATE_GEOM_SEGMENTS(GEOM_SEGMENT_1 SDO_GEOMETRY,DIM_ARRAY_1 SDO_DIM_ARRAY,GEOM_SEGMENT_2 SDO_GEOMETRY,DIM_ARRAY_2 SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONCATENATE_GEOM_SEGMENTS(GEOM_SEGMENT_1 SDO_GEOMETRY,GEOM_SEGMENT_2 SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONCATENATE_GEOM_SEGMENTS_3D(GEOM_SEGMENT_1 SDO_GEOMETRY,DIM_ARRAY_1 SDO_DIM_ARRAY,GEOM_SEGMENT_2 SDO_GEOMETRY,DIM_ARRAY_2 SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONCATENATE_GEOM_SEGMENTS_3D(GEOM_SEGMENT_1 SDO_GEOMETRY,GEOM_SEGMENT_2 SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONNECTED_GEOM_SEGMENTS(GEOM_SEGMENT_1 SDO_GEOMETRY,DIM_ARRAY_1 SDO_DIM_ARRAY,GEOM_SEGMENT_2 SDO_GEOMETRY,DIM_ARRAY_2 SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONNECTED_GEOM_SEGMENTS(GEOM_SEGMENT_1 SDO_GEOMETRY,GEOM_SEGMENT_2 SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONNECTED_GEOM_SEGMENTS_3D(GEOM_SEGMENT_1 SDO_GEOMETRY,DIM_ARRAY_1 SDO_DIM_ARRAY,GEOM_SEGMENT_2 SDO_GEOMETRY,DIM_ARRAY_2 SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONNECTED_GEOM_SEGMENTS_3D(GEOM_SEGMENT_1 SDO_GEOMETRY,GEOM_SEGMENT_2 SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_DIM_ARRAY(DIM_ARRAY SDO_DIM_ARRAY,DIM_NAME VARCHAR,DIM_POS NUMBER(38),LOWER_BOUND NUMBER,UPPER_BOUND NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_DIM_ARRAY(DIM_ARRAY SDO_DIM_ARRAY,DIM_NAME VARCHAR,LOWER_BOUND NUMBER,UPPER_BOUND NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_DIM_ARRAY(DIM_ARRAY SDO_DIM_ARRAY,LOWER_BOUND NUMBER,UPPER_BOUND NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_DIM_ARRAY_3D(DIM_ARRAY SDO_DIM_ARRAY,DIM_NAME VARCHAR,LOWER_BOUND NUMBER,UPPER_BOUND NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM(STANDARD_GEOM SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,M_POS NUMBER(38),START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM(STANDARD_GEOM SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,M_POS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM(STANDARD_GEOM SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM(STANDARD_GEOM SDO_GEOMETRY,M_POS NUMBER(38),START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM(STANDARD_GEOM SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM(STANDARD_GEOM SDO_GEOMETRY,M_POS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM(STANDARD_GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM_3D(STANDARD_GEOM SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_GEOM_3D(STANDARD_GEOM SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_LAYER(TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,LOWER_BOUND NUMBER,UPPER_BOUND NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_LAYER(TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,DIM_NAME VARCHAR,DIM_POS NUMBER(38),LOWER_BOUND NUMBER,UPPER_BOUND NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_LAYER_3D(TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,LOWER_BOUND NUMBER,UPPER_BOUND NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_LRS_LAYER_3D(TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,DIM_NAME VARCHAR,LOWER_BOUND NUMBER,UPPER_BOUND NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_DIM_ARRAY(DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_DIM_ARRAY(DIM_ARRAY SDO_DIM_ARRAY,M_POS NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_DIM_ARRAY_3D(DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_GEOM(LRS_GEOM SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_GEOM(LRS_GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_GEOM_3D(LRS_GEOM SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_GEOM_3D(LRS_GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_LAYER(TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.CONVERT_TO_STD_LAYER_3D(TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_LRS.DEFINE_GEOM_SEGMENT(DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.DEFINE_GEOM_SEGMENT(DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.DEFINE_GEOM_SEGMENT(START_MEASURE NUMBER,END_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.DEFINE_GEOM_SEGMENT(TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.DEFINE_GEOM_SEGMENT_3D(DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.DEFINE_GEOM_SEGMENT_3D(DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.DEFINE_GEOM_SEGMENT_3D(START_MEASURE NUMBER,END_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.DEFINE_GEOM_SEGMENT_3D(TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_LRS.DYNAMIC_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.DYNAMIC_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.DYNAMIC_SEGMENT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.DYNAMIC_SEGMENT_3D(GEOM_SEGMENT SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.FIND_LRS_DIM_POS(TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.FIND_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,POINT_DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.FIND_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.FIND_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,POINT_DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.FIND_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.FIND_OFFSET(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,POINT_DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.FIND_OFFSET(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_END_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_END_MEASURE(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_END_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_END_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_END_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_END_PT(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_END_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_END_PT_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_LENGTH(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_LENGTH(GEOM_SEGMENT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_LENGTH_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_LENGTH_3D(GEOM_SEGMENT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_START_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_START_MEASURE(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_START_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_START_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_START_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_START_PT(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_START_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GEOM_SEGMENT_START_PT_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_MEASURE(POINT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_MEASURE(POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_MEASURE_3D(POINT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_MEASURE_3D(POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_NEXT_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.GET_PREV_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_GEOM_SEGMENT_DEFINED(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_GEOM_SEGMENT_DEFINED(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_GEOM_SEGMENT_DEFINED_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_GEOM_SEGMENT_DEFINED_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_MEASURE_DECREASING(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_MEASURE_DECREASING(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_MEASURE_DECREASING_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_MEASURE_DECREASING_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_MEASURE_INCREASING(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_MEASURE_INCREASING(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_MEASURE_INCREASING_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_MEASURE_INCREASING_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_SHAPE_PT_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.IS_SHAPE_PT_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.LOCATE_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER,OFFSET NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.LOCATE_PT(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER,OFFSET NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.LOCATE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.LOCATE_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.LRS_INTERSECTION(GEOM_1 SDO_GEOMETRY,DIM_ARRAY_1 SDO_DIM_ARRAY,GEOM_2 SDO_GEOMETRY,DIM_ARRAY_2 SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.LRS_INTERSECTION(GEOM_1 SDO_GEOMETRY,GEOM_2 SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.MEASURE_RANGE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.MEASURE_RANGE(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.MEASURE_RANGE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.MEASURE_RANGE_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.MEASURE_TO_PERCENTAGE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.MEASURE_TO_PERCENTAGE(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.OFFSET_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER,OFFSET NUMBER,UNIT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.OFFSET_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER,OFFSET NUMBER,TOLERANCE NUMBER,UNIT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.OFFSET_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER,OFFSET NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.OFFSET_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER,OFFSET NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.OFFSET_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER,OFFSET NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PERCENTAGE_TO_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,PERCENTAGE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PERCENTAGE_TO_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,PERCENTAGE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,POINT_DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,POINT_DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,POINT_DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,POINT_DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.PROJECT_PT_3D(GEOM_SEGMENT SDO_GEOMETRY,POINT SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_LRS.REDEFINE_GEOM_SEGMENT(DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.REDEFINE_GEOM_SEGMENT(DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.REDEFINE_GEOM_SEGMENT(START_MEASURE NUMBER,END_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.REDEFINE_GEOM_SEGMENT(TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.REDEFINE_GEOM_SEGMENT_3D(DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.REDEFINE_GEOM_SEGMENT_3D(DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.REDEFINE_GEOM_SEGMENT_3D(START_MEASURE NUMBER,END_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.REDEFINE_GEOM_SEGMENT_3D(TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.RESET_MEASURE(DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.RESET_MEASURE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_LRS.REVERSE_GEOMETRY(GEOM SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.REVERSE_GEOMETRY(GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.REVERSE_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.REVERSE_MEASURE(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.REVERSE_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.REVERSE_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.SCALE_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,START_MEASURE NUMBER,END_MEASURE NUMBER,SHIFT_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.SCALE_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,START_MEASURE NUMBER,END_MEASURE NUMBER,SHIFT_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.SET_PT_MEASURE(DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,PT_DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.SET_PT_MEASURE(DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.SET_PT_MEASURE(MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.SET_PT_MEASURE(POINT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.SET_PT_MEASURE_3D(DIM_ARRAY SDO_DIM_ARRAY,POINT SDO_GEOMETRY,PT_DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.SET_PT_MEASURE_3D(POINT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_LRS.SPLIT_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,SPLIT_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.SPLIT_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,SPLIT_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.SPLIT_GEOM_SEGMENT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,SPLIT_MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_LRS.SPLIT_GEOM_SEGMENT_3D(GEOM_SEGMENT SDO_GEOMETRY,SPLIT_MEASURE NUMBER,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_LRS.TRANSLATE_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,TRANSLATE_M NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.TRANSLATE_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,TRANSLATE_M NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.TRANSLATE_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,TRANSLATE_M NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.TRANSLATE_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,TRANSLATE_M NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALIDATE_LRS_GEOMETRY(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALIDATE_LRS_GEOMETRY(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALIDATE_LRS_GEOMETRY_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALIDATE_LRS_GEOMETRY_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_GEOM_SEGMENT(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_GEOM_SEGMENT_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_GEOM_SEGMENT_3D(GEOM_SEGMENT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_LRS_PT(POINT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_LRS_PT(POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_LRS_PT_3D(POINT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_LRS_PT_3D(POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_MEASURE(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,DIM_ARRAY SDO_DIM_ARRAY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_LRS.VALID_MEASURE_3D(GEOM_SEGMENT SDO_GEOMETRY,MEASURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

