CREATE SCHEMA SDO_OLS;

CREATE OR REPLACE FUNCTION SDO_OLS.DETERMINE_CLASSIFICATION(OPENLS XMLTYPE,CLASSIFICATION_CRITERION VARCHAR,OPENLS_VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.EXTRACT(XML XMLTYPE,XPATH VARCHAR,NS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.EXTRACTVALUE(XML XMLTYPE,XPATH VARCHAR,NS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.GENERATE_ERROR(OPENLS_VERSION VARCHAR,MESSAGE VARCHAR,REQUESTID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.GENERATE_ERROR(OPENLS_VERSION VARCHAR,REQUESTID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.GETBASISXML(NODE_NAME VARCHAR,OPENLS_VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.GETNS(NSSHORTCUT VARCHAR,OPENLSVERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.GETNS(OPENLSVERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_OLS.HANDLE_OPENLS_ERROR(SPECIFIC_ERROR_MESSAGE VARCHAR,SPECIFIC_ERROR_CODE NUMBER,DEFAULT_ERROR_MESSAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_OLS.MAKEOPENLS10REQUEST(REQUEST XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.MAKEOPENLSCLOBREQUEST(REQUEST CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.MAKEOPENLSREQUEST(REQUEST XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.MAKEOPENLSSOAPREQUEST(REQUEST XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_OLS.PARSE_COORD_PAIR(COORDS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_OLS.POSTCLOB(URL VARCHAR,PAYLOAD CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_OLS.POSTXML(URL VARCHAR,PAYLOAD XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

