CREATE SCHEMA SDO_UTIL;

CREATE OR REPLACE FUNCTION SDO_UTIL.AFFINETRANSFORMS(GEOMETRY SDO_GEOMETRY,TRANSLATION VARCHAR,TX NUMBER,TY NUMBER,TZ NUMBER,SCALING VARCHAR,PSC1 SDO_GEOMETRY,SX NUMBER,SY NUMBER,SZ NUMBER,ROTATION VARCHAR,P1 SDO_GEOMETRY,LINE1 SDO_GEOMETRY,ANGLE NUMBER,DIR NUMBER,SHEARING VARCHAR,SHXY NUMBER,SHYX NUMBER,SHXZ NUMBER,SHZX NUMBER,SHYZ NUMBER,SHZY NUMBER,REFLECTION VARCHAR,PREF SDO_GEOMETRY,LINER SDO_GEOMETRY,DIRR NUMBER,PLANER VARCHAR,N SDO_NUMBER_ARRAY,BIGD SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.APPEND(GEOMETRY1 SDO_GEOMETRY,GEOMETRY2 SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_UTIL.BEARING_TILT_FOR_POINTS(START_POINT SDO_GEOMETRY,END_POINT SDO_GEOMETRY,TOL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_UTIL.CIRCLE_POLYGON(POINT SDO_GEOMETRY,RADIUS NUMBER,ARC_TOLERANCE NUMBER,START_AZIMUTH NUMBER,END_AZIMUTH NUMBER,ORIENTATION NUMBER,ARC NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.CIRCLE_POLYGON(CENTER_LONGITUDE NUMBER,CENTER_LATITUDE NUMBER,RADIUS NUMBER,ARC_TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.CIRCLE_POLYGON(CENTER_LONGITUDE NUMBER,CENTER_LATITUDE NUMBER,RADIUS NUMBER,START_AZIMUTH NUMBER,END_AZIMUTH NUMBER,ARC_TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.CONCAT_LINES(GEOMETRY1 SDO_GEOMETRY,GEOMETRY2 SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.CONVERT3007TO3008(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.CONVERT_DISTANCE(SRID NUMBER,DISTANCE NUMBER,UNIT_SPEC VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.CONVERT_UNIT(VALUE NUMBER,IN_UNIT VARCHAR,OUT_UNIT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_UTIL.DROP_WORK_TABLES(OIDSTR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_UTIL.ELLIPSE_POLYGON(CENTER_LONGITUDE NUMBER,CENTER_LATITUDE NUMBER,SEMI_MAJOR_AXIS NUMBER,SEMI_MINOR_AXIS NUMBER,AZIMUTH NUMBER,ARC_TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.EXPAND_GEOM(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.EXPAND_MULTI_POINT(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.EXTRACT(GEOMETRY SDO_GEOMETRY,ELEMENT NUMBER,RING NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.EXTRACT3D(GEOMETRY SDO_GEOMETRY,LABEL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.EXTRACTVOIDS(GEOMETRY SDO_GEOMETRY,DIM SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.EXTRACT_ALL(GEOMETRY SDO_GEOMETRY,FLATTEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.EXTRUDE(GEOMETRY SDO_GEOMETRY,GRDHEIGHT SDO_NUMBER_ARRAY,HEIGHT SDO_NUMBER_ARRAY,COND VARCHAR,TOL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.EXTRUDE(GEOMETRY SDO_GEOMETRY,GRDHEIGHT SDO_NUMBER_ARRAY,HEIGHT SDO_NUMBER_ARRAY,TOL NUMBER,OPTIONAL3DSRID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_CLOB(CLOBGEOM CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GML311GEOMETRY(GEOMETRY CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GML311GEOMETRY(GEOMETRY CLOB,SRSNAMESPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GML311GEOMETRY(GEOMETRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GML311GEOMETRY(GEOMETRY VARCHAR,SRSNAMESPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GML311GEOMETRY(GEOMETRY CLOB,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GML311GEOMETRY(GEOMETRY CLOB,SRSNAMESPACE VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GML311GEOMETRY(GEOMETRY VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GML311GEOMETRY(GEOMETRY VARCHAR,SRSNAMESPACE VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GMLGEOMETRY(GEOMETRY CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GMLGEOMETRY(GEOMETRY CLOB,SRSNAMESPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GMLGEOMETRY(GEOMETRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GMLGEOMETRY(GEOMETRY VARCHAR,SRSNAMESPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GMLGEOMETRY(GEOMETRY CLOB,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GMLGEOMETRY(GEOMETRY CLOB,SRSNAMESPACE VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GMLGEOMETRY(GEOMETRY VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_GMLGEOMETRY(GEOMETRY VARCHAR,SRSNAMESPACE VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_KMLGEOMETRY(GEOMETRY CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_KMLGEOMETRY(GEOMETRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_WKBGEOMETRY(GEOMETRY BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_WKTGEOMETRY(GEOMETRY CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.FROM_WKTGEOMETRY(GEOMETRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.GETLABELBYELEMENT(SOURCEGEOMETRY SDO_GEOMETRY,QUERYELEMENT SDO_GEOMETRY,TOL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.GETNUMELEM(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.GETNUMRINGS(GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.GETNUMVERTICES(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.GETNURBSAPPROX(GEOMETRY SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.GETVERTICES(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.GET_2D_FOOTPRINT(GEOMETRY SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.GET_BOUNDARY(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.HYBRID_TILES(GEOM SDO_GEOMETRY,SDO_LEVEL NUMBER,SDO_NTILES NUMBER,TOL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_UTIL.INITIALIZE_INDEXES_FOR_TTS(TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,DIMINFO SDO_DIM_ARRAY,SRID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_UTIL.INTERIOR_POINT(GEOM SDO_GEOMETRY,TOL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.INTERNAL_MAKE_LINE_OUT_OF_ELEM(MULTILINESTRING SDO_GEOMETRY,ELEMENT_INDEX NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.INTERNAL_MERGE_LINESTRINGS(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.INTERNAL_MERGE_LINESTRINGS(GEOMARR SDO_GEOMETRY_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_UTIL.INTERNAL_ORDINATE_COPY(SRC SDO_ORDINATE_ARRAY,SRC_POSITION NUMBER(38),DST_POSITION NUMBER(38),LENGTH NUMBER(38))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_UTIL.INTERNAL_REVERSE_LINE_POINTS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_UTIL.JSPH_GETNURBSAPPROX(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.LINEAR_KEY(GEOMETRY SDO_GEOMETRY,DIMINFO SDO_DIM_ARRAY,LVL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.LINEAR_KEY(GEOMETRY SDO_GEOMETRY,MIN_X NUMBER,MIN_Y NUMBER,MAX_X NUMBER,MAX_Y NUMBER,LVL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.MDUTL_IS_NUMERIC(INSTR VARCHAR,FORMAT_MASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.NUMBER_OF_COMPONENTS(GEOMETRY SDO_GEOMETRY,REQUESTED_TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.NUMBER_TO_CHAR(VALUE NUMBER,FORMAT_MASK VARCHAR,NLS_LANGUAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.NUMBER_TO_CHAR(VALUE VARCHAR,FORMAT_MASK VARCHAR,NLS_LANGUAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.NUMBER_TO_CHAR(VALUE DATE,FORMAT_MASK VARCHAR,OPTION_SETTING VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.NUMBER_TO_CHAR(VALUE TIMESTAMP,FORMAT_MASK VARCHAR,OPTION_SETTING VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.NUMBER_TO_CHAR(VALUE RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.NUMBER_TO_CHAR(VALUE CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.OUTERLN(GEOMETRY SDO_GEOMETRY,DIM SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_UTIL.PARTITION_TABLE(SCHEMANAME VARCHAR,TABLENAME VARCHAR,OUTPUT_DATA_TABLE VARCHAR,OUTPUT_PTN_TABLE VARCHAR,PTN_CAPACITY NUMBER,NUMDIM NUMBER,WRK_TBLSPC VARCHAR,PTN_TYPE VARCHAR,DOP NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_UTIL.POINT_AT_BEARING(START_POINT SDO_GEOMETRY,BEARING NUMBER,DISTANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.POINT_TO_LINE(GEOM1 SDO_GEOMETRY,GEOM2 SDO_GEOMETRY,TOL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.POLYGONTOLINE(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_UTIL.PREPARE_FOR_TTS(TABLE_SPACE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_UTIL.QUAD_TILES(GEOM SDO_GEOMETRY,SDO_LEVEL NUMBER,TOL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.RECTIFY_GEOMETRY(GEOMETRY SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.REFINEMGON(MGON SDO_GEOMETRY,GON SDO_GEOMETRY,DIM SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.REMOVE_DUPLICATES(GEOMETRY SDO_GEOMETRY,DIM SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.REMOVE_DUPLICATE_VERTICES(GEOMETRY SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.REMOVE_INNER_RINGS(INPGEOM SDO_GEOMETRY,INPTOL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.REVERSE_LINESTRING(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.SIMPLIFY(GEOMETRY SDO_GEOMETRY,THRESHOLD NUMBER,TOLERANCE NUMBER,REMOVE_LOOPS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.SIMPLIFYVW(GEOMETRY SDO_GEOMETRY,VERTEX_THRESHOLD NUMBER,TOLERANCE NUMBER,REMOVE_LOOPS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.THEME3D_GET_BLOCK_TABLE(THEME_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.THEME3D_HAS_LOD(THEME_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.THEME3D_HAS_TEXTURE(THEME_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TOGNOMONIC(GEOM SDO_GEOMETRY,LONGITUDE NUMBER,LATITUDE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_CLOB(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GML311GEOMETRY(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GML311GEOMETRY(GEOMETRY SDO_GEOMETRY,SRSNAMESPACE VARCHAR,SRSNSALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GML311GEOMETRY(GEOMETRY SDO_GEOMETRY,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GML311GEOMETRY(GEOMETRY SDO_GEOMETRY,SRSNAMESPACE VARCHAR,SRSNSALIAS VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GML321GEOMETRY(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GML321GEOMETRY(GEOMETRY SDO_GEOMETRY,SRSNAMESPACE VARCHAR,SRSNSALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GML321GEOMETRY(GEOMETRY SDO_GEOMETRY,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GML321GEOMETRY(GEOMETRY SDO_GEOMETRY,SRSNAMESPACE VARCHAR,SRSNSALIAS VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GMLGEOMETRY(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GMLGEOMETRY(GEOMETRY SDO_GEOMETRY,SRSNAMESPACE VARCHAR,SRSNSALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GMLGEOMETRY(GEOMETRY SDO_GEOMETRY,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_GMLGEOMETRY(GEOMETRY SDO_GEOMETRY,SRSNAMESPACE VARCHAR,SRSNSALIAS VARCHAR,COORDORDER NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_KMLGEOMETRY(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_WKBGEOMETRY(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_WKTGEOMETRY(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TO_WKTGEOMETRY_VARCHAR(GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.TRUNCATE_NUMBER(VALUE NUMBER,NO_OF_DIGITS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.VALIDATE_3DTHEME(THEME_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.VALIDATE_SCENE(SCENE_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.VALIDATE_VIEWFRAME(VIEWFRAME_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.VALIDATE_WKBGEOMETRY(GEOMETRY BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.VALIDATE_WKTGEOMETRY(GEOMETRY CLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_UTIL.VALIDATE_WKTGEOMETRY(GEOMETRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

