CREATE SCHEMA SDO_GCDR;

CREATE OR REPLACE FUNCTION SDO_GCDR.BATCH_GEOCODE(ADDRESS_LIST VARCHAR,GC_USERNAME VARCHAR,MAX_RESULT_COUNT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GCDR.CREATE_PROFILE_TABLES()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_GCDR.DATA_VERSION(ADDR_LINES SDO_KEYWORDARRAY,COUNTRY VARCHAR,MATCH_MODE VARCHAR,LOGGING NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.GEOCODE_ADDR(GC_USERNAME VARCHAR,ADDRESS SDO_GEO_ADDR,LOGGING NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.GEOCODE_ADDR_ALL(GC_USERNAME VARCHAR,ADDRESS SDO_GEO_ADDR,MAX_RES_NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.GEOCODE_ALL(GC_USERNAME VARCHAR,ADDR_LINES SDO_KEYWORDARRAY,COUNTRY VARCHAR,MATCH_MODE VARCHAR,MAX_RES_NUM NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.GEOCODE_AS_GEOMETRY(USERNAME VARCHAR,ADDR_LINES SDO_KEYWORDARRAY,COUNTRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.LIST_COUNTRIES(LONGITUDE NUMBER,LATITUDE NUMBER,COUNTRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.REVERSE_GEOCODE(USERNAME VARCHAR,LONGITUDE NUMBER,LATITUDE NUMBER,SRID NUMBER,COUNTRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.REVERSE_GEOCODE(USERNAME VARCHAR,LOCATION SDO_GEOMETRY,COUNTRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.REVERSE_GEOCODE(USERNAME VARCHAR,LONGITUDE NUMBER,LATITUDE NUMBER,LANGUAGE_ VARCHAR,COUNTRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.REVERSE_GEOCODE(USERNAME VARCHAR,LONGITUDE NUMBER,LATITUDE NUMBER,SRID NUMBER,LANGUAGE_ VARCHAR,COUNTRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_GCDR.REVERSE_GEOCODE(USERNAME VARCHAR,LOCATION SDO_GEOMETRY,LANGUAGE_ VARCHAR,COUNTRY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATECITYROW(COUNTRY VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATECOUNTRYROW(COUNTRY VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATEINLINESTREETTYPEROW(COUNTRY VARCHAR,POS VARCHAR,SEP VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATELOCALITYDICTROW(COUNTRY VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATEPLACENAMEROW(COUNTRY VARCHAR,OUT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATEPOBOXROW(COUNTRY VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATEREGIONROW(COUNTRY VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATESECONDUNITROW(COUNTRY VARCHAR,POS VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATESTREETDICTROW(COUNTRY VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATESTREETPREFIXROW(COUNTRY VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATESTREETSUFFIXROW(COUNTRY VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_GCDR.VALIDATESTREETTYPEROW(COUNTRY VARCHAR,POS VARCHAR,SEP VARCHAR,OUT VARCHAR,KEYS SDO_KEYWORDARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

