CREATE SCHEMA SDO_SAM;

CREATE OR REPLACE FUNCTION SDO_SAM.AGGREGATES_FOR_GEOMETRY(THEME_NAME VARCHAR,THEME_COLNAME VARCHAR,AGGR_TYPE_STRING VARCHAR,AGGR_COL_STRING VARCHAR,GEOM SDO_GEOMETRY,DST_SPEC VARCHAR,DST_OFFSET NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_SAM.AGGREGATES_FOR_LAYER(THEME_NAME VARCHAR,THEME_COLNAME VARCHAR,AGGR_TYPE_STRING VARCHAR,AGGR_COL_STRING VARCHAR,TABLENAME VARCHAR,COLNAME VARCHAR,DST_SPEC VARCHAR,DST_OFFSET NUMBER,ZERO_AGG_ROWS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_SAM.BIN_GEOMETRY(GEOM SDO_GEOMETRY,DIM SDO_DIM_ARRAY,BIN_TABLENAME VARCHAR,BIN_COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_SAM.BIN_GEOMETRY(GEOM SDO_GEOMETRY,TOL NUMBER,BIN_TABLENAME VARCHAR,BIN_COLNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_SAM.BIN_LAYER(TABLENAME VARCHAR,COLNAME VARCHAR,BIN_TABLENAME VARCHAR,BIN_COLNAME VARCHAR,BIN_ID_COLNAME VARCHAR,COMMIT_INTERVAL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_SAM.COLOCATED_REFERENCE_FEATURES(THEME_TABLENAME VARCHAR,THEME_COLNAME VARCHAR,THEME_PREDICATE VARCHAR,TABLENAME VARCHAR,COLNAME VARCHAR,REF_PREDICATE VARCHAR,DST_SPEC VARCHAR,RESULT_TABLENAME VARCHAR,COMMIT_INTERVAL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_SAM.INTERSECTION_RATIO(LOCATION SDO_GEOMETRY,THEMATIC_BOUNDARY SDO_GEOMETRY,DIM SDO_DIM_ARRAY,DIST NUMBER,UNITS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_SAM.PREDICATED_JOIN(TABLE_NAME1 VARCHAR,COLUMN_NAME1 VARCHAR,TABLE_NAME2 VARCHAR,COLUMN_NAME2 VARCHAR,TAB1_PREDICATE VARCHAR,TAB2_PREDICATE VARCHAR,DST_SPEC VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_SAM.SIMPLIFY_GEOMETRY(GEOM SDO_GEOMETRY,DIM SDO_DIM_ARRAY,PCT_AREA_CHANGE_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_SAM.SIMPLIFY_GEOMETRY(GEOM SDO_GEOMETRY,TOL NUMBER,PCT_AREA_CHANGE_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_SAM.SIMPLIFY_LAYER(THEME_TABLENAME VARCHAR,THEME_COLNAME VARCHAR,SMPL_GEOM_COLNAME VARCHAR,COMMIT_INTERVAL NUMBER,PCT_AREA_CHANGE_LIMIT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_SAM.SPATIAL_CLUSTERS(TABLENAME VARCHAR,COLNAME VARCHAR,MAX_CLUSTERS NUMBER,ALLOW_OUTLIERS VARCHAR,TABLEPARTITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_SAM.TILED_AGGREGATES(THEME_NAME VARCHAR,THEME_COLNAME VARCHAR,AGGR_TYPE_STRING VARCHAR,AGGR_COL_STRING VARCHAR,TILING_LEVEL NUMBER,TILING_DOMAIN SDO_DIM_ARRAY,ZERO_AGG_TILES NUMBER,XDIVS NUMBER,YDIVS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_SAM.TILED_BINS(L1 NUMBER,U1 NUMBER,L2 NUMBER,U2 NUMBER,TILING_LEVEL NUMBER,SRID NUMBER,XDIVS NUMBER,YDIVS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

