CREATE SCHEMA SDO_PC_PKG;

CREATE OR REPLACE PROCEDURE SDO_PC_PKG.ADD_TO_PC(INP SDO_PC,INPTABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_PC_PKG.CLIP_PC(INP SDO_PC,IND_DIM_QRY SDO_GEOMETRY,OTHER_DIM_QRY SDO_MBR,QRY_MIN_RES NUMBER,QRY_MAX_RES NUMBER,BLKNO NUMBER,INCLUDE_CUSTOM_DIMS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.CLIP_PC_FLAT(GEOMETRY SDO_GEOMETRY,TABLE_NAME VARCHAR,TOLERANCE NUMBER,OTHER_DIM_QRY SDO_MBR,MASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.CLIP_PC_FLAT_STRING(GEOMETRY SDO_GEOMETRY,TABLE_NAME VARCHAR,TOLERANCE NUMBER,OTHER_DIM_QRY SDO_MBR,MASK VARCHAR,DOP NUMBER(38),SDO_LEVEL NUMBER,SDO_NTILES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.CLIP_PC_INTO_TIN(PC_INP SDO_PC,PC_IND_DIM_QRY SDO_GEOMETRY,PC_OTHER_DIM_QRY SDO_MBR,PC_QRY_MIN_RES NUMBER,PC_QRY_MAX_RES NUMBER,TIN_BASETABLE VARCHAR,TIN_BASECOL VARCHAR,TIN_BLKTABLE VARCHAR,TIN_PTN_PARAMS VARCHAR,TIN_BREAK_LINES SDO_GEOMETRY,TIN_STOP_LINES SDO_GEOMETRY,TIN_VOID_RGNS SDO_GEOMETRY,TIN_CLSTPCDATATBL VARCHAR,PC_BLKNO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.CREATE_CONTOUR_GEOMETRIES(PC SDO_PC,SAMPLING_RESOLUTION NUMBER,ELEVATIONS SDO_ORDINATE_ARRAY,REGION SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.CREATE_CONTOUR_GEOMETRIES(PC_FLAT_TABLE VARCHAR,SRID NUMBER,SAMPLING_RESOLUTION NUMBER,ELEVATIONS SDO_ORDINATE_ARRAY,REGION SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_PC_PKG.CREATE_LIBLAS_PYRAMID(PC SDO_PC,KEEPLEVEL1INTACT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_PC_PKG.CREATE_PC(INP SDO_PC,INPTABLE VARCHAR,CLSTPCDATATBL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_PC_PKG.DROP_DEPENDENCIES(BASETABLE VARCHAR,COL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_PC_PKG.GETNTHHILBERTVALUE(TABLE_NAME VARCHAR,N NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.GET_BLOCKING_METHOD(INP SDO_PC)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.GET_PT_IDS(PTS BLOB,NUM_PTS NUMBER,PC_TOT_DIM NUMBER,BLK_DOMAIN SDO_ORGSCL_TYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_PC_PKG.GET_TILE_SQL(GEOMETRY SDO_GEOMETRY,TOLERANCE NUMBER,SDO_LEVEL NUMBER,SDO_NTILES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_PC_PKG.HAS_PYRAMID(INP SDO_PC)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.HILBERT_XY2D(N NUMBER,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_PC_PKG.IMPORT_LAS(SOURCE_LAS_FILE VARCHAR,SOURCE_LAS_FILE_ID VARCHAR,TARGET_TABLE VARCHAR,ADD_COLUMNS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_PC_PKG.INIT(BASETABLE VARCHAR,BASECOL VARCHAR,BLKTABLE VARCHAR,PTN_PARAMS VARCHAR,PC_EXTENT SDO_GEOMETRY,PC_TOL NUMBER,PC_TOT_DIMENSIONS NUMBER,PC_DOMAIN SDO_ORGSCL_TYPE,PC_VAL_ATTR_TABLES SDO_STRING_ARRAY,PC_OTHER_ATTRS XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.PRESERVES_LEVEL1(INP SDO_PC)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.TIN_TO_PC(TIN SDO_TIN,BASETABLE VARCHAR,BASECOL VARCHAR,BLKTABLE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_PC_PKG.TO_GEOMETRY(PTS BLOB,NUM_PTS NUMBER,PC_TOT_DIM NUMBER,SRID NUMBER,BLK_DOMAIN SDO_ORGSCL_TYPE,GET_IDS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

