CREATE SCHEMA SDO_WFS_LOCK;

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.DELETETOKENSESSIONMAP(TID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.ENABLEDBTXNS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_LOCK.GENERATETOKENID(TABLENAME VARCHAR,TABLEALIAS VARCHAR,EXPIRYTIME NUMBER,LOCKALL VARCHAR,PKEYCOLS STRINGLIST,AUTOCOMMIT VARCHAR,ROWSTOBELOCKED ROWPOINTERLIST,ORDERCLAUSE VARCHAR,INDEXCLAUSE VARCHAR,MAXCNT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.LOCKROWSBYID(PTOKENID VARCHAR,USERNAME VARCHAR,TABLENAME VARCHAR,TABLEALIAS VARCHAR,EXPIRYTIME NUMBER,LOCKALL VARCHAR,PKEYCOLS STRINGLIST,AUTOCOMMIT VARCHAR,ROWSTOBELOCKED ROWPOINTERLIST,ORDERCLAUSE VARCHAR,INDEXCLAUSE VARCHAR,MAXCNT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_LOCK.QUERYTOKENSESSIONMAP(TID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.REGISTERFEATURETABLE(USERNAME VARCHAR,TABLENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.RESETTOKENEXPIRY(TID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.TRANSFERTOKENBYID(PTOKENID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.UNLOCKROWSBYID(PTOKENID VARCHAR,USERNAME VARCHAR,TABLENAME VARCHAR,TABLEALIAS VARCHAR,PKEYCOLS STRINGLIST,AUTOCOMMIT VARCHAR,ROWSTOBEUNLOCKED ROWPOINTERLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.UNREGISTERFEATURETABLE(USERNAME VARCHAR,TABLENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_LOCK.UPDATETOKENSESSIONMAP(TID VARCHAR,SID VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

