CREATE SCHEMA SDO_TOPO;

CREATE OR REPLACE PROCEDURE SDO_TOPO.ADD_TOPO_GEOMETRY_LAYER(TOPOLOGY VARCHAR,TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,TOPO_GEOMETRY_LAYER_TYPE VARCHAR,RELATION_TABLE_STORAGE VARCHAR,CHILD_LAYER_ID NUMBER,LAYER_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO.ALIGN_EDGE_GEOMETRY(GEOMETRY1 SDO_GEOMETRY,GEOMETRY2 SDO_GEOMETRY,TOLERANCE NUMBER,DGTS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.ALIGN_LINEAR_GEOMETRY(GEOMETRY1 SDO_GEOMETRY,GEOMETRY2 SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.ALIGN_POINT_GEOMETRY(GEOMETRY1 SDO_GEOMETRY,GEOMETRY2 SDO_GEOMETRY,TOLERANCE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TOPO.CREATE_TOPOLOGY(TOPOLOGY VARCHAR,TOLERANCE NUMBER,SRID NUMBER,NODE_TABLE_STORAGE VARCHAR,EDGE_TABLE_STORAGE VARCHAR,FACE_TABLE_STORAGE VARCHAR,HISTORY_TABLE_STORAGE VARCHAR,DIGITS_RIGHT_OF_DECIMAL NUMBER,TOPOLOGY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO.DELETE_TOPO_GEOMETRY_LAYER(TOPOLOGY VARCHAR,TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO.DROP_TOPOLOGY(TOPOLOGY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO.GET_FACE_BOUNDARY(TOPOLOGY VARCHAR,FACE_ID NUMBER,ALL_EDGES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.GET_INTERACTING_TGIDS(BASE_LAYER_ID NUMBER,Q_FEATURE SDO_TOPO_GEOMETRY,MASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.GET_INTERACTING_TGIDS(TP_ID NUMBER,BASE_LAYER_ID NUMBER,TOPO_ELEM_ARRAY SDO_TOPO_OBJECT_ARRAY,MASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.GET_INTERNAL_GEOMETRY(GEOM SDO_GEOMETRY,NODEIDS SDO_NUMBER_ARRAY,DIM SDO_DIM_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.GET_TOPO_OBJECTS(TOPOLOGY VARCHAR,TOPO_GEOMETRY_LAYER_ID NUMBER,TOPO_GEOMETRY_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.GET_TOPO_OBJECTS(TOPOLOGY VARCHAR,GEOMETRY SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TOPO.INITIALIZE_AFTER_IMPORT(TOPOLOGY VARCHAR,TG_LAYER_OWNER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO.INITIALIZE_METADATA(TOPOLOGY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO.INTERNAL_GET_TGIDS(TOPOLOGY VARCHAR,GEOMETRY SDO_GEOMETRY,IN_TG_LAYER_ID NUMBER,OPERATOR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.INTERNAL_GET_TGIDS(TOPOLOGY VARCHAR,Q_TG_LAYER_ID NUMBER,Q_TG_ID NUMBER,IN_TG_LAYER_ID NUMBER,OPERATOR VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TOPO.LOCKROW_UNIVERSEFACE(TOPOLOGYID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO.PREPARE_FOR_EXPORT(TOPOLOGY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO.RELATE(GEOM1 SDO_TOPO_GEOMETRY,GEOM2 SDO_TOPO_GEOMETRY,MASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.RELATE(GEOM SDO_TOPO_GEOMETRY,TOPO_ELEM_ARRAY SDO_TOPO_OBJECT_ARRAY,MASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.RELATE(FEATURE1 SDO_TOPO_GEOMETRY,FEATURE2 SDO_GEOMETRY,MASK VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TOPO.SDO_TOPO_CRT_RLIDS_VIEW(TOPOLOGY VARCHAR,TOPO_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO.TG_INSERT_RELATION(TOPOLOGY VARCHAR,TG_LAYER_ID NUMBER,TOPO_IDS SDO_TOPO_OBJECT_ARRAY,GTYPE NUMBER,INPUT_TG_ID NUMBER,INPUT_TG_ATTRIBUTE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO.TG_INSERT_RELATION(TOPOLOGY VARCHAR,TG_LAYER_ID NUMBER,TOPO_IDS SDO_TGL_OBJECT_ARRAY,GTYPE NUMBER,INPUT_TG_ID NUMBER,INPUT_TG_ATTRIBUTE VARCHAR,CHILD_LID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

