CREATE SCHEMA SDO_WFS_PROCESS;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.CONTAINSSDO(NS VARCHAR,NAME VARCHAR,FTID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.CONTAINSSDOINTERNAL(ROOTNS VARCHAR,ROOTNAME VARCHAR,NS VARCHAR,NAME VARCHAR,FTID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.DELETECAPABILITIESINFO()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.DROPFEATURETYPE(FTNSURL VARCHAR,FTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.DROPFEATURETYPES(FTNSURL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.DROP_EXPORT_TABLES(NSPARAM VARCHAR,DATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.EXPANDPATH(ALIASEDPATH VARCHAR,NSPARAM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.EXTRACTID(XMLDATA XMLTYPE,IDPATHS STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.EXTRACTSDO(XMLDATA XMLTYPE,SPATIALPATHS STRINGLIST,SRSNS VARCHAR,ISGML3 VARCHAR,SPPATHSSRSNSLIST STRINGLISTLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.FINDNSURL(NSALIAS VARCHAR,NSALIASLIST STRINGLIST,NSURLLIST STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.GENCOLLECTIONPROCS(OBJNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GENERATEALIASSTRING(ALIASLIST STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GENERATEPARSEDSPATIALPATH(SPATIALPATHS STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GENIDVALUE(DATA XMLTYPE,IDPATHS STRINGLIST,TNS VARCHAR,TNAME VARCHAR,FTUSERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.GENRECORDTYPEPROCESSINGLOGIC(TNS VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GENSPATIALARRINFO(TABLENAMEPREFIX VARCHAR,PKVAL VARCHAR,L_SPATIALARRLIST STRINGLISTLIST,DATA XMLTYPE,SRSNS VARCHAR,SPATIALARRUPDMAP VARCHAR,ISGML3 VARCHAR,SPARRPATHSSRSNSLIST STRINGLISTLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GENSPATIALPATHELEMCOLINDEX(SPATIALPATHS STRINGLIST,SPATIALPATHELEM SDO_GEOM_PATH_ELEM)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.GENTRIGGERS(TNS VARCHAR,TNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.GENUPDATESTR(SPATIALCOLCOUNT NUMBER,UPDATE_PREFIX VARCHAR,UPDATE_SUFFIX VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GETALIAS(NSURL VARCHAR,ALIASLIST STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GETCOUNT(PATHPATTERN VARCHAR,NSPARAM VARCHAR,DATA XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GETFEATURETYPEID(FTNSURL VARCHAR,FTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GETPARSEDPATH(PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GETPATH(PATH STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GETUPDATEMAP(SPATIALARRLIST STRINGLISTLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.GETXMLTAGTYPE(TYPEOWNER VARCHAR,TYPE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.GRANTFEATURETYPETOUSER(FTNSURL VARCHAR,FTNAME VARCHAR,USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.GRANTMDACCESSTOADMINUSER(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.GRANTMDACCESSTOUSER(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.INITIALIZE_AFTER_IMPORT(WFS_VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.INSERTFTDATAUPDATED(NS VARCHAR,NAME VARCHAR,UPDATEDROWLIST ROWPOINTERLIST,UPDATETS TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.INSERTFTMDUPDATED(NS VARCHAR,NAME VARCHAR,UPDATETS TIMESTAMP)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.ISCOMPLEXOBJECTTYPE(ELEMTYPE VARCHAR,GMLALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.ISINLIST(L STRINGLIST,ITEM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.ISLISTMEMBER(FEATURETYPENAME VARCHAR,NAMESPACEURL VARCHAR,FTIDLIST STRINGLISTLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.ISPKCOLIN(R VARCHAR,RLIST ROWPOINTERLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.ISROWIDIN(R ROWID,RLIST ROWPOINTERLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.NOTINARRAY(P VARCHAR,PLIST ROWPOINTERLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.ORDERINLIST(L STRINGLIST,ITEM VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.PARSEPATH(PATH VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.POPULATEFEATURETYPEXMLINFO(XMLCOLTYPEXSD XMLTYPE,FTYPEID NUMBER,COLUMNNAME VARCHAR,OBJPATHINFO STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.POPULATEVARYINGALIASES(FTXSD XMLTYPE,FTNAME VARCHAR,FEATURETYPEID NUMBER,COL_NAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.PREPARE_FOR_EXPORT_ALL()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.PREPARE_FOR_EXPORT_FTS(FTLIST STRINGLISTLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.PREPARE_FOR_EXPORT_FTS(FTLIST STRINGLISTLIST,EXPORTSDOMETADATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PREPARE_FOR_EXPORT_FT_INT(FTNAME VARCHAR,FTNSURL VARCHAR,EXPORTSDOMETADATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PREPARE_FOR_EXPORT_FT_M_INT(FTNAME VARCHAR,FTNSURL VARCHAR,EXPORTSDOMETADATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.PREPARE_FOR_EXPORT_USER()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PREPROCESSINSERT(XMLDATA XMLTYPE,IDPATHS STRINGLIST,SPATIALPATHS STRINGLIST,PARSEDALIASSPPATH STRINGLISTLIST,SPPATHSSRSNSLIST STRINGLISTLIST,SPATIALARRPATHSLIST STRINGLISTLIST,SPARRPATHSSRSNSLIST STRINGLISTLIST,FTNS VARCHAR,FTNAME VARCHAR,FTID NUMBER,FTUSERNAME VARCHAR,TABLENAME VARCHAR,SRSNS VARCHAR,ISGML3 VARCHAR,SPATIALPATHSSTGSRIDS SDONUMLIST,SPATIALARRPATHSSTGSRIDS SDONUMLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PREPROCESSUPDATE(XMLDATA XMLTYPE,OLDID VARCHAR,SPCOLUPDMAP STRINGLIST,SPARRCOLUPDMAP STRINGLIST,IDPATHS STRINGLIST,SPATIALPATHS STRINGLIST,PARSEDALIASSPPATH STRINGLISTLIST,SPPATHSSRSNSLIST STRINGLISTLIST,SPATIALARRPATHSLIST STRINGLISTLIST,SPARRPATHSSRSNSLIST STRINGLISTLIST,FTNS VARCHAR,FTNAME VARCHAR,FTID NUMBER,FTUSERNAME VARCHAR,TABLENAME VARCHAR,SRSNS VARCHAR,ISGML3 VARCHAR,SPATIALPATHSSTGSRIDS SDONUMLIST,SPATIALARRPATHSSTGSRIDS SDONUMLIST,COMPUTESP NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PROCESSCOMPLEXELEMENT(FTXSD XMLTYPE,ELEMENTTYPE VARCHAR,GMLELEMENTSCNT NUMBER,PARENTELEMPATH VARCHAR,GMLALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.PROCESSIDPATH(SRCPATHS STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PROCESSINLINECOMPLEXELEMENT(FTXSD XMLTYPE,ELEMENTXML XMLTYPE,ELEMINDEX NUMBER,GMLELEMENTSCNT NUMBER,PARENTELEMPATH VARCHAR,GMLALIAS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.PROCESSPATH(SRCPATHS STRINGLISTLIST,GENARRIDX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PUBLISHFEATURETYPE(DATASRC VARCHAR,FTNSURL VARCHAR,FTNAME VARCHAR,FTNSALIAS VARCHAR,FEATUREDESC XMLTYPE,SCHEMALOCATION VARCHAR,PKEYCOL VARCHAR,COLUMNINFO STRINGLIST,PSPATIALCOL VARCHAR,FEATUREMEMBERNS VARCHAR,FEATUREMEMBERNAME VARCHAR,SRSNS VARCHAR,SRSNSALIAS VARCHAR,MANDATORYCOLUMNINFO STRINGLIST,WFS_VERSION VARCHAR,FTXSD XMLTYPE,CUSTOMSRSNAMEPREFIXES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PUBLISHFEATURETYPE(DATASRC VARCHAR,FTNSURL VARCHAR,FTNAME VARCHAR,FTNSALIAS VARCHAR,FEATUREDESC XMLTYPE,SCHEMALOCATION VARCHAR,PKEYCOL VARCHAR,COLUMNINFO STRINGLIST,PSPATIALCOL VARCHAR,FEATUREMEMBERNS VARCHAR,FEATUREMEMBERNAME VARCHAR,SRSNS VARCHAR,SRSNSALIAS VARCHAR,VIEWTABLENAME VARCHAR,VIEWTABLEPKEYCOL VARCHAR,MANDATORYCOLUMNINFO STRINGLIST,WFS_VERSION VARCHAR,FTXSD XMLTYPE,CUSTOMSRSNAMEPREFIXES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PUBLISHFEATURETYPE(DATASRC VARCHAR,FTNSURL VARCHAR,FTNAME VARCHAR,FTNSALIAS VARCHAR,FEATUREDESC XMLTYPE,SCHEMALOCATION VARCHAR,PKEYCOL VARCHAR,COLUMNINFO STRINGLIST,PSPATIALCOL VARCHAR,FEATUREMEMBERNS VARCHAR,FEATUREMEMBERNAME VARCHAR,SRSNS VARCHAR,SRSNSALIAS VARCHAR,FEATURECOLLECTIONNS VARCHAR,FEATURECOLLECTIONNAME VARCHAR,ISGML3 VARCHAR,FORMATTEDKEYCOLS STRINGLIST,VIEWTABLENAME VARCHAR,VIEWTABLEPKEYCOL VARCHAR,VIEWTABLEFMTKEYCOLS STRINGLIST,MANDATORYCOLUMNINFO STRINGLIST,WFS_VERSION VARCHAR,FTXSD XMLTYPE,CUSTOMSRSNAMEPREFIXES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PUBLISHFEATURETYPE(FTXSD XMLTYPE,FEATUREDESC XMLTYPE,WFS_VERSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.PUBLISH_FEATURETYPES_IN_SCHEMA(P_OWNER VARCHAR,P_NAMESPACE_URL VARCHAR,P_NAMESPACE_ALIAS VARCHAR,P_WLS_POSTXML_URL VARCHAR,P_TABLENAME_PATTERN VARCHAR,P_WFS_VERSION VARCHAR,P_WRITE_XSD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.PUTALIAS(NSURL VARCHAR,ALIAS VARCHAR,ALIASLIST STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.REGISTERMTABLEVIEW(FTNSURL VARCHAR,FTNAME VARCHAR,VIEWTABLELIST STRINGLIST,VIEWTABLEPKEYCOLLIST STRINGLIST,TABLEPKEYCOLLIST STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.REGISTERMTABLEVIEW(FTNSURL VARCHAR,FTNAME VARCHAR,VIEWTABLELIST STRINGLIST,VIEWTABLEPKEYCOLLIST STRINGLIST,FORMATTEDVIEWTABLECOLLIST STRINGLISTLIST,TABLEPKEYCOLLIST STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.REGISTEROBJECT(OBJNS VARCHAR,OBJNAME VARCHAR,FTNSURL VARCHAR,CURROBJCOLPATH VARCHAR,OBJNAMEINDEX NUMBER,FTID NUMBER,SPATIALCOLINFO STRINGLIST)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.REVOKEFEATURETYPEFROMUSER(FTNSURL VARCHAR,FTNAME VARCHAR,USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.REVOKEMDACCESSFROMADMINUSER(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.REVOKEMDACCESSFROMUSER(USERNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.SORTSPCONTENTBYCOLINDEX(SPATIALPATHS STRINGLIST,SPATIALPATHINFO SDO_GEOM_PATH_INFO,USERNAME VARCHAR,TABLENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_WFS_PROCESS.STRIP_SPECIAL_CHARS(INPUT_STR VARCHAR,CHARS_TO_BE_DELETED VARCHAR,PLACEHOLDERS VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.UNREGISTERMTABLEVIEW(FTNSURL VARCHAR,FTNAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.UPDATEOBJECTREF(REFOBJNS VARCHAR,REFOBJNAME VARCHAR,FEATURETYPEID NUMBER,REFOBJSEQNO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_WFS_PROCESS.UPDATEOBJECTREF(REFOBJNS VARCHAR,REFOBJNAME VARCHAR,REFOBJSEQNO NUMBER,NSURL VARCHAR,CONTAINEROBJNS VARCHAR,CONTAINEROBJNAME VARCHAR,CONTAINEROBJNAMEINDEX NUMBER,FEATURETYPEID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

