CREATE SCHEMA SDO_TIN_PKG;

CREATE OR REPLACE FUNCTION SDO_TIN_PKG.CLIP_TIN(INP SDO_TIN,QRY SDO_GEOMETRY,QRY_MIN_RES NUMBER,QRY_MAX_RES NUMBER,BLKNO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TIN_PKG.CLIP_TIN_INTO_PC(TIN_INP SDO_TIN,TIN_QRY SDO_GEOMETRY,TIN_QRY_MIN_RES NUMBER,TIN_QRY_MAX_RES NUMBER,PC_BASETABLE VARCHAR,PC_BASECOL VARCHAR,PC_BLKTABLE VARCHAR,PC_PTN_PARAMS VARCHAR,TIN_BLKNO NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TIN_PKG.CREATE_TIN(INP SDO_TIN,INPTABLE VARCHAR,CLSTPCDATATBL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TIN_PKG.DROP_DEPENDENCIES(BASETABLE VARCHAR,COL VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TIN_PKG.GET_SURFACE_OF_TIN(TIN SDO_TIN,GEOM2D SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TIN_PKG.GET_SURFACE_OF_TIN_FOOTPRINT(TIN SDO_TIN,GEOM2D SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TIN_PKG.GET_VOLUME_UNDER_TIN(TIN SDO_TIN,GEOM2D SDO_GEOMETRY,BASE_HEIGHT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TIN_PKG.INIT(BASETABLE VARCHAR,BASECOL VARCHAR,BLKTABLE VARCHAR,PTN_PARAMS VARCHAR,TIN_EXTENT SDO_GEOMETRY,TIN_TOL NUMBER,TIN_TOT_DIMENSIONS NUMBER,TIN_DOMAIN SDO_ORGSCL_TYPE,TIN_BREAK_LINES SDO_GEOMETRY,TIN_STOP_LINES SDO_GEOMETRY,TIN_VOID_RGNS SDO_GEOMETRY,TIN_VAL_ATTR_TABLES SDO_STRING_ARRAY,TIN_OTHER_ATTRS XMLTYPE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TIN_PKG.PROJECT_ORDINATES_ONTO_TIN(ORDINATES2D SDO_ORDINATE_ARRAY,TIN SDO_TIN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TIN_PKG.TO_DEM(TIN SDO_TIN,BLOCKSIZE NUMBER,CRS_UNITS_PER_PIXEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TIN_PKG.TO_GEOMETRY(PTS BLOB,TRS BLOB,NUM_PTS NUMBER,NUM_TRS NUMBER,TIN_IND_DIM NUMBER,TIN_TOT_DIM NUMBER,SRID NUMBER,BLK_DOMAIN SDO_ORGSCL_TYPE,GET_IDS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

