CREATE SCHEMA SDO_TOPO_MAP;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_EDGE(TOPOLOGY VARCHAR,NODE_ID1 NUMBER,NODE_ID2 NUMBER,GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_ISOLATED_NODE(TOPOLOGY VARCHAR,FACE_ID NUMBER,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_ISOLATED_NODE(TOPOLOGY VARCHAR,FACE_ID NUMBER,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_ISOLATED_NODE(TOPOLOGY VARCHAR,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_ISOLATED_NODE(TOPOLOGY VARCHAR,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_LINEAR_GEOMETRY(TOPOLOGY VARCHAR,CURVE SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_LINEAR_GEOMETRY(TOPOLOGY VARCHAR,COORDS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_LOOP(TOPOLOGY VARCHAR,NODE_ID NUMBER,GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_NODE(TOPOLOGY VARCHAR,EDGE_ID NUMBER,POINT SDO_GEOMETRY,COORD_INDEX NUMBER,IS_NEW_SHAPE_POINT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_NODE(TOPOLOGY VARCHAR,EDGE_ID NUMBER,X NUMBER,Y NUMBER,COORD_INDEX NUMBER,IS_NEW_SHAPE_POINT VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_POINT_GEOMETRY(TOPOLOGY VARCHAR,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_POINT_GEOMETRY(TOPOLOGY VARCHAR,COORD SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_POLYGON_GEOMETRY(TOPOLOGY VARCHAR,POLYGON SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.ADD_POLYGON_GEOMETRY(TOPOLOGY VARCHAR,COORDS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.CHANGE_EDGE_COORDS(TOPOLOGY VARCHAR,EDGE_ID NUMBER,GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.CHANGE_EDGE_COORDS(TOPOLOGY VARCHAR,EDGE_ID NUMBER,GEOM SDO_GEOMETRY,ALLOW_ISO_MOVES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.CLEAR_TOPO_MAP(TOPO_MAP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.COMMIT_TOPO_MAP()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.CREATE_FACE_INDEX(TOPO_MAP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.CREATE_FEATURE(TOPOLOGY VARCHAR,TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,GEOM SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.CREATE_FEATURE(TOPOLOGY VARCHAR,TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,GEOM SDO_GEOMETRY,SNAPFEATURE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.CREATE_FEATURE(TOPOLOGY VARCHAR,TABLE_NAME VARCHAR,COLUMN_NAME VARCHAR,DML_CONDITION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.CREATE_TOPO_MAP(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR,NUMBER_OF_EDGES NUMBER,NUMBER_OF_NODES NUMBER,NUMBER_OF_FACES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.CREATE_TOPO_MAP(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.DROP_TOPO_MAP(TOPO_MAP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_CONTAINING_FACE(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_CONTAINING_FACE(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR,POINT SDO_GEOMETRY,ALLOW_ISO_COINCIDENCE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_CONTAINING_FACE(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_EDGE_ADDITIONS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_EDGE_CHANGES(TOPO_MAP VARCHAR,EDGE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_EDGE_DELETIONS(TOPO_MAP VARCHAR,EDGE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_FACE_ADDITIONS(TOPO_MAP VARCHAR,FACE_ID NUMBER,OPITON NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_FACE_CHANGES()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_FACE_DELETIONS(TOPO_MAP VARCHAR,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NEAREST_EDGE(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NEAREST_EDGE_IN_CACHE(TOPO_MAP VARCHAR,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NEAREST_EDGE_IN_CACHE(TOPO_MAP VARCHAR,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NEAREST_NODE(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NEAREST_NODE(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NEAREST_NODE_IN_CACHE(TOPO_MAP VARCHAR,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NEAREST_NODE_IN_CACHE(TOPO_MAP VARCHAR,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NODE_ADDITIONS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NODE_CHANGES(TOPO_MAP VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NODE_DELETIONS(TOPO_MAP VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_NODE_STAR(TOPOLOGY VARCHAR,TOPO_MAP VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_TOPO_NAME(TOPO_MAP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.GET_TOPO_TRANSACTION_ID()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.LIST_TOPO_MAPS(XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,ALLOW_UPDATES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.LOAD_TOPO_MAP(TOPO_MAP VARCHAR,XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,ALLOW_UPDATES VARCHAR,BUILD_INDEXES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.LOAD_TOPO_MAP(TOPO_MAP VARCHAR,XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,ALLOW_UPDATES VARCHAR,BUILD_INDEXES VARCHAR,NEXT_LOAD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.LOAD_TOPO_MAP(TOPO_MAP VARCHAR,ALLOW_UPDATES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.LOAD_TOPO_MAP(TOPO_MAP VARCHAR,ALLOW_UPDATES VARCHAR,BUILD_INDEXES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.LOAD_TOPO_MAP(TOPO_MAP VARCHAR,XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,ALLOW_UPDATES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.LOAD_TOPO_MAP(TOPO_MAP VARCHAR,XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,ALLOW_UPDATES VARCHAR,BUILD_INDEXES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.LOAD_TOPO_MAP(TOPO_MAP VARCHAR,ALLOW_UPDATES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.LOAD_TOPO_MAP(TOPO_MAP VARCHAR,ALLOW_UPDATES VARCHAR,BUILD_INDEXES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.MOVE_EDGE(TOPOLOGY VARCHAR,EDGE_ID NUMBER,S_NODE_ID NUMBER,T_NODE_ID NUMBER,EDGE_COORDS SDO_NUMBER_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.MOVE_EDGE(TOPOLOGY VARCHAR,EDGE_ID NUMBER,S_NODE_ID NUMBER,T_NODE_ID NUMBER,EDGE_COORDS SDO_NUMBER_ARRAY,ALLOW_ISO_MOVES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.MOVE_ISOLATED_NODE(TOPOLOGY VARCHAR,NODE_ID NUMBER,POINT SDO_GEOMETRY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.MOVE_ISOLATED_NODE(TOPOLOGY VARCHAR,NODE_ID NUMBER,POINT SDO_GEOMETRY,ALLOW_FACE_CHANGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.MOVE_ISOLATED_NODE(TOPOLOGY VARCHAR,NODE_ID NUMBER,X NUMBER,Y NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.MOVE_ISOLATED_NODE(TOPOLOGY VARCHAR,NODE_ID NUMBER,X NUMBER,Y NUMBER,ALLOW_FACE_CHANGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.MOVE_NODE(TOPOLOGY VARCHAR,NODE_ID NUMBER,EDGES_COORDS SDO_EDGE_ARRAY)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.MOVE_NODE(TOPOLOGY VARCHAR,NODE_ID NUMBER,EDGES_COORDS SDO_EDGE_ARRAY,ALLOW_ISO_MOVES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.REMOVE_EDGE(TOPOLOGY VARCHAR,EDGE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.REMOVE_NODE(TOPOLOGY VARCHAR,NODE_ID NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.REMOVE_OBSOLETE_NODES(TOPOLOGY VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.ROLLBACK_TOPO_MAP(XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,CAPACITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.SEARCH_FACE_RTREE_TOPO_MAP(TOPO_MAP VARCHAR,XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,CAPACITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.SET_MAX_MEMORY_SIZE(BYTES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE SDO_TOPO_MAP.UPDATE_TOPO_MAP()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.VALIDATE_TOPOLOGY(TOPOLOGY VARCHAR,PREVENT_UPDATES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.VALIDATE_TOPOLOGY(TOPOLOGY VARCHAR,PREVENT_UPDATES VARCHAR,LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.VALIDATE_TOPOLOGY(TOPOLOGY VARCHAR,XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.VALIDATE_TOPOLOGY(TOPOLOGY VARCHAR,XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,PREVENT_UPDATES VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.VALIDATE_TOPOLOGY(TOPOLOGY VARCHAR,XMIN NUMBER,YMIN NUMBER,XMAX NUMBER,YMAX NUMBER,PREVENT_UPDATES VARCHAR,LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.VALIDATE_TOPO_MAP(TOPO_MAP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION SDO_TOPO_MAP.VALIDATE_TOPO_MAP(TOPO_MAP VARCHAR,LEVEL NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

