CREATE SCHEMA UTL_FILE;

CREATE OR REPLACE PROCEDURE UTL_FILE.FCLOSE()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.FCLOSE_ALL(SRC_FILENAME VARCHAR,DEST_LOCATION VARCHAR,DEST_FILENAME VARCHAR,START_LINE NUMBER,END_LINE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.FFLUSH(FILE VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.FGETATTR(LOCATION VARCHAR,FILENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_FILE.FGETPOS(FILE VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_FILE.FOPEN(LOCATION VARCHAR,FILENAME VARCHAR,OPEN_MODE VARCHAR,MAX_LINESIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_FILE.FOPEN_NCHAR(LOCATION VARCHAR,FILENAME VARCHAR,OPEN_MODE VARCHAR,MAX_LINESIZE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_FILE.FREMOVE(LOCATION VARCHAR,FILENAME VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.FRENAME(SRC_LOCATION VARCHAR,SRC_FILENAME VARCHAR,DEST_LOCATION VARCHAR,DEST_FILENAME VARCHAR,OVERWRITE BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.FSEEK(ABSOLUTE_OFFSET NUMBER,RELATIVE_OFFSET NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.GET_LINE(FILE VARIANT,LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.GET_LINE_NCHAR(FILE VARIANT,LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.GET_RAW(FILE VARIANT,LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_FILE.IS_OPEN(FILE VARIANT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_FILE.NEW_LINE(FILE VARIANT,LINES NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.PUT(FILE VARIANT,BUFFER VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.PUTF(FILE VARIANT,FORMAT VARCHAR,ARG1 VARCHAR,ARG2 VARCHAR,ARG3 VARCHAR,ARG4 VARCHAR,ARG5 VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.PUTF_NCHAR(FILE VARIANT,FORMAT NVARCHAR2,ARG1 NVARCHAR2,ARG2 NVARCHAR2,ARG3 NVARCHAR2,ARG4 NVARCHAR2,ARG5 NVARCHAR2)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.PUT_LINE(FILE VARIANT,BUFFER VARCHAR,AUTOFLUSH BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.PUT_LINE_NCHAR(FILE VARIANT,BUFFER NVARCHAR2)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.PUT_NCHAR(FILE VARIANT,BUFFER NVARCHAR2)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_FILE.PUT_RAW(FILE VARIANT,BUFFER RAW,AUTOFLUSH BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

