CREATE SCHEMA UTL_COMPRESS;

CREATE OR REPLACE FUNCTION UTL_COMPRESS.ISOPEN(HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_COMPRESS.LZ_COMPRESS(SRC RAW,QUALITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_COMPRESS.LZ_COMPRESS(SRC BLOB,QUALITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_COMPRESS.LZ_COMPRESS(SRC BLOB,QUALITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_COMPRESS.LZ_COMPRESS(QUALITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_COMPRESS.LZ_COMPRESS(QUALITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_COMPRESS.LZ_COMPRESS_ADD(HANDLE NUMBER,SRC RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_COMPRESS.LZ_COMPRESS_CLOSE(HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_COMPRESS.LZ_COMPRESS_OPEN(QUALITY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_COMPRESS.LZ_UNCOMPRESS(SRC RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_COMPRESS.LZ_UNCOMPRESS(SRC BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_COMPRESS.LZ_UNCOMPRESS(SRC BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_COMPRESS.LZ_UNCOMPRESS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_COMPRESS.LZ_UNCOMPRESS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_COMPRESS.LZ_UNCOMPRESS_CLOSE(HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_COMPRESS.LZ_UNCOMPRESS_EXTRACT(HANDLE NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_COMPRESS.LZ_UNCOMPRESS_OPEN(SRC BLOB)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

