CREATE SCHEMA UTL_INADDR;

CREATE OR REPLACE FUNCTION UTL_INADDR.GET_HOST_ADDRESS(HOST VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_INADDR.GET_HOST_NAME(IP VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

