CREATE SCHEMA UTL_URL;

CREATE OR REPLACE FUNCTION UTL_URL.ESCAPE(URL VARCHAR,ESCAPE_RESERVED_CHARS BOOLEAN,URL_CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_URL.UNESCAPE(URL VARCHAR,URL_CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

