CREATE SCHEMA UTL_ENCODE;

CREATE OR REPLACE FUNCTION UTL_ENCODE.BASE64_DECODE(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.BASE64_ENCODE(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.MIMEHEADER_DECODE(BUF VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.MIMEHEADER_ENCODE(BUF VARCHAR,ENCODE_CHARSET VARCHAR,ENCODING NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.QUOTED_PRINTABLE_DECODE(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.QUOTED_PRINTABLE_ENCODE(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.TEXT_DECODE(BUF VARCHAR,ENCODE_CHARSET VARCHAR,ENCODING NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.TEXT_ENCODE(BUF VARCHAR,ENCODE_CHARSET VARCHAR,ENCODING NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.UUDECODE(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_ENCODE.UUENCODE(R RAW,TYPE NUMBER,FILENAME VARCHAR,PERMISSION VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

