CREATE SCHEMA UTL_TCP;

CREATE OR REPLACE FUNCTION UTL_TCP.AVAILABLE(TIMEOUT NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_TCP.CLOSE_ALL_CONNECTIONS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_TCP.FLUSH()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_TCP.GET_LINE(REMOVE_CRLF BOOLEAN,PEEK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.GET_LINE_NCHAR(REMOVE_CRLF BOOLEAN,PEEK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.GET_RAW(LEN NUMBER,PEEK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.GET_TEXT(LEN NUMBER,PEEK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.GET_TEXT_NCHAR(LEN NUMBER,PEEK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.OPEN_CONNECTION(REMOTE_HOST VARCHAR,REMOTE_PORT NUMBER,LOCAL_HOST VARCHAR,LOCAL_PORT NUMBER,IN_BUFFER_SIZE NUMBER,OUT_BUFFER_SIZE NUMBER,CHARSET VARCHAR,NEWLINE VARCHAR,TX_TIMEOUT NUMBER,WALLET_PATH VARCHAR,WALLET_PASSWORD VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.READ_LINE(REMOVE_CRLF BOOLEAN,PEEK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.READ_RAW(LEN NUMBER,PEEK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.READ_TEXT(LEN NUMBER,PEEK BOOLEAN)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_TCP.SECURE_CONNECTION()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_TCP.WRITE_LINE(DATA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.WRITE_RAW(DATA RAW,LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_TCP.WRITE_TEXT(DATA VARCHAR,LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

