CREATE SCHEMA UTL_LMS;

CREATE OR REPLACE FUNCTION UTL_LMS.FORMAT_MESSAGE(FORMAT VARCHAR,ARGS UNDEFINED)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_LMS.GET_MESSAGE(ERRNUM NUMBER,PRODUCT VARCHAR,FACILITY VARCHAR,LANGUAGE VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

