CREATE SCHEMA UTL_RAW;

CREATE OR REPLACE FUNCTION UTL_RAW.BIT_AND(R1 RAW,R2 RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.BIT_COMPLEMENT(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.BIT_OR(R1 RAW,R2 RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.BIT_XOR(R1 RAW,R2 RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_FROM_BINARY_DOUBLE(N BINARY_DOUBLE,ENDIANESS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_FROM_BINARY_FLOAT(N BINARY_FLOAT,ENDIANESS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_FROM_BINARY_INTEGER(N NUMBER,ENDIANESS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_FROM_NUMBER(N NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_TO_BINARY_DOUBLE(R RAW,ENDIANESS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_TO_BINARY_FLOAT(R RAW,ENDIANESS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_TO_BINARY_INTEGER(R RAW,ENDIANESS NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_TO_NUMBER(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_TO_NVARCHAR2(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_TO_RAW(C VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CAST_TO_VARCHAR2(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.COMPARE(R1 RAW,R2 RAW,PAD RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CONCAT(R1 RAW,R2 RAW,R3 RAW,R4 RAW,R5 RAW,R6 RAW,R7 RAW,R8 RAW,R9 RAW,R10 RAW,R11 RAW,R12 RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.CONVERT(R RAW,TO_CHARSET VARCHAR,FROM_CHARSET VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.COPIES(R RAW,N NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.LENGTH(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.OVERLAY(OVERLAY_STR RAW,TARGET RAW,POS NUMBER,LEN NUMBER,PAD RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.REVERSE(R RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.SUBSTR(R RAW,POS NUMBER,LEN NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.TRANSLATE(R RAW,FROM_SET RAW,TO_SET RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.TRANSLITERATE(R RAW,TO_SET RAW,FROM_SET RAW,PAD RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_RAW.XRANGE(START_BYTE RAW,END_BYTE RAW)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

