CREATE SCHEMA UTL_NLA;

CREATE OR REPLACE FUNCTION UTL_NLA.BLAS_ASUM(N NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_NLA.BLAS_ASUM(N NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_AXPY(N NUMBER,ALPHA BINARY_DOUBLE,X UTL_NLA_ARRAY_DBL,INCX NUMBER,INCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_AXPY(N NUMBER,ALPHA BINARY_FLOAT,X UTL_NLA_ARRAY_FLT,INCX NUMBER,INCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_COPY(N NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER,INCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_COPY(N NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER,INCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_NLA.BLAS_DOT(N NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER,Y UTL_NLA_ARRAY_DBL,INCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_NLA.BLAS_DOT(N NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER,Y UTL_NLA_ARRAY_FLT,INCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_GBMV(TRANS CHAR(1),M NUMBER,N NUMBER,KL NUMBER,KU NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER,BETA BINARY_DOUBLE,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_GBMV(TRANS CHAR(1),M NUMBER,N NUMBER,KL NUMBER,KU NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER,BETA BINARY_FLOAT,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_GEMM(TRANSA CHAR(1),TRANSB CHAR(1),M NUMBER,N NUMBER,K NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,B UTL_NLA_ARRAY_DBL,LDB NUMBER,BETA BINARY_DOUBLE,LDC NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_GEMM(TRANSA CHAR(1),TRANSB CHAR(1),M NUMBER,N NUMBER,K NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,B UTL_NLA_ARRAY_FLT,LDB NUMBER,BETA BINARY_FLOAT,LDC NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_GEMV(TRANS CHAR(1),M NUMBER,N NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER,BETA BINARY_DOUBLE,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_GEMV(TRANS CHAR(1),M NUMBER,N NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER,BETA BINARY_FLOAT,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_GER(M NUMBER,N NUMBER,ALPHA BINARY_DOUBLE,X UTL_NLA_ARRAY_DBL,INCX NUMBER,Y UTL_NLA_ARRAY_DBL,INCY NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_GER(M NUMBER,N NUMBER,ALPHA BINARY_FLOAT,X UTL_NLA_ARRAY_FLT,INCX NUMBER,Y UTL_NLA_ARRAY_FLT,INCY NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE FUNCTION UTL_NLA.BLAS_IAMAX(N NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_NLA.BLAS_IAMAX(N NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_NLA.BLAS_NRM2(N NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE FUNCTION UTL_NLA.BLAS_NRM2(N NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$;

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_ROT(N NUMBER,INCX NUMBER,INCY NUMBER,C BINARY_DOUBLE,S BINARY_DOUBLE)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_ROT(N NUMBER,INCX NUMBER,INCY NUMBER,C BINARY_FLOAT,S BINARY_FLOAT)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_ROTG()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_ROTG()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SBMV(UPLO CHAR(1),N NUMBER,K NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER,BETA BINARY_DOUBLE,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SBMV(UPLO CHAR(1),N NUMBER,K NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER,BETA BINARY_FLOAT,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SCAL(N NUMBER,ALPHA BINARY_DOUBLE,INCX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SCAL(N NUMBER,ALPHA BINARY_FLOAT,INCX NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SPMV(UPLO CHAR(1),N NUMBER,ALPHA BINARY_DOUBLE,AP UTL_NLA_ARRAY_DBL,X UTL_NLA_ARRAY_DBL,INCX NUMBER,BETA BINARY_DOUBLE,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SPMV(UPLO CHAR(1),N NUMBER,ALPHA BINARY_FLOAT,AP UTL_NLA_ARRAY_FLT,X UTL_NLA_ARRAY_FLT,INCX NUMBER,BETA BINARY_FLOAT,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SPR(UPLO CHAR(1),N NUMBER,ALPHA BINARY_DOUBLE,X UTL_NLA_ARRAY_DBL,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SPR(UPLO CHAR(1),N NUMBER,ALPHA BINARY_FLOAT,X UTL_NLA_ARRAY_FLT,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SPR2(UPLO CHAR(1),N NUMBER,ALPHA BINARY_DOUBLE,X UTL_NLA_ARRAY_DBL,INCX NUMBER,Y UTL_NLA_ARRAY_DBL,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SPR2(UPLO CHAR(1),N NUMBER,ALPHA BINARY_FLOAT,X UTL_NLA_ARRAY_FLT,INCX NUMBER,Y UTL_NLA_ARRAY_FLT,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SWAP(N NUMBER,INCX NUMBER,INCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SWAP(N NUMBER,INCX NUMBER,INCY NUMBER)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYMM(SIDE CHAR(1),UPLO CHAR(1),M NUMBER,N NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,B UTL_NLA_ARRAY_DBL,LDB NUMBER,BETA BINARY_DOUBLE,LDC NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYMM(SIDE CHAR(1),UPLO CHAR(1),M NUMBER,N NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,B UTL_NLA_ARRAY_FLT,LDB NUMBER,BETA BINARY_FLOAT,LDC NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYMV(UPLO CHAR(1),N NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,X UTL_NLA_ARRAY_DBL,INCX NUMBER,BETA BINARY_DOUBLE,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYMV(UPLO CHAR(1),N NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,X UTL_NLA_ARRAY_FLT,INCX NUMBER,BETA BINARY_FLOAT,INCY NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYR(UPLO CHAR(1),N NUMBER,ALPHA BINARY_DOUBLE,X UTL_NLA_ARRAY_DBL,INCX NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYR(UPLO CHAR(1),N NUMBER,ALPHA BINARY_FLOAT,X UTL_NLA_ARRAY_FLT,INCX NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYR2(UPLO CHAR(1),N NUMBER,ALPHA BINARY_DOUBLE,X UTL_NLA_ARRAY_DBL,INCX NUMBER,Y UTL_NLA_ARRAY_DBL,INCY NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYR2(UPLO CHAR(1),N NUMBER,ALPHA BINARY_FLOAT,X UTL_NLA_ARRAY_FLT,INCX NUMBER,Y UTL_NLA_ARRAY_FLT,INCY NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYR2K(UPLO CHAR(1),TRANS CHAR(1),N NUMBER,K NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,B UTL_NLA_ARRAY_DBL,LDB NUMBER,BETA BINARY_DOUBLE,LDC NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYR2K(UPLO CHAR(1),TRANS CHAR(1),N NUMBER,K NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,B UTL_NLA_ARRAY_FLT,LDB NUMBER,BETA BINARY_FLOAT,LDC NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYRK(UPLO CHAR(1),TRANS CHAR(1),N NUMBER,K NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,BETA BINARY_DOUBLE,LDC NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_SYRK(UPLO CHAR(1),TRANS CHAR(1),N NUMBER,K NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,BETA BINARY_FLOAT,LDC NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TBMV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,K NUMBER,A UTL_NLA_ARRAY_DBL,LDA NUMBER,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TBMV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,K NUMBER,A UTL_NLA_ARRAY_FLT,LDA NUMBER,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TBSV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,K NUMBER,A UTL_NLA_ARRAY_DBL,LDA NUMBER,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TBSV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,K NUMBER,A UTL_NLA_ARRAY_FLT,LDA NUMBER,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TPMV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,AP UTL_NLA_ARRAY_DBL,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TPMV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,AP UTL_NLA_ARRAY_FLT,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TPSV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,AP UTL_NLA_ARRAY_DBL,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TPSV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,AP UTL_NLA_ARRAY_FLT,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TRMM(SIDE CHAR(1),UPLO CHAR(1),TRANSA CHAR(1),DIAG CHAR(1),M NUMBER,N NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TRMM(SIDE CHAR(1),UPLO CHAR(1),TRANSA CHAR(1),DIAG CHAR(1),M NUMBER,N NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TRMV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,A UTL_NLA_ARRAY_DBL,LDA NUMBER,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TRMV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,A UTL_NLA_ARRAY_FLT,LDA NUMBER,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TRSM(SIDE CHAR(1),UPLO CHAR(1),TRANSA CHAR(1),DIAG CHAR(1),M NUMBER,N NUMBER,ALPHA BINARY_DOUBLE,A UTL_NLA_ARRAY_DBL,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TRSM(SIDE CHAR(1),UPLO CHAR(1),TRANSA CHAR(1),DIAG CHAR(1),M NUMBER,N NUMBER,ALPHA BINARY_FLOAT,A UTL_NLA_ARRAY_FLT,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TRSV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,A UTL_NLA_ARRAY_DBL,LDA NUMBER,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.BLAS_TRSV(UPLO CHAR(1),TRANS CHAR(1),DIAG CHAR(1),N NUMBER,A UTL_NLA_ARRAY_FLT,LDA NUMBER,INCX NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GBSV(N NUMBER,KL NUMBER,KU NUMBER,NRHS NUMBER,LDAB NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GBSV(N NUMBER,KL NUMBER,KU NUMBER,NRHS NUMBER,LDAB NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GEES(JOBVS CHAR(1),N NUMBER,LDA NUMBER,LDVS NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GEES(JOBVS CHAR(1),N NUMBER,LDA NUMBER,LDVS NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GEEV(JOBVL CHAR(1),JOBVR CHAR(1),N NUMBER,LDA NUMBER,LDVL NUMBER,LDVR NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GEEV(JOBVL CHAR(1),JOBVR CHAR(1),N NUMBER,LDA NUMBER,LDVL NUMBER,LDVR NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GELS(TRANS CHAR(1),M NUMBER,N NUMBER,NRHS NUMBER,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GELS(TRANS CHAR(1),M NUMBER,N NUMBER,NRHS NUMBER,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GESDD(JOBZ CHAR(1),M NUMBER,N NUMBER,LDA NUMBER,LDU NUMBER,LDVT NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GESDD(JOBZ CHAR(1),M NUMBER,N NUMBER,LDA NUMBER,LDU NUMBER,LDVT NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GESV(N NUMBER,NRHS NUMBER,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GESV(N NUMBER,NRHS NUMBER,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GESVD(JOBU CHAR(1),JOBVT CHAR(1),M NUMBER,N NUMBER,LDA NUMBER,LDU NUMBER,LDVT NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GESVD(JOBU CHAR(1),JOBVT CHAR(1),M NUMBER,N NUMBER,LDA NUMBER,LDU NUMBER,LDVT NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GTSV(N NUMBER,NRHS NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_GTSV(N NUMBER,NRHS NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_PBSV(UPLO CHAR(1),N NUMBER,KD NUMBER,NRHS NUMBER,LDAB NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_PBSV(UPLO CHAR(1),N NUMBER,KD NUMBER,NRHS NUMBER,LDAB NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_POSV(UPLO CHAR(1),N NUMBER,NRHS NUMBER,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_POSV(UPLO CHAR(1),N NUMBER,NRHS NUMBER,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_PPSV(UPLO CHAR(1),N NUMBER,NRHS NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_PPSV(UPLO CHAR(1),N NUMBER,NRHS NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_PTSV(N NUMBER,NRHS NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_PTSV(N NUMBER,NRHS NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SBEV(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,KD NUMBER,LDAB NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SBEV(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,KD NUMBER,LDAB NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SBEVD(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,KD NUMBER,LDAB NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SBEVD(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,KD NUMBER,LDAB NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SPEV(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SPEV(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SPEVD(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SPEVD(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SPSV(UPLO CHAR(1),N NUMBER,NRHS NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SPSV(UPLO CHAR(1),N NUMBER,NRHS NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_STEV(JOBZ CHAR(1),N NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_STEV(JOBZ CHAR(1),N NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_STEVD(JOBZ CHAR(1),N NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_STEVD(JOBZ CHAR(1),N NUMBER,LDZ NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SYEV(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SYEV(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SYEVD(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SYEVD(JOBZ CHAR(1),UPLO CHAR(1),N NUMBER,LDA NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SYSV(UPLO CHAR(1),N NUMBER,NRHS NUMBER,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.LAPACK_SYSV(UPLO CHAR(1),N NUMBER,NRHS NUMBER,LDA NUMBER,LDB NUMBER,PACK CHAR(1))
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

CREATE OR REPLACE PROCEDURE UTL_NLA.UNIT_TEST_BLAS()
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
/** add some code here **/
$$

